### ISSUE TITLE
ALOps Package Import - No Docker Container found with Label

### ISSUE THREAD

**Issue by ChristianMuetzePrintVis** [HodorNV/ALOps#101]
Hi

I added the Package Import to my Pipeline

``` YAML
- task: ALOpsPackageImport@1
  displayName: 'ALOps Package Import'
  inputs:
   usedocker: True 
```  

But it does only shows an error.

```
Starting: ALOps Package Import
==============================================================================
Task         : ALOps Package Import
Description  : ALOps Package Import
Version      : 1.428.1141
Author       : Hodor
Help         : Import and Process RapidStart/Configuration Package
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
##[error]No Docker Container found with Label [PV AL app_1402]. Remove aborted.
Finishing: ALOps Package Import
```

Seems it is a combination of the App name and the build.

I used beforehand 

```
- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    fixed_tag: '$(docker_container_name)'
    installaltesttool: true
    artifact_path: '*.app'
```

How can I get this to work?

**Comment by waldo1001** [comment]
Hi - did you do a dockerwait as well?  Like:

```
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
```

**Comment by waldo1001** [comment]
Hi,
can you share the entire pipeline?

**Comment by ChristianMuetzePrintVis** [comment]
Hi @waldo1001 ,

sorry, Sure!
[ALOPsPipelineCMALOpsTest.txt](https://github.com/HodorNV/ALOps/files/4392113/ALOPsPipelineCMALOpsTest.txt)
[](url)
// Christian

**Comment by waldo1001** [comment]
Why do you have the fixed_tag in there?  

Since you remove the container, I'd advise to remove the "fixed_tag" (we take care of tagging it for you if you don't provide one).

In the meantime, we'll add the "fixed_tag" param on the package import (we forgot that, apparently ...).

So, test this pipeline:

```yaml
name: $(Build.BuildId)

pool:
 name: CM Local Private

steps:
- checkout: self
  clean: true 

- task: ALOpsInfo@1

- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'bcinsider.azurecr.io/bcsandbox-master:w1'
    enable_symbol_loading: true
    enable_api_services: true
    dockerauthentication: 'UsernamePassword'
    docker_username: '$(docker_username)'
    docker_password: '$(docker_password)'
    memory_gb: '6'
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: './PVApp/res/PV.flf'
    print_license_info: true

- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: PVApp'
  inputs:
    usedocker: true
    targetproject: 'PVApp/app.json'
    nav_app_version: '16.1.[yyyyWW].*'
    download_test_symbols: true
    app_file_suffix: '_PVALAPP'
    setup_working_folder: true

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    installaltesttool: true
    artifact_path: '*.app'

- task: ALOpsInfo@1

- task: ALOpsPackageImport@1
  displayName: 'ALOps Package Import'
  inputs:
   usedocker: True   

- task: ALOpsAppTest@1
  displayName: 'Run TestSuite'
  inputs:
    usedocker: true
    import_testtoolkit: false
    import_action: 'Skip'
    testpage: '130455'
    testsuite: 'DEFAULT'
  continueOnError: true
 
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: './PVApp/Tests/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'
  
- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
```

**Comment by ChristianMuetzePrintVis** [comment]
Thanks @waldo1001 !

That made it work ... partly :)

Now my data killed it ...

```
*** Start RapidStart Package Validation
*** RapidStart Package Handler: no configuration found, defaulting to all *.rapidstart packages
*** RapidStart Start Package Validation
  * Reading Rapidstart package: .\PVApp\.configurationpackages\1_NAV15.2.W1.ENU.STANDARD.rapidstart
    + 174 tables, 2364 records
  * Reading Rapidstart package: .\PVApp\.configurationpackages\2_PackagePVSDEMO.rapidstart
##[warning]Exception of type 'System.OutOfMemoryException' was thrown.
  * Reading Rapidstart package: .\PV\.configurationpackages\3_PackageCUSTVENCONT.rapidstart

An error has occurred that was not properly handled. Additional information is shown below. The Windows PowerShell process will exit.

Unhandled Exception: OutOfMemoryException.
```

**Comment by waldo1001** [comment]
Try to add more memory when creating the container?  6 is quite limited for data (and running tests).  Minimum we use is 8 - start with that, and upscale if needed?

**Comment by ChristianMuetzePrintVis** [comment]
Allready done, test is running :)

**Comment by waldo1001** [comment]
So I assume package import succeeded :-)

**Comment by ChristianMuetzePrintVis** [comment]
Apparrently not :(

```
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'bcinsider.azurecr.io/bcsandbox-master:w1'
    enable_symbol_loading: true
    enable_api_services: true
    dockerauthentication: 'UsernamePassword'
    docker_username: '$(docker_username)'
    docker_password: '$(docker_password)'
    memory_gb: '11'
    docker_parameters: '--isolation=hyperv'
```

```
WARNING: This license is not compatible with this version of Business Central.
*** Start RapidStart Package Validation
*** RapidStart Package Handler: no configuration found, defaulting to all *.rapidstart packages
*** RapidStart Start Package Validation
  * Reading Rapidstart package: .\PVApp\.configurationpackages\1_NAV15.2.W1.ENU.STANDARD.rapidstart
    + 174 tables, 2364 records
  * Reading Rapidstart package: .\PVApp\.configurationpackages\2_PackagePVSDEMO.rapidstart
##[warning]Exception of type 'System.OutOfMemoryException' was thrown.
  * Reading Rapidstart package: .\PVApp\.configurationpackages\3_PackageCUSTVENCONT.rapidstart
##[warning]An error occurred while enumerating through a collection: Exception of type 'System.OutOfMemoryException' was thrown..
*** RapidStart Configuration Loaded
    - UID        : 6a1058a9-9787-4c2a-bd27-d0683b2d54ab
    - Name       : --AutoGenerated--
    - Packages   : 3
    - Tables     : 174
    - Records    : 2364
    - Exceptions : 2
    - Valid      : False

An error has occurred that was not properly handled. Additional information is shown below. The Windows PowerShell process will exit.

Unhandled Exception: OutOfMemoryException.
##[error]Exit code -532462766 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'C:\agent\vsts-agent-win-x64-2.165.2\_work\_tasks\ALOpsPackageImport_3d90facf-8f6e-4614-8860-9e17e7277cc2\1.428.1141\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''C:\agent\vsts-agent-win-x64-2.165.2\_work\_tasks\ALOpsPackageImport_3d90facf-8f6e-4614-8860-9e17e7277cc2\1.428.1141\9d7174c4-791c-45b2-9499-6baeb8119b30.ps1'''))"'.
Finishing: ALOps Package Import
```


I'll try to slice the failing rapidstart file in smaller slices

**Comment by ChristianMuetzePrintVis** [comment]
@waldo1001 short question.

I removed for now the braking rapidstart package.

Now I get a new error.

```
*** Check WebService: ConfigurationPackages
WARNING: This license is not compatible with this version of Business Central.
*** Create WebService: ConfigurationPackages
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
*** Create WebService: ConfigurationPackageErrors
WARNING: This license is not compatible with this version of Business Central.
VERBOSE: GET https://94b7dea56842:7048/BC/ODataV4/Company('My Company')/ConfigurationPackages with 0-byte payload
##[error]There is no AllObj within the filter.

Filters: Object Type: Page, Object ID: 8615
Finishing: ALOps Package Import
```

What puzzles me is the "Company('My Company')". From where does the script reads that?

**Comment by AdminHodor** [comment]
Dear @ChristianMuetzePrintVis ,

The "fixed_tag" is now also added for the PackageImport task.

>>What puzzles me is the "Company('My Company')". From where does the script reads that?
The scripts reads all companies from the database, then selects the first on. In the latest release we added the parameter "company_name" so you can overrule this behavior.

Please note the PackageImport required quite some resources (RAM), not only do you have to assign it to the container on DockerStart, the resources have to be free on the host machine also.

To monitor memory usage during the pipeline run, you can insert the boolean environment variable [Alops_PrintMemoryStats] = true. This will print memory stats at the starts of every task.

Kind regards

**Comment by ChristianMuetzePrintVis** [comment]
Hi @AdminHodor,

I aded the setting and also removed the faulty rapidstart package.
Now there are only two Microsoft created packages left to be imported.

`*** Memory Status: 0.8/8 (10.03% Free)`

The tag works as expected - thanks!

Import also works now without errors.

I'm not sure if the remaining error is due to data or due to the above mentioned "My Company" webservice.
Need to investigate :(

```
*** RapidStart Configuration Loaded
    - UID        : c99237af-8518-4a06-8ef5-e069cfbf1077
    - Name       : --AutoGenerated--
    - Packages   : 2
    - Tables     : 204
    - Records    : 3737
    - Exceptions : 0
    - Valid      : True
*** Check WebService: ConfigurationPackages
WARNING: This license is not compatible with this version of Business Central.
*** Create WebService: ConfigurationPackages
WARNING: This license is not compatible with this version of Business Central.
*** Check WebService: ConfigurationPackageErrors
WARNING: This license is not compatible with this version of Business Central.
*** Create WebService: ConfigurationPackageErrors
WARNING: This license is not compatible with this version of Business Central.
VERBOSE: GET https://1136051545a1:7048/BC/ODataV4/Company('My Company')/ConfigurationPackages with 0-byte payload
##[error]There is no AllObj within the filter.

```

**Comment by waldo1001** [comment]
That looks very much like an internal BC error - so you'll have to investigate that .. .

if you do - I'd advise to take the exact same docker image.
You could even disable the "docker remove", and play with that container that ALOps create on the agent...

**Comment by ChristianMuetzePrintVis** [comment]
Hi

First Update... seems that the latest build still does not like the fixed_tag

```
- task: ALOpsPackageImport@1
  displayName: 'ALOps Package Import'
  inputs:
    fixed_tag: '$(docker_container_name)'
    company_name: 'Cronus'
```

```
Starting: ALOps Package Import
==============================================================================
Task         : ALOps Package Import
Description  : ALOps Package Import
Version      : 1.428.1160
Author       : Hodor
Help         : Import and Process RapidStart/Configuration Package
==============================================================================
*** Validate configuration
*** Memory Status: 1.12/8 (14.04% Free)
*** Importing required PS-Functions
##[warning]No containers found.
##[error]No Docker Container found with Label [PV AL app_1510]. Remove aborted.
Finishing: ALOps Package Import

```

**Comment by waldo1001** [comment]
So you're using the same fixed_tag parameter for all ALOps-steps?

**Comment by ChristianMuetzePrintVis** [comment]
Yes

With this setting I kept one container on the agent machine.

Without I got multiple docker contaienr dangling on that machine

![image](https://user-images.githubusercontent.com/36710633/78026190-7e83b380-735b-11ea-9396-e3b6124889c1.png)

**Comment by waldo1001** [comment]
Well, if you don't include the remove-docker-step, they will stay there ... .  

look at this example:
https://github.com/HodorNV/ALOps/blob/master/Examples/06_UseDocker_TestTool_v15_Multiroot.yml

No fixed-tag, always creating and cleaning up the docker container ...

**Comment by ChristianMuetzePrintVis** [comment]
🥇 Yes, thats clear.

But it seems in some rare cases when the pipeline crashes, that the contaienr stays.

Did not yet had the time to repro it... before you ask :)

**Comment by waldo1001** [comment]
Can you show me the remove-docker step in yaml?

**Comment by ChristianMuetzePrintVis** [comment]
Sure:

```
- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
  inputs:
    fixed_tag: '$(docker_container_name)'
```
