### ISSUE TITLE
Issue with license import again

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#104]
Hey Guys, 

This license import task is tough cookie :)

I get my license by downloading to the working folder:

```
      - task: DownloadPackage@1
        displayName: 'Download Package license file'
        inputs:
          packageType: upack
          feed: '9ce20875-af67-4251-abf2-6decb112898c/3c947a61-d29d-4d2a-8873-aef36c0d5f8e'
          definition: 'customer_license'
          version: '*'
          downloadPath: '$(System.DefaultWorkingDirectory)/license'
          files: fin.flf 
```

I can see license gets downloaded succesfully

![image](https://user-images.githubusercontent.com/16342128/78376836-281eab00-75cf-11ea-94a7-be3686e0a8f3.png)

but if i try to timport it, ALOpsLicenseImport cannot find the file:
I believe i tried all possible variations of license_path property
```
      - task: Hodor.hodor-alops.alopslicenseimport.ALOpsLicenseImport@1
        displayName: 'ALOps License Import'
        inputs:
          nav_serverinstance: buildTest
          license_path: '.\license\fin.flf'
          print_license_info: true
```
It always give me the same error message
```
##[error]The path cannot be processed because it resolved to more than one file; only one file at a time can be processed.
````

I already had similiar case with another ALOpsTask type. See reported issue #62 
Any clues, what I'm doing wrong?
