### ISSUE TITLE
ALOps Compile Extension - The Path to c:\Run\DevOps\xxx.app can not be found...

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#109]
In the beginning of april this pipeline worked well. 
Now I get following fault during ALOPs Compile Extension App:
![JobLogScreen](https://user-images.githubusercontent.com/62563638/79247469-e0274000-7e7a-11ea-9c70-b58dfd205f6d.png)

*** AL Compiler raw logs: End
*** Start processing compile results.
*** Compile OK.
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
##[error]The Path "c:\Run\DevOps\xxx.app can not be found...

**Comment by Darren-OO** [comment]
I am seeing the same issue when compiling against the bcsandbox docker image.

It looks like the compiler is returning a non zero exit code which indicates an error, but does not provide an error message.

![image](https://user-images.githubusercontent.com/62528516/79288932-3215a780-7f07-11ea-832a-09c61b698b4e.png)

This pipeline was working last week (onprem instead of sandbox and v15 instead of v16). The compiler is showing a startup message when it succeeds, but no message when it fails.

![image](https://user-images.githubusercontent.com/62528516/79289058-77d27000-7f07-11ea-8d17-eda2966c5393.png)

Could this be related to the update to v16 docker images?

**Comment by Darren-OO** [comment]
I managed to fix this issue by enabling hyper-v process isolation and specifying 8GB memory.

```
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true
    docker_parameters: '--isolation=hyperv'
    memory_gb: 8
```

Hope this helps
