### ISSUE TITLE
How to set ALOps license key via yaml template

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#112]
I would like to set the license key for ALOps in a yaml template, so I don't have to update a variable group per Project in DevOps.

I am already using yaml templates in my pipelines and below is info about my resource reference to the templates an the use of one of template steps:

```
resources:
  repositories:
    - repository: 'yamltemplates'
      type: 'git'
      name: 'Templates/Templates'
      ref:  'refs/heads/master'

# EV: Copy EVBusinessCentralDevelopmentHelper to Build Agent
- template: 'OnPrem-Builds/CopyEVBCDevHelperToBuildAgent.yml@yamltemplates'

```

How can I set an environment variable for the ALOps license key via an yaml template file.
Please advice.

Thx. in advance.

**Comment by waldo1001** [comment]
Hi @kasperdj ,

I'm not sure that's possible.  We have been trying to do so, but without success.. .  

What I could suggest is to create a link (any kind of URL ...), and use that in all your templates.  Updating a license is simply a matter of updating that endpoint of that URL... .

would that be a solution?

**Comment by kasperdj** [comment]
Hi @waldo1001 

Your suggestion is a possible solution that I will happily go for as we already have a secure environment in Azure Blob Storage for our license files.

Can you give an example on how to process this url for ALOps to read the license file correctly?

**Comment by kasperdj** [comment]
Will this yml template example work for the ALOps License key or do I need an endpoint and if so, please give a fictive example.:

**- template: 'OnPrem-Builds/PrintALOpsLicenseKey.yml@yamltemplates'**

`steps:
- task: ALOpsDockerExec@1
  displayName: 'Print License Key for ALOps'
  inputs:
    inline_script: |
      $ALOps_LicenseId = 'abc-123456789-ewq'
      Write-Host "ALOps License Key: $ALOps_LicenseId"`

**Comment by waldo1001** [comment]
Hi Kasper,

It seems a bit odd why you're using the `ALOpsDockerExec` step for this .. why not the `ALOpsLicenseImport`?

Here an example of our template:

```yaml
parameters:
  docker_image: ''
  license_flf_url: ''
  

steps:          
- task: ALOpsDockerStart@1
  displayName: 'Start Docker Container'
  inputs:
    docker_image: ${{ parameters['docker_image'] }}
    docker_pull: true
    accept_image_eula: true
    accept_image_outdated: true
    memory_gb: 16    

- task: ALOpsDockerWait@1
  displayName: 'Wait for Docker Container'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS License Import'
  inputs:
    usedocker: true
    license_path: ${{ parameters['license_flf_url'] }}

- task: ALOpsAppPublish@1
  displayName: 'ALOPS Install AL TestTool'
  inputs:
    usedocker: true
    installaltesttool: true
    skip_verification: true
    install_al_app_names: |
     Tests-TestLibraries
     System Application Test
     System Application Test Library
     Any
     Library Assert
     Test Runner
```

**Comment by kasperdj** [comment]
Please note that this if for handling the **ALOps license key** and not the BC license file.

My simple suggestion (which I need confirmation on is OK or not for ALOps to validate the license key correctly) will basically allow me to maintain my ALOps license key in one global file and just refer to this file (via yaml templates) in my pipelines. When I get a new license key from Hodor (next year I expect), I only need to update 1 file and then all of my pipelines would use the new ALOps license key :-)

For your example:
I don't think that the the reuse of the ALOpsLicenseImport will be a good idea as it will probably mess up my flf file handling. Also in you example I cannot see how to get the license key from either a yaml template file or an url

**Comment by waldo1001** [comment]
Ah, sorry :-).

What I would recommend to do: just create a variable in a variable group that you link in your pipeline - that's it.  It needs to be an active variable (but doesn't have to be used).

I'm not sure the dockerexec will work - however, you could try to do it with a PowerShell cmdlet, and use the "vso-task set-variable" to update it with a script:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

However-I have been experimenting with this, and it doesn't always give the desired results.. .

Running it in the docker container is not necessary - we check the variable and the content of it, that's all.  It just needs to exist in the pipeline.

**Comment by kasperdj** [comment]
ok, I will try to follow the vso-task set-variable approach and update a global variable in the pipeline via a yaml template as I currently have 14 DevOps Projects and do not want to use a variable group as the is project specific - and I expect that I will receive a new license key every year.

**Comment by waldo1001** [comment]
Ok! Let us know!

We have been trying to do quite the same.
Do know you would be able to work with Azure Keyvault as well.  This way, you can set up the values in Azure, and use in variable groups all over your projects.. .  You'd only have to change the value in azure to have the value changed in all pipelines!

Freddy used it in this blogpost - this can get you going.
https://freddysblog.com/2018/11/12/developing-business-central-extensions-part-1/

**Comment by kasperdj** [comment]
I have created a simple example and would like confirmation, that ALOps can read my output correctly. See attachments:

![01 Yaml Template](https://user-images.githubusercontent.com/54669593/80367809-02ae5580-888c-11ea-8061-6d1574d49d53.png)
![02 Simple Pipeline using Template](https://user-images.githubusercontent.com/54669593/80367815-05a94600-888c-11ea-93de-f7a3380cbde2.png)
![02 Simple Pipeline using Template](https://user-images.githubusercontent.com/54669593/80367822-093ccd00-888c-11ea-9345-61061de9f157.png)
![02 Simple Pipeline using Template](https://user-images.githubusercontent.com/54669593/80367829-0b069080-888c-11ea-8fc4-5704ed4a4f08.png)

**Comment by kasperdj** [comment]
@AdminHodor or @waldo1001 can you please confirm that my suggestion (see to last images from previous comment) provides the correct information for ALOps to read the ALOps License Key correctly?

Thx. in advance.

**Comment by waldo1001** [comment]
Hi Kasper,

what is unclear to me: did you create the variable to set up the license id?  All I can see is the write-host?

**Comment by kasperdj** [comment]
In the example, there is an unused variable in my primary yaml file.
The License Key is assigned to a variable in the yaml template and afterward via write-host printed to the console

**Comment by kasperdj** [comment]
This is the code in the yaml template - just for explanation:

![image](https://user-images.githubusercontent.com/54669593/80578112-4af28280-8a08-11ea-94e1-52eabe232d3e.png)

**Comment by AdminHodor** [comment]
Dear @kasperdj ,

The ID is stored in a regular DevOps Pipeline variable. The can be set via the classic editor, or mapped directly into the yml.

If you want to set the variable using Script/Templates, you can use following snippet to set the ID (first step, before all ALOps tasks).

```yml
- task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: '"##vso[task.setvariable variable=alops-licenseid]00000000-0000-0000-0000-000000000000"'
```

Kind regards,

**Comment by kasperdj** [comment]
Thx. for the input.

I have updated my license test pipeline and yaml template.

I have defined an environment variable in my pipeline that is correctly updated via my yaml template and written to the log.

I have attached screenshots for documentation.

So far I am happy, I just don't know if ALOps is reading the license key correctly as the ALOps steps does not "confirm" this in the log. Can you confirm that the attached solution solves this issue?

Thx. in advance.

![01 - License Test Pipeline Overview](https://user-images.githubusercontent.com/54669593/80605525-835b8600-8a33-11ea-9ebe-5aa046603050.png)
![02 - License Test Pipeline yaml](https://user-images.githubusercontent.com/54669593/80605527-83f41c80-8a33-11ea-8625-53bc3c1dc6c6.png)
![03 - Set ALOps License Key via Template](https://user-images.githubusercontent.com/54669593/80605530-848cb300-8a33-11ea-9296-c679387d4afe.png)
![04 - Log Analysis - Environment variable correctly updated from template and printed to log via write-host code](https://user-images.githubusercontent.com/54669593/80605532-85254980-8a33-11ea-9e9c-29cdc8ccc88e.png)

**Comment by waldo1001** [comment]
You can remove this part .. afaik, that hasn't got any use:
![image](https://user-images.githubusercontent.com/12088142/80612674-958df200-8a3c-11ea-9f18-40e4633bb1b8.png)
Also, I'm not sure about the "echo" in powershell, which you use here:
[image](https://user-images.githubusercontent.com/12088142/80612738-ac344900-8a3c-11ea-9136-9750469a8c34.png)
try to change that to:
```yaml
- task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'write-host "##vso[task.setvariable variable=alops-licenseid]00000000-0000-0000-0000-000000000000"'
```

In the output of your pipeline, you should see the used alops-key (you don't have to foresee any kind of step to show it with your own write-host - therefore, please remove that step "Print ALOps License Key")
