### ISSUE TITLE
Issue while publishing app - Windows PowerShell is in NonInteractive mode.

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#114]
Hey guys, 

I receive this error message while trying to publish the app. Compilation of the app goes through, but fails to publish it. We are using docker image for all the steps.

```
Starting: Publish AL-App
==============================================================================
Task         : ALOps App Publish
Description  : Publish NAV Apps
Version      : 1.428.1196
Author       : Hodor
Help         : Publish Business Central extension to service tier.
==============================================================================

....


*** Sync Tenant default
*** Sync App [MyApp] on tenant [default]
*** Install App [MyApp] on tenant [default]
WARNING: UnhandledErrorMessage

**************************************

##[error]Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
Async Command Start: Add Build Tag

...
```

Code for app publishing is super simple:

```
- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 
```

**Comment by gintuoklis** [comment]
We noticed that issue happens only for extensions, that has decency. Dependency app is published first, then extension compiles, and then fails on the publishing step (shown above)

**Comment by waldo1001** [comment]
Can you share the entire yaml?

**Comment by gintuoklis** [comment]
```
parameters:
- name: imageName 
  type: string 
  default: 'devops.azurecr.io/imv:latest'
- name: dependantApp
  type: string  
  default: ''

steps:
- checkout: self
  clean: true 
  
- task: Docker@2
  displayName: Login to ACR
  inputs:
   command: login
   containerRegistry: DevopsRegistryServiceConnection

- task: ALOpsDockerStart@1
  inputs:
    docker_image: ${{ parameters.imageName }}
    docker_pull: true
    enable_symbol_loading: true
    accept_image_outdated: true 

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- ${{ if ne(parameters.dependantApp, '') }}:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Dependant App'
    inputs:
      buildType: 'specific'
      project: '9ce20875-af67-4251-abf2-6decb112898c'
      pipeline: ${{ parameters.dependantApp }}
      buildVersionToDownload: 'latest'
      downloadType: 'specific'
      itemPattern: '**/*.app'
      downloadPath: '$(System.ArtifactsDirectory)'

- ${{ if ne(parameters.dependantApp, '') }}:    
  - task: ALOpsAppPublish@1
    displayName: 'Publish Dependant App'
    inputs:
      usedocker: true
      nav_artifact_app_filter: '*.app'   
      skip_verification: true 

- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

 - task: ALOpsAppTest@1
   displayName: 'Run TestSuite'
   inputs:
     usedocker: true
     testfilter: '(50000..70099|70301..99999)&<>53051'
     import_testtoolkit: false
     show_available_tests: true

   continueOnError: true

 - task: PublishTestResults@2
   displayName: 'Publish Test Results **/TestResults.xml'
   inputs:
     testResultsFormat: XUnit
     testResultsFiles: '**/TestResults.xml'
     testRunTitle: 'BC Test Results: $(Build.BuildId)'

- powershell: |
   $netpackagesExists = Test-Path -Path "$(Pipeline.Workspace)\.netpackages\"
   Write-Output "##vso[task.setvariable variable=netpackagesExists]$netpackagesExists"
  displayName: 'Check If netpackagesExists'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Dlls '
  condition: eq(variables['netpackagesExists'], True)
  inputs:
    targetPath: '.netpackages'
    artifact: dlls
  
- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()

```
