### ISSUE TITLE
Issue running test case

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#115]
Hey Guys, 

We started experiencing issues with running test cases today:
We are running NAV container of version 14.0.35916.0 which is based on this image: mcr.microsoft.com/businesscentral/onprem:1904-cu4-w1-ltsc2019
self-hosted Agent is running on windows server 2019
Any suggestions how to fix it?

```
Starting: Run TestSuite
==============================================================================
Task         : ALOps App Test
Description  : ALOps App Test
Version      : 1.428.1196
Author       : Hodor
Help         : Run Business Central Test-Suite and collect results.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Working folder: C:\agent\_work\46\s
***
*** Prepare Docker Session
*** Connect Docker Session
*** Initiate Docker Session
*** Copy Modules to Docker
*** Setup Docker Session
*** Checking for container-specific Test Assemblies
*** Using container-specific Test Assemblies
*** Import Modules in Docker Session
*** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
VERBOSE: Loading module from path 'C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll'.
*** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\140\Service\Newtonsoft.Json.dll]
*** Import Modules in Docker Session: class_ClientContext
*** Setup BC Credentials in Docker
*** Set TCP Keep-Alive
*** Start TestSuite
*** Running TestSuite with authentication [NavUserPassword] with User [***]
*** Run warm-up with page [130409]
*** Warm-up Client Context
UnhandledException : Object reference not set to an instance of an object.
at <ScriptBlock>, <No file>: line 105
at InvokeInteractionAndCatchForm, <No file>: line 220
at OpenForm, <No file>: line 231
at Test-OpenForm, <No file>: line 7
at <ScriptBlock>, <No file>: line 14
at <ScriptBlock>, <No file>: line 1
Current Interaction: Microsoft.Dynamics.Framework.UI.Client.Interactions.OpenFormInteraction
Time spend: 16 seconds
*** Create Client Context
*** Add Tests to Default-TestSuite with filter [(50000..70099|70301..99999)&<>53051]
UnhandledException : Object reference not set to an instance of an object.
at <ScriptBlock>, <No file>: line 105
at InvokeInteractionAndCatchForm, <No file>: line 220
at OpenForm, <No file>: line 231
at Add-AllTestCodeunits, <No file>: line 10
at <ScriptBlock>, <No file>: line 45
at <ScriptBlock>, <No file>: line 1
Current Interaction: Microsoft.Dynamics.Framework.UI.Client.Interactions.OpenFormInteraction
Time spend: 0 seconds
##[error]Run-Test-Exception: Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
*** Get XUnit Test file from [] to [C:\agent\_work\46\s\]
##[error]Cannot bind argument to parameter 'Path' because it is null.
Finishing: Run TestSuite
```

```
- task: ALOpsAppTest@1
  displayName: 'Run TestSuite'
  inputs:
    usedocker: true
    testfilter: '(50000..70099|70301..99999)&<>53051'
    import_testtoolkit: false
    show_available_tests: true

```

**Comment by waldo1001** [comment]
Please share entire yaml .. 
this is a working yaml for v14: https://github.com/HodorNV/ALOps/blob/master/Examples/05_UseDocker_TestTool_v14.yml

did you compare/base on that one?

**Comment by gintuoklis** [comment]
see our yaml here:
https://github.com/HodorNV/ALOps/issues/114#issuecomment-616841790

I looked at it, but couldn't find anything that could have caused it

**Comment by waldo1001** [comment]
I don't see you importing the Test Toolkit?

Look at this step from the example that I mentioned:
```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOps Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    show_available_tests: true
    import_testtoolkit: true
    failed_test_action: 'Ignore'
  continueOnError: true  
```

In yours, it's set explicitly to " import_testtoolkit: false"
