### ISSUE TITLE
ALOps SaaS Get Extensions / Publish Extension

### ISSUE THREAD

**Issue by InnoNavSupport** [HodorNV/ALOps#116]
Hi,
is it possible to use basic authentication instead of OAuth2 because of the MultiFactorAuthentication issues not solved right now by microsoft? Switch of MFA is also not an option because of this warning message always showing up and deny access without using a GUI.
Regards

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,
Yess this is possible! We redesigned the API interface in ALOps for this based on the feedback we got from the last WebCast. Please be patient for a couple of days, we should be able to release the new task this week. We already have successful test on deploying apps to BC SaaS using the WebserviceAccessKey.

We'll report status on this issue as soon as the release is available!

Kind regards,

**Comment by AdminHodor** [comment]
Dear @InnoNavSupport ,

Fix for this is in version v1.429, which we just released. Please note we replaced both the ALOpsSaaS tasks with one new task:  ALOpsExtensionAPI. Setup is similar and allows for all types of authentication. For SaaS you can use the BC-Username and a WebserviceAccessKey instead of OAuth.

Get Extensions:
```yaml
- task: ALOpsExtensionAPI@1
  displayName: 'Get Extensions - Azure Basic WebserviceAccessKey'
  inputs:
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api'
    authentication: basic
    azure_tenant_id: '$(azure_tenant_id)'
    username: '$(bc_ws_user)'
    password: '$(bc_ws_pass)'
```

Publish Extension:
```yaml
- task: ALOpsExtensionAPI@1
  displayName: 'Publish Extensions - Azure Basic WebserviceAccessKey'
  inputs:
    interaction: publish
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api'
    authentication: basic
    azure_tenant_id: '$(azure_tenant_id)'
    username: '$(bc_user)'
    password: '$(bc_password)'
    artifact_filter: '*.app'
```

Could you please validate the solution?

Kind regards,
