### ISSUE TITLE
ALOps Docker Wait : Exception calling "AddAccessRule"

### ISSUE THREAD

**Issue by ThierryPermentier** [HodorNV/ALOps#118]
YAML:

```
steps:
- task: Hodor.hodor-alops.alopsdockerwait.ALOpsDockerWait@1
  displayName: 'ALOps Docker Wait'
```

RESULT:

```
Starting: ALOps Docker Wait
==============================================================================
Task         : ALOps Docker Wait
Description  : ALOps Docker Wait
Version      : 1.428.1196
Author       : Hodor
Help         : Wait until the Business Central container is started.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Waiting for Docker Container Log Entry: Ready for connections!
Initializing...
Starting Container
Hostname is 8c03854745b6
PublicDnsName is 8c03854745b6
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 7B3ED277CCB7E68B97F754A077D7E36390CCDFCF
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Exception calling "AddAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
##[error]*** Docker container exited.
Finishing: ALOps Docker Wait
```

PREVIOUS STEP:

```
steps:
- task: Hodor.hodor-alops.alopsdockerstart.ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox:be-ltsc2016'
    memory_gb: 6
```

```
Starting: ALOps Docker Start
==============================================================================
Task         : ALOps Docker Start
Description  : ALOps Docker Start
Version      : 1.428.1196
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
*** Importing required PS-Functions
*** Validate configuration
*** Pull Docker Image: mcr.microsoft.com/businesscentral/sandbox:be-ltsc2016
be-ltsc2016: Pulling from businesscentral/sandbox
Digest: sha256:1eda121c14107969d44e5ea46aa9a0905860237e30539ed8b02b16f0bb056584
Status: Image is up to date for mcr.microsoft.com/businesscentral/sandbox:be-ltsc2016
mcr.microsoft.com/businesscentral/sandbox:be-ltsc2016
*** Pull Docker Image: mcr.microsoft.com/businesscentral/sandbox:be-ltsc2016 [OK]

"docker" run --detach --memory 6G --env accept_eula=Y --restart no --label TFSBuild=CMFRT_Base_2342 mcr.microsoft.com/businesscentral/sandbox:be-ltsc2016
*** Container Started: 8c03854745b67a69c7080ed8c1454b336499d646bd131fca7e911060cbf62274
*** Container Labels:


TFSBuild   : CMFRT_Base_2342
country    : be
created    : 202004201111
cu         : 
eula       : https://go.microsoft.com/fwlink/?linkid=861843
legal      : http://go.microsoft.com/fwlink/?LinkId=837447
maintainer : Dynamics SMB
nav        : 
osversion  : 10.0.14393.3443
platform   : 16.0.11233.12436
tag        : 0.0.9.99
version    : 16.0.11240.12474

*** Docker Start OK.
*** Cleanup VSTS Environment: True
Async Command Start: Add Build Tag
Build '2342' has following tags now: mcr.microsoft.com/businesscentral/sandbox-be-ltsc2016
Async Command End: Add Build Tag
Async Command Start: Add Build Tag
Build '2342' has following tags now: mcr.microsoft.com/businesscentral/sandbox-be-ltsc2016, BC.Platform.16.0.11233.12436
Async Command End: Add Build Tag
Async Command Start: Add Build Tag
Build '2342' has following tags now: mcr.microsoft.com/businesscentral/sandbox-be-ltsc2016, BC.Platform.16.0.11233.12436, BC.Version.16.0.11240.12474
Async Command End: Add Build Tag
Finishing: ALOps Docker Start
```

**Comment by waldo1001** [comment]
Hi,
Can you give me more info on the DevOps Build Agent?  I hope it's not a Win10?
Furthermore, does it have windows update?
Can you try to run the pipeline with Hyper-V isolation?  This is how you do it:

```yaml
    - task: ALOpsDockerStart@1
      inputs:
        docker_image: '$(ContainerVersion)'
        accept_image_outdated: true
        enable_symbol_loading: true
        memory_gb: '8'
        container_restart: 'always'
        docker_parameters: '--isolation=hyperv'
```
