### ISSUE TITLE
batch_publish_folder behaves differently while using docker

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#120]
Hey Guys, 

I noticed a difference with _batch_publish_folder_

If I run it  **usedocker: false**, it works fine. It resolves multiples files perfectly fine. 
```
  - task: ALOpsAppPublish@1
    displayName: 'Publish Dependant App'
    inputs:
      usedocker: false
      nav_artifact_app_filter: '*.app'   
      skip_verification: true
      batch_publish_folder: '$(System.ArtifactsDirectory)\**\'
      nav_serverinstance: buildtest
```
![image](https://user-images.githubusercontent.com/16342128/80498200-b9353780-896b-11ea-935f-f26dbf94c8f2.png)

But if I run it using docker, I get a problem with it. As you can see in the error bellow, you can see it tries c:\run\devops\C:\agent\_work\90\a\**\

```
  - task: ALOpsAppPublish@1
    displayName: 'Publish Dependant App'
    inputs:
      usedocker: true
      nav_artifact_app_filter: '*.app'   
      skip_verification: true
      batch_publish_folder: '$(System.ArtifactsDirectory)\**\'
```
![image](https://user-images.githubusercontent.com/16342128/80498474-0fa27600-896c-11ea-8996-49562fb4344c.png)

Any advice, how i car work around this limitation?

Best Regards, 
Gintautas

**Comment by waldo1001** [comment]
For the batch-publish when using docker, the apps need to be in Docker, and you see the path it adds to your relative path "C:\run\devops".

Where do the app-files come from?

**Comment by waldo1001** [comment]
please share the complete pipeline

**Comment by gintuoklis** [comment]
App files comes from another build pipeline. I download them using DownloadBuildArtifacts@0.
It's downloaded to the agent's artifact directory, not to the docker's file system.

```
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Dependant App'
    inputs:
      buildType: 'specific'
      project: '9ce20875-af67-4251-abf2-6decb112898c'
      pipeline: ${{ parameters.dependantApp }}
      buildVersionToDownload: 'latest'
      downloadType: 'specific'
      itemPattern: '**/*.app'
      downloadPath: '$(System.ArtifactsDirectory)'
```

**Comment by gintuoklis** [comment]
I think I could copy those files using `docker cp` to the container. But I don't know containers name. Does ALOpsDockerStart sets any environment variable with container name, so I could use it?

```
- task: ALOpsDockerStart@1
  inputs:
    docker_image: ${{ parameters.imageName }}
    docker_pull: true
    enable_symbol_loading: true
    accept_image_outdated: true 

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
```

**Comment by gintuoklis** [comment]
Managed to fix it by ditching _batch_publish_folder_ option and using loops. 
Just one issue, I need to store dependantApps in the right order while your code does it dependecy ordering automatically. Nevertheless it works now.

Some feedback regarding your documentation. 
- when it comes to paths, it not always clear where does it look for it: on docker, or on my build workspace 
- it's not always clear which parameters are able to resolve ** nicely which not (don't have example now). 
- some parameters are totally mystery. for e.g. artifact_path on ALOpsAppPublish. How does it work together with app_artifact_filter?
- not clear what 'relative to $(path_to_publish)' means. Is it '$(Build.ArtifactStagingDirectory)'?

Here's my code with snippets. 
```
- ${{ if ne(parameters.dependantApps, '') }}:
  - ${{ each app in parameters.dependantApps }}:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Dependant App'
      inputs:
        buildType: 'specific'
        project: '9ce20875-af67-4251-abf2-6decb112898c'
        pipeline: ${{ app }}
        buildVersionToDownload: 'latest'
        downloadType: 'specific'
        itemPattern: '**/*.app'
        downloadPath: '$(Pipeline.Workspace)\s\${{ app }}\'

- ${{ if ne(parameters.dependantApps, '') }}:   
  - ${{ each app in parameters.dependantApps }}: 
    - task: ALOpsAppPublish@1
      displayName: 'Publish Dependant App'
      inputs:
        usedocker: true
        nav_artifact_app_filter: '**\${{ app }}\**\*.app'  
        skip_verification: true
```
