### ISSUE TITLE
Outdated Image if you use docker_parameters: '--isolation=hyperv'?

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#129]
I like to solve issue #119. If I add `docker_parameters: '--isolation=hyperv'` to my **ALOpsDockerStart@1** task, 
```yaml
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/onprem:de'
    docker_pull: true
    memory_gb: '8'
    docker_parameters: '--isolation=hyperv'
```
the task **ALOpsDockerWait@1** results in an error:

> You are trying to run a container which is more than 90 days old.
>     Microsoft recommends that you always run the latest version of our containers.
>     Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
> ##[error]*** Docker container exited.

Does anyone know why this is?

I like to use non outdated containers... :-D

**Comment by waldo1001** [comment]
That means it works ;-).  You just have to set the "accept outdated" switch ;-).

```yaml
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/onprem:de'
    docker_pull: true
    memory_gb: '8'
    docker_parameters: '--isolation=hyperv'
    accept_image_outdated: True
```

Microsoft usually does not update images when there is no reason to.  So, if you are using a BC version of 3 months or older .. it might happen that it's outdated.. .

There is nothing wrong with using the parameter ;-)

**Comment by DanielGoehler** [comment]
But mcr.microsoft.com/businesscentral/onprem:de is the current German BC 16.1 OnPrem image.

**Comment by waldo1001** [comment]
Ok, I didn't look at the exact image.  I'll have a look ...

**Comment by DanielGoehler** [comment]
Without isolation=hyperv and the same image this didn‘t happen. But then App Compilation don‘t work.

**Comment by fvet** [comment]
@waldo1001  Our vNext pipelines also fail on the 'outdated' message, although we're targetting sandbox and sandbox-master. Any clue?
```

- task: ALOpsDockerStart@1
  displayName: 'Start Docker Container'
  inputs:
    docker_image: 'bcinsider.azurecr.io/bcsandbox-master'
    docker_pull: true
    dockerauthentication: 'UsernamePassword'
    docker_username: $(docker_username)
    docker_password: $(docker_password)
    docker_registry: 'bcinsider.azurecr.io'
```
