### ISSUE TITLE
Build Pipeline: Is there a best practice to upload custom DLLs into the docker container?

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#132]
In the build pipeline I would like to upload custom DLLs into the Docker Container. Is there a best practice for doing that? 

One way would be to use **Copy-FileToNavContainer** of the navcontainerhelper. For that I need the current container name. Is there a way to fetch that container name in the Build Pipeline?
```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Copy-FileToNavContainer -localPath .netpackages\*.dll -containerPath "C:\Program Files\Microsoft Dynamics NAV\140\Service\Add-ins" -containerName ???'
    failOnStderr: true
```
