### ISSUE TITLE
ALOps Package Import - There is no AllObj within the filter.

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#137]
We've integrated a rapidstart file to the build pipeline. The rapidstart file can be imported / applied via the UI and should thus be valid. however, when import the rapidstart via ALOps, I get following output:

```
*** Start RapidStart Package Validation
*** RapidStart Package Handler: no configuration found, defaulting to all *.rapidstart packages
*** RapidStart Start Package Validation
  * Reading Rapidstart package: .\Test\configurationpackages\PackageNVT_STATUS_NLB_17.rapidstart
    + 1 tables, 145 records
*** RapidStart Configuration Loaded
    - UID        : 160cc460-5cef-486c-8085-9785a401b05f
    - Name       : --AutoGenerated--
    - Packages   : 
    - Tables     : 1
    - Records    : 145
    - Exceptions : 0
    - Valid      : True
*** Check WebService: ConfigurationPackages
*** Create WebService: ConfigurationPackages
##[error]There is no AllObj within the filter.

Filters: Object Type: Page, Object ID: 8615
Finishing: Import RapidStarts

```

Table reference in the rapidstart should exist, since if has been compiled / published in a previous step.

![image](https://user-images.githubusercontent.com/25268332/84408521-8b9b0980-ac0c-11ea-94c0-0d1566f6763e.png)

**Comment by fvet** [comment]
For you info, it seems not related with the contents of the rapidstart file. Even if no rapidstart packages are present, it still fails.

```
*** Start RapidStart Package Validation
*** RapidStart Package Handler: no configuration found, defaulting to all *.rapidstart packages
*** RapidStart Start Package Validation
*** RapidStart Configuration Loaded
    - UID        : 4039d54b-f776-4ced-ba37-b3b5ff211db7
    - Name       : --AutoGenerated--
    - Packages   : 0
    - Tables     : 0
    - Records    : 0
    - Exceptions : 0
    - Valid      : True
*** Check WebService: ConfigurationPackages
*** Create WebService: ConfigurationPackages
##[error]There is no AllObj within the filter.

Filters: Object Type: Page, Object ID: 8615
Finishing: Import RapidStarts

```

**Comment by waldo1001** [comment]
Hi, it seems the stem works just fine, but there is a problem with the NAV environment.  Does page 8615 exist in your environment.

can I ask which version/container/environment u use and how you set it up?
can you verify the page actually exists?
can you verify it's in the license permissions and other permission sets?

**Comment by fvet** [comment]
Here's the version we use. I'll check if the page exists.

```
Starting: Start Docker Container
==============================================================================
Task         : ALOps Docker Start
Description  : ALOps Docker Start
Version      : 1.429.1405
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
*** Importing required PS-Functions
*** Validate configuration
*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
Cleanup old Tasks
*** Memory Status: 17.45/24 (72.72% Free)
Add tag 'ltsc2019' to image for OS Match
*** Pull Docker Image: mcr.microsoft.com/businesscentral/onprem:16.1.12629.12805-w1-ltsc2019
16.1.12629.12805-w1-ltsc2019: Pulling from businesscentral/onprem
Digest: sha256:a153344582066a60c0eb5ef22a16f073c4081f7fb058dd5203627cace731dca1
Status: Image is up to date for mcr.microsoft.com/businesscentral/onprem:16.1.12629.12805-w1-ltsc2019
mcr.microsoft.com/businesscentral/onprem:16.1.12629.12805-w1-ltsc2019
*** Pull Docker Image: mcr.microsoft.com/businesscentral/onprem:16.1.12629.12805-w1-ltsc2019 [OK]

"docker" run --detach --memory 8G --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=Navitrans.Core_2118 mcr.microsoft.com/businesscentral/onprem:16.1.12629.12805-w1-ltsc2019
*** Container Started: d10c7f48ef3d4e253548c2afec1a05e6ba63899fbec741a92b6c1ae3b2fb43ae
*** Container Labels:


TFSBuild   : Navitrans.Core_2118
country    : W1
created    : 202005120738
cu         : cu1
eula       : https://go.microsoft.com/fwlink/?linkid=861843
legal      : http://go.microsoft.com/fwlink/?LinkId=837447
maintainer : Dynamics SMB
nav        : 
osversion  : 10.0.17763.973
platform   : 16.0.12630.12758
tag        : 0.0.9.99
version    : 16.1.12629.12805
```

**Comment by fvet** [comment]
Tried a lot, but apparently not the right things yet ... :) 
Executed the script below in several steps.

```
name: $(Build.BuildId)

variables:
- group: PipelineVariables

stages:
  - stage: Build
    jobs:
      - job: Build
        pool: Build Agents
        steps:       
          - task: ALOpsDockerStart@1
            displayName: 'Start Docker Container'
            inputs:
              docker_image: 'mcr.microsoft.com/businesscentral/onprem:16.1.12629.12805-w1'
              accept_image_outdated: true

          - task: ALOpsDockerWait@1
            displayName: 'Wait for Docker Container'
            inputs:
              search_string: 'Ready for connections!'
            
          - task: ALOpsLicenseImport@1
            displayName: 'Import License'
            inputs:
              usedocker: true
              license_path: '$(nvt_license)'
              print_license_info: true

          - task: ALOpsDockerExec@1
            displayName: 'Restart BC Service'
            inputs:
              inline_script: |
                Restart-NAVServerInstance -ServerInstance 'BC'

          - task: ALOpsPackageImport@1
            inputs:
              usedocker: true
```
Build agent is a 2019 server, installed according to the ALOps recommendations.

All untill the ALOpsLicenseImport step works fine. Got my BC environments, could login via the browser and got access to page 8615. So the page object it's in the db.

- To logon via the browser I had to connect by IP instead of hostname. First updated the etc\hosts file manually, then tried adding dockerparameters '--env updatehosts=Y'
- Got a certificate warning, downloaded the container certificate and installed it in the Trusted Roots
- Had to disable the IE Enhanced Security 

Adding the ALOpsLicenseImport step to upload our license and force restart the Instance gave the same results. Still able to access to page 8615, so the license is valid. 

Added the page 8615 to the webservices and accessed it via OData URL (by IP). Authenticated via admin/userpassword (https://172.18.247.55:7048/BC/ODataV4/Company('CRONUS%20International%20Ltd.')/ConfigurationPackages)

Adding the ALOpsPackageImport steps still fails with the same warning. Here I had no luck connecting via the webclient to the BC, since the authentication changed to Windows and I've got a communication protocol mismatch. Didn't knew which windows credentials to use to test a standard webservice.
(e.g. https://172.18.247.55:7048/BC/ODataV4/Company('CRONUS%20International%20Ltd.')/workflowCustomers)

Objects / license seems fine, so seems like security / authentication / webservice connection related instead.

Maybe the docker / event viewer logs can give you more insight?
[docker_logs_final.txt](https://github.com/HodorNV/ALOps/files/4774276/docker_logs_final.txt)
