### ISSUE TITLE
BC moving from Docker images to 'BC Artifacts'

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#144]
What kind of changes should we expect from ALOps when reading through https://freddysblog.com/2020/06/25/changing-the-way-you-run-business-central-in-docker/

- What will be the impact on our current pipelines? (we're especially using fixed build / nextminor / nextmajor images)
- Will ALOps provide some documentation / instructions on how to update pipelines / implement the new artifacts?
- Any ALOps timing / planning (esp. since the insider builds would only ship till end of July?) 

Can we expect some ALOps improvements on the 'compile' part (if we would not be interested in publishing / running tests as part of the pipeline)? (https://tobiasfenster.io/making-use-of-the-new-bc-artifacts)

**Comment by waldo1001** [comment]
Hi Frédéric,

we are working on it.  

We will try to make the experience as seemless as at all possible.  But it has to make sense.  So many people using ALOps in so many different ways .. .

By the way ... you can already use this: just create your images and refer to those images in the pipeline.  Only, we want to make an extra step to be able to create images based on artifact urls .. that's more user friendly.

Do know there is not an immediate expected advantage.  In a way, we need to do an extra step (building an image) to get exactly the same like we were able to download.. .

More coming very soon!

**Comment by kasperdj** [comment]
Hi @waldo1001 

Microsoft has already stopped releasing new images at mcr.microsoft.com/businesscentral
As I understand ALOps can already utilize BC Artifacts based your previous comments. 
I would like to test this out and get an overview of the pipeline updates needed for this.

In one of my pipelines I use the DK image for BC16.3:

name: 'dockerimage'
value: 'mcr.microsoft.com/businesscentral/onprem:1910-rtm-dk-ltsc2019'

This works fine, but if I want to work on e.g. BC16.4 I need to use BC Artificats.
Can you provide yaml configuration examples for using BC Artifacts for using:

1. BC16.4 DK
2. BC16 latest DK version (latest minor)
3. BC16 next minor DK version
4. Upcoming next major DK version

Thx. in advance.

**Comment by waldo1001** [comment]
Hi Kasper,

What I would do, is create a pipeline to create all images on a host, and schedule it overnight.  The pipeline could look something like this:

```yaml
name: Build Docker Images

pool: WaldoHetzner

variables:
  - group: Secrets
  - name: DockerImageName.current
    value: bccurrent
  - name: DockerImageName.insider
    value: bcinsider

steps:
# Update BcContainerHelper
- task: PowerShell@2
  displayName: Install/Update BcContainerHelper
  inputs:
    targetType: 'inline'
    script: |
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12
      install-module BcContainerHelper -verbose -force
      Import-Module bccontainerhelper

# W1
- task: PowerShell@2
  displayName: Creating W1 Image
  inputs:
    targetType: 'inline'
    script: |
      $artifactUrl = Get-BCArtifactUrl
      New-BcImage -artifactUrl $artifactUrl -imageName $(DockerImageName.current):w1-latest

# Belgium
- task: PowerShell@2
  displayName: Creating BE Image
  inputs:
    targetType: 'inline'
    script: |
      $artifactUrl = Get-BCArtifactUrl -country be
      New-BcImage -artifactUrl $artifactUrl -imageName $(DockerImageName.current):be-latest

# Belgium - Insider 
- task: PowerShell@2
  displayName: Creating BE Image (insider)
  inputs:
    targetType: 'inline'
    script: |
      $artifactUrl = Get-bcartifacturl -country be -storageAccount bcinsider -sasToken "$(bc.insider.sasToken)"
      New-BcImage -artifactUrl $artifactUrl -imageName $(DockerImageName.current):be-latest

# Images
- task: PowerShell@2
  displayName: Docker Images Info
  inputs:
    targetType: 'inline'
    script: |
      docker images
```

To get to the exact artifacts you're after, you can do this:

1. BC16.4 DK: `Get-BCArtifactUrl -country dk -version 16.4`
2. BC16 latest DK version (latest minor): `Get-BCArtifactUrl -country dk -select Latest`
3. BC16 next minor DK version: `Get-BCArtifactUrl -country dk -select SecondToLastMajor  -storageAccount bcinsider -sasToken "<thecurrentsastoken>"`
4. Upcoming next major DK version: `Get-BCArtifactUrl -country dk -select Latest  -storageAccount bcinsider -sasToken "<thecurrentsastoken>"`


We have ideas to make it much easier with ALOps to work with Artifacts, but as said, we need this month to finish that.. .  IN the meantime, the above yaml does work.
