### ISSUE TITLE
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by sriniGalway** [HodorNV/ALOps#158]
Hi Waldo,

We have a BC application YYYY which is dependant on XXXX.
The app XXXX is compiled and published (using ALops and with docker).
 => Publishing App 'XXXX v1.0.0.8'
we can view the app under
Published
-Dynamics 365 App
--compilelog.txt
--EEEE_XXXX_1.0.0.8.app

The app.json file of Application YYYY is as below:
{
  "id": "AAAA",
  "name": "YYYY",
  "publisher": "BBBB",
  "version": "1.0.4.0",
---
  "dependencies": [
    {
      "id": "DDDD",
      "publisher": "EEEE",
      "name": "X",
      "version": "1.0.0.8"
    }
  ],
----
}

Below is error snippet from the compile of Application YYYY
*** Download Application-Symbols for [XXXX v1.0.0.8]
*** Downloading NAV Symbols for [XXXXXv1.0.0.8]
*** Downloading NAV Symbols from [https://1999777bf640:7049/BC/dev/packages?publisher=EEEE&appName=XXXX&versionText=1.0.0.8&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
Invoke-RestMethod -Method Get -Uri https://1999777bf640:7049/BC/dev/packages?publisher=EEEE&appName=XXXX&versionText=1.0.0.8&tenant=default
##[error]Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

we are using docker image:
docker_image: 'mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019'
Can you kindly advice how to get the dependant app XXXX while compiling the YYYY app in ALOps using docker.

Thanks in advance

Regards
Srini

**Comment by mrabus** [comment]
Your case seems to be the same as my issue #157

**Comment by sriniGalway** [comment]
Yes @mrabus , seems similar as #157
let's see what Waldo has to say on this.

**Comment by waldo1001** [comment]
Can you give me the yaml you use?  and the output of the downloadartifact, publish and the failing step?

**Comment by sriniGalway** [comment]
Hi Waldo,

Thanks for the reply.
Below is the yaml file: We have a BC application YYYY which is dependant on XXXX.

```
name: $(Build.BuildId)

trigger: none

pool: Default

variables:
- group: license
- group: BC-Version

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019'
    accept_image_outdated: true
    enable_symbol_loading: true
    memory_gb: 6
    docker_pull: true
    container_restart: always
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
    
- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bcdeploylicense)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $a = Get-Content './XXXX/app.json' -raw | ConvertFrom-Json
            $a.update | % {if($_.name -eq 'XXXX'){$_.version=$(XXXX_dev2_version)}}
            $a | ConvertTo-Json -depth 32| set-content './YYYY/app.json'

- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '$(YYYY_dev2_version)'
    targetproject: './YYYY/app.json'
    setup_working_folder: true
    failed_on_warnings: false 
    al_analyzer: PerTenantExtensionCop,UICop

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: 'YYYY_*.app'
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()

```
downloadartifact for XXXX is the app file and compilelog.txt .

the failing step is ALOpscompiler and below is the error:
Below is error snippet from the compile of Application YYYY
*** Download Application-Symbols for [XXXX v1.0.0.8]
*** Downloading NAV Symbols for [XXXXXv1.0.0.8]
*** Downloading NAV Symbols from [https://1999777bf640:7049/BC/dev/packages?publisher=EEEE&appName=XXXX&versionText=1.0.0.8&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
Invoke-RestMethod -Method Get -Uri https://1999777bf640:7049/BC/dev/packages?publisher=EEEE&appName=XXXX&versionText=1.0.0.8&tenant=default
##[error]Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

Thanks for the help.

**Comment by mrabus** [comment]
Don't you have to publish the downloaded artifact BEFORE compiling the extension?

**Comment by waldo1001** [comment]
> Don't you have to publish the downloaded artifact BEFORE compiling the extension?

Exactly .. :-)

try this:

```yaml
name: $(Build.BuildId)

trigger: none

pool: Default

variables:
- group: license
- group: BC-Version

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019'
    accept_image_outdated: true
    enable_symbol_loading: true
    memory_gb: 6
    docker_pull: true
    container_restart: always
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
    
- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bcdeploylicense)

- task: DownloadBuildArtifacts@0
  displayName: 'Download XXXX'
  inputs:
    buildType: 'specific'
    project: 'a3503a04-5599-48cd-b0fc-29d84ef3a54e'
    pipeline: '71'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/dev2'
    downloadType: 'specific'
    itemPattern: '*/**.app'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'

- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '$(YYYY_dev2_version)'
    targetproject: './YYYY/app.json'
    setup_working_folder: true
    failed_on_warnings: false 
    al_analyzer: PerTenantExtensionCop,UICop

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: 'YYYY_*.app'
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
```
