### ISSUE TITLE
Question: How to find container's name & login details?

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#171]
How can i know container name & it's login details that is created during AlOPsDockerStart/Wait so i could use it within my scripts.
The reason, i would like to know container name, because i want to run some custom script for it. (like copying files and etc or accessing database within the container)

This is how i spin my container
```
- task: ALOpsDockerStart@1
  inputs:
    fixed_tag: 'develop_testing'
    docker_image: 'myrepository.azurecr.io/imv:latest'

- task: ALOpsDockerWait@1
  inputs:
    fixed_tag: 'develop_testing'
    search_string: 'Ready for connections!'
    setup_working_folder: false
    usecompression: false
```

I found on your release notes you talk about global parameters, but i am not sure if that it is what i am looking for and how to access it.

> Use global parameters [alops-docker-computer] / [alops-docker-username] / [alops-docker-password] 
> https://github.com/HodorNV/ALOps/blob/9be4e72731f0f881137c0f7cf6c66d058b245c08/Documentation/changelog.md

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

The parameters you mention (Use global parameters [alops-docker-computer] / [alops-docker-username] / [alops-docker-password]) are for other functionality, these are meant for making remote sessions from within another docker container.

You can also use "ALOpsDockerExec" to execute powershell code directly inside of the container, this task also automatically preloads the NAV/BC management Cmdlets.

We should however be able to implement your request quite easily. Please check the output from the ALOpsDockerWait step, look for the lines behind "*** BC Container Parameters:", should look something like:

```
*** BC Container Parameters:

Thumbprint        : F4F967FC9F930DC450E0CA89722EE4F28B234BC1
IPAddress         : 172.22.65.64
Hostname          : bb71e09ae4ab
DnsName           : bb71e09ae4ab
WebClient         : https://bb71e09ae4ab/BC/
AdminUser         : admin
AdminPassword     : Lile8462
NavServerInstance : BC
VSIX              : http://bb71e09ae4ab:8080/ALLanguage.vsix
SSLCertificate    : http://bb71e09ae4ab:8080/certificate.cer
Duration          : 61
```

Would it be sufficient for you if we extend this dataset with the "Full ContainerID" and store it in a global variable ?

Kind regards,

**Comment by gintuoklis** [comment]
Output of the ALOpsDockerWait step already has all needed information (ip, hostname, username, psw). I just don't know how to take it/read it on my next step - my powershell script. Any hints?

**Comment by waldo1001** [comment]
Hi @gintuoklis ,

you'll see in the "Docker Wait" some output which should make that clear for you ;-).  There is a variable "ALOPS_DOCKER_CONTAINER_ID" that you can use after the Docker Wait step.

![image](https://user-images.githubusercontent.com/12088142/90135418-e965e200-dd72-11ea-8c3b-91f3fbf99165.png)

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

The ALOPs Docker info parameters can be used in tasks/yaml the following way:

```
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "ContainerID => $(ALOPS_DOCKER_CONTAINER_ID)"'
```

Kind regards,
