### ISSUE TITLE
AlopsDockerWait stalls at Starting Local SQL Server

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#177]
I often experience the pipeline hangs af ALOpsDockerWait step Starting Local SQL Server

are there any settings I can add or settings on the Server to configure, 

Here is my Yaml:
***************
```yaml
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - app/*
    - test/*

name: $(Build.BuildId)

pool: default

variables:
- group: Secrets
- name: 'AppVersion'
  value: '16.1.[yyyyWW].*'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/sandbox'

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  inputs:
    docker_image: '$(dockerimage)'
    accept_image_outdated: true
    memory_gb: '8'
    container_restart: 'always'
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: $(LicenseFile)

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: DownloadBuildArtifacts@0
  displayName: 'Download Library App'
  enabled: true
  inputs:
    buildType: 'specific'
    project: 'Abakion Apps'
    pipeline: '1'
    buildVersionToDownload: 'latestFromBranch'
    allowPartiallySucceededBuilds: true
    downloadType: 'specific'
    itemPattern: '**/*.app'
    
- task: ALOpsAppPublish@1
  displayName: 'Publish Library App'
  enabled: true
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*app.app'
    skip_verification: false

- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: App'
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    nav_app_version: '$(AppVersion)'
    failed_on_warnings: false
    app_file_suffix: 'app'

- task: ALOpsAppSign@1
  displayName: 'ALOps App Sign'
  env:
    pfx_password: $(CodeSignPfxPassword)
  inputs:
    pfx_path: $(CodeSignPfxFile)
    nav_artifact_app_filter: '*app.app'
    timestamp_uri: 'http://timestamp.comodoca.com/authenticode'
    usedocker: True  

- task: ALOpsAppSignVerify@1
  displayName: 'ALOps App Sign Verify'
  inputs:
    usedocker: True
    nav_artifact_app_filter: '*app.app '


- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish Extension: app'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*app.app'
    skip_verification: false   

- task: ALOpsAppRuntimePackage@1
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    publish_artifact: true


#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'ALOps Remove Docker Container'
  enabled: true
  condition: always()

```
