### ISSUE TITLE
Issue ALOpsAppPublish ForceSync error

### ISSUE THREAD

**Issue by ldumont13** [HodorNV/ALOps#178]
Hi,

I tried the fix you made in the issue #146. 

I tried to publish using forcesync but i get the following error because the old extension does not uninstall
![image](https://user-images.githubusercontent.com/44373612/91021108-93efc780-e5f3-11ea-8c59-637aa63d33da.png)

Best Regards,

**Comment by AdminHodor** [comment]
Dear @ldumont13 ,

This is indeed a requirement for ForceSync introduced in BC v16.x, 

Please do note "Forcing" is bad practice, and for us adding the automatisch "Uninstall-NAVApp" could have unwanted side-effects which we will not try to counter. Where previously the "ForceSync" option would only 'destroy' data of the app you are trying to update. The "Uninstall-NAVApp" will also uninstall other apps that have dependencies on the uninstalled app.

That being said, we will implement a fix for this in v1.434 and keep you posted on  this.

Kind regards,

**Comment by peterz84** [comment]
Has this been released already? If yes, this does not work for Batch Publish. Could you fix this also?

**Comment by waldo1001** [comment]
It doesn't work on a batch publish indeed - but do you really think it's a good idea to have this working in batch?  We'll see if we can add it - but it just so smell like bad practice :(.

**Comment by peterz84** [comment]
ForceSync is bad practice indeed. But when choosing this, it should work. Now we have to manually uninstall it first when we moved some fields around between several extensions. (our extensions aren't live in any customers database, so we can move around still). Database design in this fase is more important than keeping all data in the correct fields.

**Comment by jcoe-nvt** [comment]
@waldo1001 : Is this issue still open? We're also searching for the possibility to use ForceSync on our batch publish. It's for same case as @peterz84 mentioned: Moving around fields that haven't been released to any live customer database.
By default we would turn off this param and only turn it on for 1 run if needed...

**Comment by waldo1001** [comment]
We have put it higher on the roadmap.  We are releasing other features first before implementing this one.  We aim end of next week.

That said - I'm a bit worried on the support requests that will follow in this , as I'm expecting "side effects" and people losing data in an automated way.. .  And we don't want to be blamed for it..

**Comment by yurim108** [comment]
We have a similar problem. We had to increase a field length of a primary key of one table (ported from NAV 2009 to BC 16, and later we discovered that the field length must be increased) and change data type of another field. The app has already been published to a customer's DEV and TEST databases (OnPrem), the data is not so important. Setting forcesync in launch.json leasds to no data loss and desired changes in local docker container. Setting forcesync parameter in task ALOpsAppPublish had no effect and the build pipeline failed. The parameter "forcesync" was shown as "True" in the pipeline log. After updating ALOps to the latest version (1.440.2155) I get the same error as mentioned above: "Cannot synchronize the schema with 'ForceSync' mode until the extension has been uninstalled."

Micorsoft has allowed this setting, so why not ALOps? Now we are confronted with cumbersome workarounds... The release pipeline runs also on a similar error inspite of "Force Sync" setting. So we have to uninstall the apps manually, so that the release pipeline works. 

I don't think people will blame you, your product is of a big help. And if someone wrongly uses it, it' his own mistake. May be you could add some warning into pipieline's log, as a reminder to switch off "forcesync".

**Comment by pri-kise** [comment]
@waldo1001 any update on this topic?

**Comment by waldo1001** [comment]
Unfortunately not. 
To date, we have been busy with other more important features that slipped through.   

Can I ask what the usecase is?  Why you want to forcesync from a pipeline?  Why this is not an exception?

**Comment by pri-kise** [comment]
We sometimes have the requirement to change primary keys by increasing a text field of inividual customer extensions.
For those pull request we wan to be able to easy publish the app with forcesync in our pipeline.
We could disable the publishing of the previous release, but with forcesync it would be the process as later in the OnPrem Customer System.

**Comment by pri-kise** [comment]
@waldo1001 you mentioned that it should work for Single Publishing.
Am I doing something wrong in my simplified pipeline below?
I only want to publish the BaseApp.app with forcesync.
```
name: $(Build.BuildId)

parameters:
- name: ForceSync
  type: boolean
  default: false

variables:
- name: 'AppVersion'
  value: '?.?.0.*'
- name: 'AppName'
  value: 'BaseApp'
- name: 'artifact.country'
  value: 'de'
- name: 'artifact.version'
  value: '17.3'
- name: 'bc_license'
  value: 'CustomerLicence.flf'
- name: 'System.PreferGitFromPath'
  value: true
- name: 'ForceSync'
  value: ${{parameters.ForceSync}}
- group: 'ALOps Settings'

pool:
  name: BusinessCentralBuildAgents

trigger:
- master

steps:
- checkout: self
  clean: true
  lfs: true
  persistCredentials: true

- task: ALOpsDockerCreate@1
  inputs:
    artifactversion: '$(artifact.version)'
    artifactcountry: '$(artifact.country)'
    licensefile: '\\files\DevOps\Common\developer.flf'
  
- task: ALOpsDockerStart@1
  inputs:
    memory_gb: '8'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc_license)


- task: DownloadBuildArtifacts@0
  displayName: 'Download Previous Version (master)'
  inputs:
    buildType: 'specific'
    project: '$(System.TeamProjectId)'
    pipeline: '$(System.DefinitionId)'
    buildVersionToDownload: 'latestFromBranch'
    allowPartiallySucceededBuilds: true
    branchName: 'refs/heads/master'
    downloadType: 'specific'
    itemPattern: '**/*$(AppName)*.app'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ALOpsAppPublish@1
  displayName: 'Publish Previous Version'
  condition:  in(variables['Agent.JobStatus'], 'Succeeded')
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'

- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    targetproject: 'MainApp/app.json'
    al_analyzer: 'AppSourceCop,CodeCop,PerTenantExtensionCop,UICop'
    nav_app_version: '$(AppVersion)'

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true
    forcesync: $(ForceSync)

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()
```
