### ISSUE TITLE
Invalid reference format: repository name must be lowercase - when using artifacts

### ISSUE THREAD

**Issue by borisimple** [HodorNV/ALOps#183]
I am getting this error after switching to the artifacts.

Here is the ALOps Docker start command:

``` 
 - task: ALOpsDockerStart@1
    inputs:
      artifactcountry: 'na'
      artifacttype: OnPrem
```
And the error message: 

```
"docker" create --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=ROYAL_1314 $(ALOPS_BC_IMAGE)
##[error]invalid reference format: repository name must be lowercase
