### ISSUE TITLE
Question : ALOpsDockerCreate - tag / artifactversion to select the next minor

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#186]
What would be the tag to select the next insider minor using the new ALOpsDockerCreate task?

```
# W1 - Current Build (Specific version)
- task: ALOpsDockerCreate@1
  inputs:    
    artifactcountry: 'w1'
    artifacttype: OnPrem
    artifactversion: $(currentBuild)

# W1 - Latest Minor 
- task: ALOpsDockerCreate@1
  inputs:    
    artifactcountry: 'w1'
    artifacttype: OnPrem

# W1 - Next Minor (Insider)
- task: ALOpsDockerCreate@1
  inputs:
    artifactcountry: 'w1'
    artifacttype: Sandbox
    artifactversion: SecondToLastMajor // this failse
    sastoken: $(bcinsider_sas_token)

 # W1 - Next Major (Insider)
- task: ALOpsDockerCreate@1
  inputs:
    artifactcountry: 'w1'
    artifacttype: Sandbox
    sastoken: $(bcinsider_sas_token)
```

**Comment by waldo1001** [comment]
Hi @fvet ,

I created these examples: https://github.com/HodorNV/ALOps/tree/master/Examples/Working%20with%20Artifacts

So, for now, it's like this:
```yaml
- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    sastoken: $(bc.sasToken)
    artifactversion: 16
    artifacttype: Sandbox
```

Not perfect,  I know - the "selectSecondToLast" is on the list..
