### ISSUE TITLE
ALOpsDockerCreate throws error "The method returned a COM Variant type that is not Interop compatible."

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#192]
**Describe the bug**
Today our Pipelines start failing at the step "ALOpsDockerCreate" with the error "The method returned a COM Variant type that is not Interop compatible."

__*The interesting part is, that the exact same pipeline with the exact same ALOps Build Number did run yesterday.*__

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
  - task: ALOpsDockerCreate@1
    displayName: 'Create Docker Image ${{ parameters.dockerimage }}'
    inputs:
      artifacttype: Sandbox
      artifactcountry: 'de'
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
Starting: Create Docker Image: sandbox:de
==============================================================================
Task         : ALOps Docker Create
Description  : Create Docker image from Business Central Artifacts
Version      : 1.434.1680
Author       : Hodor
Help         : Create Docker image based on NAV/BC Artifacts.
==============================================================================
*** Validate configuration
*** ALOps License: ###
*** ALOps License: 

collectionUID : ###
projectUID    : ###
licenseUID    : ###
description   : ###




##[error]Exception calling "GetObjectForNativeVariant" with "1" argument(s): "The method returned a COM Variant type that is not Interop compatible."
Finishing: Create Docker Image sandbox:de

```
