### ISSUE TITLE
[BC14] Compiler did not see imported C/AL Objects

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#194]
**Describe the issue**
I used _enable_symbol_loading_ on **ALOpsDockerStart** and _generate_symbol_reference_ on **ALOpsFobImport** and the compiler (**ALOpsAppCompiler**) sees the C/AL Object Changes, but not new C/AL Objects.

If I remove the references to the new C/AL Objects, the build process works. Produced solution works in Test and Production with the C/AL Object Changes (e.g. new fields or new codeunits functions).

**the used yaml**
```yaml
name: $(Build.BuildId)

pool:
  name: BusinessCentralBuildAgents

trigger:
- master
- develop

steps:
- checkout: self
  clean: true

- task: ALOpsDockerCreate@1
  inputs:
    artifactversion: '14.17'
    artifactcountry: 'de'

- task: ALOpsDockerStart@1
  inputs:
    enable_symbol_loading: true
    memory_gb: '8'
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: 'CustomerLicence.flf'

- task: ALOpsFobImport@1
  displayName: 'Import C/SIDE Customisations'
  inputs:
    usedocker: true
    filePath: 'Customisations.fob'
    import_action: 'Overwrite'
    generate_symbol_reference: true

- task: ALOpsAppCompiler@1
  displayName: 'ALOps - Compile Extension: App'
  inputs:
    usedocker: true
    targetproject: 'MainApp/app.json'
    al_analyzer: 'CodeCop,PerTenantExtensionCop,UICop'
    nav_app_version: '1.0.[yyyyWW].*'
    publish_artifact: false

- task: ALOpsAppPublish@1
  displayName: 'ALOps - Publish Extension: App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()
```

**the output**
```
##[section]Starting: ALOps - Compile Extension: App
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extensions for Business Central
Version      : 1.434.1680
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================

*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [NAV].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\140\service]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Setting up AL Compiler [ALLanguage]
*** Using AL Compiler [vALLanguage] located [C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe]
***
*** Working folder: C:\agent\_work\4\s
***
*** Copy Working folder to Docker Container: 0def71c1a5fae09886aa3f942d9c1542c4d9cc9afdce60eb92f4818d2ecb1b86
*** Docker Working Folder: c:\Run\DevOps\
*** Copy from [C:\agent\_work\4\s] to [c:\Run\DevOps\]
*** Source File setup completed
*** Target Project: \MainApp\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Multiple projects found:
   - C:\Run\DevOps\MainApp
   - C:\Run\DevOps\MainApp
*** Retrieving App-Info [\MainApp\app.json]
*** Loading Json Object: [c:\Run\DevOps\MainApp\app.json]
  * App.ID          = a097e1fa-0958-4ab5-a922-293a52e7bd69
  * App.Name        = MyApp
  * App.Publisher   = Some Company
  * App.Version     = 0.1.0.0
  * App.Platform    = 14.0.0.0
  * App.Application = 14.0.0.0
***
*** Match: yyyyWW
*** Setting Managed App Version [c:\Run\DevOps\MainApp\app.json] =>  1.0.202037.1732
***
*** Working Direcotry: [c:\Run\DevOps\]
*** Target Project: [\MainApp\app.json]
*** Project Directory: [c:\Run\DevOps\MainApp]
*** VSCode Settings: [c:\Run\DevOps\MainApp\.vscode\settings.json]
*** VSCode-Settings json found.
*** Loading Json Object: [c:\Run\DevOps\MainApp\.vscode\settings.json]
*** Using Ruleset: [c:\Run\DevOps\MainApp\.vscode\ruleset.json]
***
*** Resolve Docker Credentials
*** Setup BC Username/Password from Container info
*** Download Symbols
*** Working Dir: c:\Run\DevOps\
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\140\service]
*** PackageCache path created [c:\Run\DevOps\PackageCache]
***
*** Propagated Dependency: Some Company - MyApp - 1.0.0.0
*** Download System-Symbols for [14.0.0.0]
*** Downloading NAV Symbols for [System v14.0.0.0]
*** Downloading NAV Symbols from [https://0def71c1a5fa:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
##[command]Invoke-RestMethod -Method Get -Uri https://0def71c1a5fa:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0&tenant=default
*** Content-Disposition: attachment; filename=Microsoft_System_14.0.44656.0.app
*** Saving symbol file [Microsoft_System_14.0.44656.0.app] to [c:\Run\DevOps\PackageCache]
*** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_System_14.0.44656.0.app].
***
*** Download Application-Symbols for [14.0.0.0]
*** Downloading NAV Symbols for [Application v14.0.0.0]
*** Downloading NAV Symbols from [https://0def71c1a5fa:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
##[command]Invoke-RestMethod -Method Get -Uri https://0def71c1a5fa:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0&tenant=default
*** Content-Disposition: attachment; filename=Microsoft_Application_14.17.44663.0.app
*** Saving symbol file [Microsoft_Application_14.17.44663.0.app] to [c:\Run\DevOps\PackageCache]
*** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_Application_14.17.44663.0.app].
***
*** Check for Depency Apps 1
*** Download Application-Symbols for [MyApp v1.0.0.0]
*** Downloading NAV Symbols for [MyApp v1.0.0.0]
*** Downloading NAV Symbols from [https://0def71c1a5fa:7049/NAV/dev/packages?publisher=Some+Company&appName=MyApp&versionText=1.0.0.0&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
##[command]Invoke-RestMethod -Method Get -Uri https://0def71c1a5fa:7049/NAV/dev/packages?publisher=Some+Company&appName=MyApp&versionText=1.0.0.0&tenant=default
*** Content-Disposition: attachment; filename="Some Company_MyApp_1.0.202037.1732.app"
*** Saving symbol file [Some Company_MyApp_1.0.202037.1732.app] to [c:\Run\DevOps\PackageCache]
*** Read App Manifest: [c:\Run\DevOps\PackageCache\Some Company_MyApp_1.0.202037.1732.app].
***
*** Starting AL Compiler...
*** App.Name         = MyApp
*** App.Publisher    = Some Company
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
*** Checking for Assemblies in App
*** Add Windows Assembly Path [C:\Windows\assembly]
##[command]& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\MainApp" /out:"c:\Run\DevOps\Some Company_MyApp_1.0.202037.1732.app" /fullpaths /ruleset:"c:\Run\DevOps\MainApp\.vscode\ruleset.json" /assemblyprobingpaths:C:\Windows\assembly
*** AL Compiler Exit Code: 1
*** AL Compiler raw logs: Start
Microsoft (R) AL Compiler version 3.0.4.37648 Copyright (C) Microsoft Corporation. All rights reserved  Compilation started for project 'MyApp' containing '3' files at '23:28:45.126'.  c:\Run\DevOps\MainApp\src\Mgt.Codeunit.al(12,20): error AL0185: Table 'New Table' is missing c:\Run\DevOps\MainApp\src\Mgt.Codeunit.al(14,25): error AL0185: Codeunit 'New Codeunit' is missing  Compilation ended at '23:28:50.688'. 
*** AL Compiler raw logs: End
*** Start processing compile results.
##[error]Compilation started for project 'MyApp' containing '3' files at '23:28:45.126'.
##[error]c:\Run\DevOps\MainApp\src\Mgt.Codeunit.al(12,20): error AL0185: Table 'New Table' is missing
##[error]c:\Run\DevOps\MainApp\src\Mgt.Codeunit.al(14,25): error AL0185: Codeunit 'New Codeunit' is missing
##[error]Compilation ended at '23:28:50.688'.
*** Store compile log to [c:\Run\DevOps\compilelog.txt]
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
##[error]Der Pfad "c:\Run\DevOps\Some Company_MyApp_1.0.202037.1732.app" kann nicht gefunden werden, da er nicht vorhanden ist.
##[section]Async Command Start: Add Build Tag
Build '1732' has following tags now: AL.Analyzer.PerTenantExtensionCop, AL.Analyzer.CodeCop, AL.Analyzer.UICop, AL.Compiler.ALLanguage, BC.Platform.14.0.44656.0, BC.Version.14.17.44663.0, myimage-onprem-14.17.44663.0-de-10.0.17763.1457-ltsc2019, App.Html Editor.1.0.202037.1682, App.Erweiterte Textverwaltung.1.0.202037.1677, App.MyApp.1.0.202037.1697, App.Erweiterte Projektverwaltung.1.0.202037.1702, App.MyApp.1.0.202037.1732
##[section]Async Command End: Add Build Tag
##[section]Async Command Start: Update Build Number
Update build number to 1.0.202037.1732 for build 1732
##[section]Async Command End: Update Build Number
##[section]Finishing: ALOps - Compile Extension: App
```
