### ISSUE TITLE
Error creating docker

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#198]
Getting an error while creating docker image step:

```
Step 1/6 : FROM mcr.microsoft.com/dynamicsnav:10.0.17763.615-generic
 ---> 20350d9d8804
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/16.5.15897.15953/w1
 ---> Running in 837b7e0473a9
Removing intermediate container 837b7e0473a9
 ---> 8490ba072dea
Step 3/6 : COPY my /run/
 ---> d215b87c8897
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> efc536966106
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in 23d4829f28b8
##[error]hcsshim::CreateComputeSystem 23d4829f28b810480a6ff461588c9ece25b534384a5f2dc242725859e0bd13a8: The virtual machine could not be started because a required feature is not installed.
```

I'm running on a W2019 server. Script:

```
name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master

variables:
- name: 'bc.license'
  value: 'c:\Licenses\16.flf'

pool: BHNL Business Central Pool

steps:
- checkout: self
  clean: true 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'write-host "##vso[task.setvariable variable=alops-licenseid]XXXX-XXXXXXXXXX-XXXXXXXXXXX-XXX"'

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: 16.1
    artifactcountry: nl

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS - License Import'
  inputs:
    usedocker: true
    license_path: '$(bc.license)'  # more info: https://www.youtube.com/watch?v=iVLOerdCuwA&t=3078s

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: true
    targetproject: 'app.json'

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish App' # to be able to run test
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

What do I need to install? There was no problem before using the Artifacts.

**Comment by waldo1001** [comment]
Hi @peterz84 ,

could you see if you have installed Hyper-V and "Containers" feature?  You can easily check that in PowerShell:
![image](https://user-images.githubusercontent.com/12088142/93772222-dfab8600-fc1e-11ea-8645-2fba6922eb6c.png)

thx

**Comment by peterz84** [comment]
![image](https://user-images.githubusercontent.com/25202313/93774387-855ff480-fc21-11ea-874b-4c237708490c.png)

**Comment by peterz84** [comment]
ps. I see the script isn't matching the error message completely because I changed the version of the artifacts later in the Yaml. But you get the point, and the error is still the same.

**Comment by waldo1001** [comment]
Probably unnecessary question - but is docker running? 
I'll check internally to see if there is any experience with this error .. strange 🤔

**Comment by peterz84** [comment]
Docker info gives me result, so I suppose its running...

```
PS C:\WINDOWS\system32> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 12
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.593)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 16GiB
 Name: Castor
 ID: B3YJ:N6HE:C6Q5:ATRC:TES3:QDXA:HHG6:H26D:67BJ:HQIW:ZKQE:BC5R
 Docker Root Dir: D:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by peterz84** [comment]
Docker images gives me these...

![image](https://user-images.githubusercontent.com/25202313/93781407-a3c9ee00-fc29-11ea-91d5-540d6bbd9a48.png)

the oldest one is in use for a pipeline without artifacts. The ones with repo <none> (isn't this weird?) are created for the pipeline with artifacts

**Comment by waldo1001** [comment]
You have a working Docker ... 🤔.
Can you check the user account that is running the build service?  If it's the "network service" account, please change it to "localsystem" or a "real" admin account..

**Comment by peterz84** [comment]
I'm not really keen on changing a working agent. When I change the exact script posted above in my first message, to not use artifacts, but the complete image with the same version:

```
variables:
- name: 'bc.license'
  value: 'c:\Licenses\16.flf'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/onprem:cu1-nl'

pool: BHNL Business Central Pool

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  inputs:
    docker_image: $(dockerimage)
    docker_pull: true

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'
```
It works. If there is no other solution I would change the user account running the agent, but really doubt that is the solution.
