### ISSUE TITLE
 ALOpsAppRuntimePackage gives errors: Cannot bind argument to parameter 'Path' because it is null

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#202]
**Describe the bug**
Seems to be a problem generating Runtimepackage, the yaml is generating the app fine with no problem.
Problem also persist using artifacts. no changes to the pipeline for several weeks.

**the used yaml**

```yaml
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - app/*
    - test/*

name: $(Build.BuildId)

pool: default

variables:
- group: Secrets
- name: 'AppVersion'
  value: '16.1.[yyyyWW].*'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/sandbox'

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  inputs:
    docker_image: '$(dockerimage)'
    accept_image_outdated: true
    memory_gb: '8'
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: $(LicenseFile)

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: App'
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    nav_app_version: '$(AppVersion)'
    failed_on_warnings: false
    app_file_suffix: 'app'


- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish Extension: app'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*app.app'
    skip_verification: true

- task: ALOpsAppRuntimePackage@1
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    publish_artifact: true  

- task: ALOpsDockerRemove@1
  displayName: 'ALOps Remove Docker Container'
  enabled: true
  condition: always()
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
Starting: ALOpsAppRuntimePackage
==============================================================================
Task         : ALOps App Runtime Package
Description  : Create Runtime Package from AL Extension
Version      : 1.434.1755
Author       : Hodor
Help         : Get a NAV App runtime package for onprem deployment.
==============================================================================
*** Validate configuration
*** ALOps License:
  * License Key: xxx
  * Licensed To: xxx

*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
 - Use Docker         = True
*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\160\service]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Target Project: \app\app.json
*** Check for app.json files: 
##[error]Cannot bind argument to parameter 'Path' because it is null.
Finishing: ALOpsAppRuntimePackage

```

**Expected behavior**
A runtime package

**Comment by DanielGoehler** [comment]
@waldo1001: We have the same Problem.

**Comment by waldo1001** [comment]
We're looking into it - not able to repro for now, but we didn't change anything on this level.  So it might be a DevOps issue where they changed the behavior of some vars ... just thinking out loud.  As said, we're looking into it!

**Comment by DanielGoehler** [comment]
Before 2020-09-19:
```
##[section]Starting: Create Runtime Package
==============================================================================
Task         : ALOps App Runtime Package
Description  : Create Runtime Package from AL Extension
Version      : 1.434.1680
Author       : Hodor
Help         : Get a NAV App runtime package for onprem deployment.
==============================================================================
*** Validate configuration




*** Importing required PS-Functions
 - Use Docker         = True
*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\160\service]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Target Project: \MainApp\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Project found:
   - C:\Run\DevOps\MainApp
*** Retrieving App-Info [\MainApp\app.json]
*** Loading Json Object: [c:\Run\DevOps\MainApp\app.json]
  * App.ID          = 30390585-0c88-4da4-ba3c-4c42f3b34aa4
  * App.Name        = DocuWare Connector
  * App.Publisher   = prisma informatik GmbH
*** Retrieving Published App Info [\MainApp\app.json] from [BC]
  * App.Version     = 1.0.202038.1834
***
*** Exporting App [DocuWare Connector] as RuntimePackage [c:\Run\DevOps\prisma informatik GmbH_DocuWare Connector_1.0.202038.1834_runtime.app]
*** Transfer Runtime-App Artifact from Docker container.

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  1 WinRM1          8b6f5fac74a7... Container       Opened                                 Available
*** Disconnect Docker session.
*** Remove Docker session.
*** Docker session removed.
*** Runtime-App Artifact upload skipped.
***
*** Business Central App exported as Runtime Package
*** Cleanup VSTS Environment: True
##[section]Finishing: Create Runtime Package
```
Before 2020-09-24:
```
##[section]Starting: Create Runtime Package
==============================================================================
Task         : ALOps App Runtime Package
Description  : Create Runtime Package from AL Extension
Version      : 1.434.1755
Author       : Hodor
Help         : Get a NAV App runtime package for onprem deployment.
==============================================================================
*** Validate configuration

*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
 - Use Docker         = True
*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\160\service]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\160\service\Microsoft.Dynamics.Nav.Management.dll]
*** Target Project: \MainApp\app.json
*** Check for app.json files: 
##[error]Cannot bind argument to parameter 'Path' because it is null.
##[section]Finishing: Create Runtime Package
```

**Comment by DanielGoehler** [comment]
The example above is for BC 16. I also checked an BC 14 and reran the pipeline without any change. Same Problem.

Is it possible to downgrade to ALOps 1.434.1680?

Before 2020-09-14:
```
##[section]Starting: Create Runtime Package
==============================================================================
Task         : ALOps App Runtime Package
Description  : Create Runtime Package from AL Extension
Version      : 1.434.1680
Author       : Hodor
Help         : Get a NAV App runtime package for onprem deployment.
==============================================================================
*** Validate configuration



*** Importing required PS-Functions
 - Use Docker         = True
*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [NAV].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\140\service]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Target Project: \MainApp\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Project found:
   - C:\Run\DevOps\MainApp
*** Retrieving App-Info [\MainApp\app.json]
*** Loading Json Object: [c:\Run\DevOps\MainApp\app.json]
  * App.ID          = f9f406ba-a7c2-43fb-9534-abe714aafe6d
  * App.Name        = Some other App
  * App.Publisher   = Some Company
*** Retrieving Published App Info [\MainApp\app.json] from [NAV]
  * App.Version     = 1.1.202037.1764
***
*** Exporting App [Some other App] as RuntimePackage [c:\Run\DevOps\Some Company_Some other App_1.1.202037.1764_runtime.app]
*** Transfer Runtime-App Artifact from Docker container.

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  1 WinRM1          a0b58b0d67de... Container       Opened                                 Available
*** Disconnect Docker session.
*** Remove Docker session.
*** Docker session removed.
*** Runtime-App Artifact upload skipped.
***
*** Business Central App exported as Runtime Package
*** Cleanup VSTS Environment: True
##[section]Finishing: Create Runtime Package
```
Today 2020-09-24:
```
##[section]Starting: Create Runtime Package
==============================================================================
Task         : ALOps App Runtime Package
Description  : Create Runtime Package from AL Extension
Version      : 1.434.1755
Author       : Hodor
Help         : Get a NAV App runtime package for onprem deployment.
==============================================================================
*** Validate configuration

*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
 - Use Docker         = True
*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [NAV].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\140\service]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Target Project: \MainApp\app.json
*** Check for app.json files: 
##[error]Cannot bind argument to parameter 'Path' because it is null.
##[section]Finishing: Create Runtime Package
```

**Comment by DanielGoehler** [comment]
@waldo1001 Is it possible to downgrade to ALOps 1.434.1680?

**Comment by waldo1001** [comment]
You can't - but we're working on it!

**Comment by DanielGoehler** [comment]
@waldo1001 Any update?

**Comment by waldo1001** [comment]
We pushed a new release last night .. since we're still not able to repro this, please try again.. .  Our test-pipeline works...
![image](https://user-images.githubusercontent.com/12088142/94663134-9c7da100-0309-11eb-85ff-db7c19b5daec.png)

**Comment by DanielGoehler** [comment]
Ok, I try again as soon as the new build was deployed.
![image](https://user-images.githubusercontent.com/9556549/94663703-45c49700-030a-11eb-976e-ffc8a32485e0.png)

If there is anything I can to do, e.g. provide telemetry, just let me know.

**Comment by MortenRa** [comment]
Yes Same error at my end aswell for the runtimepackage

**Comment by waldo1001** [comment]
Make sure you report back when tested with the right build number.  In the screenshots I see that it's still 1755.
It could take a few builds for DevOps to download the new version of ALOps

**Comment by MortenRa** [comment]
But is 1755 not the latest

![image](https://user-images.githubusercontent.com/28138717/94669295-575d6d00-0311-11eb-9c89-90ede59357e8.png)

**Comment by MortenRa** [comment]
And is this not correct as the folder where the app.json is located is app

- task: ALOpsAppRuntimePackage@1
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    publish_artifact: true

**Comment by waldo1001** [comment]
It should be build 1775, not 1755 (like in the screenshot), like it says on the marketplace.
https://marketplace.visualstudio.com/items?itemName=Hodor.hodor-alops

the step looks perfect - that's literally what I use in our test-pipeline:

```yaml
- task: ALOpsAppRuntimePackage@1
  displayName: 'ALOPS - Create Runtime Package' 
  inputs:
    usedocker: true
    targetproject: 'app/app.json'   # point to the folder in your repo
    publish_artifact: true
```
