### ISSUE TITLE
How to specify which company to run the Unit Tests in?

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#203]
**Describe the bug**
I cannot find a parameter in ALOpsAppTest to specify that I want to run my Unit Tests a specific company, e.g. Cronus Danmark A/S

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsAppTest@1
  displayName: 'EV: Run Custom Tests'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testsuite: $(TestSuite) 
    testpage: '130455'
    failed_test_action: 'Error'
  continueOnError: true   
```
