### ISSUE TITLE
Best Practice to remove 'unused' docker images?

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#211]
**Is your feature request related to a problem? Please describe.**
Together with #201, we see available disk space of the buildserver decreasing rapidly. We use daily CI builds for OnPrem 16.3 (so this image is required  to keep) and perform less frequent builds on nextMinor / nextMajor. Since these are updated daily, the previous images are of no use to us (in our situation). Currently, we schedule a weekly cleanup of **all** docker images, using

`docker image prune -a -f`

Is there any 'better' option to remove all images, except the 'needed' ones (and apply same rules to the bcartifacts.cache), e.g. by looking to images that have not been 'used' by any container in the past 7 days?

**Comment by waldo1001** [comment]
Hi @fvet,

It's on our list to deal with, but we're not sure how.  Any feedback on this, would be very helpful.

**Comment by AdminHodor** [comment]
Dear @fvet ,

We just released v1.435.1856 which should tackle this issue with a new Task [ALOpsAgentMaintenance]
Please note it could take a couple of pipeline runs for DevOps to pickup the new version.

```
- task: ALOpsAgentMaintenance@1
  displayName: 'ALOps Agent Maintenance'
  inputs:
    removeoldtasks: true
    removeunusedcontainers: true
    removebcartifacts: true
    daysunused: 14
```

Kind regards,
