### ISSUE TITLE
Feature -AlopsSchedule, AlopsTemplate

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#212]
When having +20 pipelines running it could be a good idea to break the pipelines into smaller templates referenced from another repo to easy update the yaml file instead of having to modify every repository.

Maybe add an ALopsTemplateTask or best practice how this could be configured in some examples using ALops.

Maybe also add ALopsScheduleTask to be able to schedule yaml pipelines.

**Comment by dNsl9r** [comment]
May I ask why you don't use the standard YAML Template functionality?
I added this in our DevOps and it is working very good.
Usage e.g.:

```
jobs:
  - job: StartDockerContainer
    steps:
    - template: CI/Templates/PrepareDockerEnvironment.yml@CITemplates
      parameters:
        country: 'bcnextmajor:de'
        useinsider: true
```

In the template file:

```
parameters:
  - name: country
    type: string
  - name: usehyperv
    type: boolean
    default: false
  - name: useinsider
    type: boolean
    default: false


steps:
  - script: |
            echo "Preparing Docker Environment"
            echo "country ${{ parameters.country }}"
            echo "useinsider ${{ parameters.useinsider }}"
  - task: ALOpsDockerCreate@1
    displayName: 'Create Docker Image'
    inputs:
      ${{ if eq(parameters.useinsider,true) }}:
        versionselect: NextMajor
        sastoken: $(BCInsider.sasToken)
        artifacttype: Sandbox
      ${{ if eq(parameters.useinsider,false) }}:
        artifacttype: Sandbox
      artifactcountry: ${{ parameters.country }}
....
....
....
```


For the scheduling part we are also using the standard functionality:

```
schedules:
- cron: "0 0 * * 2,4"
  displayName: Dienstag / Donnerstag
  branches:
    include:
      - master
  always: true
```
