### ISSUE TITLE
Compile step fails

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#214]
Getting an error in the compile step:
![image](https://user-images.githubusercontent.com/25202313/94993066-9f3cf800-058e-11eb-9fc4-0e6d8f1b5ed9.png)

Script:
```
trigger: none
name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.0.*'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/onprem:1910-cu2-nl'
- name: 'bc_license'
  value: 'c:\Licenses\15.flf'

pool:
  name: BHNL Business Central Pool

steps:
- checkout: self
  clean: true
  
#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: 'write-host "##vso[task.setvariable variable=alops-licenseid]----------------"'

- task: ALOpsDockerStart@1
  inputs:
    docker_image: '$(dockerimage)'
    docker_parameters: |
      -v "D:\CustomSQLbak:C:/temp"
      -v "C:\Licenses:C:/licenses"
      -e licensefile=C:\licenses\15.flf
    sql_backup_file: 'c:\temp\KNK2020R1_CU2_NL.bak'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS Compile'
  inputs:
    usedocker: true
    targetproject: './app.json'
    nav_app_version: '$(AppVersion)'

- task: ALOpsAppPublish@1
  displayName: 'ALOPS Publish'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'

#- task: ALOpsDockerRemove@1
#  enabled: true
#  condition: always()  
```

As you can see I disabled the DockerRemove step, to check if the app file does exist and it seems to exist in the container:
![image](https://user-images.githubusercontent.com/25202313/94993148-3ace6880-058f-11eb-8af9-cb83aa36ffd9.png)

What might be the problem? Is the name too long? Does it not like the [W1] at the end?
