### ISSUE TITLE
Feature Request for ALOpsAppPublish: Allow to only publish the "Test Runner" app

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#215]
It would be nice, if **ALOpsAppPublish** could also only publish the "Test Runner" app. It takes up 
approx. one minute to pubish all test apps vs. a few seconds, if only the Test Runner gets published.

This could be achived by considering install_al_app_names as App Filter...

```yaml
- task: ALOpsAppPublish@1
      displayName: 'ALOps App Publish'
      inputs:
        installaltesttool: true
        install_al_app_names: Test Runner #only publishes Test Runner App
```
... or by allowing to publish apps like **C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app** from the file system of the local docker. I have not been able to get this to work.
