### ISSUE TITLE
Compile BC against multiple versions 

### ISSUE THREAD

**Issue by borisimple** [HodorNV/ALOps#218]
Is there a way to use a specific app.json (if you have any) instead of standard app.json?
In the screenshot, you can see that the JSON object is always reading app.json file.

![image](https://user-images.githubusercontent.com/16119596/95455281-e7349400-096d-11eb-9a01-9f2d4690ae75.png)

The story here is that we temporarily need to compile and build project against v16.

We have one build pipeline which compiles the app against the latest available BC, which at the moment is 17.
I was thinking to create another build pipeline which will compile the app against V16, by using app-v16.json.
So in yaml, I reference correct app-v16.json file for compilation:

```
  - task: ALOpsAppCompiler@1
    displayName: Compiling the app $(app_name)
    inputs:
      usedocker: true
      targetproject: "app/app-v16.json"
      nav_app_version: "17.0.[yyyyww].*"
      app_file_suffix: _APP_V16
      failed_on_warnings: true
```

There is maybe a better way to do this, but I thought to give this a shot.
