### ISSUE TITLE
ALOpsAppCompiler@2 - Cannot find an overload for "GetObjectsForNativeVariants"

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#223]
**Describe the bug**
While testing ALOpsAppCompiler@2, I got this warning 

`Dotnet Framework probably missing. Please install latest Dotnet framework.`

So I have installed .NET framework 4.8 on the buildserver, and now I'm getting 

`##[error]Cannot find an overload for "GetObjectsForNativeVariants" and the argument count: "1".`

**the used yaml**

```
steps:
- task: ALOpsAppCompiler@2
  displayName: 'Compile ${{ parameters.app_name }}'
  enabled: ${{ parameters.enabled }}
  inputs:
    artifactversion: $(currentBuild)
    artifacttype: 'OnPrem' # 'Sandbox' ?
    artifactcountry: $(country)
    appversiontemplate: '?.?.?.*'
    alcodeanalyzer: ${{ parameters.al_analyzer }}
    failonwarnings: ${{ parameters.failed_on_warnings }}
    # app_file_suffix: ${{ parameters.file_suffix }}
```

**the output**

```
Starting: Compile Navitrans.Core
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extension(s) for Business Central
Version      : 2.0.1864
Author       : Hodor
Help         : Compile Business Central extension(s) from AL code.
==============================================================================
******************************************************************************
*** ALOps v2 - Preview                                                     ***
******************************************************************************
*** Importing required ALOps-Functions
##[error]Cannot find an overload for "GetObjectsForNativeVariants" and the argument count: "1".
Finishing: Compile Navitrans.Core
```
