### ISSUE TITLE
ALOps License Import fails with Download URL & Docker usage

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#23]
My license is stored in a blob storage and I use a SaS URL to download stored in variable LicenseFile as secret.

```yml
  - task: ALOpsLicenseImport@1
    displayName: 'ALOPS License Import'
    inputs:
      usedocker: true
      license_path: $(LicenseFile)
```

![image](https://user-images.githubusercontent.com/15800069/63591440-198b0280-c5af-11e9-9af4-2ee0ed569f5b.png)

For Import License (OnPrem this works fine)
