### ISSUE TITLE
ALOpsAppPublish: Build tag 'App.Meine App fï¿½r mein Kunden.1.0.202044.2513' was not added successfully.

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#241]
**Describe the bug**
Special Character in the App Name produce error. With ALOpsAppCompiler 1.435.1864 that had worked.

**the used yaml**

```yaml
name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.[yyyyWW].*'
- group: 'ALOps Settings'

pool:
  name: BusinessCentralBuildAgents

trigger:
- master

steps:
- checkout: self
  clean: true

- task: ALOpsDockerCreate@1
  inputs:
    artifactversion: '14.17'
    artifactcountry: 'de'
    licensefile: '\\files\DevOps\Common\BC.flf'

- task: ALOpsDockerStart@1
  inputs:
    memory_gb: '8'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

[..]

- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    targetproject: 'MainApp/app.json'
    al_analyzer: 'AppSourceCop,CodeCop,PerTenantExtensionCop,UICop'
    nav_app_version: '$(AppVersion)'

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()

```

```json
{
  [..]
  "name": "Meine App für mein Kunden",
  "publisher": "Meine Firma",
  "version": "1.0.0.0",
  [..]
}
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
##[section]Starting: ALOpsAppPublish
==============================================================================
Task         : ALOps App Publish
Description  : Publish AL Extension to Business Central
Version      : 1.435.1904
Author       : Hodor
Help         : Publish Business Central extension to service tier.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                                                                                       defaultValue
----                                                                                                       ------------
usedocker                                                                                                         False
fixed_tag                                                                                                              
installaltesttool                                                                                                 False
install_al_app_names                                                                             Tests-TestLibraries...
strictappnames                                                                                                    False
nav_serverinstance                                                                                                BC140
artifact_path                                                                                                          
nav_artifact_app_filter                                                                                           *.app
skip_verification                                                                                                  True
forcesync                                                                                                         False
publish_scope                                                                                                    Global
tenant                                                                                                          default
batch_publish_folder                                                                                                   



*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
 - Use Docker         = True
 - Artifact Path      = 
 - App Filter         = *.app
 - Process Type       = Build
 - Skip Verification  = True
 - Force Sync         = False

*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Install AL TestTool: False
*** Working folder: C:\agent2\_work\16\s
*** Artifact folder: C:\agent2\_work\16\a
*** Pipeline workspace: C:\agent2\_work\16
***
*** Copy Artifacts to Docker Container: 52562e054f5ae16f24415b5494260abeef1ff44dcd7390fb836666f72bcc34c2
*** Docker Artifacts Folder: c:\Run\DevOps\Artifacts
*** Dynamic resolve App file.
*** Scanning [System.DefaultWorkingDirectory].
*** Scanning [System.ArtifactsDirectory].
*** Scanning [Pipeline.Workspace].
*** Multiple App files found with filter [*.app].
  * C:\agent2\_work\16\a\PRI-BC-EDIModule\Meine Firma_Andere App_1.0.202035.1387_runtime.app
  * C:\agent2\_work\16\a\PRI-BC-TecComConnectorForSupplier\Meine Firma_Meine App fÃ¼r mein Kunden_1.0.202042.2046_runtime.app
  * C:\agent2\_work\16\a\Meine Firma_Meine App fÃ¼r mein Kunden_1.0.202044.2513.app
*** Resolved App File: [Meine Firma_Meine App fÃ¼r mein Kunden_1.0.202044.2513.app].
*** Copy Artifact: [C:\agent2\_work\16\s\Meine Firma_Meine App fÃ¼r mein Kunden_1.0.202044.2513.app]
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [NAV].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\140\service]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]

**************************************
 * App File = [c:\Run\DevOps\Artifacts\Meine Firma_Meine App fÃ¼r mein Kunden_1.0.202044.2513.app]

 * App.ID        = 3527298c-d783-437a-8c7e-e94fde38fb9a
 * App.Name      = Meine App fï¿½r mein Kunden
 * App.Publisher = Meine Firma
 * App.Version   = 1.0.202044.2513
 => Publishing App 'Meine App fï¿½r mein Kunden v1.0.202044.2513'
*** Get Tenants

*** Sync Tenant default
*** Sync App [Meine App fï¿½r mein Kunden] on tenant [default]
*** Tenant Dataupgrade default

**************************************

*** Disconnect Docker session.
*** Remove Docker session.
*** Docker session removed.
*** AL-Extension Published to ALOps Repository
*** Cleanup VSTS Environment: True
##[section]Async Command Start: Add Build Tag
##[section]Async Command End: Add Build Tag
##[error]Build tag 'App.Meine App fï¿½r mein Kunden.1.0.202044.2513' was not added successfully.
##[section]Finishing: ALOpsAppPublish
```
