### ISSUE TITLE
batch_publish_folder not respected in ALOpsAppPublish

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#246]
**Describe the bug**
I have a task to install the previous verion of my app which is in the a folder in my repo.
When this task is run, the system tries to install/re-install **all apps** in my repo and not only the ones specified in the **batch_publish_folder** parameter causing overhead and longer runtimes in my pipelines!

See screenshot for details:

![image](https://user-images.githubusercontent.com/54669593/97970075-42b53e80-1dc1-11eb-954d-24c6ee2ebc31.png)

**the used yaml**
```yaml
name: $(Build.BuildId)

variables:
- group: AzureKeyVault
- name: 'RunTests'
  value: '0'
- name: 'TestSuite'
  value: 'EV-TEST'
- name: 'CodeAnalyzers'
  value: 'CodeCop,UICop'
- name: 'PublishDependencies'
  value: '0'  

pool:
  name: EV_OnPremise

resources:
  repositories:
    - repository: 'yamltemplates'
      type: 'git'
      name: 'Templates/Templates'
      ref:  'refs/heads/master'

steps:
- checkout: self
  clean: true

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Move Unit Tests to Test app if needed
- template: 'OnPrem-Builds/MoveUnitTestToTest.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Copy EVBusinessCentralDevelopmentHelper to Build Agent
- template: 'OnPrem-Builds/CopyEVBCDevHelperToBuildAgent.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerCreate@1
  inputs:
    artifactversion: $(BC_Version)
    artifactcountry: $(BC_Localization)
    artifacttype: $(BC_EnvironmentType)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerStart@1
  inputs:
    docker_pull: false
    accept_image_eula: true
    accept_image_outdated: true
    docker_parameters: '--isolation=hyperv'
    memory_gb: 16  
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(BC_license)
    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerExec@1
  displayName: 'EV: Show Businees Central License Information'
  inputs:
    inline_script: |
      Get-NavServerInstance | Export-NavServerLicenseInformation
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Install AL TestTool'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    installaltesttool: true
    skip_verification: true
    install_al_app_names: |
     Tests-TestLibraries
     System Application Test
     System Application Test Library
     Any
     Library Assert
     Test Runner
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'EV: Install ISV and dependencies apps'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.\app\Dependencies'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Install EVBusinessCentralDevelopmentHelper
- template: 'OnPrem-Builds/InstallEVBCDevHelperInDocker.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Breaking changes - compare with master
#- task: DownloadBuildArtifacts@0
#  inputs:
#    buildType: 'specific'
#    project: '9f67f062-53be-47a5-bdd7-08a6af20386f'
#    pipeline: '17'
#    buildVersionToDownload: 'latestFromBranch'
#    branchName: 'refs/heads/master'
#    downloadType: 'specific'
#    itemPattern: '**/*APP.app'
#    downloadPath: '$(System.ArtifactsDirectory)'

#- task: ALOpsAppPublish@1
#  displayName: 'ALOps Previous master Publish AL-App'
#  inputs:
#    usedocker: true
#    nav_artifact_app_filter: '*_APP.app'   
#    skip_verification: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile App'
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    nav_app_version: '?.?.?.*'
    al_analyzer: $(CodeAnalyzers)
    app_file_suffix: '_APP'
    failed_on_warnings: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# EV: Generate Xliff files
- template: 'OnPrem-Builds/GenerateXliffFiles.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Re-Compile App with xliff'
  inputs:
    usedocker: true
    targetproject: 'app/app.json'
    nav_app_version: '?.?.?.?'
    app_file_suffix: '_APP'
    failed_on_warnings: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'EV: Install Previous App Version'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    batch_publish_folder: '.\app\PrevAppVersion'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_APP.app'   
    skip_verification: true 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Test App'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    targetproject: 'Test/app.json'
    nav_app_version: '?.?.?.?'
    app_file_suffix: '_TEST'
    failed_on_warnings: true    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish AL-TEST App'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_TEST.app'   
    skip_verification: true 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppTest@1
  displayName: 'EV: Run Custom Tests'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    testsuite: $(TestSuite) 
    failed_test_action: 'Error'
  continueOnError: true   
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: PublishTestResults@2
  displayName: 'ALOps Publish Test Results **/TestResults.xml'
  condition: and(succeeded(), eq(variables['RunTests'], '1'))
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: PublishBuildArtifacts@1
  displayName: 'Publish App Dependencies'
  condition: and(succeeded(), eq(variables['PublishDependencies'], '1'))
  inputs:
    PathtoPublish: '.\app\Dependencies'
    ArtifactName: 'Dependencies'
    publishLocation: 'Container'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsDockerRemove@1
  displayName: 'ALOps Remove Docker Container'
  enabled: true
  condition: always()
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**the output**
```
See attached pipeline log
```
[EV_Internal_1600.0.1.2297.txt](https://github.com/HodorNV/ALOps/files/5480395/EV_Internal_1600.0.1.2297.txt)
