### ISSUE TITLE
ALOps App Test: Specify tenant

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#252]
Not sure if it's a bug, or if it's not possible.

We run a multi-tenant onprem setup and here we always run our tests in a dedicated test tenant.
But the list of parameters to the ALOps App Test task does not seem to include a tenant parameter.
If that is correct, then I would like to request this to be added please.

**Comment by waldo1001** [comment]
Hi @epernst ,

I didn't really have any occasion to test this out.  But can I see the yaml that you tried to make it work?

Did you try to give the tenant with the webclient-url, like this?
```yaml
- task: ALOpsAppTest@1
  inputs:
    nav_serverinstance: 'BC140'
    bc_webclient_url: 'httos://server/?tenant=mytenant'
```
