### ISSUE TITLE
Publishing not working

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#254]
I'm trying to publish an app, but it fails to do so, and it seems that it's either not picking up my inputs, or that I'm completely misunderstanding how to use this task. 
1) It doesn't use my server instances
2) It think it must publish test apps, which it should not.

Yaml code used:
```yaml
          - task: ALOpsAppPublish@1
            displayName: Publish App and Test App
            inputs:
              nav_serverinstance: 'dbc'
              batch_publish_folder: '$(AppFolder)'
              tenant: default
              skip_verification: true
```

Log output attached.
