### ISSUE TITLE
ALOpsDockerCreate licensefile does not resolve variable

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#257]
**Describe the bug**
I'm changing some pipelines and want to add our dev license directly to the image. So I moved the step for downloading the dev livense from "Creating a Container" to the scheduled task "Create the Build Image".
I added the parameter "licensefile"to "ALOpsDockerCreate" - in the YAML File I refer to the variable where the location of the license ('$(DockerLicense.secureFilePath)'.

But it seems the task can not resolve the variable:
`##[error]Cannot find path 'C:\Agent\_work\_tasks\ALOpsDockerCreate_f4c04016-bb3f-4614-b978-ce92409ce78a\1.435.1904\'$(DockerLicense.secureFilePath)'' because it does not exist.`

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
  jobs:
  - job: DownloadDevLicense
    steps:
    - checkout: none
    - task: DownloadSecureFile@1
      displayName: 'Download Dev License'
      name: DockerLicense
      inputs: 
        secureFile: DevLicense
  - job: BuildDockerImages
    steps:
    - checkout: none
    - task: ALOpsDockerCreate@1
      displayName: 'Create DE Docker Image'
      inputs:
        artifacttype: 'Sandbox'
        artifactcountry: 'de'
        imageprefix: 'bcdecurr'
        licensefile: $(DockerLicense.secureFilePath)
        includetesttoolkit: true
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
Building image bcdecurr:sandbox-17.0.17126.18919-de-10.0.17763.1282-ltsc2019 based on mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic with https://bcartifacts.azureedge.net/sandbox/17.0.17126.18919/de
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
10.0.17763.1282-generic: Pulling from dynamicsnav
Generic Tag: 0.1.0.24
Container OS Version: 10.0.17763.1282 (ltsc2019)
Host OS Version: 10.0.17763.1282 (ltsc2019)
Using process isolation
Using license file $(DockerLicense.secureFilePath)
Files in c:\bcartifacts.cache\tmp637411124584006060\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
##[error]Cannot find path 'C:\Agent\_work\_tasks\ALOpsDockerCreate_f4c04016-bb3f-4614-b978-ce92409ce78a\1.435.1904\$(DockerLicense.secureFilePath)' because it does not exist.
```

**Expected behavior**
Using the correct path (as defined in $(DockerLicense.secureFilePath))
