### ISSUE TITLE
Source file 'c:\Run\DevOps\app.json' could not be found

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#259]
**Describe the bug**
For one pipeline we get the error _Source file 'c:\Run\DevOps\app.json' could not be found
_ again, and again and again. Actually I disabled this pipeline because it is not major important, but this afternoon I wanted to check and fix it again.
I have no idea what is wrong.
I have checked the working folder on the build machine - everything is fine.
The "copy log" looks okay for me, too.
When I check the C:\Run\DevOps folder in the container it is not as expected.
![image](https://user-images.githubusercontent.com/5330063/99550079-9aa39600-29ba-11eb-978e-b02cf49e4c79.png)

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- stage: BuildDockerContainerDE
  condition: succeeded('StartBuildVM')
  pool: Default

  jobs:
  - job: StartDockerContainerDE
    steps:
    - checkout: none
    - template: CI/Templates/PrepareDockerEnvironment.yml@CITemplates
      parameters:
        dockerimage: 'sandbox:de'
        usehyperv: true

  - job: PrepareDEDockerContainerWithDependencies
    dependsOn: StartDockerContainerDE
    condition: succeeded('StartDockerContainerDE')
    steps:
    - checkout: none
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Core App'
      inputs:
        buildType: 'specific'
        project: '8d660e8b-36cc-4d1e-af63-9a9459239166'
        pipeline: '3' 
        buildVersionToDownload: 'latestFromBranch'
        allowPartiallySucceededBuilds: true
        branchName: 'refs/heads/master'
        downloadType: 'specific'
        itemPattern: '**/*.app'
        downloadPath: '$(System.ArtifactsDirectory)/Core'      

    - task: DownloadBuildArtifacts@0
      displayName: 'Download PAY App'
      inputs:
        buildType: 'specific'
        project: '8d660e8b-36cc-4d1e-af63-9a9459239166'
        pipeline: '4'
        buildVersionToDownload: 'latestFromBranch'
        allowPartiallySucceededBuilds: true
        branchName: 'refs/heads/master'
        downloadType: 'specific'
        itemPattern: '**/*.app'
        downloadPath: '$(System.ArtifactsDirectory)/PAY'

    - task: ALOpsAppPublish@1
      displayName: 'Import Core'
      inputs:
        usedocker: true
        artifact_path: '$(System.ArtifactsDirectory)/Core'
        nav_artifact_app_filter: '*.app'
        skip_verification: true 

    - task: ALOpsAppPublish@1
      displayName: 'Import PAY'
      inputs:
        usedocker: true
        artifact_path: '$(System.ArtifactsDirectory)/PAY'
        nav_artifact_app_filter: '*.app'
        skip_verification: true               

  - job: TestBuildJobDE
    dependsOn: PrepareDEDockerContainerWithDependencies
    condition: succeeded('PrepareDEDockerContainerWithDependencies')
    steps:
    - checkout: ATTCurrent

    - task: ALOpsAppCompiler@1
      displayName: 'Compile ATT App'
      inputs:
        usedocker: true
        nav_app_version: '$(D365BC16-ReleaseNo).*'
        failed_on_warnings: false
        publish_artifact: false
```

The YAML works for other apps - so no idea whats wrong here..

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
...
*** Copy Working folder to Docker Container: 90f6337e072e5031efe8a3de9d74373c7981c0e010726b550897f728a2944b62
*** Docker Working Folder: c:\Run\DevOps\
*** Copy from [C:\Agent\_work\283\s] to [c:\Run\DevOps\]
*** Source File setup completed
*** Target Project: \app.json
*** Check for app.json files: c:\Run\DevOps\
*** Retrieving App-Info [\app.json]
##[warning]Get-NAVInfoStep: Application manifest [c:\Run\DevOps\app.json] not found.
...
```
