### ISSUE TITLE
Issues accepting  EULA

### ISSUE THREAD

**Issue by tartino** [HodorNV/ALOps#260]
Hi all,

I am having some issues accepting  EULA when trying to use the Alops Docker Step in release pipeline

![image](https://user-images.githubusercontent.com/24921182/99691699-68a93700-2a81-11eb-8b54-980686450db5.png)

Below the yaml

```
steps:
- task: Hodor.hodor-alops.ALOpsDockerCreate.ALOpsDockerCreate@1
  displayName: 'ALOps Docker Create'
  inputs:
    artifactversion: 17.0
    artifacttype: Sandbox
    artifactcountry: gb

steps:
- task: Hodor.hodor-alops.alopsdockerstart.ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    ignore_no_container_warning: true
    docker_pull: false
    memory_gb: 6
    container_restart: always
    docker_parameters: '--isolation=hyperv'

steps:
- task: Hodor.hodor-alops.alopsdockerwait.ALOpsDockerWait@1
  displayName: 'ALOps Docker Wait'

```

Despite having selected the Accept Image Eula in Alops Docker Start I get the following error in a loop

![image](https://user-images.githubusercontent.com/24921182/99692116-d6556300-2a81-11eb-9da6-5ec56e3fef87.png)

Any hint to get me pass this bit? Thank you
