### ISSUE TITLE
Question: how to timeoutInMinutes for the whole pipeline?

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#267]
**Issue**
I have set up a pipeline with ALOps based on template to build my app and run all standard MS test against it. By default a pipeline times out after 60 minutes. As running those thousands of standard tests takes a couple of hours, the pipeline halts with error 
```
##[error]The job running on agent WinSrvr2019-4-2 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
```
Following the link I did find out that you can set **timeoutInMinutes** on a job. As the ALOps templates do not have jobs (and apparently I cannot set that) but tasks, I did set it on the relevant task **ALOpsAppTest**. But this does not seem to have effect. Whether I set it to 0 (meaning it could run endlessly) or 360 (meaning 6 hours) the pipeline halts after 60 minutes.

**Question**
How to **timeoutInMinutes** for the whole pipeline?

I do get that this probably has nothing to do with ALOps, but maybe someone out here did ran into the same and did get it solved. Thanx in advance.

**yaml**
This is my pipeline:
```
name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master/Chapter-9-(LookupValue-Extension)

variables:
- group: 'PipelineVariables'

pool: default

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifactversion: '14'
    artifactcountry: 'w1'

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS - License Import'
  inputs:
    usedocker: true
    license_path: '$(LuxBeheerBcDevLicense)'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject: 'Chapter 9 (LookupValue Extension)/app.json'
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    testfilter: '81000..'
    failed_test_action: 'Ignore'
  continueOnError: true
  timeoutInMinutes: 360

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

**Comment by waldo1001** [comment]
You need to add the Jobs-attribute to be able to set that up.  When doing that, you can set up multiple jobs on multiple agents.  As a default, we don't do this .. but in this case, you'll have to, to be able to set up the timeout.

Try this ;-):

```yaml
name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master

variables:
- group: 'Secrets'

jobs:
- job: default
  timeoutInMinutes: 600
  pool: HOD-DOCKER

  steps:
  - checkout: self
    clean: true 

  - task: ALOpsDockerCreate@1
    displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
    inputs:
      artifactversion: '14'
      artifactcountry: 'w1'

  - task: ALOpsDockerStart@1
    displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

  - task: ALOpsDockerWait@1
    displayName: 'ALOPS - Wait for Docker Container to start'
    inputs:
      search_string: 'Ready for connections!'

  - task: ALOpsLicenseImport@1
    displayName: 'ALOPS - License Import'
    inputs:
      usedocker: true
      license_path: '$(LuxBeheerBcDevLicense)'

  - task: ALOpsAppCompiler@1
    displayName: 'ALOPS - Compile Extension: App'
    inputs:
      usedocker: true
      nav_app_version: '1.0.[yyyyWW].*'
      targetproject: 'Chapter 9 (LookupValue Extension)/app.json'
      app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

  - task: ALOpsAppPublish@1
    displayName: 'ALOPS - Publish Extension'
    inputs:
      usedocker: true
      nav_artifact_app_filter: '*.app'
      skip_verification: true

  #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

  - task: ALOpsAppTest@1
    displayName: 'ALOPS - Run TestSuite'
    inputs:
      usedocker: true
      testfilter: '81000..'
      failed_test_action: 'Ignore'
    continueOnError: true
    timeoutInMinutes: 360

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TestResults.xml'
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: '**/TestResults.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'BC Test Results: $(Build.BuildId)'

  #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

  - task: ALOpsDockerRemove@1
    displayName: 'ALOPS - Remove Docker Container'
    enabled: true
    condition: always()
```
