### ISSUE TITLE
Question: example .yml for on-prem deployment

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#269]
**Issue**
Looking for an example .yml of a on-prem release pipeline with ALOps

**Question**
Could you provide a .yml example for an on-prem release pipeline?

Maybe overlooked it in your nice collections of examples.

**Comment by lvanvugt** [comment]
This would be a great topic for a webinar, IMHO.

**Comment by waldo1001** [comment]
Hi Luc, 

Best example I can give you is this one:
https://www.waldo.be/2020/06/15/deploying-from-devops-the-right-way-enabling-external-deployment-in-onprem-business-central-environments/

a release pipeline cannot be done with yaml.

However, you can do multistage pipelines.  We don't have it on the examples list yet, but here is a snippet form our internal pipeline.

This is one stage, deploying first dependencies, then the actual app, and then the dependent apps.  The reason for the 3 steps is readability - it's very clear now that the main app is installed.  You could also just do everything in batch and don't care..

```yaml
stages:  
  - stage: DeployQA
    displayName: 'Deploy to iFacto'
    jobs:
    - deployment: 'QA'
      pool: '${{ deploy_pool  }}'
      environment: QA
      workspace:
        clean: all
      strategy:
        runOnce:
          deploy:
            steps:
            - task: ALOpsExtensionAPI@1
              displayName: 'Publish Dependencies'
              inputs:
                interaction: batch
                api_endpoint: '$(QA_endpoint)/BC/api'
                authentication: windows
                artifact_path: '$(Agent.BuildDirectory)\Dependencies\'
            - task: ALOpsExtensionAPI@1
              displayName: 'Publish Customer-PTE $(app_name)'
              inputs:
                interaction: publish
                api_endpoint: '$(QA_endpoint)/BC/api'
                authentication: windows
                artifact_path: '$(Agent.BuildDirectory)\$(System.TeamProject)\'
                artifact_filter: '*$(app_name)_*.app'
            - task: ALOpsExtensionAPI@1
              displayName: 'Publish Dependent Apps'
              inputs:
                interaction: batch
                api_endpoint: '$(QA_endpoint)/BC/api'
                authentication: windows
                artifact_path: '$(Agent.BuildDirectory)\DependentApps\'             
 
```

Good idea on the video - I'll think about it!  I'll first foresee a workable template with multistage first!

Do realize I'm using the alops.externaldeployer in this case, which needs a URL.  If you don't want to use that, you can use the normal publish-step which is all over the place (in many examples) to deploy to an NST in docker - but do note that this same step can also be used for non-docker publishes.  Just install a devops agent on the machine, and you should be good to go!

**Comment by waldo1001** [comment]
may be to conclude .. ALOps has all the steps to easily deploy.  You just need to know how to use them!

Easiest is to use:

```yaml
- task: ALOpsExtensionAPI@1
      displayName: 'ALOps Extension API'
      inputs:
        usedocker: False                      # Run task in Docker container. $(usedocker)
        fixed_tag:                            # Allows recycling of docker containers. $(fixed_tag)
        interaction: get                      # Set Interaction Method to use. (Get/Publish/Batch Publish). $(interaction)
        api_endpoint: https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api# Set API Endpoint. (protocol://host:port/serverinstance/api) $(api_endpoint)
        authentication: oauth                 # Set authentication Method to use. Default [Windows]. $(authentication)
        azure_tenant_id:                      # Azure Tenant Id. Only required for BC SaaS $(azure_tenant_id)
        azure_app_client_id:                  # Azure AD Application Client Id. $(azure_app_client_id)
        azure_app_client_secret:              # Azure AD Application Client Secret. $(azure_app_client_secret)
        username:                             # Business Central Username. $(username)
        password:                             # Business Central User Password. $(password)
        bccompany:                            # Business Central Company (Id or Name). $(bccompany)
        artifact_path: $(System.ArtifactsDirectory)# Path for App Artifact. $(artifact_path)
        artifact_filter: *.app                # Filter used for locating App file relative to $(path_to_publish). $(artifact_filter)
        showdeploymentstatus: True            # Show Extension Deployment Status. $(showdeploymentstatus)
```

But you also have:
```yaml
 - task: ALOpsAppPublish@1
      displayName: 'ALOps App Publish'
      inputs:
        usedocker: False                      # Run task in Docker container. $(usedocker)
        fixed_tag:                            # Allows recycling of docker containers. $(fixed_tag)
        installaltesttool: False              # Install the AL TestTool for v15. $(installaltesttool)
        install_al_app_names: Tests-TestLibraries
System Application Test
System Application Test Library
Any
Library Assert
Test Runner
# Specify additional docker parameters. $(install_al_app_names)
        strictappnames: False                 # Only install Specified Apps. $(strictappnames)
        nav_serverinstance: BC140             # Business Central Server Instance Name. $(nav_serverinstance)
        artifact_path:                        # Path for storing App Artifact. $(artifact_path)
        nav_artifact_app_filter: *.app        # Filter used for locating App file relative to $(path_to_publish). $(nav_artifact_app_filter)
        skip_verification: True               # Skip CodeSign Verification of Business Central App. $(skip_verification)
        forcesync: False                      # Sets the Sync-Mode to Force, enables pushing breaking changes. $(forcesync)
        publish_scope: Global                 # Set the scope for publishing extensions. $(publish_scope)
        tenant: default                       # Tenant to publish to when Scope is set to Tenant. $(tenant)
        batch_publish_folder:                 # Path containing Apps to publish. $(batch_publish_folder)
```
