### ISSUE TITLE
One global log file per ALOpsAppCompile tasks

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#274]
**Is your feature request related to a problem? Please describe.**
I'm compiling all of our apps with one ALOpsAppCompile step - using the batch compile option - against different targets to be aware of new warnings. Right now, I get an immense pipeline output, with different compile log results, one per app. 

Would be good it the compile log files of all individual apps could be bundled in a single 'compile.log' file, so we could publish this as pipeline artefacts and have a summary of the effort needed to fix warnings in future versions across all apps.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/25268332/101160071-ae8ffe80-362e-11eb-829f-5eea60d71cb7.png)

**Describe alternatives you've considered**
Is this something ALOps can deliver? If not, we'll process the log files ourselves and join the content in a single log file instead.

**Comment by waldo1001** [comment]
Can I see (part of) the yaml to exactly see what you mean?

**Comment by fvet** [comment]
Clue is the multi checkout combined with one Compile step.

```
name: $(Build.BuildId)

resources:
  repositories:
    - repository: templates
      type: git
      name: Templates
      ref: 'refs/heads/master'

parameters:
  - name : versionSelect
    displayName: Version Select
    type: string
    default: NextMajor
  - name: artifactVersion
    displayName: Artifact Version
    type: string
    default: ' '
  - name: artifactType
    displayName: Artifact Type
    type: string
    default: Sandbox
  - name: branch
    displayName: Branch
    type: string
    default: master
  - name: bundle
    displayName: Extensions
    type: string
    default: All
    values:
      - AppSource
      - All
      - Custom
  - name: country
    displayName: Country
    type: string
    default: BE 
  - name: repositories
    displayName: Repositories (only applies if 'Bundle' is 'Custom')
    type: object
    default:
      - Navitrans.Core

variables:
  - template: CI\variables\pipeline_variables.yml@templates

trigger: none
pool: $(pool_build)

stages:
  - stage: Compile
    displayName: Compile
    jobs:
      - job: Compile
        displayName: Compile
        steps:
          - checkout: git://Navitrans.Base/Scripts
            persistCredentials: true
          - ${{ if eq(parameters.bundle, 'AppSource') }}:
            - template: CI Pipelines\clone_repositories_appsource.yml@templates
          - ${{ if eq(parameters.bundle, 'All') }}:
            - template: CI Pipelines\clone_repositories_full.yml@templates
          - ${{ if eq(parameters.bundle, 'Custom') }}:
            - ${{ each repository in parameters.repositories }}:
              - checkout: git://Navitrans.Base/${{ repository }}
                persistCredentials: true
          - task: PowerShell@2
            displayName: Change branches
            inputs:
              filePath: $(System.DefaultWorkingDirectory)\Scripts\Development\Git\Change branches.ps1
              arguments: -WorkingDirectory '$(System.DefaultWorkingDirectory)' -Branch '${{ parameters.branch }}'

          - task: PowerShell@2
            displayName: Delete .alpackages directory
            inputs:
              filePath: $(System.DefaultWorkingDirectory)\Scripts\Misc\Delete Folders Recursively.ps1
              arguments: -WorkingDirectory '$(System.DefaultWorkingDirectory)' -Depth 1 -Filter '.alpackages'
                            
          - task: ALOpsAppCompiler@2
            displayName: Compile applications
            inputs:
              artifacttype: ${{ parameters.artifactType }}
              artifactcountry: ${{ parameters.country }}
              versionselect: ${{ parameters.versionSelect }}
              appversiontemplate: '?.?.?.*'
              alcodeanalyzer: ''
              failonwarnings: false
              publishartifact: false     
              sastoken: $(bcinsider_sas_token)


```

![image](https://user-images.githubusercontent.com/25268332/101160991-332f4c80-3630-11eb-9e8c-e51916c1ab58.png)
