### ISSUE TITLE
Setup Example Appsource Validation with previous version from PipelineArtifacts

### ISSUE THREAD

**Issue by pri-kise** [HodorNV/ALOps#276]
**Is your feature request related to a problem? Please describe.**
I would like to setup the appsource validation an use the artifact of the pipeline to get previous version.

**Describe the solution you'd like**
Could you please provide an example how to get this work?
I'm unsure about which folders I should use and how they need to be in relative path position that everything works fine and that the template will be able to find the downloaded artifact of the previous version.
**Describe alternatives you've considered**

**Additional context**
The new template I'm refering to.
https://github.com/HodorNV/ALOps/blob/e3257ec3a9ae321199613934bc92f5f870059d4f/Examples/AppSourceValidation/AppSourceValidationTemplateMultiStage.yml#L74

**Comment by waldo1001** [comment]
I'm going to have to put time into setting up an example pipeline .. working on it!

**Comment by waldo1001** [comment]
Don't worry - it's still in the works - but we are re-thinking the way on how to run this in combo with ALOps.. .

**Comment by waldo1001** [comment]
Hi,
the more I look into this, the more I realize that we shouldn't do AppSource validation pipelines with ALOps.  
Freddy is changing the validation rules frequently on many levels (Docker, code analyzer rules, the pipeline, .. ), which makes it impossible for ALOps to follow (it's basically completely undocumented).

For ALValidation, I think the best way is to run the BcContainerHelper Run-ALValidation cmdlet.

don't you agree?

**Comment by waldo1001** [comment]
I didn't realize this was still open.  There has been a new step for a long time already, where we wrapped the Run-ALValidation.

```yaml
    - task: ALOpsAppValidation@1
      displayName: 'ALOps App Validation'
      inputs:
        license_path:                         # Path of the FLF license to import. Must be a fully qualified path or relative to $(System.DefaultWorkingDirectory) or a downloadable Url. $(license_path)
        countries:                            # Comma seperated array of countries to validate. When blank SupportedCountries value from AppSourceCop.json is used. $(countries)
        affixes:                              # Comma seperated array of affixes. $(affixes)
        artifact_path: $(System.ArtifactsDirectory)# Path for App Artifact(s). $(artifact_path)
        artifact_filter: *.app                # Filter used for locating App file relative to $(artifact_path). $(artifact_filter)
        installapps_path: $(System.ArtifactsDirectory)# Path for InstallApps Artifact(s). $(installapps_path)
        installapps_filter: *.app             # Filter used for locating App file relative to $(installapps_path). $(installapps_filter)
        previousapps_path: $(System.ArtifactsDirectory)# Path for PreviousApps Artifact(s). $(previousapps_path)
        previousapps_filter: *.app            # Filter used for locating App file relative to $(previousapps_path). $(previousapps_filter)
        memory: 8G                            # Set maximum memory for Container. $(memory)
        validateversion:                      # Full or partial version number. If specified, apps will also be validated against this version. $(validateversion)
        validatecurrent: False                # Validate against current version of Business Central. $(validatecurrent)
        validatenextminor: False              # Validate against Next Minor version of Business Central. $(validatenextminor)
        validatenextmajor: False              # Validate against Next Major version of Business Central. $(validatenextmajor)
        sastoken:                             # SAS Token used to access Storage Account. $(sastoken)
        skipverification: False               #  $(skipverification)
        skipupgrade: False                    #  $(skipupgrade)
        skipappsourcecop: False               #  $(skipappsourcecop)
        skipconnectiontest: False             #  $(skipconnectiontest)
        includewarnings: False                # Include this switch if you want to include Warnings. $(includewarnings)
        failonerror: True                     # Include this switch if you want to fail on the first error instead of returning all errors to the caller. $(failonerror)
        containername: bcserver               # Only required when running multiple DevOps Agents on the same server. (Not recommended) $(containername)
```
