### ISSUE TITLE
AppSourceValidation sample with multi repo support

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#279]
**Is your feature request related to a problem? Please describe.**
The AppSourceValidation samples will probably work fine for single repo apps. However, when having multiple apps spread accross multiple repo's and managing your product as a suite of dependend apps (spread accross repos), it would make sense to be able to run the AppSourceValidation accross repos (similar to how the BatchCompile works).7

Not sure how to achieve this with the current samples (fix reference to the app/app.json, .previous, ...)

In the sample below, I checkedout some of our apps, but the compile step fails (makes sense)

![image](https://user-images.githubusercontent.com/25268332/101987376-0c0df600-3c94-11eb-8895-5503ee82aa06.png)

It would need some kind of loop for the fast compile steps, as well for the dependend and previous apps.

PS: If I would have to manage a pipeline per app, it would take a lot of setup and I would be forced to store the .dependendapps separatly, whereas I would like to take them from the fast compile step instead.

**Comment by MortenRa** [comment]
We have the same situation

**Comment by waldo1001** [comment]
Hi, can I see the yaml?  Or did you do this in a release pipeline?

**Comment by fvet** [comment]
Copy of the ALOps samples

**AppSourceValidationPipelineMultiStage.yml**

```
name: $(Build.BuildId)

resources:
  repositories:
    - repository: templates
      type: git
      name: Templates
      ref: 'refs/heads/master'

variables:
- group: PipelineVariables
- group: PipelineSecrets

trigger: none
pool: $(pool_build)

stages:
- template: AppSourceValidationTemplateMultiStage.yml  
  parameters:
    AppName: 'Appsource Test'
    appversiontemplate: '1.0.[yyyyWW].*'
    skipverification: true  #this should be false as AppSourceValidation will fail when the app is not signed!
    countries: ['w1'] # ['w1','be']
    selectVersions: ['Current'] # ['Current','NextMinor']
    alsourcepath: App/app.json
    pool: $(pool_build)
    sasToken: $(bcinsider-sas-token)
```

AppSourceValidationTemplateMultiStage.yml


```
parameters:
  AppName: ''
  selectVersions: ['Current']
  countries: ['w1']
  skipverification: false
  alsourcepath: ''
  appversiontemplate: ''
  pool: ''
  sasToken: ''

stages:
- ${{ each country in parameters.countries }}:
  - ${{ each version in parameters.selectVersions }}:
  # Compile your app, taking the AppSourceCop into account.  
  # It will also take all apps in your repo into account.  So make sure you have a decent AppSourceCop.json, that indicates a previous version to check for breaking changes!
  # more info on breaking changes: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0003-previousversionnotfound
  # Also include affixes in the AppSourceCop.json
    - stage: 'build${{ country }}${{ version }}'
      displayName: '${{ country }} ${{ version }}'
      dependsOn: [] #run indepedently
      jobs:
      - job: 'build${{ country }}${{ version }}'
        displayName: 'Job - Validate  ${{ country }} ${{ version }}'
        pool:
          name: ${{ parameters.pool }}
        steps:
        - template: CI Pipelines\clone_repositories_appsource.yml@templates
        - task: ALOpsAppCompiler@2
          displayName: 'Fast compile with AppSourceCop and testing breaking changes - ${{ country }} ${{ version }}'
          inputs:
            artifacttype: 'Sandbox'
            artifactcountry: '${{ country  }}'
            versionselect: ${{ version }}
            publishartifact: false
            alcodeanalyzer: AppSourceCop  #AppSourceCop
            alsourcepath: ${{ parameters.alsourcepath }}
            appversiontemplate: ${{ parameters.appversiontemplate }}
            sasToken: ${{ parameters.sasToken }}

      # Compile is done and succeeded. Only now, we'll set up containers, because we need to be able to see if the apps work against the previous!

        - task: ALOpsDockerCreate@1
          displayName: 'Creating Docker - ${{ country }} ${{ version }}'
          inputs:
            artifacttype: Sandbox
            artifactcountry: '${{ country  }}'
            versionselect: ${{ version }}
            sasToken: ${{ parameters.sasToken }}

        - task: ALOpsDockerStart@1
          displayName: 'Starting Docker - ${{ country }} ${{ version }}'

        - task: ALOpsDockerWait@1
          displayName: 'Waiting for Docker to be started - ${{ country }} ${{ version }}'
          inputs:
            search_string: 'Ready for connections!'

        - task: ALOpsLicenseImport@1
          displayName: 'Import License - ${{ country }} ${{ version }}'
          inputs:
            usedocker: true
            license_path: '$(bc.license)'  #  Don't forget to create this variable.  more info: https://www.youtube.com/watch?v=iVLOerdCuwA&t=3078s

        - task: ALOpsAppPublish@1
          displayName: 'Publish dependent apps - ${{ country }} ${{ version }}'
          inputs:
            usedocker: true
            batch_publish_folder: 'app/.apps' #dependentapps
            skip_verification: ${{ parameters.skipverification }}

        - task: ALOpsAppPublish@1
          displayName: 'Publish previous version of my app - ${{ country }} ${{ version }}'
          inputs:
            usedocker: true
            batch_publish_folder: 'app/.previous'
            skip_verification: ${{ parameters.skipverification }}

        - task: ALOpsAppPublish@1
          displayName: 'Publish new version of app - ${{ country }} ${{ version }}'
          inputs:
            usedocker: true
            artifact_path: '$(ALOPS_COMPILE_ARTIFACT)'
            skip_verification: ${{ parameters.skipverification }}

        # if all this was successfull, we're good!
    
        - task: ALOpsDockerRemove@1
          displayName: 'Remove Docker - ${{ country }} ${{ version }}'
          enabled: true
          condition: always()
```

Only changed the checkout part to 

`CI Pipelines\clone_repositories_appsource.yml@templates`

```
parameters:
  - name: country
    displayName: Country
    type: string
    default: W1

steps:
  - checkout: git://Navitrans.Base/Navitrans.Core
    persistCredentials: true
  - checkout: git://Navitrans.Base/Navitrans.Base
    persistCredentials: true
  - checkout: git://Navitrans.Base/Navitrans.Scanning
    persistCredentials: true
  - checkout: git://Navitrans.Base/Navitrans.Package
    persistCredentials: true
  - checkout: git://Navitrans.Base/Navitrans.CrossDock
    persistCredentials: true
  - checkout: git://Navitrans.Base/Navitrans.DriverAppConnector
    persistCredentials: true
  - checkout: git://Navitrans.Base/Navitrans.Navitrans_365
    persistCredentials: true
```

**Comment by waldo1001** [comment]
The more I look into this, the more I realize that we shouldn't do this with ALOps.

Freddy does changes to different levels of the validation, and the only way to keep up, is to run the BcContainerHelper ALValidation, I'm afraid.

Don't you agree?

**Comment by waldo1001** [comment]
The wrapper was already on the table .. but the complete rebuild of the validation process - that's where we have doubts.. .

Ok, thanks for the feedback!  Very much appreciated!

**Comment by waldo1001** [comment]
Hi @fvet,

because we value the opinion of our customers ;-) - we'll add a wrapper for Run-ALValdiation.

We'll foresee a way to do additionalParameters for the ones we don't find important, so in fact all future parameters will also be addressable.

**Comment by waldo1001** [comment]
The wrapper exists in the form of a new step:

```yaml
 - task: ALOpsAppValidation@1
      displayName: 'ALOps Docker Create'
      inputs:
        license_path:                         # Path of the FLF license to import. Must be a fully qualified path or relative to $(System.DefaultWorkingDirectory) or a downloadable Url. $(license_path)
        countries: W1                         # Comma seperated array of countries to validate. $(countries)
        affixes:                              # Comma seperated array of affixes. $(affixes)
        artifact_path: $(System.ArtifactsDirectory)# Path for App Artifact. $(artifact_path)
        artifact_filter: *.app                # Filter used for locating App file relative to $(path_to_publish). $(artifact_filter)
        memory: 8G                            # Set maximum memory for Container. $(memory)
        validateversion:                      # Full or partial version number. If specified, apps will also be validated against this version. $(validateversion)
        validatecurrent: False                # Validate against current version of Business Central. $(validatecurrent)
        validatenextminor: False              # Validate against Next Minor version of Business Central. $(validatenextminor)
        validatenextmajor: False              # Validate against Next Major version of Business Central. $(validatenextmajor)
        sastoken:                             # SAS Token used to access Storage Account. $(sastoken)
        skipverification: False               #  $(skipverification)
        skipupgrade: False                    #  $(skipupgrade)
        skipappsourcecop: False               #  $(skipappsourcecop)
        skipconnectiontest: False             #  $(skipconnectiontest)
        includewarnings: False                # Include this switch if you want to include Warnings. $(includewarnings)
        failonerror: True                     # Include this switch if you want to fail on the first error instead of returning all errors to the caller. $(failonerror)
```
