### ISSUE TITLE
Unexpected Artifacts from CI

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#28]
I have an unexpected Artifact structure after CI (App + TestApp)

My CI pipeline contains at least these steps:

![image](https://user-images.githubusercontent.com/15800069/64485817-64e71700-d225-11e9-9672-230adb8b643e.png)

```yml
  - task: ALOpsAppCompiler@1
    displayName: 'ALOPS Compile App'
    inputs:
      usedocker: true
      targetproject: 'app/app.json'
      nav_app_version: '$(AppVersion)'

# Publish App ...

  - task: ALOpsAppCompiler@1
    displayName: 'ALOPS Compile Test-Extension'
    inputs:
      usedocker: true
      targetproject: 'testapp/app.json'
      nav_app_version: $(AppVersion)

# Publish Test App & Run Tests ...

  - task: PublishBuildArtifacts@1  
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'app'
      publishLocation: 'Container'
```

My Artifact contains:

![image](https://user-images.githubusercontent.com/15800069/64485844-995ad300-d225-11e9-9f2d-12d44bbab21b.png)

When I uses this Artifact in CD I get:

![image](https://user-images.githubusercontent.com/15800069/64485769-ca86d380-d224-11e9-96b2-23b093674bb4.png)

![image](https://user-images.githubusercontent.com/15800069/64485861-c909db00-d225-11e9-8d6a-af23dec590dc.png)

![image](https://user-images.githubusercontent.com/15800069/64485765-c490f280-d224-11e9-9666-d7157efe6caf.png)

Is there a better way to define, what's inside of the artifact?

**Comment by waldo1001** [comment]
Now, there is a "publish_artifact" option in the compile-step, which lets you disable the auto-artifact-creation:

```yaml
- task: ALOpsAppCompiler@1
      displayName: 'ALOps App Compiler'
      inputs:
        usedocker: False                      # Run task in Docker container. $(usedocker)
        fixed_tag:                            # Allows recycling of docker containers. $(fixed_tag)
        targetproject: ./app.json             # Path of the project to compile. Must be a fully qualified path or relative to $(System.DefaultWorkingDirectory). $(targetproject)
        nav_computername: localhost           # Target Business Central Server running service tier. $(nav_computername)
        nav_serverinstance: BC140             # Business Central Server Instance Name. $(nav_serverinstance)
        nav_tenant: default                   # NAV Tenant used for symbols and compiling the app. $(nav_tenant)
        nav_ports_dev: 7049                   # NAV Port used for DEV-Service. $(nav_ports_dev)
        bc_username:                          # BC Username for ServiceTier connection. $(bc_username)
        bc_password:                          # BC User Password for ServiceTier connection. $(bc_password)
        al_compiler_version: 0.12.15355       # AL Compiler version used for compiling. $(al_compiler_version)
        al_analyzer:                          # AL Analyzer(s) used for compiling. (Example: CodeCop,UICop) $(al_analyzer)
        nav_app_version: 1.0.*.0              # Template for versioning NAV-Apps. '*' is replaced by the current Build Number. $(nav_app_version)
        vsix_download_path:                   # Alternative VSIX download url. $(vsix_download_path)
        use_ssl: False                        # Use SSL for Business Central connections. $(use_ssl)
        download_test_symbols: False          # Download Test Symbols explicitly (without Test-Version reference in App.json). $(download_test_symbols)
        usecompression: True                  # Compress Source-Folder for transfer to docker container. $(usecompression)
        publish_artifact: True                # Publish generated App Artifact to DevOps. $(publish_artifact)
        failed_on_warnings: False             # Fail task when any warning occurs. $(failed_on_warnings)
        app_file_suffix:                      # Set a suffix tag on the compiled App filename. $(app_file_suffix)
        updatebuildnumber: True               # Update the Build number with the current version. $(updatebuildnumber)
```
