### ISSUE TITLE
Question regarding ALOpsAgentMaintenance

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#294]
Hey Guys, 

Could you please clarify how does internals of ALOpsAgentMaintenance task works. I have a feeling that its cleaning up logic for images works incorrectly. I noticed, that I am missing some of the images on my buildserver and I am sure they been used in the past 30days. 

**the used yaml**
```
- task: ALOpsAgentMaintenance@1
  inputs:
    removeoldtasks: true
    removeunusedcontainers: true
    removebcartifacts: true
```
