### ISSUE TITLE
ALOpsDockerStart misses multi-tenancy option

### ISSUE THREAD

**Issue by tfenster** [HodorNV/ALOps#296]
**Describe the bug**
Not sure if this is a bug or a design decision but I noticed that there is no parameter to define whether a container should be in multi-tenant mode (our scenario is an onprem customer running in multi-tenancy, so we need a way start a multi-tenant container if we want to use a customer db backup in our build pipeline). It is available for ALOpsDockerCreate, so I am wondering whether it would be able to add it to ALOpsDockerStart as well? I know I can add it to the environment parameters but it would be cleaner and easier to understand as a dedicated parameter

**Comment by waldo1001** [comment]
We'll add the parameter!

**Comment by waldo1001** [comment]
There's a new parameter for this:

```yaml
- task: ALOpsDockerCreate@1
      displayName: 'ALOps Docker Create'
      inputs:
         multitenant: False                    # Create a Multi-Tenant image. $(multitenant)
```

Can you confirm it helps your case?
