### ISSUE TITLE
Build pipeline creates two artifacts folders with identical content

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#297]
**Describe the bug**
Yesterday, we started using the new feature **createsqlbackup** in the _ALOpsDockerRemove_ step (see #268). After this change we do get two artifacts folders with the same content. Note that this is the only change made to the pipeline.
Have a look at the screenshot down below.

**the used yaml**
```
name: $(Build.BuildId)

trigger:
 branches:
    include:
      - ontwikkeling

variables:
  - group: "AlOps" # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds

pool: "AlOps"

steps:
  - checkout: self
    clean: true

  - task: ALOpsDockerCreate@1
    displayName: "ALOPS - Create Docker Image" # It will reuse the image if already exists, or build one if it doesn't.
    inputs:
      artifactversion: '17'
      artifactcountry: 'w1'

  - task: ALOpsDockerStart@1
    displayName: "ALOPS - Start Docker Container" # No need to provide any details - it will get the details from previous step
    inputs:
      docker_parameters: '--volume d:\temp\Arien:c:\run\Arien'

  - task: ALOpsDockerWait@1
    displayName: "ALOPS - Wait for Docker Container to start"
    inputs:
      search_string: "Ready for connections!"

  - task: ALOpsLicenseImport@1
    displayName: "ALOPS - License Import"
    inputs:
      usedocker: true
      license_path: '$(Direct)'
  # more info: https://www.youtube.com/watch?v=iVLOerdCuwA&t=3078s

  #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  - task: ALOpsAppPublish@1
    displayName: "ALOPS - Install AL TestTool" # install necessary dependent apps for testability
    inputs:
      usedocker: true
      installaltesttool: true
      skip_verification: true
      install_al_app_names: |
        Tests-TestLibraries
        System Application Test
        System Application Test Library
        Any
        Library Assert
        Test Runner

  #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  - task: PowerShell@2
    displayName: "Create new LicensePageListenerCodeunit"
    inputs:
        targetType: filePath
        filePath: 'Powershell\SDK-al\New-LicensePageListenerCodeunit.ps1'
        arguments: '-appFolders "Code" -Destination "Code\Src\License\AgriwareLicPageListener.Codeunit.al"'

  - task: PowerShell@2
    displayName: "Check for FIXMEs"
    inputs:
      filePath: 'Powershell\SDK-al\CheckForFIXMEs.ps1'
      arguments: '-inputfolderpath ''Code\Src'' -Outputfolderpath $(Build.ArtifactStagingDirectory)'
      errorActionPreference: 'continue'

  - task: ALOpsAppCompiler@1
    displayName: "ALOPS - Compile Extension: Agriware W1"
    inputs:
      usedocker: true
      targetproject: 'Code/app.json'
      nav_app_version: '17.0.[yyyyWW].*'
      app_file_suffix: '_APP'

  - task: PowerShell@2
    displayName: "Export compilelog of App"
    inputs:
      targetType: 'inline'
      script: 'Copy-Item -Path compilelog.txt -Destination $(Build.ArtifactStagingDirectory)\compilelog_App.txt'
      errorActionPreference: 'continue'

  - task: ALOpsAppPublish@1
    displayName: "ALOPS - Publish Extension"
    inputs:
      usedocker: true
      nav_artifact_app_filter: "*.app"
      skip_verification: true

  - task: ALOpsAppCompiler@1
    displayName: "ALOPS - Compile Extension: Test-App"
    inputs:
      usedocker: true
      nav_app_version: "?.?.[yyyyWW].*"
      targetproject: "test/app.json" # The Test-App
      app_file_suffix: "_TEST" # A trick to uniquely identify the Test-App (from the App)

  - task: PowerShell@2
    displayName: "Export compilelog of Test"
    inputs:
      targetType: 'inline'
      script: 'Copy-Item -Path compilelog.txt -Destination  $(Build.ArtifactStagingDirectory)\compilelog_Test.txt'
      errorActionPreference: 'continue'
  
  - task: ALOpsAppPublish@1
    displayName: "ALOPS - Publish Extension"
    inputs:
      usedocker: true
      nav_artifact_app_filter: "*.app"
      skip_verification: true

  #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  - task: PowerShell@2
    inputs:
      filePath: 'Powershell/SDK-al/Import-AgriwareLicense.ps1'
      arguments: '-containername $(ALOPS_DOCKER_CONTAINER_ID)'
      
  - task: ALOpsAppTest@1
    displayName: "ALOPS - Run TestSuite"
    inputs:
      usedocker: true
      import_testtoolkit: false
      import_action: 'Skip'
      testpage: '130455'
      failed_test_action: 'Ignore'
    continueOnError: true

  - task: PublishTestResults@2
    displayName: "Publish Test Results **/TestResults.xml"
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: "**/TestResults.xml"
      testRunTitle: "BC Test Results: $(Build.BuildId)"

  #<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

  - task: ALOpsDockerRemove@1
    displayName: "ALOPS - Remove Docker Container"
    enabled: true
    condition: always()
    inputs:
      createsqlbackup: true
      zipsqlbackup: false
```

**the output**
Not sure what logs are exactly need, and as there are many in the wholepipeline I wanted to add the raw text of the **ALOpsDockerRemove** step only, but did get an error (see below as `code`). Therefor all logs have been added in a .zip here: [logs_1686.zip](https://github.com/HodorNV/ALOps/files/5819870/logs_1686.zip)
```
There was an error creating your Issue: body is too long (maximum is 65536 characters).
```

**Expected behavior**
We had expected to have:

- **option 1:** only one artifacts folder with all artifacts, or
- **option 2:** two folders being the one we already had (i.e. _Dynamics 365 APP_), including is content as before, and a new one that would contain the db backup

**Screenshots**

![image](https://user-images.githubusercontent.com/18466198/104703136-3f222a00-5717-11eb-99e4-b2775812a6b5.png)
