### ISSUE TITLE
ALOpsCompile - add option to overwrite ShowMyCode

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#300]
**Is your feature request related to a problem? Please describe.**
We currently only publish one version of our app (no runtimepackages) for OnPrem (customers/partners), with ShowMyCode = true (checked in with true on our repo). We don't want this 'showmycode' to be set to true when targetting AppSource untill MS actually provides a better IP protection / debug experience.

Therefore we'd like to change the 'ShowMyCode' setting as part of the ALOpsCompile step, similar to the ALOpsAppRuntimePackage paramater

`showmycode: False                     # Overwrites the ShowMyCode value in the manifest. $(showmycode)`

This also would result in duplicating our pipelines, to get different artifacts for OnPrem vs AppSource.

**Comment by waldo1001** [comment]
This shouldn't be that difficult .. we'll include it!

**Comment by fvet** [comment]
First of all, thanks for the latest update!

I'm trying to add a new NOCODE version of our apps in our pipelines, adding a new ALOpsCompiler@2 step with the new ShowMyCode setting. However, when opening the compiled NOCODE app file, the manifest file still shows ShowMyCode = true. Any clues?

Here's part of our template based ymls.

```
- task: ALOpsAppCompiler@2
  displayName: 'Compile $(Build.Repository.Name)'
  inputs:    
    artifactversion: '17.2' # Current version
    artifacttype:  'OnPrem'
    artifactcountry: $(country)
    appversiontemplate: '?.?.?.*'
    alcodeanalyzer: ${{ parameters.al_analyzer }}
    alsourcepath: '$(System.DefaultWorkingDirectory)/${{ parameters.alsourcepath }}'
    failonwarnings: ${{ parameters.failed_on_warnings }}
    publishartifact: false
    # alternativevsixurl: $(alops_alternativevsixurl) # // TODO - Waiting ALOps improvements (currently slow)

- template: ..\..\CI Pipelines\publish_permissions.yml@templates
  parameters:
    checkPermissions: true
    logMissingPermissionAsError: true #setting this to true will fail the step

- ${{ if eq(parameters.include_appsource, true) }}:
  - task: ALOpsAppCompiler@2
    displayName: 'Compile $(Build.Repository.Name) (AppSource)'
    inputs:    
      artifactversion: '17.2' # Current version
      artifacttype:  'OnPrem' # Cloud?
      artifactcountry: $(country)
      appversiontemplate: '?.?.?.*'
      alcodeanalyzer: ${{ parameters.al_analyzer }}
      alsourcepath: '$(System.DefaultWorkingDirectory)/${{ parameters.alsourcepath }}'
      failonwarnings: ${{ parameters.failed_on_warnings }}
      publishartifact: false
      appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_%BC_TYPE%_%BC_VERSION%_NOCODE_%BC_COUNTRY%.app' # Added 'NOCODE' to default naming
      showmycode: 'Disable' # ShowMyCode = False

- template: sign_app.yml
```

![image](https://user-images.githubusercontent.com/25268332/108685544-8d83cf00-74f4-11eb-8a17-6bf29f437110.png)
