### ISSUE TITLE
Add option to Force-Install App

### ISSUE THREAD

**Issue by jcoe-nvt** [HodorNV/ALOps#305]
**Is your feature request related to a problem? Please describe.**
We have a few environments where we always want all our apps to be installed. If someone previously uninstalled it, we want it back on next run. (Or if app was only published during previous run, we want it installed on next.)

**Describe the solution you'd like**
A new variable in the batch publish step: Force-Install. If enabled: app will be installed regardless of the previous status. (If disabled (default): step may behave as usual)

**Comment by waldo1001** [comment]
There's a new parameter for this:

```yaml
- task: ALOpsAppPublish@1
      displayName: 'ALOps App Publish'
      inputs:
.
.
.
        forceinstall: True
```

Can you confirm it helps your case?
