### ISSUE TITLE
Question Regarding PublisherAzureActiveDirectoryTenantId 

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#306]
Are -PublisherAzureActiveDirectoryTenantId supported in ALOps App Publish. 

For on-premises deployments, you can configure Business Central Server to run with or without publisher validation of key vault secret providers. Publisher validation is controlled by the server's Enable Publisher Validation (AzureKeyVaultAppSecretsPublisherValidationEnabled) configuration setting. The validation is a runtime operation that ensures extensions use only key vaults that belong to their publishers. It essentially blocks attempts in AL to read secrets from another publisher's key vault.

Publisher validation is done by comparing the key vault's Azure AD tenant ID with the extension publisher's Azure AD tenant ID

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-app-key-vault

**Comment by waldo1001** [comment]
Thanks for putting this on GitHub, Morton!  Here, I can ask additional questions, and we help all other ALOps users as well.

It's the first time I hear of this .. and it's not clear to me how this is used in BcContainerHelper either :-/.  It's added to the publish-script, but it doesn't seem to be using it 🤔.

What do you expect from this?

**Comment by MortenRa** [comment]
As We use Keyvault in our apps on appsource, It will help me to test on-prem before submitting to appsource but I use App Publish in a release pipeline to QA and Release enviroment internally, so to avoid for me to manually publish this through powershell

**Comment by waldo1001** [comment]
Makes sense .. we'll add it on the (already extensive) list!

**Comment by waldo1001** [comment]
There's a new parameter for this:

```yaml
- task: ALOpsAppPublish@1
      displayName: 'ALOps App Publish'
      inputs:
.
.
.
        publisherazureactivedirectorytenantid: # Publisher Azure AD TenantId. $(publisherazureactivedirectorytenantid)
```
