### ISSUE TITLE
Artifact Name was changed in ALOpsAppCompiler@1 from `Dynamics 365 App` to `Dynamics 365`

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#307]
The old version of ALOpsAppCompiler@1 have published the App-Artifact as: **`Dynamics 365 App`** the current version publish the App-Artifact as **`Dynamics 365`** this resulted in broken builds of each pipeline, because we publish the artifact to an artifact feed :(

**the used yaml**
However, 
```yaml
  - task: ALOpsAppCompiler@1
    displayName: 'ALOps Compile App'
    inputs:
      usedocker: true
      targetproject:      ${{ parameters.AppJson }}
      nav_app_version:    $(AppVersion)
      vsix_download_path: '$(job.VSIX_PATH)'
      failed_on_warnings: $(job.Compile.FailOnWarning)
```

Before:
```
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extensions for Business Central
Version      : 1.438.2074
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
```
![image](https://user-images.githubusercontent.com/15800069/107022572-dc67ff80-67a5-11eb-93f8-5d38f75e76d0.png)

Now:
```
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extensions for Business Central
Version      : 1.438.2098
Author       : Hodor
Help         : Compile a Business Central extension from AL code.
==============================================================================
```
![image](https://user-images.githubusercontent.com/15800069/107022842-27821280-67a6-11eb-82e9-66358b36eb04.png)

**However, we have changed our templates. To avoid such breaking changes in the future, I recommend strongly to add a parameter to the Task to configured it.**
