### ISSUE TITLE
ContainerHelper cannot run in Windows PowerShell (x86), need 64bit mode

### ISSUE THREAD

**Issue by marcelvos1** [HodorNV/ALOps#314]
**Describe the bug**
I have setup a build agent on my own build server. If I create a docker image the pipeline returned the following error: ContainerHelper cannot run in Windows PowerShell (x86), need 64bit mode. I'am using Windows Server 2019.
Thanks for helping.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```
- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: '17'
    artifactcountry: 'NL'
```

**the output**

```
*** Importing required PS-Functions
*** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
*** Check BcContainerHelper
*** Load BcContainerHelper
##[error]ContainerHelper cannot run in Windows PowerShell (x86), need 64bit mode
```

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/41510009/107519009-fc396200-6baf-11eb-9a62-4b718371fb04.png)
