### ISSUE TITLE
AlopsAmsiController.ps1 error while already implemented "alops_disable_amsi" = true

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#318]
Having setup a full blown new agents server we ran in to the same issue as #128. We implemented the pipeline variable `"alops_disable_amsi" = true`, which did solve the initial issue. Our pipeline did ran through the first steps:

- ALOpsDockerCreate
- ALOpsDockerStart
- ALOpsDockerWait
- ALOpsLicenseImport

But failed with a similar error on step _ALOpsAppPublish "ALOPS - Install AL TestTool"_

```
##[error]At C:\ADO Agents\Agent1\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.440.2155\45989934-1f65-4833-b2ce-220f38695611.ps1:1 char:1
+ . ".\ps_modules\alops\_AlopsAmsiController.ps1"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
```
**the used yaml**
```yaml
name: $(Build.BuildId)

trigger:
 branches:
    include:
      - ontwikkeling

variables:
  - group: "AlOps" # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds
  - name: 'alops_disable_amsi'
    value: true

pool: "BLDA Agents"

steps:
  - checkout: self
    clean: true

  - task: ALOpsDockerCreate@1
    displayName: "ALOPS - Create Docker Image" # It will reuse the image if already exists, or build one if it doesn't.
    inputs:
      artifactversion: '17'
      artifactcountry: 'w1'

  - task: ALOpsDockerStart@1
    displayName: "ALOPS - Start Docker Container" # No need to provide any details - it will get the details from previous step

  - task: ALOpsDockerWait@1
    displayName: "ALOPS - Wait for Docker Container to start"
    inputs:
      search_string: "Ready for connections!"

  - task: ALOpsLicenseImport@1
    displayName: "ALOPS - License Import"
    inputs:
      usedocker: true
      license_path: '$(Direct)'

  - task: ALOpsAppPublish@1
    displayName: "ALOPS - Install AL TestTool" # install necessary dependent apps for testability
    inputs:
      usedocker: true
      installaltesttool: true
      skip_verification: true
      install_al_app_names: |
        Tests-TestLibraries
        System Application Test
        System Application Test Library
        Any
        Library Assert
        Test Runner
  
  - task: PowerShell@2
    displayName: "Create new LicensePageListenerCodeunit"
    inputs:
        targetType: filePath
        filePath: 'Powershell\SDK-al\New-LicensePageListenerCodeunit.ps1'
        arguments: '-appFolders "Code" -Destination "Code\Src\License\AgriwareLicPageListener.Codeunit.al"'

  - task: PowerShell@2
    displayName: "Check for FIXMEs"
    inputs:
      filePath: 'Powershell\SDK-al\CheckForFIXMEs.ps1'
      arguments: '-inputfolderpath ''Code\Src'' -Outputfolderpath $(Build.ArtifactStagingDirectory)'
      errorActionPreference: 'continue'

  - task: ALOpsAppCompiler@1
    displayName: "ALOPS - Compile Extension: Agriware W1"
    inputs:
      usedocker: true
      targetproject: 'Code/app.json'
      nav_app_version: '17.0.[yyyyWW].*'
      app_file_suffix: '_APP'

  - task: PowerShell@2
    displayName: "Export compilelog of App"
    inputs:
      targetType: 'inline'
      script: 'Copy-Item -Path compilelog.txt -Destination $(Build.ArtifactStagingDirectory)\compilelog_App.txt'
      errorActionPreference: 'continue'

  - task: ALOpsAppPublish@1
    displayName: "ALOPS - Publish Extension"
    inputs:
      usedocker: true
      nav_artifact_app_filter: "*.app"
      skip_verification: true

  - task: ALOpsAppCompiler@1
    displayName: "ALOPS - Compile Extension: Test-App"
    inputs:
      usedocker: true
      nav_app_version: "?.?.[yyyyWW].*"
      targetproject: "test/app.json" # The Test-App
      app_file_suffix: "_TEST" # A trick to uniquely identify the Test-App (from the App)

  - task: PowerShell@2
    displayName: "Export compilelog of Test"
    inputs:
      targetType: 'inline'
      script: 'Copy-Item -Path compilelog.txt -Destination  $(Build.ArtifactStagingDirectory)\compilelog_Test.txt'
      errorActionPreference: 'continue'
  
  - task: ALOpsAppPublish@1
    displayName: "ALOPS - Publish Extension"
    inputs:
      usedocker: true
      nav_artifact_app_filter: "*.app"
      skip_verification: true

      
  - task: ALOpsAppTest@1
    displayName: "ALOPS - Run TestSuite"
    inputs:
      usedocker: true
      import_testtoolkit: false
      import_action: 'Skip'
      testpage: '130455'
      failed_test_action: 'Ignore'
    continueOnError: true

  - task: PublishTestResults@2
    displayName: "Publish Test Results **/TestResults.xml"
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: "**/TestResults.xml"
      testRunTitle: "BC Test Results: $(Build.BuildId)"

  - task: ALOpsDockerRemove@1
    displayName: "ALOPS - Remove Docker Container"
    enabled: true
    condition: always()
    inputs:
      createsqlbackup: 'onfailure'
```

**the output**
```
2021-02-18T08:48:52.7458526Z ##[section]Starting: ALOPS - Install AL TestTool
2021-02-18T08:48:52.7693455Z ==============================================================================
2021-02-18T08:48:52.7694364Z Task         : ALOps App Publish
2021-02-18T08:48:52.7695133Z Description  : Publish AL Extension to Business Central
2021-02-18T08:48:52.7695817Z Version      : 1.440.2155
2021-02-18T08:48:52.7696382Z Author       : Hodor
2021-02-18T08:48:52.7697156Z Help         : Publish Business Central extension to service tier.
2021-02-18T08:48:52.7698073Z ==============================================================================
2021-02-18T08:48:54.2584014Z ##[error]At C:\ADO Agents\Agent1\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.440.2155\45989934-1f65-4833-b2ce-220f38695611.ps1:1 char:1
+ . ".\ps_modules\alops\_AlopsAmsiController.ps1"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
2021-02-18T08:48:54.9072028Z ##[section]Finishing: ALOPS - Install AL TestTool
```

**Expected behavior**
We had expected that setting `"alops_disable_amsi" = true` would have solved this also.
