### ISSUE TITLE
ALOpsAppCompiler fails

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#32]
```yml
  - task: ALOpsAppCompiler@1
    displayName: 'ALOps Compile App'
    inputs:
      targetproject: './app/app.json'
      nav_computername: 'build-agent-nst'
      use_ssl: true
      nav_serverinstance: 'NAV'
      nav_tenant: 'default'
      nav_ports_dev: 7049
      al_compiler_version: '3.0.154634'
      vsix_download_path: '$(VSIXDownloadPath)'
      nav_app_version: $(AppVersion)
```

![image](https://user-images.githubusercontent.com/15800069/64874829-1f26b600-d64c-11e9-8232-22375e2754c7.png)

![image](https://user-images.githubusercontent.com/15800069/64874789-0b7b4f80-d64c-11e9-962a-bc544f6a9606.png)

`VSIXDownloadPath` is set to: `C:\run\*.vsix`
