### ISSUE TITLE
ALOps Docker Start fails for "'Set-MpPreference' is not recognized"

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#341]
**Describe the bug**
ALOps Docker Start fails since today in several projects.

![image](https://user-images.githubusercontent.com/15800069/110826803-c0201c80-8295-11eb-92f4-1f15b0d88c86.png)

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image:          '$(DockerImage)'
    container_restart:     'always'
    accept_image_outdated: true
    docker_pull:           $(job.Docker.Pull)
    enable_symbol_loading: ${{ parameters.EnableSymbolLoading }}
    enable_api_services:   true
    memory_gb:             $(job.Docker.MemoryGB)
    docker_parameters:    '$(job.Docker.Parameters)'
```

**the output**
```
Starting: ALOps Docker Start
==============================================================================
Task         : ALOps Docker Start
Description  : Start a Business Central container
Version      : 1.440.2363
Author       : Hodor
Help         : Start Business Central docker container.
==============================================================================
##[error]The term 'Set-MpPreference' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Finishing: ALOps Docker Start
```

**Expected behavior**
🤔 docker container should be started 😁
