### ISSUE TITLE
Error response from daemon: invalid volume specification: ' C:\Licenses:C:/licenses'

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#345]
Since today I am not able to finish my pipeline succesfully anymore. In the ALOPS - Start Docker Container step it fails on the following code:

```
*** Splitting Additional Docker Parameters
*** Additional Docker parameters:
 -v "C:\Licenses:C:/licenses"
*** Add docker parameter:  -v "C:\Licenses:C:/licenses"
"docker" create --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=MyCustomer_22045  -v "C:\Licenses:C:/licenses" myimage:onprem-17.2.19367.19735-be-10.0.17763.1817-ltsc2019
Error response from daemon: invalid volume specification: ' C:\Licenses:C:/licenses'
*** Checking for Assemblies in App
"docker" start 
"docker start" requires at least 1 argument.
See 'docker start --help'.

Usage:  docker start [OPTIONS] CONTAINER [CONTAINER...]

Start one or more stopped containers
*** Container Started: 
##[error]Cannot bind argument to parameter 'ContainerID' because it is an empty string.
```

The c:\licenses directory still exist on the building machine.
The Yaml wasn't changed recently:

```
trigger: none
name: $(Build.BuildId)

variables:
- group: 'Secrets'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds

pool: BHNL Business Central Pool

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: 17.2
    artifactcountry: 'be'
    licensefile: C:\licenses\17.flf

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step
  inputs:
    docker_parameters: |
      -v "C:\Licenses:C:/licenses"

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.0.*'
    failed_on_warnings: true    
    targetproject: './app.json'   # point to the folder in your repo that you want to compile in this step

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

Any idea?
