### ISSUE TITLE
Retrieve generated nav_app_version

### ISSUE THREAD

**Issue by StijnBt** [HodorNV/ALOps#346]
**Is your feature request related to a problem? Please describe.**
My pipelines calls 3 templates in 3 jobs, the last job adds a version tag.
Since ALOps generates the version tag that's the one I want to use in my tag.

**Describe the solution you'd like**
Some kind of global variable that allows me to use the generated nav_app_version in other jobs/steps.

**Describe alternatives you've considered**
Generate  version tag accordingly as ALOps does it, in my template that handles the version tag.

**Comment by StijnBt** [comment]
Nevermind it can be found in the Freddyscripts.

**Comment by waldo1001** [comment]
Can you share it?  Just that it's documented on this issue as well? :-)

**Comment by StijnBt** [comment]
Well... I saw the Freddyscripts passing by in your DevOps course of this week.
I **thought** I saw he version numbering function. 
I was wrong and actually pretty happy about it... because the answer was right in front of me al the time.

It's the the BuildNo... 
![image](https://user-images.githubusercontent.com/37275572/112747143-b85db900-8fb3-11eb-9460-f7ae90e9dab5.png)

The actual code to set a (version) tag

```yaml
steps:
- checkout: self
  clean: true
  persistCredentials: true
- powershell: |
    $env:GIT_REDIRECT_STDERR = '2>&1' # Do not report git output as error... However error is also only text now

    Write-Host "Tagging Build: $env:appversion"
    
    git tag $env:appversion
    git push origin $env:appversion

  env:
    appversion: $(Build.BuildNumber)
  condition: eq(variables['bc-versiontag'],'true')
  displayName: 'Adding version tag'
```

Usecase:
In an OnPrem world where new versions are not necesarely deployed by default within x amount of time.
Due to infrastructure, approval, ... issues. So if a customer might remain on an older version, it could come in handy to check what that version actually contained.
