### ISSUE TITLE
How to install the right previous app for the AppSource Validation

### ISSUE THREAD

**Issue by CarloAxians** [HodorNV/ALOps#350]
**Describe the bug**
We are using the AppSource validation example AppSourceValidationPipelineMultiStage.yml mentioned on https://github.com/HodorNV/ALOps/tree/master/Examples/AppSource

The .previous directory contains the previous app version and the Microsoft apps, so the build in VSCode also uses the correct app files.

**the used AppSource.json in VSCode**
```
{
    "mandatoryAffixes": ["AXI"],
    "supportedCountries": ["nl", "be"],
    "version": "5.0.20210225.791",
    "baselinePackageCachePath": "./.previous"
}
```

**the used yaml**
In the AppSourceValidationTemplateMultiStage.yml we have changed the part that is installing the previous version to:
```        - task: ALOpsAppPublish@1
          displayName: 'Publish previous version of my app - ${{ country }} ${{ version }}'
          inputs:
            usedocker: true
            artifact_path: 'base/.previous'
            nav_artifact_app_filter: '*_APP.app'
            skip_verification: ${{ parameters.skipverification }}
```

**the output**
This results in the following output:
```
Starting: Publish previous version of my app - nl Current
==============================================================================
Task         : ALOps App Publish
Description  : Publish AL Extension to Business Central
Version      : 1.440.2371
Author       : Hodor
Help         : Publish Business Central extension to service tier.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                                                                                              value
----                                                                                                              -----
usedocker                                                                                                          True
fixed_tag                                                                                                              
installpublishedapps                                                                                               True
installaltesttool                                                                                                 False
install_al_app_names                                                                             Tests-TestLibraries...
strictappnames                                                                                                    False
nav_serverinstance                                                                                                BC140
artifact_path                                                                                            base/.previous
nav_artifact_app_filter                                                                                       *_APP.app
skip_verification                                                                                                  True
forceinstall                                                                                                      False
forcesync                                                                                                         False
publish_scope                                                                                                    Global
tenant                                                                                                          default
batch_publish_folder                                                                                                   
publisherazureactivedirectorytenantid                                                                                  



*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: Axians Business Solutions (RepositoryPer5 License)

*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Install AL TestTool: False
*** Working folder: E:\Agent\_work\4\s
*** Artifact folder: E:\Agent\_work\4\a
*** Pipeline workspace: E:\Agent\_work\4
***
*** Copy Artifacts to Docker Container: a2af9e743fa029b7f1a73691a9913358c153b87aebec996e4eb1c8c5f7462103
*** Docker Artifacts Folder: c:\Run\DevOps\Artifacts
*** Resolve App file in [base/.previous]
##[error]Cannot find path 'E:\Agent\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.440.2371\base\.previous' because it does not exist.
```

**Expected behavior**
Only our previous app version should be installed.

**Comment by waldo1001** [comment]
To start with:
your artifact_path (base/.previous) seems wrong.  you see that this folder is totally wrong "E:\Agent\_work\_tasks\ALOpsAppPublish_c004e2d2-e842-40f0-9ed4-89fb9bdd2e33\1.440.2371\base\.previous".  It shouldn't try to find the previous there.  This is because the script is executed in that folder.. .

I see in the template that the "batch_publish_folder" is used.  So let's try that first to try to make it work.


that said .. 


Do know, there is now a way for you to run the default BcContainerHelper ALValidation.  From the documentation:

```yaml
 - task: ALOpsAppValidation@1
      displayName: 'ALOps Docker Create'
      inputs:
        license_path:                         # Path of the FLF license to import. Must be a fully qualified path or relative to $(System.DefaultWorkingDirectory) or a downloadable Url. $(license_path)
        countries: W1                         # Comma seperated array of countries to validate. $(countries)
        affixes:                              # Comma seperated array of affixes. $(affixes)
        artifact_path: $(System.ArtifactsDirectory)# Path for App Artifact. $(artifact_path)
        artifact_filter: *.app                # Filter used for locating App file relative to $(path_to_publish). $(artifact_filter)
        memory: 8G                            # Set maximum memory for Container. $(memory)
        validateversion:                      # Full or partial version number. If specified, apps will also be validated against this version. $(validateversion)
        validatecurrent: False                # Validate against current version of Business Central. $(validatecurrent)
        validatenextminor: False              # Validate against Next Minor version of Business Central. $(validatenextminor)
        validatenextmajor: False              # Validate against Next Major version of Business Central. $(validatenextmajor)
        sastoken:                             # SAS Token used to access Storage Account. $(sastoken)
        skipverification: False               #  $(skipverification)
        skipupgrade: False                    #  $(skipupgrade)
        skipappsourcecop: False               #  $(skipappsourcecop)
        skipconnectiontest: False             #  $(skipconnectiontest)
        includewarnings: False                # Include this switch if you want to include Warnings. $(includewarnings)
        failonerror: True                     # Include this switch if you want to fail on the first error instead of returning all errors to the caller. $(failonerror)
        containername: bcserver               # Only required when running multiple DevOps Agents on the same server. (Not recommended) $(containername)

```

To do "true" AppSource validation, I'd use that step.
