### ISSUE TITLE
Error in ALOps Agent Maintenance run

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#357]
**Describe the bug**
I just cleaned our build server, after that I started a pipeline where one step is "ALOps Agent Maintenance".
Now I get an the following error:
##[error]Cannot convert argument "0", with value: "2964489633736", for "GetStartComSlot" to type "System.Type": "Cannot convert the "2964489633736" value of type "System.IntPtr" to type "System.Type"."

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
name: Build ATT Docker Image $(Build.BuildId)

trigger:
    - none

schedules:
  - cron: "0 0 1 * *"
    displayName: Monthly Build Image Creation
    branches:
      include: 
        - master
    always: true

variables:
    - group: AzureBuildRessources
    - group: 'ALOps License'
    - group: DockerHandling

stages:
- stage: StartBuildVM
  condition: always()
  pool:
    name: 'Azure Pipelines'
    vmImage: 'vs2017-win2016'
    
  jobs:
  - job: StartVM
    steps:
    - checkout: none

    - task: AzureResourceGroupDeployment@2
      displayName: 'Start build Azure VM'
      inputs:
        azureSubscription: $(AzureServiceConnectionName)
        action: Start
        resourceGroupName: $(AzureResourceGroup)

- stage: BuildDockerCIImages
  condition: succeeded('StartBuildVM')
  pool: Default
  jobs:
  - job: CleanBuildMachine
    steps:
    - checkout: none
    - task: ALOpsAgentMaintenance@1
      inputs:
        removeoldtasks: true
        removeunusedcontainers: true
        removebcartifacts: true
        daysunused: '5'

.........
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
Starting: ALOpsAgentMaintenance
==============================================================================
Task         : ALOps Agent Maintenance
Description  : Cleanup and maintain DevOps a Agent for Business Central
Version      : 1.441.2425
Author       : Hodor
Help         : Cleanup and maintain DevOps a Agent for Business Central.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                  value
----                                  -----
removeoldtasks                         True
removeunusedcontainers                 True
removebcartifacts                      True
bcartifactscachefolder C:\bcartifacts.cache
daysunused                                5



*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: akquinet NEXT GmbH (RepositoryPer5 License)

*** Importing required PS-Functions
*** Importing required Task-Functions
##[error]Cannot convert argument "0", with value: "2964489633736", for "GetStartComSlot" to type "System.Type": "Cannot convert the "2964489633736" value of type "System.IntPtr" to type "System.Type"."
Finishing: ALOpsAgentMaintenance

```

**Expected behavior**
Skipping the step when nothing todo.
