### ISSUE TITLE
Documentation Enhancement - ALOpsAppTest@1

### ISSUE THREAD

**Issue by dNsl9r** [HodorNV/ALOps#359]
[Microsoft yesterday told me,](https://github.com/microsoft/AL/issues/6570#issuecomment-820298833) not to fill the TestSuite in the OnInstall Codeunit as I did before and as you do [your example](https://dev.azure.com/ALOpsWebinars/02_Dependencies/_git/1_JustOneAppAndATestApp?path=%2FTest%2FSrc%2FTestInstall.Codeunit.al)

I tried some ways to change the YAML but did not succeed until now.
```yaml
    - task: ALOpsAppTest@1
      displayName: 'Run TestSuite'
      inputs:
        usedocker: true
        import_action: "Skip"
        import_testtoolkit: false
        testfilter: '50000..50010'
        extensionid: '1234'
        testpage: '130455'
        testsuite: 'DEFAULT'
        failed_test_action: 'Ignore'
      continueOnError: true   
```

Want I want to achieve:
* Install our ATT App, where we do not fill the DEFAULT TestSuite "OnInstall" anymore because it does not work anymore.
* Load our defined codeunits (e.g. via no range or just all for this appid) into the testsuite
* Run the testsuite and publish the testresults

**Describe the solution you'd like**
Could you please enhance the documentation so I know how to use this step correct?

**Comment by waldo1001** [comment]
Yeah.
Documentation is not easy when you have an endless amount of combinations ;-).  That's why I like these issues on GitHub ;-).

This snippet runs successfully 2 testsuites on ExtensionId:
```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    extensionid: '1fb2e583-f2c3-4484-a8d4-387e3adce46d'
    resultfilename: 'TestResults_Bank.xml'
    failed_test_action: 'Ignore'
  continueOnError: true   

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults_Bank.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults_Bank.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    extensionid: '9bf23d52-8194-4857-8896-5e48b24493f6'
    resultfilename: 'TestResults_Job.xml'
    failed_test_action: 'Ignore'
  continueOnError: true   

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults_Job.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults_Job.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

```

**Comment by waldo1001** [comment]
Do know - you can still do it with an install-codeunit.  

```al
        //TestSuiteMgt.SelectTestMethodsByExtension(ALTestSuite, me.Id());
        TestSuiteMgt.SelectTestMethodsByRange(ALTestSuite, '81040..81189');
```

**Comment by dNsl9r** [comment]
> Do know - you can still do it with an install-codeunit.
> 
> ```al
>         //TestSuiteMgt.SelectTestMethodsByExtension(ALTestSuite, me.Id());
>         TestSuiteMgt.SelectTestMethodsByRange(ALTestSuite, '81040..81189');
> ```

Niklola wrote 

> The setup of test suite by using the OnInstall is an old approach. It has the problem that it can block the extension from being installed.

so, we won't do this anymore :-)

**Comment by waldo1001** [comment]
I know.  
Thing is, they broke it and now hide behind the *new* recommendation that it is "bad practice" to do so.  The reason why it can fail is they moved some kind of event where you don't have a PackageID OnInstall anymore (which the SelectTestMethodsByExtension relies on).  

The SelectTestMethodsByRange doesn't have this dependency, so it should work just fine.

I'll keep using it, because when installing an app, I want to run its business logic.  That's the sole reason to install an app.  for a test-app, the business logic is "running tests".  So they need to be there.

The recommendation to not use an install-codeunit is simply not the right approach for a user(developer)-friendly design.

Just my 0.02 cents

**Comment by dNsl9r** [comment]
> Just my 0.02 cents
absolutely agree. as I do not want to spend any more work on this and your solution with the YAML works - I'll just follow this way.

**Comment by waldo1001** [comment]
@dNsl9r ,

so you mean that running the tests by extensionid-parameter works now for you?  perfect!

**Comment by dNsl9r** [comment]
> @dNsl9r ,
> 
> so you mean that running the tests by extensionid-parameter works now for you? perfect!

```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    extensionid: '1fb2e583-f2c3-4484-a8d4-387e3adce46d'
    resultfilename: 'TestResults_Bank.xml'
    failed_test_action: 'Ignore'
  continueOnError: true   
```

this one worked perfect 👍
