### ISSUE TITLE
Ability to select a TestRunner when running tests in a pipeline

### ISSUE THREAD

**Issue by RichardSefton** [HodorNV/ALOps#365]
I don't know if this has been requested before, or if it is a planned release, or as stated in a previous post you're not looking to invest the time too much into testing as its a bit up in the air atm but is there a way to select a TestRunner to use on a test suite? The current issue we have is tests that are testing a function that uses the `StartSession()` function needs to be run with `TestIsolation=Disabled;`

**Comment by waldo1001** [comment]
May be ... I haven't tested this, so this is purely theoretical

we're highly dependent on what MS makes available .. and the way they are testing now is by running a page in the client (to be able to run UI testability).

Here's an example on how to run tests with ALOps:

```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    testsuite: 'DEFAULT'
    failed_test_action: 'Ignore'
  continueOnError: true 
```

You see we use the default page: 130455

Looking at that page, I see that there is a testrunnercodeunitid that you can set up on a suite.

So ..

With an install codeunit, you can create your own suite, import the tests, set the testrunner, and off you go?

Here's an example of a test-codeunit:

```al
codeunit 80990 "FNC Test Install"
{
    Subtype = Install;

    trigger OnInstallAppPerCompany()
    begin
        SetupTestSuite();
    end;

    procedure SetupTestSuite()
    var
        ALTestSuite: Record "AL Test Suite";
        TestSuiteMgt: Codeunit "Test Suite Mgt.";
        SuiteName: Code[10];
        Me: ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(Me);
        SuiteName := copystr(me.Name().ToUpper().Replace('-TEST', ''), 1, MaxStrLen(SuiteName));

        if ALTestSuite.Get(SuiteName) then
            ALTestSuite.DELETE(true);

        TestSuiteMgt.CreateTestSuite(SuiteName);
        Commit();
        ALTestSuite.Get(SuiteName);

        //setup runner here

        TestSuiteMgt.SelectTestMethodsByExtension(ALTestSuite, me.Id());
    end;
}


```
