### ISSUE TITLE
ALOps Sign App does not work

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#370]
**Describe the bug**
ALOps Sign App fails with access denied. Certificate download link & password are correct (double-checked).

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
# ...
variables:
  - name: 'job.SignApp.AppFilter'
    value: $[ coalesce(variables['SignApp.AppFilter'], '*.app') ]
  - name: 'job.SignApp.PfxPath'
    value: $[ coalesce(variables['SignApp.PfxPath'], '') ]
  - name: 'job.SignApp.TimeStampUri'
    value: $[ coalesce(variables['SignApp.TimeStampUri'], 'http://timestamp.comodoca.com/authenticode') ]
  - name: 'job.SignApp.PfxPassword'
    value: $[ coalesce(variables['SignApp.PfxPassword'],  '') ]
steps:

# ...
- task: ALOpsAppSign@1
  displayName: 'ALOps App Sign'
  inputs:
    usedocker:                true
    nav_artifact_app_filter:  '$(job.SignApp.AppFilter)'
    pfx_path:                 '$(job.SignApp.PfxPath)'
    timestamp_uri:            '$(job.SignApp.TimeStampUri)'
    pfx_password:             '$(job.SignApp.PfxPassword)'
  condition: and(succeeded(), ne(variables['job.SignApp.PfxPath'], ''), ne(variables['job.SignApp.PfxPassword'], ''))

- task: ALOpsAppSignVerify@1
  displayName: 'ALOps App Sign Verify'
  inputs:
    usedocker:                true
    nav_artifact_app_filter:  '$(job.SignApp.AppFilter)'
  condition: and(succeeded(), ne(variables['job.SignApp.PfxPath'], ''), ne(variables['job.SignApp.PfxPassword'], ''))
```

**the output**
![image](https://user-images.githubusercontent.com/15800069/119007579-a257ed80-b991-11eb-82ec-27c6958df553.png)

**Expected behavior**
😉 no error

**Additional context**
Is it possible, that signing the test-app cause the problem?
