### ISSUE TITLE
ALOpsAppValidation: Get countries from AppSourceCop.json

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#387]
**Is your feature request related to a problem? Please describe.**
When working with a generic template for multiple App for AppSource, the setting of countries for the ALOpsAppValidation needs to be a pipeline variable or passed though with the yaml file.

**Describe the solution you'd like**
The information for this setting is already in the source of the project available with the AppSourceCop.json.

**Describe alternatives you've considered**
I've created some PowerShell now to pass this variabele dynamically, but i think ALOps could create a better and more robust way of retreiving this info from the file.

```yaml
steps:
- task: PowerShell@2
  displayName: 'Get Supported Countries '
  condition: succeeded()
  inputs:
    targetType: 'inline'
    script: |
      $AppSourceCopFile = "$(System.SourcesDirectory)\App\AppSourceCop.json"
      Write-Host "##[command]Read $AppSourceCopFile"
      $obj = Get-Content -Raw -Path $AppSourceCopFile | ConvertFrom-Json
      $countries = $obj.supportedCountries -join ','
      Write-Host "##vso[task.setvariable variable=countries]$countries"
      Write-Host "##[command]Countries: $countries"
```
