### ISSUE TITLE
[Question] Use of ALOps to publish on prem extensions to remote servers

### ISSUE THREAD

**Issue by sboeve** [HodorNV/ALOps#39]
Let me first say that this is all very new to me.  We currently publish all of our apps on our client servers from VS Code.  We're looking for a way to be able to publish from DevOps.  We aren't using Docker or Containers and DevOps is accessed via the web.

Is this possible?  I've downloaded this extension to DevOps and modified the YML for the pipeline.  It's pointed to an Azure Pipeline pool for VS2017.  But, I'm not understanding how the web app accesses local files such as the compiler or any other files required .  I specified the compiler version.

Below is my yml and the error I'm getting based on what I've set up so far.  Thank you!!

![image](https://user-images.githubusercontent.com/31968749/66572420-ec82b700-eb3e-11e9-8aee-047cfd61bd74.png)

![image](https://user-images.githubusercontent.com/31968749/66572180-7aaa6d80-eb3e-11e9-9625-9c74fe8e40d0.png)

**Comment by PatrickGrabensteiner** [comment]
I would also need this. I want to publish to a customer Production Environment without installing an Agent on the System. Is there a possibilty to use the api for Publishing? Or can i use the SaaS Publishing for onPrem the api should be the same

**Comment by waldo1001** [comment]
It might, but we don't have a testcase.  Look at the documentation on: https://marketplace.visualstudio.com/items?itemName=Hodor.hodor-alops

You'll see you can set the api endpoint:
```yaml
- task: ALOpsSaaSPublishExtension@1
      displayName: 'ALOps SaaS Publish Extension'
      inputs:
        azure_api_endpoint: api.businesscentral.dynamics.com# Azure API Endpoint. $(azure_api_endpoint)
        azure_api_version: v2.0               # Azure API Endpoint version. $(azure_api_version)
        azure_tenant_id:                      # Azure Tenant Id. $(azure_tenant_id)
        azure_app_client_id:                  # Azure AD Application Client Id. $(azure_app_client_id)
        azure_app_client_secret:              # Azure AD Application Client Secret. $(azure_app_client_secret)
        bc_impersonate_user:                  # Business Central User to impersonate. $(bc_impersonate_user)
        bc_impersonate_password:              # Business Central User Password to impersonate. $(bc_impersonate_password)
        bc_environment: sandbox               # Business Central environment to publish extension on. $(bc_environment)
        bc_companyname:                       # Business Central Company. $(bc_companyname)
        artifact_path:                        # Path for App Artifact. $(artifact_path)
        app_artifact_filter: *.app            # Filter used for locating App file relative to $(path_to_publish). $(app_artifact_filter)
```

At this point, the step not intended to support that scenario - but I understand the usecase.  If you tried it - please give us feedback.  

In the meantime, we'll put it on the backlog.
