### ISSUE TITLE
Docker Task from Example cause authorization error

### ISSUE THREAD

**Issue by megel** [HodorNV/ALOps#4]
Docker Task from Snippet from [Example](https://github.com/HodorNV/ALOps/blob/master/Examples/1_DefaultBuild.yml) causes some errors

```yml
- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
  inputs:
    docker_login: 'Insider Docker Registry'
```

![image](https://user-images.githubusercontent.com/15800069/59503798-9f008100-8ea1-11e9-89c2-f7dd59e417c6.png)

Changed to:
```yml
- task: ALOpsDockerRemove@1
  condition: always()
  inputs:
    fixed_tag: 'W1'
```
works :)
