### ISSUE TITLE
ALOpsDockerCreate & myscripts  usage examples

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#402]
Hey Alops Gurus,
Could you please provide few examples how to use **myscripts** parameter for task ALOpsDockerCreate?
Struggling to find the right syntax for it. 

Best Regards, 
Gintautas

**Comment by waldo1001** [comment]
Basically the same as how BcContainerHelper would work.
it works with an array, and to split multiple paths into multiple items, you can split by a "New Line" or a "|"

You should be able to provide a path or url (depending on what containerhelper supports).

**Comment by gintuoklis** [comment]
Sorry, for reopening the closed issue, but I got related question.  Question is about passing parameters to scripts. Here's an example

Let's say this is my task
```
          - task: ALOpsDockerCreate@1
            displayName: 'ALOPS - Create Docker Image' 
            inputs:
              artifactversion: ${{ parameters.baseVersion }}
              artifactcountry: 'w1'
              artifacttype: OnPrem
              includetesttoolkit: true
              licensefile: $(Pipeline.Workspace)\license\fin.flf
              myscripts: $(Agent.BuildDirectory)\templates\AdditionalSetup.ps1
              dockerregistry: 'mydevops.azurecr.io'
              imageprefix: 'imv'
```

And here's my content of AdditionalSetup.ps1

```
param ($servername = 'BC')
Write-Host "--------------------"
Write-Host "| Creating AutoTest Company |"
Write-Host "--------------------"
New-NAVCompany $servername -CompanyName "AutoTest"   
```

Can i pass ServerName to the AdditionalSetup.ps1? 
I tried the simpliest way, but it did not work

`myscripts: $(Agent.BuildDirectory)\templates\AdditionalSetup.ps1 NAV`

Any ideas?
