### ISSUE TITLE
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

### ISSUE THREAD

**Issue by simcrest** [HodorNV/ALOps#417]
I get this error when I compile my test app.

Here is the output from the step:
```
*** Download System-Symbols for [1.0.0.0]
*** Downloading NAV Symbols for [System v1.0.0.0]
*** Downloading NAV Symbols from [https://03b205077164:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
Invoke-RestMethod -Method Get -Uri https://03b205077164:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=1.0.0.0&tenant=default
*** Content-Disposition: attachment; filename=Microsoft_System_18.0.27224.29197.app
*** Saving symbol file [Microsoft_System_18.0.27224.29197.app] to [c:\Run\DevOps\PackageCache]
*** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_System_18.0.27224.29197.app].
***
*** Download Application-Symbols for [18.0.0.0]
*** Downloading NAV Symbols for [Application v18.0.0.0]
*** Downloading NAV Symbols from [https://03b205077164:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=18.0.0.0&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
Invoke-RestMethod -Method Get -Uri https://03b205077164:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=18.0.0.0&tenant=default
*** Content-Disposition: attachment; filename=Microsoft_Application_18.3.27240.29362.app
*** Saving symbol file [Microsoft_Application_18.3.27240.29362.app] to [c:\Run\DevOps\PackageCache]
*** Read App Manifest: [c:\Run\DevOps\PackageCache\Microsoft_Application_18.3.27240.29362.app].
*** Propagated Dependency: Microsoft - System Application - 18.3.0.0
*** Propagated Dependency: Microsoft - Base Application - 18.3.0.0
***
*** Check for Depency Apps 7
*** Download Application-Symbols for [Auto Email v18.0.0.0]
*** Downloading NAV Symbols for [Auto Email v18.0.0.0]
*** Downloading NAV Symbols from [https://03b205077164:7049/BC/dev/packages?publisher=SimCrest&appName=Auto+Email&versionText=18.0.0.0&tenant=default]
*** Downloading NAV Symbols with BasicAuthentication [admin]
Invoke-RestMethod -Method Get -Uri https://03b205077164:7049/BC/dev/packages?publisher=SimCrest&appName=Auto+Email&versionText=18.0.0.0&tenant=default
##[error]Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Async Command Start: Add Build Tag
Build '56' has following tags now: BC.Platform.18.0.27224.29197, App.SimCrest Subscription.18.0.0.5, AL.Compiler.ALLanguage, myimage-sandbox-18.3.27240.29362-w1-10.0.14393.4583-ltsc2016, BC.Version.18.3.27240.29362, App.Auto Email.1.0.202134.56
Async Command End: Add Build Tag
Async Command Start: Update Build Number
Update build number to 1.0.202134.56 for build 56
Async Command End: Update Build Number
```

Here is the YAML file
```yaml
name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master

variables:
- group: 'Secrets'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds

pool: simcrest

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: Sandbox

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS - License Import'
  inputs:
    usedocker: true
    license_path: '$(bc.license)'  # more info: https://www.youtube.com/watch?v=iVLOerdCuwA&t=3078s

- task: DownloadFileshareArtifacts@1
  inputs:
    filesharePath: '\'
    artifactName: 'Files'
    itemPattern: '**/*.app'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish App' # to be able to use subscription
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 


- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Install AL TestTool' # install necessary dependent apps for testability
  inputs:
    usedocker: true
    installaltesttool: true
    install_al_app_names: |
      Tests-TestLibraries
      System Application Test
      System Application Test Library
      Any
      Library Assert
      Test Runner
      Permissions Mock

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject: 'app/app.json'                           # The App
    failed_on_warnings: false
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: Test-App'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject: 'test/app.json'                           # The Test-App
    failed_on_warnings: false   
    app_file_suffix: '_TEST'                                 # A trick to uniquely identify the Test-App (from the App)

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true   

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    testsuite: 'DEFAULT'
    failed_test_action: 'Ignore'
  continueOnError: true   

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```
