### ISSUE TITLE
ALOpsAppPublish/install_al_app_names - how to set parameter value correctly?

### ISSUE THREAD

**Issue by martonsagi** [HodorNV/ALOps#42]
Hi again,

I'm trying to make a BC15 test app work. I've updated the Build definition to install the new test libraries, however, I receive a warning and bunch of errors in response.

[Latest build](https://dev.azure.com/dynasist/ATDD.TestManager/_build/results?buildId=119)
[Build YML](https://github.com/dynasist/ATDD.TestManager/blob/master/azure-pipelines.yml)

Tests are in a separate app, so I have 2 Compile/Publish task pairs.

Test tool installation is set during the first App Publish task, so it should be installed when Test App compilation starts.

```
- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 
    installaltesttool: true    
    install_al_app_names: "Tests-TestLibraries
System Application Test
System Application Test Library
Any
Library Assert
Test Runner"
```

This is what I get during the first App Publish
```
WARNING: *** App [Tests-TestLibraries System Application Test System Application Test Library Any Library Assert Test 
Runner] not found.
*** Installing Applications:
*** AL-TestTool installation finished.
```

----

It looks as if `install_al_app_names` is defined incorrectly. I think it should be an array of string instead of a string. How can I pass multiple apps to be installed?

Thanks,
Marton

**Comment by waldo1001** [comment]
Like this:

```yaml
- task: ALOpsAppPublish@1
  displayName: 'ALOPS Install AL TestTool'
  inputs:
    usedocker: true
    installaltesttool: true
    skip_verification: true
    install_al_app_names: |
     Tests-TestLibraries
     System Application Test
     System Application Test Library
     Any
     Library Assert
     Test Runner
```
