### ISSUE TITLE
AppSourceCop not specified, skipping download previous

### ISSUE THREAD

**Issue by MortenRa** [HodorNV/ALOps#421]
**Describe the bug**
started to recieve this error after update today

AppSourceCop not specified, skipping download previous

what do I need to set in the yaml , not changes at my end.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsAppPublish@1
    displayName: 'Publish Previous App'
    enabled: true
    inputs:
      usedocker: true
      batch_publish_folder: 'app/.previous'
      nav_artifact_app_filter: 'app/.previous/*.app'
      skip_verification: true


  - task: ALOpsAppCompiler@1
    displayName: 'ALOps Compile Extension: App'
    inputs:
      usedocker: true
      targetproject: 'app/app.json'
      ${{ if eq(parameters.appversion,false) }}:
        nav_app_version: $(AppVersion)
      ${{ if eq(parameters.appversion,true) }}:
        nav_app_version: $(AppVersion2)
      failed_on_warnings: false
      app_file_suffix:  $(app_file_suffix)
      al_analyzer: AppSource
      publishxlif: true
      updatebuildnumber: True
```
