### ISSUE TITLE
ALOpsAppPublish@1 with batch_publish_folder and nav_artifact_app_filter

### ISSUE THREAD

**Issue by StijnBt** [HodorNV/ALOps#426]
Hello,

Am I making a wrong assumption the the nav_artifact_app_filter in combination with batch_publish_folder should behave as the "contents" paramter in the [Copy Files task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=azure-devops&tabs=yaml)?

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 

```yaml
 task: ALOpsAppPublish@1
  displayName: Publishing Multiple Apps
  inputs:
    nav_serverinstance: CUS_BC185
    batch_publish_folder: $(Agent.BuildDirectory)
    nav_artifact_app_filter: |
          **/*Customer App_*
          **/*_Customer App SYNC_*
```
The agent builddirectory contains 5 apps, but I would only like to batch publish the 2 apps that correspond to the nav_artifact_app_filter.
Now it just publishes them all without considering the nav_artifact_app_filter from the example above.
