### ISSUE TITLE
ALOps App Test run different Test Suites

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [HodorNV/ALOps#43]
ALOps App Test Always runs Default Test Suite, we need to run different suites in our Project.

Is this possible?

**Comment by waldo1001** [comment]
We are working on it ... the default functionality from Microsoft acts weird .. we are trying to find a solution.. .

We need it ourselves, so should be fixed pretty soon  ;-)

**Comment by waldo1001** [comment]
Hi @PatrickGrabensteiner, in the current version, you should be able to run a specific testsuite now for Wave2:

```yaml
- task: ALOpsAppTest@1
  displayName: 'ALOPS Run TestSuite: DEFAULT'
  inputs:
    usedocker: true
    show_available_tests: false
    import_testtoolkit: false
    testpage: '130455'
    testsuite: 'DEFAULT'
    installaltesttool: false
    failed_test_action: 'Error'
  continueOnError: false    
```
