### ISSUE TITLE
Unable to run Connection test on container based on https://bcartifacts.azureedge.net/sandbox/19.0.29894.30870/be. You can try to re-run with -skipConnectionTest.

### ISSUE THREAD

**Issue by VRABart** [HodorNV/ALOps#434]
On Validating the app the connection with the artifact cannot be made.
Unable to run Connection test on container based on https://bcartifacts.azureedge.net/sandbox/19.0.29894.30870/be. You can try to re-run with -skipConnectionTest.

Yaml:
```
name: $(Build.BuildId)

variables:
  - group: bc-app-config
  - group: bc-app-config-global
  - group: bc-insider
  - group: bc-vanroeybe-license

trigger:
  branches:
    include:
      - master

pool:
  name: $(build_pool)

resources:
  repositories:
    - repository: templates
      type: git
      name: Templates/BusinessCentralPipeline
      ref: master

stages:
  - template: build_test_and_validation.yml@templates
```
Output:
```
Removing container bcserver
Removing bcserver from container hosts file
Removing bcserver-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\bcserver

Removing container took 2 seconds

AL Validation finished in 180 seconds
 __      __   _ _     _       _   _               _____                _ _       
 \ \    / /  | (_)   | |     | | (_)             |  __ \              | | |      
  \ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__) |___ ___ _   _| | |_ ___ 
   \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  _  // _ \ __| | | | | __/ __|
    \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | \ \  __\__ \ |_| | | |_\__ \
     \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \_\___|___/\__,_|_|\__|___/

Unable to run Connection test on container based on https://bcartifacts.azureedge.net/sandbox/19.0.29894.30870/be. You can try to re-run with -skipConnectionTest.
Error is: Cannot open rolecenter
  _____                          ___      __   _ _     _       _   _               ______    _ _                
 |  __ \                   /\   | \ \    / /  | (_)   | |     | | (_)             |  ____|  (_) |               
 | |__) |   _ _ __ ______ /  \  | |\ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__ __ _ _| |_   _ _ __ ___ 
 |  _  / | | | '_ \______/ /\ \ | | \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  __/ _` | | | | | | '__/ _ \
 | | \ \ |_| | | | |    / ____ \| |  \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | | (_| | | | |_| | | |  __/
 |_|  \_\__,_|_| |_|   /_/    \_\_|   \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \__,_|_|_|\__,_|_|  \___|

##[error]Unable to run Connection test on container based on https://bcartifacts.azureedge.net/sandbox/19.0.29894.30870/be. You can try to re-run with -skipConnectionTest.
Error is: Cannot open rolecenter
*** Cleanup VSTS Environment: True

```

Expected behavior:                                     

Removing container bcserver
Removing bcserver from container hosts file
Removing bcserver-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\bcserver

Removing container took 2 seconds

AL Validation finished in 184 seconds
  _____                          ___      __   _ _     _       _   _                _____                            
 |  __ \                   /\   | \ \    / /  | (_)   | |     | | (_)              / ____|                           
 | |__) |   _ _ __ ______ /  \  | |\ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | (___  _   _  ___ ___ ___ ___ ___ 
 |  _  / | | | '_ \______/ /\ \ | | \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \   \___ \| | | |/ __/ __/ _ \ __/ __|
 | | \ \ |_| | | | |    / ____ \| |  \  / (_| | | | (_| | (_| | |_| | (_) | | | |  ____) | |_| | (__ (__  __\__ \__ \
 |_|  \_\__,_|_| |_|   /_/    \_\_|   \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_____/ \__,_|\___\___\___|___/___/
                                                                                                  
*** Cleanup VSTS Environment: True
Finishing: App Validation

Screenshots:
![image](https://user-images.githubusercontent.com/91888188/135850174-424c96d4-d6f9-4ad0-9cb1-5602ba99ab6e.png)
