### ISSUE TITLE
ALOpsAppCompiler: delayed 'Copy Working Folder to Docker Container' ?

### ISSUE THREAD

**Issue by Pharrious** [HodorNV/ALOps#437]
**Describe the bug**
Before ALOpsAppCompiler step, I switch branch using powershell.
Git checkout followed by git pull.
The compile step uses files from the previous commit in the branch.

**the used yaml**
```yaml
name: $(Build.BuildId)

variables:
- group: AzureKeyVault

# SBA
- name: 'BC_EnvironmentType'
  value: 'OnPrem'
- name: 'BC_Localization'
  value: 'dk'
- name: 'BC_Version'
  value: '18.3'
- name: 'BC_SignApp'
  value: '0'
- name: 'RecursiveDependencyFolder' # Set by DevOps
- name: 'RecursiveAppJsonPath' # Set by DevOps
- name: 'DependencySuffix' # Set by DevOps
- name: 'BranchName'
- name: 'DefaultBranchName'

# Variables with a default value which can be overruled by a DevOps variable.
- name: 'InstallPrevApp'
  value: '0'
- name: 'CodeAnalyzers'
  value: 'CodeCop,UICop'
- name: 'FailAppOnWarnings'
  value: "true"
- name: 'PublishDependencies'
  value: '0'
- name: 'SignApp'
  value: '1'
- name: AppFolder
  value: 'maj-adv\app'
- name: TestAppFolder
  value: 'test'
- name: 'TestSuite'
  value: ''
- name: 'RunTests'
  value: '0'
- name: 'PreserveVersionNo'
  value: '0'

# Variables set from DevOps Pipeline without a default value.
- name: 'EnvironmentType'
- name: 'Version'
- name: 'Localization'
- name: 'ArtifactVersion'
- name: 'SaaSToken'
- name: 'License'

# Folder and Path Variables.
- name: 'AppJsonPath'
- name: 'DependenciesFolder'
- name: 'PrevAppVersionFolder'
- name: 'XliffGenFolder'
- name: 'TestAppJsonPath'

# Misc Variables.
- name: 'CompilerArgumentForVersionNo'

parameters:
  - name: 'DependencyRepositories'
    type: object
    default:
    - maj-basic

pool:
  name: EV_OnPremise

resources:
  repositories:
    - repository: 'yamltemplates'
      type: 'git'
      name: 'Templates/Templates'
      ref:  'refs/heads/master'
    - repository: 'maj-basic'
      type: 'bitbucket'
      name: 'ElbekVejrup/maj-basic'
      endpoint: 'Bitbucket - evmaj'

steps:
- checkout: self
  clean: true
  
- task: PowerShell@2
  displayName: 'SBA: Get branchName'
  inputs:
    targetType: 'inline'
    script: |
       Write-Host "Build Reason: $($Env:BUILD_REASON)"
       $envBranch = $($Env:BUILD_SOURCEBRANCH)
       $defBranch = $($Env:BUILD_SOURCEBRANCH)
       if ($($Env:BUILD_REASON) -ne 'PullRequest')
       {
         Write-Host "Normal trigger"
         $envBranch = $envBranch.replace('refs/heads/', '')
         $defBranch = $envBranch
       } Else
       {
         Write-Host "PULL trigger"
         $defBranch = $($Env:SYSTEM_PULLREQUEST_TARGETBRANCH)
         $envBranch = $($Env:SYSTEM_PULLREQUEST_SOURCEBRANCH)
         $envBranch = $envBranch.replace('refs/heads/', '')
         $defBranch = $defBranch.replace('refs/heads/', '')
       }
       Write-Host "Working branch $envBranch"
       Write-Host "Default branch $defBranch"
       Write-Host "##vso[task.setvariable variable=BranchName]$envBranch"
       Write-Host "##vso[task.setvariable variable=DefaultBranchName]$defBranch"


#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# EV: Set Yaml Variables From DevOps Variables
- task: PowerShell@2
  displayName: 'EV: Set Yaml Variables From DevOps Variables'
  inputs:
    targetType: 'inline'
    script: |
      function ConvertPipelineVariableToString($InputVariable)
      {
          $StringVariable = Out-String -InputObject $InputVariable
          $StringVariable = $StringVariable.replace("`n","").replace("`r","")
          return $StringVariable
      }

      Write-Host "Converting DevOps Defined Variables to Strings..."
      
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_ENVIRONMENTTYPE}
      Write-Host "##vso[task.setvariable variable=EnvironmentType]$DevOpsVariable"

      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_VERSION}
      Write-Host "##vso[task.setvariable variable=Version]$DevOpsVariable"

      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_LOCALIZATION}
      Write-Host "##vso[task.setvariable variable=Localization]$DevOpsVariable"
      
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_ARTIFACTVERSION}
      Write-Host "##vso[task.setvariable variable=ArtifactVersion]$DevOpsVariable"
      
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_SAASTOKEN}
      Write-Host "##vso[task.setvariable variable=SaaSToken]$DevOpsVariable"

  
      Write-Host "Identifying BC License..."
      if (${env:BC_LICENSE} -eq $null)
      {
          $LicenseVersion = ConvertPipelineVariableToString ${env:BC_VERSION}
          if ($LicenseVersion.Length -ge 2)
          {
            $LicenseVersion = $LicenseVersion.Substring(0, 2)
            $LicenseString = "<hidden>"
          }
          Write-Host "##vso[task.setvariable variable=License]$LicenseString"
      }    


      Write-Host "Overruling variables with default value with DevOps specified value..."
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_INSTALLPREVAPP}
      if ($DevOpsVariable -ne "")
      {
          Write-Host "##vso[task.setvariable variable=InstallPrevApp]$DevOpsVariable"
      }

      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_CODEANALYZERS}
      if ($DevOpsVariable -ne "")
      {
          Write-Host "##vso[task.setvariable variable=CodeAnalyzers]$DevOpsVariable"
      }
      
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_ALLOWAPPWARNINGS}
      if ($DevOpsVariable -eq "1")
      {
          Write-Host "##vso[task.setvariable variable=FailAppOnWarnings]false"
      }
      
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_PUBLISHDEPENDENCIES}
      if ($DevOpsVariable -ne "")
      {
          Write-Host "##vso[task.setvariable variable=PublishDependencies]$DevOpsVariable"
      }

      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_SIGNAPP}
      if ($DevOpsVariable -ne "")
      {
          Write-Host "##vso[task.setvariable variable=SignApp]$DevOpsVariable"
      }

      Write-Host "Identifying if Version No should be preserved..."
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_PRESERVEVERSIONNO}
      if ($DevOpsVariable -eq "1")
      {
          Write-Host "##vso[task.setvariable variable=PreserveVersionNo]$DevOpsVariable"
      }
      else
      {
          $DevOpsVariable = ConvertPipelineVariableToString ${env:PreserveVersionNo}
      }
      
      if ($DevOpsVariable -eq "1")
      {
          $CompilerArgumentForVersionNo = '?.?.?.?'
      }
      else
      {
          $CompilerArgumentForVersionNo = '?.?.?.*'
      }
      Write-Host "##vso[task.setvariable variable=CompilerArgumentForVersionNo]$CompilerArgumentForVersionNo"

      Write-Host "Identifying App Folder..."
      
      $AppFolder = ConvertPipelineVariableToString ${env:BC_APPFOLDER}
      if ($AppFolder -eq "")
      {
          $AppFolder = ConvertPipelineVariableToString ${env:APPFOLDER}
      }
      Write-Host "##vso[task.setvariable variable=AppFolder]$AppFolder"

      Write-Host "Assigning folder and path variable values..."

      $VariablePath = "$AppFolder/app.json"
      Write-Host "##vso[task.setvariable variable=AppJsonPath]$VariablePath"

      $AppFolder = $AppFolder.Replace("/","\")

      $VariablePath = ".\$AppFolder\Dependencies"
      Write-Host "##vso[task.setvariable variable=DependenciesFolder]$VariablePath"

      $VariablePath = ".\$AppFolder\PrevAppVersion"
      Write-Host "##vso[task.setvariable variable=PrevAppVersionFolder]$VariablePath"

      $VariablePath = "C:\Run\DevOps\$AppFolder"
      Write-Host "##vso[task.setvariable variable=XliffGenFolder]$VariablePath"

      Write-Host "Identifying Test App Folder..."
      $AppFolder = ConvertPipelineVariableToString  ${env:BC_TESTAPPFOLDER}
      if ($AppFolder -eq "")
      {
          $AppFolder = ConvertPipelineVariableToString ${env:TESTAPPFOLDER}
      }
      Write-Host "##vso[task.setvariable variable=TestAppFolder]$AppFolder"

      $VariablePath = ""
      if ($AppFolder -ne "")
      {
        $VariablePath = "$AppFolder/app.json"
      }
      Write-Host "##vso[task.setvariable variable=TestAppJsonPath]$VariablePath"

      Write-Host "Setting TestSuite..."
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_TESTSUITE}
      if ($DevOpsVariable -ne "")
      {
          Write-Host "##vso[task.setvariable variable=TestSuite]$DevOpsVariable"
      }
      
      $DevOpsVariable = ConvertPipelineVariableToString ${env:BC_RUNTESTS}
      if ($DevOpsVariable -ne "")
      {
          Write-Host "##vso[task.setvariable variable=RunTests]$DevOpsVariable"
      }
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# EV: Print Yaml Variable Values
- task: PowerShell@2
  displayName: 'EV: Print Yaml Variable Values'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Yaml Variable Values:"
      Write-Host " - EnvironmentType: ${env:ENVIRONMENTTYPE}"
      Write-Host " - Version: ${env:VERSION}"
      Write-Host " - Localization: ${env:LOCALIZATION}"
      Write-Host " - ArtifactVersion: ${env:ARTIFACTVERSION}"
      Write-Host " - SaaSToken: ${env:SAASTOKEN}"
      Write-Host " - DevOps Defined License: ${env:BC_LICENSE}"
      Write-Host " - Auto Selected License: ${env:LICENSE}"
      Write-Host " - InstallPrevApp: ${env:INSTALLPREVAPP}"
      Write-Host " - CodeAnalyzers: ${env:CODEANALYZERS}"
      Write-Host " - FailAppOnWarnings: ${env:FAILAPPONWARNINGS}"
      Write-Host " - PublishDependencies: ${env:PUBLISHDEPENDENCIES}"
      Write-Host " - SignApp: ${env:SignApp}"
      Write-Host " - PreserveVersionNo: ${env:PreserveVersionNo}"
      Write-Host " -- CompilerArgumentForVersionNo: ${env:CompilerArgumentForVersionNo}"
      Write-Host " - AppFolder: ${env:AppFolder}"
      Write-Host " -- AppJsonPath: ${env:APPJSONPATH}"
      Write-Host " -- DependenciesFolder: ${env:DEPENDENCIESFOLDER}"
      Write-Host " -- PrevAppVersionFolder: ${env:PREVAPPVERSIONFOLDER}"
      Write-Host " -- XliffGenFolder: ${env:XLIFFGENFOLDER}"
      Write-Host " - TestAppFolder: ${env:TestAppFolder}"
      Write-Host " -- TestAppJsonPath: ${env:TESTAPPJSONPATH}"
      Write-Host " - TestSuite: ${env:TESTSUITE}"
      Write-Host " - RunTests: ${env:RUNTESTS}"
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Copy EVBusinessCentralDevelopmentHelper to Build Agent
- template: 'OnPrem-Builds/CopyEVBCDevHelperToBuildAgent.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerCreate@1
  timeoutInMinutes: 12
  inputs:
    artifactversion: $(Version)
    artifactcountry: $(Localization)
    artifacttype: $(EnvironmentType)
    versionselect: $(ArtifactVersion)
    sastoken: $(SaaSToken)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>><

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerStart@1
  inputs:
    docker_pull: false
    accept_image_eula: true
    accept_image_outdated: true
    docker_parameters: '--isolation=hyperv'
    memory_gb: 16  
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsDockerWait@1
  timeoutInMinutes: 6
  inputs:
    search_string: 'Ready for connections!'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsLicenseImport@1
  displayName: 'EV: Import DevOps Defined License'
  condition: and(succeeded(), ne(variables['BC_License'], ''))
  inputs:
    usedocker: true
    license_path: $(BC_License)

- task: ALOpsLicenseImport@1
  displayName: 'EV: Import Auto Selected License'
  condition: and(succeeded(), eq(variables['BC_License'], ''), ne(variables['License'], ''))
  inputs:
    usedocker: true
    license_path: $(License)
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
- task: ALOpsDockerExec@1
  displayName: 'EV: Show Businees Central License Information'
  inputs:
    inline_script: |
      Get-NavServerInstance | Export-NavServerLicenseInformation
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- ${{each p in parameters.DependencyRepositories}}:
  - checkout: ${{ p }}
    clean: true
    displayName: "SBA ${{ p }} Checkout"
    persistCredentials: true
  - task: PowerShell@2
    displayName: "SBA ${{ p }} Folder structure"
    inputs:
      targetType: 'inline'
      script: |
        function GetAppFolder($repoPath)
        {
          Write-Host " "
          Write-Host "Files >>"
          Get-ChildItem -Path $(Join-Path $repoPath '*.*') -Recurse | Write-Host
          Write-Host "Files <<"
          Write-Host " "          

          # App folder is expected to be either './app' or './BC<Version>'/app
          $appFolder = Join-path $repoPath "app"
          if (!(test-path $appFolder))
          {
            $appFolder = [System.IO.Path]::Combine($repoPath, "BC${env:Version}", "$app")
          }
          write-host "AppFolder $appFolder, exists $(test-path $appFolder)"

          Write-Host " "
          Write-Host "App.Json"
          Get-Content -path "C:\Agent\_work\225\s\maj-basic\app\app.json" | Write-Host  # debugging
          Write-Host " "
          return $appFolder
        }
        function SwitchBranch($repoPath)
        {
          $branch = ${env:BranchName}
          $defbranch = ${env:DefaultBranchName}
          Push-Location $pRepoPath

          git fetch

          if (git branch --list $branch)
          {
            Write-Host "Found local: $branch"
            git checkout $branch
          }
          elseif(git ls-remote --heads origin --list $branch)
          {
            Write-Host "Found remote: $branch"
            git checkout -b $branch "origin/$branch"
          } else 
          { 
            git checkout '$defbranch'
            Write-Host "Using default: $defbranch"
          }
          git pull
          Pop-Location
        }

        $repo="${{ p }}"
        $pRepoPath = Join-Path $(Get-Location) $repo
        SwitchBranch $pRepoPath

        $appFolder = GetAppFolder $repo
        $dependencyFolder = "$appFolder\Dependencies"
        $appJSONFolder = "$appFolder\app.json"
                        
        Write-Host "##vso[task.setvariable variable=RecursiveDependencyFolder]$dependencyFolder"
        Write-Host "##vso[task.setvariable variable=RecursiveAppJsonPath]$appJSONFolder"
        Write-Host "##vso[task.setvariable variable=DependencySuffix]$repo"        
        Write-Host "Dependency variables"
        Write-Host "- RecursiveDependencyFolder - $dependencyFolder"
        Write-Host "- RecursiveAppJsonPath - $appJSONFolder"
        Write-Host "- DependencySuffix - $repo"

  - task: ALOpsAppPublish@1
    displayName: 'SBA ${{ p }} Install apps'
    inputs:
      usedocker: true
      nav_artifact_app_filter: '*.app'
      batch_publish_folder: $(RecursiveDependencyFolder)

  - task: ALOpsAppCompiler@1
    displayName: 'SBA ${{ p }} Compile'
    inputs:
      usedocker: true
      targetproject: $(RecursiveAppJsonPath)
      nav_app_version: $(CompilerArgumentForVersionNo)
      al_analyzer: $(CodeAnalyzers)
      app_file_suffix: '*_$(DependencySuffix)'
      failed_on_warnings: $(FailAppOnWarnings)

  - task: ALOpsAppPublish@1
    displayName: 'SBA ${{ p }} Publish'
    inputs:
      usedocker: true
      artifact_path: '$(ALOPS_COMPILE_ARTIFACT)'
      skip_verification: true 

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 
# EV: Install EVBusinessCentralDevelopmentHelper
- template: 'OnPrem-Builds/InstallEVBCDevHelperInDocker.yml@yamltemplates'
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile App'
  inputs:
    usedocker: true
    targetproject: $(AppJsonPath)
    nav_app_version: $(CompilerArgumentForVersionNo)
    al_analyzer: $(CodeAnalyzers)
    app_file_suffix: '_APP'
    failed_on_warnings: $(FailAppOnWarnings)


#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppSign@1
  displayName: 'ALOps App Sign'
  condition: and(succeeded(), eq(variables['SignApp'], '1'))
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_APP.app'
    pfx_path: $(CodeSignPfx)
    timestamp_uri: 'http://timestamp.comodoca.com/authenticode'
    pfx_password: $(CodeSignPfxPswd)
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_APP.app'   
    skip_verification: true 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
- task: ALOpsDockerRemove@1
  displayName: 'ALOps Remove Docker Container'
  enabled: true
  condition: always()
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

**the output**
```
The 'Folder Structure' step, showing that NewBrief.txt has been renamed
Found local: New-brief
Previous HEAD position was 57a1000 Settings
Switched to branch 'New-brief'
Your branch is behind 'origin/New-brief' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating aa158b7..9acb002
Fast-forward
 app/{NewBrief.txt => NewBrief.md} | 0
 app/app.json                      | 2 +-
 2 files changed, 1 insertion(+), 1 deletion(-)
 rename app/{NewBrief.txt => NewBrief.md} (100%)
 
Files >>
C:\Agent\_work\225\s\maj-basic\app\.vscode
C:\Agent\_work\225\s\maj-basic\app\.vscode\settings.json
C:\Agent\_work\225\s\maj-basic\app\Dependencies\.gitignore
C:\Agent\_work\225\s\maj-basic\app\Dependencies\Elbek & Vejrup AS_MAJ Third Party_1.0.0.0.app
C:\Agent\_work\225\s\maj-basic\app\Images\.gitkeep
C:\Agent\_work\225\s\maj-basic\app\Images\EV_Logo.png
C:\Agent\_work\225\s\maj-basic\app\Source\BasicList.PageExt.al
C:\Agent\_work\225\s\maj-basic\app\Translations\.gitkeep
C:\Agent\_work\225\s\maj-basic\app\app.json
C:\Agent\_work\225\s\maj-basic\app\AppSourceCop.json
C:\Agent\_work\225\s\maj-basic\app\custom.ruleset.json
C:\Agent\_work\225\s\maj-basic\app\NewBrief.md
C:\Agent\_work\225\s\maj-basic\.gitattributes
C:\Agent\_work\225\s\maj-basic\.gitignore
C:\Agent\_work\225\s\maj-basic\azure-pipelines.yml
C:\Agent\_work\225\s\maj-basic\MAJ-Basic.code-workspace
Files <<


Compile step
It copies the files to docker container
*** Using AL Compiler [vALLanguage] located [C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe]
*** Working folder: C:\Agent\_work\225\s
*** Copy Working folder to Docker Container: 7751347ae0da75b69eb27433ee422ab1cae2adb355d3bb93486b25c949322da2
*** Docker Working Folder: c:\Run\DevOps\
*** Copy from [C:\Agent\_work\225\s] to [c:\Run\DevOps\]
*** Source File setup completed
*** Target Project: \maj-basic\app\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Multiple projects found:
   - C:\Run\DevOps\maj-adv\app
   - C:\Run\DevOps\maj-basic\app
*** Retrieving App-Info [\maj-basic\app\app.json]
... lots of symbol downloading

_It has the old NewBrief.txt file :(
Compilation started for project 'MAJ Basic' containing '1' files at '20:8:34.572'._
c:\Run\DevOps\maj-basic\app\NewBrief.txt(1,1): warning AL1025: The file at location 'c:\Run\DevOps\maj-basic\app\NewBrief.txt' does not match any definition.
Compilation ended at '20:8:43.525'.
*** AL Compiler raw logs: End
*** Start processing compile results.
##[warning]c:\Run\DevOps\maj-basic\app\NewBrief.txt(1,1): warning AL1025: The file at location 'c:\Run\DevOps\maj-basic\app\NewBrief.txt' does not match any definition.
```

**Expected behavior**
The compile step should use the same files as downloaded by git checkout and pull

**Additional context**
The script tries to download and compile dependencies instead of having to keep an updated dependency folder.
The log is from 'MAJ-ADV' (advanced) pipeline being triggered, downloading and compiling the dependency 'MAJ-Basic'.
A task for MAJ-ADV might have to add changes to MAJ-Basic as well, requiring an updated dependency. 
I don't know in which order the other pipelines are completing. 
This is just a test setup, to test/develop the yaml.

Other suggestions are welcome! :)
