### ISSUE TITLE
Confusion regarding targetFolder & ALOpsAppCompiler@1 task

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#449]
Hey ALOps gurus, 

Could you please help me out with folder paths for ALOpsAppCompiler@1 task

I have multiple yaml files (templates) that makes my build pipeline. Thereofore, i will post only important snippets.

I have multiple repos that i define as resources

```
resources:
  repositories:
  - repository: scripts
    type: git
    name: AL_scripts
    ref: test-ms-agent-build
  - repository: dependencies
    type: git
    name: MVBC-dependencies
    ref: test-new-build
```
I checkout these repos, and self (the one with AL code) by using this code:

```
steps:
- checkout: self
  clean: true 
  path: code
- checkout: scripts
  path: scripts
- checkout: dependencies
  path: dependencies

```

When you checkout multiple repos and specify path param in checkout it checkouts folder under (Agent.BuildDirectory) path. It does not use \s\ path. (see ms [documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops#checkout-path))

Then I try to compile my app. 

```
- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: False    
    publish_artifact: False
    targetproject: $(Agent.BuildDirectory)\code\app.json
    setup_working_folder: true

```

But compilation fails with error:
**`##[error]error AL1001: Source file 'c:\Run\DevOps\C:\code\app.json' could not be found`**

Here's a screenshot with my comments

![image](https://user-images.githubusercontent.com/16342128/140330274-43135970-46c4-4433-95ed-dae96dafcb32.png)

Full log

```
*** Working Direcotry: [c:\Run\DevOps\]
*** Target Project: [C:\a\4\code\app.json]
*** Project Directory: [c:\Run\DevOps\C:\a\4\code]
*** VSCode Settings: [c:\Run\DevOps\C:\a\4\code\.vscode\settings.json]
*** No VSCode-Settings json found.
*** No AL-RuleSet json found.
***
*** Resolve Docker Credentials
*** Setup BC Username/Password from Container info
*** Download Symbols
*** Working Dir: c:\Run\DevOps\
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\180\service]
*** PackageCache path created [c:\Run\DevOps\PackageCache]
***
*** Check for Depency Apps 0
*** Starting AL Compiler...
*** App.Name         = 
*** App.Publisher    = 
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
*** Checking for Assemblies in App
*** Add Windows Assembly Path [C:\Windows\assembly]
*** Detect ALC.EXE Features.
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /?
  * PARALLEL
  * MAXDEGREEOFPARALLELISM
  * ASSEMBLYPROBINGPATHS
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\C:\a\4\code" /out:"c:\Run\DevOps\__.app" /fullpaths /parallel+ /maxDegreeOfParallelism:2 /assemblyprobingpaths:"C:\Windows\assembly","C:\Windows\Microsoft.NET\assembly","C:\program files\microsoft dynamics nav\180\service"
*** AL Compiler Exit Code: 1
*** Full Compile Log:
Microsoft (R) AL Compiler version 7.4.7.43206 Copyright (C) Microsoft Corporation. All rights reserved  error AL1018: Directory 'c:\Run\DevOps\C:\a\4\code' could not be found error AL1001: Source file 'c:\Run\DevOps\C:\a\4\code\app.json' could not be found

*** AL Compiler raw logs: Start
Microsoft (R) AL Compiler version 7.4.7.43206
Copyright (C) Microsoft Corporation. All rights reserved
error AL1018: Directory 'c:\Run\DevOps\C:\a\4\code' could not be found
error AL1001: Source file 'c:\Run\DevOps\C:\a\4\code\app.json' could not be found
*** AL Compiler raw logs: End
*** Start processing compile results.
##[error]error AL1001: Source file 'c:\Run\DevOps\C:\a\4\code\app.json' could not be found
*** Store compile log to [c:\Run\DevOps\compilelog.txt]
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
##[error]Cannot find path 'c:\Run\DevOps\__.app' because it does not exist.
Async Command Start: Add Build Tag
Build '68817' has following tags now: AL.Compiler.ALLanguage, BC.Platform.18.0.28593.29123, BC.Version.18.4.28601.29139, App.LS Central.18.3.1.0, App.LS Central System App.18.3.0.0, App.LS Central Autotests.18.3.0.0, ***.azurecr.io/imv-onprem-18.4.28601.29139-w1-10.0.17763.2237-ltsc2019
Async Command End: Add Build Tag
Finishing: Compile Extension
```

**Comment by gintuoklis** [comment]
Managed to go around this. had to change checkout paths by adding s/...

```
- checkout: self
  clean: true 
  path: s/code
- checkout: scripts
  path: s/scripts
- checkout: dependencies
  path: s/dependencies
- powershell: |
```

then adjusted targetproject to point to relative path **code\app.json**

```
- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: False    
    publish_artifact: False
    targetproject: code\app.json
    setup_working_folder: true

```
