### ISSUE TITLE
Disabling Analysers and Rulesets does not seem to work

### ISSUE THREAD

**Issue by petertijsma** [HodorNV/ALOps#452]
When using this Compiler command:

```
- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: App'
  inputs:
    usedocker: true
    targetproject: 'CurrentApp/App/app.json'
    nav_app_version: '1.0.[yyyyWW].*'
    app_file_suffix: '_APP'
    al_analyzer: none
    ruleset: none

```
I would expect the compiler to disregard any CodeCops or Rulesets setup in the settings.json, but apparently that's not the case:

![image](https://user-images.githubusercontent.com/86952584/141798536-6912fd60-e50c-4586-ada1-6eae806e5c37.png)

![image](https://user-images.githubusercontent.com/86952584/141798855-965d6560-f533-45a3-9760-8601ce5300e4.png)
