### ISSUE TITLE
Cleanup build server

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#460]
When I log in to our build server Docker ps shows me the following:

![image](https://user-images.githubusercontent.com/25202313/144432201-39e8cb3d-bc82-4a67-a1c5-4e716948f655.png)

It looks like new images are downloaded everytime the base image (?) of business central is updated. Is this because the build server itself is updated on regular basis? Is it possible with a ALOPS Cleanup task to remove unneeded/unused images? (in this case all images based on .2237)?

**Comment by waldo1001** [comment]
Not sure what I'm looking at here .. I'd say it depends on which pipelines run on this buildserver, and how you configured the DockerCreate.. 🤔

**Comment by peterz84** [comment]
These are the docker images created for several pipelines. They remain on the build server, which is great, because you dont want to download them every time a pipeline is triggered. But I'm guessing with every update of the host (build server) the OS gets a new (sub)version and when a pipeline is then triggered, a new image is downloaded.

I can safely delete the lower 4 images, because they are not in use anymore.

The docker creates in the several pipelines/projects are quiet standard:

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: OnPrem
    artifactversion: 18.0

**Comment by waldo1001** [comment]
First of all, there is a maintenance task you can use:
```
      - task: ALOpsAgentMaintenance@1
        displayName: 'ALOps Agent Maintenance'
      inputs:
        removeoldtasks: False                 # Remove old ALOps tasks. $(removeoldtasks)
        removeunusedcontainers: False         # Force docker container pruning. $(removeunusedcontainers)
        pruneimagesdayscreated: 0             # Force docker image pruning based on creation date (x days). $(pruneimagesdayscreated)
        removebcartifacts: False              # Remove BC Artifacts. $(removebcartifacts)
        bcartifactscachefolder: C:\bcartifacts.cache# Set non-default BC Artifact Cache folder. $(bcartifactscachefolder)
        daysunused: 30                        # Define date-range for cleanup BC-Artifacts. $(daysunused)

```

Second,

It probably did create new images, simply because you updated windows, and there was a better generic image that matches that update.  Since the images have the generic image name included in the name, it's building new images for the different versions.  you can manipulate the image name, but I wouldn't do that.. since it's best to run the images on the best generic images.

It seems everything works as expected, just include the maintenance task above.
