### ISSUE TITLE
Forcesync in batch publish? Publishing a modified Base app.

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#461]
The previous issue was closed, so opening a new one. (I cannot reopen an issue right?)
Question:
Is the forcesync already added to the batch publish? I'm having problems with publishing a modified Base app.

First I'm unpublishing the standard Base app:

- task: ALOpsDockerExec@1
  displayName: 'ALOPS - Unpublish MS Base'
  inputs:
    scriptsource: 'Workfolder'
    script_location: '/devops/unpublishbase.ps1'

afterwards I'm publishing the modified base app, which is in the .dependancies folder:

- task: ALOpsAppPublish@1
  displayName: 'ALOps Dependant extensions'
  inputs:
    usedocker: true
    skip_verification: true
    forcesync: true
    batch_publish_folder: '/.dependencies'

The error message is:

```
 * App File = [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_Base Application_18.0.23013.23795.app]

 * App.ID        = 437dbf0e-84ff-417a-965d-ed2bb9650972
 * App.Name      = Base Application
 * App.Publisher = Microsoft
 * App.Version   = 18.0.23013.23795
 => Publishing App 'Base Application v18.0.23013.23795'
*** Get Tenants
*** Sync Tenant default
*** App Already installed, doing upgrade default
*** Install App [Base Application] on tenant [default]
The extension 'Base Application by Microsoft 18.0.23013.23795' is synchronized with the correct version. However, the 
provided extension has a different set of tables and table extensions than the synchronized extension.
At line:146 char:17
+ ...             $Result = Invoke-Command -Session $DockerSession -ScriptB ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Ins 
   tallNavApp
```

The error is there because the standard base app is still synchronized with SQL. 
When I publish the modified base app manually on a docker container and use the command :
Sync-NAVApp -ServerInstance $ServerInstance -Name "Base Application" -Version "18.0.23013.23795" -Mode ForceSync -Force
it works fine.

_Originally posted by @peterz84 in https://github.com/HodorNV/ALOps/issues/178#issuecomment-984938288_

**Comment by waldo1001** [comment]
It should .. 
Can we have the full log?

**Comment by peterz84** [comment]
Full log of the publish step?:

2021-12-02T16:05:55.9636911Z ##[section]Starting: ALOps Dependant extensions
2021-12-02T16:05:55.9794927Z ==============================================================================
2021-12-02T16:05:55.9795300Z Task         : ALOps App Publish
2021-12-02T16:05:55.9795594Z Description  : Publish AL Extension to Business Central
2021-12-02T16:05:55.9795882Z Version      : 1.446.2712
2021-12-02T16:05:55.9796117Z Author       : Hodor
2021-12-02T16:05:55.9796415Z Help         : Publish Business Central extension to service tier.
2021-12-02T16:05:55.9796806Z ==============================================================================
2021-12-02T16:05:57.8645905Z *** Validate configuration
2021-12-02T16:05:58.3054977Z *** Task Inputs:
2021-12-02T16:05:58.3055521Z 
2021-12-02T16:05:58.3056972Z name                                                                                                              value
2021-12-02T16:05:58.3057677Z ----                                                                                                              -----
2021-12-02T16:05:58.3059109Z usedocker                                                                                                          True
2021-12-02T16:05:58.3059833Z fixed_tag                                                                                                              
2021-12-02T16:05:58.3061192Z installpublishedapps                                                                                               True
2021-12-02T16:05:58.3062118Z installaltesttool                                                                                                 False
2021-12-02T16:05:58.3063109Z install_al_app_names                                                                             Tests-TestLibraries...
2021-12-02T16:05:58.3064176Z strictappnames                                                                                                    False
2021-12-02T16:05:58.3065308Z nav_serverinstance                                                                                                BC140
2021-12-02T16:05:58.3066390Z artifact_path                                                                                                          
2021-12-02T16:05:58.3067118Z nav_artifact_app_filter                                                                                           *.app
2021-12-02T16:05:58.3068668Z skip_verification                                                                                                  True
2021-12-02T16:05:58.3069773Z forceinstall                                                                                                      False
2021-12-02T16:05:58.3070678Z forcesync                                                                                                          True
2021-12-02T16:05:58.3071637Z publish_scope                                                                                                    Global
2021-12-02T16:05:58.3072799Z tenant                                                                                                          default
2021-12-02T16:05:58.3074188Z batch_publish_folder                                                                                     /.dependencies
2021-12-02T16:05:58.3075601Z publisherazureactivedirectorytenantid                                                                                  
2021-12-02T16:05:58.3076000Z 
2021-12-02T16:05:58.3094924Z 
2021-12-02T16:05:58.3102201Z 
2021-12-02T16:05:58.3310825Z *** For documentation, please visit   : https://www.alops.be/documentation
2021-12-02T16:05:58.3313706Z 
2021-12-02T16:05:58.6055500Z *** ALOps License:
2021-12-02T16:05:58.6079660Z   * Licensed To: Broad Horizon Abecon (Per Run License)
2021-12-02T16:05:58.6082322Z 
2021-12-02T16:05:58.6179898Z *** Importing required PS-Functions
2021-12-02T16:05:58.9900351Z *** Initiate Docker Session
2021-12-02T16:05:59.2315477Z *** Set Docker Container ErrorActionPreference = Stop
2021-12-02T16:05:59.4886050Z *** Start Batch App-Publish.
2021-12-02T16:05:59.5584327Z *** Copy Artifacts: [C:\agent\_work\4\s\.dependencies] to [c:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2]
2021-12-02T16:06:17.8564930Z *** Import NAV/BC Management DLL's
2021-12-02T16:06:17.8591933Z *** Loading assemblies for ServiceTier [BC].
2021-12-02T16:06:18.0431489Z *** Loading assemblies from: [C:\program files\microsoft dynamics nav\180\service]
2021-12-02T16:06:18.0535613Z *** Selected module: [C:\program files\microsoft dynamics nav\180\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
2021-12-02T16:06:18.0549786Z *** Loading module: [C:\program files\microsoft dynamics nav\180\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
2021-12-02T16:06:18.0787843Z *** Selected module: [C:\program files\microsoft dynamics nav\180\service\Microsoft.Dynamics.Nav.Management.dll]
2021-12-02T16:06:18.0796313Z *** Loading module: [C:\program files\microsoft dynamics nav\180\service\Microsoft.Dynamics.Nav.Management.dll]
2021-12-02T16:06:18.4727446Z *** Get Available Applications from [c:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2].
2021-12-02T16:06:19.9086380Z *** Get [*.app] files recursive from [c:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2]
2021-12-02T16:06:19.9086867Z *** Found [5] files.
2021-12-02T16:06:19.9087408Z *** Extract App detail from [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\knk Business Software AG_knkPublishing_3.1.0.0_runtime.app]
2021-12-02T16:06:19.9088175Z *** Extract App detail from [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_Application_18.0.23013.23795.app]
2021-12-02T16:06:19.9088920Z *** Extract App detail from [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_Base Application_18.0.23013.23795.app]
2021-12-02T16:06:19.9089704Z *** Extract App detail from [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_System Application_18.0.23013.23795.app]
2021-12-02T16:06:19.9090438Z *** Extract App detail from [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_System_18.0.22893.23773.app]
2021-12-02T16:06:19.9090977Z *** Installing Applications:
2021-12-02T16:06:19.9091142Z 
2021-12-02T16:06:19.9091404Z **************************************
2021-12-02T16:06:19.9091933Z  * App File = [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_System Application_18.0.23013.23795.app]
2021-12-02T16:06:19.9092261Z 
2021-12-02T16:06:19.9092563Z  * App.ID        = 63ca2fa4-4f03-4f2b-a480-172fef340d3f
2021-12-02T16:06:19.9092946Z  * App.Name      = System Application
2021-12-02T16:06:19.9093255Z  * App.Publisher = Microsoft
2021-12-02T16:06:19.9093567Z  * App.Version   = 18.0.23013.23795
2021-12-02T16:06:20.0042078Z  * App 'System Application v18.0.23013.23795' already published.
2021-12-02T16:06:20.0042989Z *** Get Tenants
2021-12-02T16:06:20.1536722Z *** Sync Tenant default
2021-12-02T16:06:20.1945146Z *** App Already installed, doing upgrade default
2021-12-02T16:06:20.2088314Z 
2021-12-02T16:06:20.2105403Z **************************************
2021-12-02T16:06:20.2106186Z 
2021-12-02T16:06:20.2117493Z 
2021-12-02T16:06:20.2124384Z **************************************
2021-12-02T16:06:20.2134438Z  * App File = [C:\Run\DevOps\Artifacts-a1eecd165a094776a73317eb3c2a4eb2\Microsoft_Base Application_18.0.23013.23795.app]
2021-12-02T16:06:20.2145791Z 
2021-12-02T16:06:20.4146017Z  * App.ID        = 437dbf0e-84ff-417a-965d-ed2bb9650972
2021-12-02T16:06:20.4162590Z  * App.Name      = Base Application
2021-12-02T16:06:20.4170393Z  * App.Publisher = Microsoft
2021-12-02T16:06:20.4173736Z  * App.Version   = 18.0.23013.23795
2021-12-02T16:06:20.4517190Z  => Publishing App 'Base Application v18.0.23013.23795'
2021-12-02T16:09:55.3418104Z *** Get Tenants
2021-12-02T16:09:55.7325344Z *** Sync Tenant default
2021-12-02T16:09:55.7584773Z *** App Already installed, doing upgrade default
2021-12-02T16:09:55.7597726Z *** Install App [Base Application] on tenant [default]
2021-12-02T16:10:35.6640085Z The extension 'Base Application by Microsoft 18.0.23013.23795' is synchronized with the correct version. However, the 
2021-12-02T16:10:35.6646084Z provided extension has a different set of tables and table extensions than the synchronized extension.
2021-12-02T16:10:35.6647091Z At line:146 char:17
2021-12-02T16:10:35.6648022Z + ...             $Result = Invoke-Command -Session $DockerSession -ScriptB ...
2021-12-02T16:10:35.6648584Z +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-12-02T16:10:35.6649445Z     + CategoryInfo          : InvalidOperation: (:) [Install-NAVApp], InvalidOperationException
2021-12-02T16:10:35.6650534Z     + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Ins 
2021-12-02T16:10:35.6651476Z    tallNavApp
2021-12-02T16:10:35.6652117Z  
2021-12-02T16:10:35.6652603Z 
2021-12-02T16:10:35.6684076Z ##[error]Batch App-Publish failed: The extension 'Base Application by Microsoft 18.0.23013.23795' is synchronized with the correct version. However, the provided extension has a different set of tables and table extensions than the synchronized extension.
2021-12-02T16:10:35.7425635Z ##[section]Async Command Start: Add Build Tag
2021-12-02T16:10:35.7426412Z Build '29373' has following tags now: myimage-onprem-18.0.23013.23795-w1-10.0.17763.2300-ltsc2019, BC.Version.18.0.23013.23795, BC.Platform.18.0.22893.23773, App.System Application.18.0.23013.23795
2021-12-02T16:10:35.7427055Z ##[section]Async Command End: Add Build Tag
2021-12-02T16:10:35.7427903Z ##[section]Async Command Start: Add Build Tag
2021-12-02T16:10:35.7428722Z Build '29373' has following tags now: myimage-onprem-18.0.23013.23795-w1-10.0.17763.2300-ltsc2019, BC.Version.18.0.23013.23795, BC.Platform.18.0.22893.23773, App.Base Application.18.0.23013.23795, App.System Application.18.0.23013.23795
2021-12-02T16:10:35.7429436Z ##[section]Async Command End: Add Build Tag
2021-12-02T16:10:35.7430491Z ##[section]Finishing: ALOps Dependant extensions

**Comment by waldo1001** [comment]
Could it be that you didn't change your version of the extension?  To enter upgrade-mode, there needs to be a change in version.

**Comment by peterz84** [comment]
The base app indeed has the same version. But that is why we need the ForceSync. 
I first delete the Base app with /devops/unpublishbase.ps1:

```
$ServerInstance = "BC" 
$ApplicationName = "Base Application" 

function UnpublishAppAndDependencies($ServerInstance, $ApplicationName) { 
  Get-NAVAppInfo -ServerInstance $ServerInstance | Where-Object {  
    # If the dependencies of this extension include the application that we want to unpublish, it means we have to unpublish this application first. 
  (Get-NavAppInfo -ServerInstance $ServerInstance -Name $_.Name).Dependencies | Where-Object { $_.Name -eq $ApplicationName } 

  } | ForEach-Object { 
    UnpublishAppAndDependencies $ServerInstance $_.Name 
  } 
  Get-NAVAppInfo -ServerInstance $ServerInstance | Where-Object Name -eq $ApplicationName | Unpublish-NavApp -ServerInstance $ServerInstance -Name $ApplicationName 
} 

function UninstallAndUnpublish($ServerInstance, $ApplicationName) { 
  Get-NAVAppInfo -ServerInstance $ServerInstance | Where-Object Name -eq $ApplicationName | Uninstall-NavApp -ServerInstance $ServerInstance -Name $ApplicationName -Force -Tenant default 
  UnpublishAppAndDependencies $ServerInstance  $ApplicationName 
} 

# Unpublish and uninstall the extensions  
Write-Host Unpublish and uninstall extensions 
UninstallAndUnpublish -ApplicationName $ApplicationName -ServerInstance $ServerInstance 
```
And then Iwant to publish the modified base app with ForceSync mode. When I do this manually with these commands, it works:
```
Publish-NAVApp -Path "C:\Run\Microsoft_Base Application_18.0.23013.23795.app" -ServerInstance BC -SkipVerification
#Sync with force because same version without modified fields are synced to SQL
Sync-NAVApp -ServerInstance $ServerInstance -Name "Base Application" -Version "18.0.23013.23795" -Mode ForceSync -Force
Install-NAVApp -Name "Base Application" -ServerInstance BC

```

**Comment by waldo1001** [comment]
What we did, is to create a separate step for the base application:

´´´yaml
- task: ALOpsAppPublish@1
  displayName: 'Publish Base Application'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_Base Application_*'
    forcesync: True
´´´

Basically: not a batch publish, but one app.

Do this before all others, and see if it works?

**Comment by peterz84** [comment]
Tried this, but still no luck. Here is my full script. Still using the unpublish base script, because the modified base app has the same version.

```
trigger: none
name: $(Build.BuildId)

variables:
- group: 'Secrets' 

pool: Business Central Pool

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image'
  inputs:
    artifacttype: OnPrem
    artifactversion: 19.0

- task: ALOpsDockerStart@1
  inputs:
    enable_symbol_loading: true
    memory_gb: '8'
    container_restart: 'always'
    docker_parameters: |
      --volume "C:\Licenses:C:/licenses"

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS - License Import'
  inputs:
    usedocker: true
    license_path: 'C:\licenses\Vendor - Business Central v19.flf' 
    remove_license_file: false    

- task: ALOpsDockerExec@1
  displayName: 'ALOPS - Unpublish MS Base'
  inputs:
    scriptsource: 'Workfolder'
    script_location: '/devops/unpublishbase.ps1'

- task: ALOpsAppPublish@1
  displayName: 'Publish Base Application'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_Base Application_*'
    forcesync: True

- task: ALOpsAppPublish@1
  displayName: 'ALOps Dependant extensions'
  inputs:
    usedocker: true
    skip_verification: true
    forcesync: true
    batch_publish_folder: '/.dependencies'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.0.*'
    targetproject: './app.json'
    failed_on_warnings: false

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: false
  condition: always()
```

Log in Publish Base Application step:
```

*** Scanning [Pipeline.Workspace].
*** Multiple App files found with filter [*_Base Application_*].
  * C:\agent\_work\19\s\Microsoft_Base Application_19.0.29894.30693.app
*** Resolved App File: [C:\agent\_work\19\s\Microsoft_Base Application_19.0.29894.30693.app].
*** Copy Artifact: [C:\agent\_work\19\s\Microsoft_Base Application_19.0.29894.30693.app]
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\190\service]
*** Selected module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\190\service\Microsoft.Dynamics.Nav.Management.dll]

**************************************
 * App File = [c:\Run\DevOps\Artifacts\Microsoft_Base Application_19.0.29894.30693.app]

 * App.ID        = 437dbf0e-84ff-417a-965d-ed2bb9650972
 * App.Name      = Base Application
 * App.Publisher = Microsoft
 * App.Version   = 19.0.29894.30693
 => Publishing App 'Base Application v19.0.29894.30693'
*** Get Tenants

*** Sync Tenant default
*** App Already installed, doing upgrade default
*** Install App [Base Application] on tenant [default]
##[error]The extension package for 'Base Application by Microsoft 19.0.29894.30693' that you are trying to install has a different set of tables and table extensions than the extension package that has been previously synchronized. You should increase the version of the extension and restart the deployment process or force synchronize the current extension package.
```

Looks like the sync is not forced in this also?

**Comment by waldo1001** [comment]
Would you be able to test this when having a different baseapp version?

**Comment by peterz84** [comment]
The base app is delivered by another Partner, so I don't have another base app version available.

**Comment by waldo1001** [comment]
We recently got into the same kind of situation, and were able to resolve it with a simple publish (no batchpublish).

It comes down to having 2 publish-steps: one for the base-app, one for the rest.. .

```yaml
### Install Dependencies
- task: ALOpsAppPublish@1
  displayName: 'Publish Base Application'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*_Base Application_*'
    forcesync: True
```
