### ISSUE TITLE
applicationinsightskey setting on ALOpsAppCompiler

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#464]
**Is your feature request related to a problem? Please describe.**
In our pipelines we use the applicationinsightskey property in the ALOpsAppCompiler. In that way only the shipped version of the App has the applicationinsightskey for production.

Example of a YAML file in the App (with a fake key)
```YAML
stages:
  - template: build_test_and_validation.yml@templates
    parameters:
      applicationinsightskey: '1e645y9b-ab01-40b5-a4aq-564x241aea69'
```

Sniplet of the template (we're using the v2, but the v1 also has this property)
```YAML
steps:
- task: ALOpsAppCompiler@2
  displayName: 'Compile Extension'
  condition: succeeded()
  inputs:
    applicationinsightskey: '${{ parameters.applicationinsightskey }}'
```

```
C:\azure-vsts-agent-build\_work\148\s\App\app.json(43,5): warning AL0667: 'applicationInsightsKey' is being deprecated in the versions: '7.2' or greater. This property is being deprecated in favor of 'applicationInsightsConnectionString'. This warning will become an error in a future release.
```

**Describe the solution you'd like**
Could we get a new property applicationInsightsConnectionString for the deprecated applicationinsightskey property?
