### ISSUE TITLE
ALOpsDockerRemove & createsqlbackup usage might cause a trouble.

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#468]
Hey All, 

Since we started using ALOpsDockerRemove with createsqlbackup option, we started getting strange issues. It turns out that if you run the same pipeline multiple times, each run publishes new backup. In the end your artifacts might look like this were u have more than one backup published. It resulted into other problems for other pipelines that are using those backups.

![image](https://user-images.githubusercontent.com/16342128/145388538-077bb1b6-d3c1-4393-810f-2d834c270f10.png)

Our orignal code looked like this. We were always making sqlbackup. 
```
- task: ALOpsDockerRemove@1
            displayName: "Remove Docker Container"
            condition: always()
            inputs:
              createsqlbackup: always
              print_logs: false
              publishsqlbackup: true
              zipsqlbackup: false
```

Since createsqlbackup has only 3 options available (onFailure, always, disabled), we had to use task conditions to sort the issue. we changed the logic, to create sqlbackup only when all other steps succeeded.

```
          - task: ALOpsDockerRemove@1
            displayName: "Remove Docker Container and make SQL Backup"
            condition: succeeded()
            inputs:
              createsqlbackup: always
              print_logs: false
              publishsqlbackup: true
              zipsqlbackup: false
          - task: ALOpsDockerRemove@1
            displayName: "Remove Docker Container"
            condition: or(failed(), canceled())
            inputs:
              createsqlbackup: disabled
              print_logs: false
              publishsqlbackup: false
              zipsqlbackup: false   
```

It's not a bug, just wanted to bring awareness for other ALOPS users.
