### ISSUE TITLE
Apply ruleset from settings.json or pipeline?

### ISSUE THREAD

**Issue by rasmusskov** [HodorNV/ALOps#473]
**Describe the bug**
We have disabled some of the sourcecop rules in our code, and our settings.json file has a reference to the ruleset file in it.
Is it possible to use the settings from the settings.json file for the codeanalyzers and rulesetpath, or do we have to define it in the pipeline file?  We already has the alcodeanalyzer setup in both places.. Do we also have to define the path in the tml file?
ruleset: 'AppSourceCop-RuleSet.json'

    "al.ruleSetPath": "AppSourceCop-RuleSet.json",
    "al.codeAnalyzers": [
        "${AppSourceCop}",
	"${CodeCop}",
	"${UICop}"
    ]

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: 'alops-licenseid'
  value: '******'
      
pool:
  Default

steps:
  
- task: ALOpsAppCompiler@2
  inputs:
    artifactversion: '18.2.26217.26490'
    artifactcountry: 'w1'
    alsourcepath: '$(System.DefaultWorkingDirectory)'
    appversiontemplate: '18.1.[yyyyMMdd].*'
    appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%.app'
    alcodeanalyzer: 'CodeCop,UICop'
    alcachepath: '$(System.DefaultWorkingDirectory)'
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
*** VSCode Settings: [C:\agent\_work\12\s\.vscode\settings.json]
*** VSCode-Settings json found.
*** Loading Json Object: [C:\agent\_work\12\s\.vscode\settings.json]
*** No AL-RuleSet json found.
```

**Expected behavior**
Ruleset and same codeanalyzers applied
