### ISSUE TITLE
[Idea] New Buildstep 'ALOps-GetArtifactVersion'

### ISSUE THREAD

**Issue by fvet** [HodorNV/ALOps#474]
**Is your feature request related to a problem? Please describe.**
Some background on our app landscape:
- We apply the **release flow** branching strategy. (= one branch per major/minor release of our product suite)
  - release/17_7
  - release/18_7
  - release/19_1
  - ...
- We have (template based) CI pipelines running on the different (release) branches (to allow hot-fixing on different releases)
- With each new major release, our yaml templates / CI pipelines are updated (via custom scripts), to ensure the `artifactversion` is properly updated in e.g. `ALOpsDockerCreate` step (and others)
  - release/17_7   : `artifactversion` = '17.1'
  - release/18_7   : `artifactversion` = '18.1'
  - release/19_1   : `artifactversion` = '19.1'
  - ...
- All our apps are released simultaneously and follow the same version pattern.

We truly think that the app manifest contains several valid information that can be re-used for pipeline creation (instead of having to repeat some information in separate yaml / pipeline definitions)

**Describe the solution you'd like**

It would be good if we could get rid of some custom scripting, by having a new **ALOps-GetArtifactVersion** step.

When we checkout code (of multiple repo's) in a pipeline, the builds source directory contains various repositories, each having a `\app` and `\test` folder, resulting in various `app.json` files. The **ALOps-GetArtifactVersion** could then scan all `app.json` files and get the highest (*) `application` version of all app.jsons (e.g. "application": "19.1.0.0") and store this in a global ALOps_ApplicationVersion variable, that can then be re-used in other ALOps steps (e.g. ALOpsDockerCreate) as `artifactversion`.

(*) Highest: In theory, all apps would have the same `application` version. In the unlikely event of having different `application` versions, the highest version is to be used (to meet the BC application dependencies)

**Describe alternatives you've considered**
- We've created lots of custom pipelines / scripting for 'releasing' our apps, but would like to simplify some of the steps by having native ALOps support.
- Similar results could be achieved via VS Code workspaces and some regex replace behaviour / scripting, although we tend to automate the (preparation of) release process as much via CI/CD / Azure DevOps.

**Comment by waldo1001** [comment]
If we do this - we'd like to add it in the ALOps-Info step - would that be ok?

**Comment by fvet** [comment]
Yes, that'd be fine too. As long as we have the bcartifacts majorMinor version (detected by ALOps, cfr. logic above) available as a global variable to re-use in other steps, that'd be great.

**Comment by fvet** [comment]
@waldo1001 Any change in having this included in the next (February?) release?

**Comment by fvet** [comment]
@AdminHodor @waldo1001 Any update pls?

**Comment by waldo1001** [comment]
It was more complex then we thought - but yes.
We tested it - but please test it as well as soon as we release (expected tomorrow).

**Comment by jcoe-nvt** [comment]
@waldo1001 We are getting the highest version from the ALOps-Info step. This now saves the value '19.1.0.0' in $(ALOPS_APPLICATION_VERSION).

However, we can't use this variable in the compile step (19.1.0.0 is a non-existing version). We would like to use the latest 19 or latest 19.1.
Could you save the major and minor version into 2 different variables? $(ALOPS_APPLICATION_MAJOR_VERSION) & $(ALOPS_APPLICATION_MINOR_VERSION)

**Comment by Arthurvdv** [comment]
Sorry for intervening, but this could be easily achieved with a flew lines of PowerShell.

Maybe this helps (not tested this so maybe it needs a few tweaks);

```YAML
steps:
- task: PowerShell@2
  displayName: 'Set Application Version'
  inputs:
    targetType: 'inline'
    script: |
      $version = [version]$(ALOPS_APPLICATION_VERSION)

      Write-Host "##[command]CUSTOM_ALOPS_APPLICATION_MAJOR_VERSION: $version.Major"
      Write-Host "##vso[task.setvariable variable=CUSTOM_ALOPS_APPLICATION_MAJOR_VERSION]$version.Major"
      
      Write-Host "##[command]CUSTOM_ALOPS_APPLICATION_MAJORMINOR_VERSION: $version.Minor"
      Write-Host "##vso[task.setvariable variable=CUSTOM_ALOPS_APPLICATION_MAJORMINOR_VERSION]$version.Minor"
```
