### ISSUE TITLE
Error: Cannot include TestToolkit without a licensefile, please specify licensefile

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#476]
### Update 20220124
Read on next comments that this appeared not to be related to CU19.3

## Issue
Since CU19.3 all [my pipelines](https://dev.azure.com/PacktPublishing/Automated-Testing-in-Microsoft-Dynamics-365-Business-Central-2Ed/_build) fail with error in the `ALOpsDockerCreate` task:

`Cannot include TestToolkit without a licensefile, please specify licensefile`

As CU19.3 is just new ALOpsDockerCreate needs to cerate a new docker image.

The license file clearly is there (in an Azure storage). All BC18 pipelines, making use of the same license reference do run well.
Each pipeline in this project has a BC19 version and a BC18 version. As the BC18 pipelines do not fail with this error, that's why I am reporting this issue here as it seems to me not related to the license as such.

**the used yaml**
```
name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master/Chapter-11-(LookupValue-Extension)

variables:
- group: 'PipelineVariables'

pool: default

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifactversion: '$(artifactVersion)'
    artifactcountry: '$(artifactCountry)'
    forcecreateimage: $(forceCreateImage)
    includetesttoolkit: true
    includetestlibrariesonly: true

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS - License Import'
  inputs:
    usedocker: true
    license_path: '$(LuxBeheerBcDevLicense)'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: '?.?.[yyyyWW].*'
    targetproject: 'Chapter 11 (LookupValue Extension)/app.json'
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*APP.app'
    skip_verification: true

- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    disabledtests: '$(Build.SourcesDirectory)/Chapter 11 (LookupValue Extension)/disabledtests/DisabledTests.json'
    import_testtoolkit: false
    import_action: 'Skip'
    testpage: '130455'
    extensionid: 'e26890f8-fafe-49c6-8951-2c1457921f9b'
    failed_test_action: 'Ignore'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: PowerShell@2
  displayName: "Create DisabledTests.json"
  inputs:
    filePath: '$(Build.SourcesDirectory)/Chapter 11 (LookupValue Extension)/disabledtests/ConvertTo-DisabledTests.ps1'
    arguments: '-inputFolderPath ''$(System.DefaultWorkingDirectory)/'''
    errorActionPreference: 'continue'
  condition: always()

- task: CopyFiles@2
  displayName: 'Copy Test Artifacts to $(Agent.BuildDirectory)/TestResults'
  inputs:
    SourceFolder: '$(Build.Sourcesdirectory)'
    Contents: ?(TestResults.xml|DisabledTests.json)
    TargetFolder: '$(Agent.BuildDirectory)/TestResults'
  condition: always()

- task: PublishPipelineArtifact@1
  displayName: 'Publish Test Artifacts: TestResults.xml and DisabledTests.json'
  inputs:
    targetPath: '$(Agent.BuildDirectory)/TestResults'
    artifact: 'TestResults'
    publishLocation: 'pipeline'
  condition: always()

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

**the output of ALOpsDockerCreate task**
```
artifactUrl                    https://bcartifacts.azureedge.net/onprem/19.3.34541.35002/w1                            
multitenant                    False                                                                                   
imageName                      myimage:onprem-19.3.34541.35002-w1-10.0.17763.2452-ltsc2019                             
includeTestLibrariesOnly       True                                                                                    
includeTestFrameworkOnly       False                                                                                   

Building image myimage:onprem-19.3.34541.35002-w1-10.0.17763.2452-ltsc2019 based on mcr.microsoft.com/businesscentral:10.0.17763.2452 with https://bcartifacts.azureedge.net/onprem/19.3.34541.35002/w1
Pulling latest image mcr.microsoft.com/businesscentral:10.0.17763.2452
10.0.17763.2452: Pulling from businesscentral
Generic Tag: 1.0.2.1
Container OS Version: 10.0.17763.2452 (ltsc2019)
Host OS Version: 10.0.17763.2452 (ltsc2019)
Using process isolation
Files in c:\bcartifacts.cache\r0muwpqo.qlm\my:
Copying Platform Artifacts
c:\bcartifacts.cache\onprem\19.3.34541.35002\platform
Copying Database
Copying Licensefile
c:\bcartifacts.cache\r0muwpqo.qlm
Cannot include TestToolkit without a licensefile, please specify licensefile
Sending build context to Docker daemon  1.575GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.2452
 ---> cf2fb2b72ee3
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/19.3.34541.35002/w1 filesOnly=False
 ---> Using cache
 ---> f95ef21273aa
Step 3/6 : COPY my /run/
 ---> Using cache
 ---> 6b0dc785600b
Step 4/6 : COPY NAVDVD /NAVDVD/
re-exec error: exit status 1: output: time="2022-01-22T13:46:56Z" level=error msg="hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)" error="hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)" importFolderPath="C:\\ProgramData\\docker\\tmp\\hcs501759635" path="\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\218c82eb9de7ef3c513c0febb55d5953efbef85af53fec554948660c704b9689"
hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)
BcContainerHelper\New-BcImage Telemetry Correlation Id: c8295702-13a1-44ad-a45d-4a84cf7fd5cf
##[error]Docker Build failed with exit code 1
Finishing: ALOPS - Create Docker Image
```

**Expected behavior**
BC19 (now 19.3) pipelines should run just as the BC18 (now 18.9 and also just released) do.

**Comment by lvanvugt** [comment]
Just to check-and-double-check reran some BC19 pipelines and saw that (having two agents on two different Azure VMs) that on one the pipelines succeed and on the other the fail with above error. So, will investigate further.

**Comment by lvanvugt** [comment]
### Questions

- Might it be that the maintenance task is only cleaning out the machine where the agent resides the task is running on?
Which seems to be always **VM A** as the maintenance task is mostly run when no other pipeline is running is thus always defaulting to the same agent (which is on **VM A**).
- So, it does not clean out the other VM, being **VM B**?
- How can I make sure that our maintenance pipeline is cleaning out both VMs?

**Comment by Arthurvdv** [comment]
> ### Questions
> * Might it be that the maintenance task is only cleaning out the machine where the agent resides the task is running on?
>   Which seems to be always **VM A** as the maintenance task is mostly run when no other pipeline is running is thus always defaulting to the same agent (which is on **VM A**).
> * So, it does not clean out the other VM, being **VM B**?
> * How can I make sure that our maintenance pipeline is cleaning out both VMs?
>   I was assuming it would clean up all machines with build agents in the same agent pool.

Hi Luc,

Maybe working with Strategies could be a solution? We use this to run our maintaince-pipeline on multiple buildserver.

```yaml

jobs:
- job: SomeJob
  strategy:
    matrix:
      Agent1:
        AGENT_NAME: 'AgentName1'
      Agent2:
        AGENT_NAME: 'AgentName2'
  pool: 
    name: BuildServers
    demands: 
    - agent.name -equals $(AGENT_NAME)
  timeoutInMinutes: 120
  steps:
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#strategies
