### ISSUE TITLE
Dynamic selection of supported isolation

### ISSUE THREAD

**Issue by kasperdj** [HodorNV/ALOps#488]
**Describe the bug**
We have 3 build servers with Intel Xeon E5-2620 v3 CPU runing Windows Server 2019. These servers requires hyper-v isolation and are working perfectly.

We now have an additional build server being added to the Agent Pool. This build server is on a different CPU architecture, AMD EPYC 7402P , and are running Windows Server 2022. This server does not support hyper-v isolation as it's an AMD CPU. We can manually create a docker container with proces isolation directly on the new server and this works.

The issue: how do I dynamically control the isolation handling in the ALOpsDockerStart parameters?
If this is not possible, is there an alternative way to control that if a build is running on build server a, b or c then use hyper-v isolation but if running on build server d, then use proces isolation instead.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsDockerStart@1
  inputs:
    docker_pull: false
    accept_image_eula: true
    accept_image_outdated: true
    docker_parameters: '--isolation=hyperv --env customNavSettings=EnableTaskScheduler=False'
    memory_gb: 16  
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
your output log
```

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can easily paste them in here.

**Additional context**
