### ISSUE TITLE
[error] Artifact Url could not be retrieved.

### ISSUE THREAD

**Issue by lvanvugt** [HodorNV/ALOps#491]
**Describe the bug**
I am busy building new build pipelines on my [TestFixtureInitializer](https://github.com/fluxxus-nl/TestFixtureInitializer/) project to run MS tests and test the improvements that MS has made to their tests to stabilize them.
For that I have create [this specific yaml](https://github.com/fluxxus-nl/TestFixtureInitializer/blob/master/TestFixtureInitializer/Azure%20Pipelines/azure-pipelines-CASH%20FLOW%20-%20onprem%20insider.yml) based on the yaml template below to build a nextmajor container providing the latest sasToken.'
When building the container the following error occurs:
```
##[error]Artifact Url could not be retrieved.
```

**the used yaml**
[This yaml ](https://github.com/fluxxus-nl/TestFixtureInitializer/blob/master/TestFixtureInitializer/Azure%20Pipelines/azure-pipelines-CASH%20FLOW%20-%20onprem%20insider.yml) based on the following yaml template:
```
parameters:
  artifactVersion: ''
  artifactCountry: ''
  versionSelect: ''
  sasToken: ''
  forceCreateImage: false
  uninstallMsApps: true
  licenseUrl: ''
steps:          
- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, '', 'latest'), ne(variables.artifactVersion, ''), ne(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image - Version ${{ parameters.artifactVersion }} ${{ parameters.artifactCountry }}"
  inputs:
    artifactversion: ${{ parameters.artifactVersion }}
    artifactcountry: ${{ parameters.artifactCountry }}
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }} 
- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, '', 'latest'), eq(variables.artifactVersion, ''), eq(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image - latest w1"
  inputs:
    artifactcountry: 'w1'
    versionselect: 'latest'
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}

- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, '', 'latest'), eq(variables.artifactVersion, ''), ne(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image - latest ${{ parameters.artifactCountry }}"
  inputs:
    artifactcountry: ${{ parameters.artifactCountry }}
    versionselect: 'latest'
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}

- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, 'nextminor', 'nextmajor'), eq(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image -  Insider ${{ parameters.versionSelect }} w1"
  inputs:
    artifacttype: 'Sandbox'
    artifactcountry: 'w1'
    versionselect: ${{ parameters.versionSelect }}
    sastoken: ${{ parameters.sasToken }}
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}

- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, 'nextminor', 'nextmajor'), ne(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image -  Insider ${{ parameters.versionSelect }} ${{ parameters.artifactCountry }}"
  inputs:
    artifacttype: 'Sandbox'
    artifactcountry: ${{ parameters.artifactCountry }}
    versionselect: ${{ parameters.versionSelect }}
    sastoken: ${{ parameters.sasToken }}
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container'
- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsDockerExec@1
  condition: eq(variables.uninstallMsApps, 'true')
  displayName: 'ALOPS - Uninstall MS apps (but leave Application apps)'
  inputs:
    inline_script: |
      Get-NAVAppInfo -ServerInstance BC -tenant default -tenantspecificproperties | 
        where isinstalled -eq $true | 
          Where Publisher -eq Microsoft | 
            where {$_.Name -ne 'Base Application' -and $_.Name -ne 'System Application' -and $_.Name -ne 'Application'}  | 
              uninstall-navapp -tenant default -force

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Install AL TestTool'
  inputs:
    usedocker: true
    installaltesttool: true
    skip_verification: true
    install_al_app_names: |
      Any
      Library Assert
      Library Variable Storage
      System Application Test Library
      Tests-TestLibraries
      Permissions Mock
      Test Runner
```

**the output**

```
Starting: ALOPS - Create Docker Image -  Insider nextmajor $(artifactCountry)
==============================================================================
Task         : ALOps Docker Create
Description  : Create Docker image from Business Central Artifacts
Version      : 1.447.2769
Author       : Hodor
Help         : Create Docker image based on NAV/BC Artifacts.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                      value                                                                                        
----                      -----                                                                                        
artifactspecification     Specific                                                                                     
artifactversion                                                                                                        
artifacttype              Sandbox                                                                                      
artifactcountry           w1                                                                                           
versionselect             nextmajor                                                                                    
artifacthint                                                                                                           
multitenant               False                                                                                        
memory                    8G                                                                                           
imageprefix               myImage                                                                                      
dockerregistry      
dockerusername                                                                                                         
dockerpassword                                                                                                         
storageaccount                                                                                                         
sastoken                  ?sv=2020-08-04&ss=b&srt=sco&spr=https&st=2...
forcecreateimage          False                                                                                        
myscripts                                                                                                              
imagenametemplate         %IMAGE_PREFIX%:%ARTIFACT_TYPE%-%ARTIFACT_VERSION%-%ARTIFACT_COUNTRY%-%OS_VERSION%-%OS_LTSC%  
licensefile               https://lux.../BC19%20Development%20License%20...
includetesttoolkit        False                                                                                        
includetestlibrariesonly  False                                                                                        
includetestframeworkonly  False                                                                                        
includeperformancetoolkit False                                                                                        

*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** To acquire a license, please visit: https://www.alops.be/getlicense
*** For pricing options, please visit : https://www.alops.be/pricing
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Trial Key  : 9e49a0a1-45c6-4038-b670-7f21fd35e892
  * Licensed To: Public Project (Free License)

*** Importing required PS-Functions
*** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
*** Check BcContainerHelper
*** Load BcContainerHelper
BcContainerHelper version 3.0.3
BcContainerHelper emits usage statistics telemetry to Microsoft

ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     3.0.3      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-...

*** Get Artifact Url for Version [] / Country [w1] / Type [Sandbox]: nextmajor
"Get-BCArtifactUrl" 
Name                           Value                                                                                   
----                           -----                                                                                   
sasToken                       ?sv=2020-08-04&ss=b&srt=sco&spr=https&st=2022-03-15T00%3A00%3A00Z&se=2022-10-01T00%3A...
select                         nextmajor                                                                               
type                           Sandbox                                                                                 
country                        w1                                                                                      

##[error]Artifact Url could not be retrieved.
Finishing: ALOPS - Create Docker Image -  Insider nextmajor $(artifactCountry)
```

**Expected behavior**
Container is built.

**Comment by lvanvugt** [comment]
Just also checked what happened when the country version was set to _base_: same error.

**Comment by lvanvugt** [comment]
Another test, however, worked well, when I changed
```
- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, 'nextminor', 'nextmajor'), eq(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image -  Insider ${{ parameters.versionSelect }} base"
  inputs:
    artifacttype: 'Sandbox'
    artifactcountry: 'base'
    versionselect: ${{ parameters.versionSelect }}
    sastoken: ${{ parameters.sasToken }}
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}
```
to
```
- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, 'nextminor', 'nextmajor'), eq(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image -  Insider ${{ parameters.versionSelect }} base"
  inputs:
    artifactcountry: 'base'
    sastoken: ${{ parameters.sasToken }}
    storageaccount: 'bcinsider'
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}
```
Seems all strange to me that initial setup was not working as I do have another pipeline setup where it works fine.

**Comment by waldo1001** [comment]
That is strange - seems there is something going wrong with the template. 
Could you give a default value to the version being "null" ($null)?  Just to try out?

**Comment by lvanvugt** [comment]
Sure ...

**Comment by lvanvugt** [comment]
No sure if I did it right. Changed to:

```
- task: ALOpsDockerCreate@1
  condition: and(in(variables.versionSelect, 'nextminor', 'nextmajor'), eq(variables.artifactCountry, ''))
  displayName: "ALOPS - Create Docker Image -  Insider ${{ parameters.versionSelect }} w1"
  inputs:
    artifactversion: $null
    artifactcountry: 'w1'
    sastoken: ${{ parameters.sasToken }}
    storageaccount: 'bcinsider'
    forcecreateimage: ${{ parameters.forceCreateImage }}
    licensefile: ${{ parameters.licenseUrl }}
```
throwing the following error:
```
*** Get Artifact Url for Version [$null] / Country [w1] / Type [OnPrem]: Latest
##[error]Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."
```
