### ISSUE TITLE
Release Pipeline - Only install specific apps

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#499]
Hi,
I'm having trouble to figure out how to use the option "Only install specific apps" in the release pipelines for the task LOPS App Publish.
Can you please specify an example?

**Comment by waldo1001** [comment]
Hi, 

With ALOpsAppPublish, you can use the `nav_artifact_app_filter` to filter.

like:

```yaml
- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*SomeSpecificAppName*.app'
```

**Comment by waldo1001** [comment]
If that doesn't help, just let me know what you try to do, and your current yaml with how you want to do it, and then may be also the output on where it fails.

**Comment by NAVFreak** [comment]
Well it works but I was more interested in` strictappnames` parameter and where I specify the strict names

```
steps:
- task: Hodor.hodor-alops.alopspublishtask.ALOpsAppPublish@1
  displayName: 'ALOps App Publish'
  inputs:
    strictappnames: true
    nav_serverinstance: BC190
    nav_artifact_app_filter: '*_App.app'
```
![image](https://user-images.githubusercontent.com/34970096/165745857-bae00371-2820-4126-88fc-97d838ef9eff.png)
