### ISSUE TITLE
Question: How should we manage pipelines

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#50]
Hey Guys, 

How do you envision maintenance of the build pipelines. Let's say I have 100 repositories and all of them have their identical yml files. Suddenly I need to change my pipeline (it can be anything: bugfixig, new feature, new image name, and etc...). If you have 2-3 repos, it's not a problem to update manually, but once you have 100 it's not fun :)  Perhaps there's another way to setup build pipelines by using central repo?

Best Regards, 
Gintautas

**Comment by AdminHodor** [comment]
Hello Gintautas,

In our opinion the best way to tackle this is using "[Templates](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops)". 

The templates can reside in a central/separate repository and referenced from the build yaml. Please check "[Using other repositories](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#using-other-repositories)" from the DevOps documentation for this.

Templates can also leverage parameters, which  allow you to build in some flexibility. 

As an example, here is a pipeline using templates stored in another repository named "AL".
```yaml
name: $(Build.BuildId)

variables:
- group: GlobalVariables
- group: BC-License

trigger:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: 'git'
      name: 'AL'
      ref: 'refs/heads/master'

stages:  
  - stage: Build
    jobs:
      - job: Build
        pool: $(pool_build)
        steps:
          ### Initialize Container
          - template: .devops/initialize_container.yml@templates
            parameters:
              docker_image: $(docker_image)
              license_flf_url: $(D365-VERSION15)

          ### Install Dependencies
          - template: .tasks/PublishApp/BartBourgeois/REST.yml@templates
                  
          ### Compile and Cleanup
          - template: .devops/compile_publish.yml@templates
            parameters:
              nav_app_version: $(nav_app_version)
              run_test_suite: false
```

The in the AL repository we have the templates.
**initialize_container.yml**
```yaml
parameters:
  docker_image: ''
  license_flf_url: ''

steps:          
- task: ALOpsDockerStart@1
  displayName: 'Start Docker Container'
  inputs:
    docker_image: ${{ parameters['docker_image'] }}
    docker_pull: true
    accept_image_eula: true
    memory_gb: 8    

- task: ALOpsDockerWait@1
  displayName: 'Wait for Docker Container'

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS License Import'
  inputs:
    usedocker: true
    license_path: ${{ parameters['license_flf_url'] }}
    print_license_info: false
```

**compile_publish.yml**
```yaml
parameters:
  nav_app_version: '4.2.[yyyyWW].*'
  run_test_suite: 'true'
  targetproject: 'app.json'
  artifact_filter: '*_$(Build.Repository.Name)_*.app'

steps:   
- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    targetproject: '${{ parameters.targetproject }}'
    nav_app_version: ${{ parameters['nav_app_version'] }}
    failed_on_warnings: true
    publish_artifact: false

- task: ALOpsAppPublish@1
  displayName: 'Publish App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: ${{ parameters['artifact_filter'] }}

- task: ALOpsAppTest@1
  displayName: 'Run TestSuite'
  enabled: ${{ parameters['run_test_suite'] }}
  inputs:
    usedocker: true
    failed_test_action: 'Error'
    testfilter: $(TestFilter)

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  enabled: ${{ parameters['run_test_suite'] }}
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'
  condition: always()    

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
```

We are successfully running this setup  in multiple projects, using a central repository immensely reduced the time required for maintaining the pipelines. 

>new image name

For the image name we suggest to use "Variable Groups" from the "Library" and importing them into the pipeline. Variable groups are the perfect match for these settings. You can even link them with Azure Key Vault, hereby you can span variables over multiple repositories/projects/organisations.

Kind regards,

Bart Bourgeois

**Comment by gintuoklis** [comment]
Hey @AdminHodor,

Thanks for the tip. I did in similiar way. Added this file to each reposiotry. While all the logic is on  AL_scripts repository. 


```
name: $(Build.BuildId)

pool: 
 name: AL

resources:
  repositories:
  - repository: scripts
    type: git
    name: AL_scripts 


variables:
  - group: AzureVaultForBuilds

steps: 
  - template: ALOpsCI.yml@scripts

```

Advantage of your script is that you could set different variables. For e.g. you can set different docker image per repo using $(docker_image) variable.
