### ISSUE TITLE
##[error]ServiceTier [BC###] not found.   ALOpsAppCompiler@1

### ISSUE THREAD

**Issue by johnvturbo** [HodorNV/ALOps#506]
Running build yaml to compile on premise BC central application running on a windows server.  The build server is a windows agent.
I confirmed the active directory account can access the application server using Visual Studio Code and manually downloading symbols, but when I run the build it always fails at the Service Tier, **##[error]ServiceTier [BC###] not found**.  See below yaml file.  The yaml file fetches the project, code and compiler fine but alway fails on the service tier. TFSBUILDACCOUNT and TFSBUILDPASSWORD are secret variables.

variables:
  VMS_USER: $(TFSBUILDACCOUNT)
  VMS_PASS: $(TFSBUILDPASSWORD)
pr:
  branches:
    include:
    - release/r1.0.16.0 
stages:
 - stage: Build
   displayName: 'Business Central Build'
   variables:
    agentFolder: $env:agentfolder
   jobs:
   - job: Build
     pool:
      vmImage: 'windows-latest'
     workspace:
       clean: all
     steps:    
     - task: ALOpsAppCompiler@1
       inputs:
        usedocker: false
        bc_username: $(VMS_USER)
        bc_password: $(VMS_PASS)
        targetproject: ./#####/app.json
        nav_computername: http://#####:8080/BC190
        nav_serverinstance: BC190
        nav_tenant: default
        nav_ports_dev: 7049 
        output_alc_logs: True       
        al_compiler_version: 9.0.615906
```

My output log has the following error
*** No VSCode-Settings json found.
*** No AL-RuleSet json found.
***
*** Setup BC Username/Password
*** Download Symbols
*** Working Dir: D:\a\1\s
##[error]ServiceTier [BC190] not found.
Async Command Start: Add Build Tag
Build '50923' has following tags now: AL.Compiler.9.0.615906
Async Command End: Add Build Tag
Async Command Start: Update Build Number
Update build number to 1.0.50923.0 for build 50923
Async Command End: Update Build Number
Finishing: ALOpsAppCompiler

```
I expected the the .app file to be compiled and published as an artifact,

**Comment by waldo1001** [comment]
I see you defined the serverinstance twice..
![image](https://user-images.githubusercontent.com/12088142/168538897-17959c3e-0438-4508-9491-b42038891927.png)


Can you try:
```yaml
variables:
  VMS_USER: $(TFSBUILDACCOUNT)
  VMS_PASS: $(TFSBUILDPASSWORD)
pr:
  branches:
    include:
    - release/r1.0.16.0 
stages:
 - stage: Build
   displayName: 'Business Central Build'
   variables:
    agentFolder: $env:agentfolder
   jobs:
   - job: Build
     pool:
      vmImage: 'windows-latest'
     workspace:
       clean: all
     steps:    
     - task: ALOpsAppCompiler@1
       inputs:
        usedocker: false
        bc_username: $(VMS_USER)
        bc_password: $(VMS_PASS)
        targetproject: ./#####/app.json
        nav_computername: http://#####:8080
        nav_serverinstance: BC190
        nav_tenant: default
        nav_ports_dev: 7049 
        output_alc_logs: True       
        al_compiler_version: 9.0.615906
```

Ps, 
is there a reason to not use docker for this?  Depending on an installed serverinstance looks very weird to me in a build process .. 🤔
