### ISSUE TITLE
Error while trying to import fob file

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#51]
Hey Guys, 

I do receive this error while importing fob file using:
##[error]Exception calling "ReadAllText" with "1" argument(s): "The given path's format is not supported."

My fob import task look like this:

```
- task: ALOpsFobImport@1
  displayName: 'Import pstesttoolpage.fob'
  inputs:
    usedocker: true    
    fixed_tag: test_tag
    filePath: '$(Agent.TempDirectory)\pstesttoolpage.fob'

```

Full log
```
Starting: Import pstesttoolpage.fob

==============================================================================

Task         : ALOps Import FOB

Description  : ALOps Import FOB

Version      : 1.426.933

Author       : Hodor

Help         : Import objects from .FOB file.

==============================================================================

*** Validate configuration

*** Importing required PS-Functions

*** Connect Docker Session

*** Initiate Docker Session

*** Setup Docker Session

*** Setup database connection

*** Using Windows-Authentication for Database

*** Setup FinSql link

*** Searching for Client-FinSql in Registry

*** Client-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\RoleTailored Client]

*** Searching for Service-FinSql in Registry

*** Service-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\Service]

*** Searching for RoleTailoredClient-FinSql in FileSystem

*** Found FinSql path: [C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe]

C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe

*** FOB File filter: C:\agent\_work\_temp\pstesttoolpage.fob

*** Import Action: Default

*** Start processing FOB: [pstesttoolpage.fob]

*** Transfer FOB to session: [pstesttoolpage.fob]

*** Import FOB: [pstesttoolpage.fob] in [NAV]

##[error]Exception calling "ReadAllText" with "1" argument(s): "The given path's format is not supported."

Finishing: Import pstesttoolpage.fob
```

I receive the same error, when i try to import testoolkit through ALOpsAppTest task

```
- task: ALOpsAppTest@1
  displayName: 'Run TestSuite'
  inputs:
    usedocker: true
    testfilter: '50000..99999'
    fixed_tag: test_tag
    import_action: "Skip"
    import_testtoolkit: true
    show_available_tests: true
```

```
Starting: Run TestSuite

==============================================================================

Task         : ALOps App Test

Description  : ALOps App Test

Author       : Hodor

Help         : Run Business Central Test-Suite and collect results.


==============================================================================

*** Validate configuration

*** Importing required PS-Functions

*** Working folder: C:\agent\_work\2\s

***

*** Prepare Docker Session

*** Connect Docker Session

*** Initiate Docker Session

*** Copy Modules to Docker

*** Setup Docker Session

*** Import Modules in Docker Session

*** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]

VERBOSE: Loading module from path 'C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll'.

*** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\140\Service\Add-ins\LSRetail\Newtonsoft.Json\Newtonsoft.Json.dll]

*** Import Modules in Docker Session: class_ClientContext

*** Setup BC Credentials in Docker

*** Prepare FinSql

*** Searching for Client-FinSql in Registry

*** Client-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\RoleTailored Client]

*** Searching for Service-FinSql in Registry

*** Service-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\Service]

*** Searching for RoleTailoredClient-FinSql in FileSystem

*** Found FinSql path: [C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe]

C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe

*** Import TestSuite Objects

*** Import TestSuite Page FOB: pstesttoolpage_auto.fob

*** Import TestToolKit FOB: CALTestCodeunits.W1.fob

*** Import TestToolKit FOB: CALTestLibraries.W1.fob

*** Import TestToolKit FOB: CALTestRunner.fob

##[error]Exception calling "ReadAllText" with "1" argument(s): "The given path's format is not supported."

Finishing: Run TestSuite
```

Any ideas?

Best Regards, 
Gintautas

**Comment by AdminHodor** [comment]
Dear Gintautas,

Are there any modifications/manipulations made to the containers? We would expect this error rather in an OnPrem installation but not in docker. We will have to investigate further, but it seems the tasks fails to retrieve the "CustomSettings.config" file which for docker should be in the root of the service folder.

We'll make an adjustment to the task asap with some extra checks concerning the CustomSettings.config file with proper printout to the logs. 

Following YAML is from one of our test-pipelines which does a FOB Import on BC v14.
```yaml
- task: ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: $(BCImage)
    docker_pull: true

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: $(license)

- task: ALOpsFobImport@1
  displayName: 'ALOps Import FOB'
  inputs:
    usedocker: true
    filePath: '.fob/*.fob'
    import_action: 'Overwrite'
```

Kind regards,

Bart Bourgeois
