### ISSUE TITLE
"Docker Start ... " error

### ISSUE THREAD

**Issue by olusola-adio-sweaty** [HodorNV/ALOps#515]
I just downloaded the free trial. I am using a build server with Docker and Hyper-V installed on it but kept getting a "Docker Start .." error.
![image](https://user-images.githubusercontent.com/104525381/169665985-e3b63fd1-cf3a-4c2e-95ba-7618bda3fd05.png)

**the used yaml**
```yaml

name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.0.0'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/sandbox'
- name: 'TestFilter'
  value: '51130..51139'
- name: 'bc_license'
  value: 'C:\vsts-agent-azure\license.flf'

pool:
  name: DevOpsPool

steps:
- checkout: self
  clean: true
  
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true
    memory_gb: '8'
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc_license)
    
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsAppTest@1
  inputs:
    usedocker: true
    import_action: "Skip"
    testfilter: $(TestFilter)
    show_available_tests: true
  continueOnError: true    

- task: PublishTestResults@2
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()    

```

**the output**
```

sql_backup_file                                                      
encryption_key                                                       
taskscheduler               Keep                                     




*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** To acquire a license, please visit: https://www.alops.be/getlicense
*** For pricing options, please visit : https://www.alops.be/pricing
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Trial Key  : f7d732f3-3a2d-44f4-b8ce-75140ef1a697
  * Licensed To: ALOps Trial [29/31] days remaining. Trial ends: Monday, 20 June 2022

Add tag 'ltsc2019' to image for OS Match
*** Pull Docker Image: mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019
Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019 not found: manifest unknown: manifest tagged by "latest-ltsc2019" is not found
*** Pull Docker Image: mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019 [OK]

*** Splitting Additional Docker Parameters
*** Additional Docker parameters:
--isolation=hyperv
*** Add docker parameter: --isolation=hyperv
"docker" create --memory 8G --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=BaseALApp_1286 --isolation=hyperv mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019
Unable to find image 'mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019' locally
Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019 not found: manifest unknown: manifest tagged by "latest-ltsc2019" is not found
*** Checking for Assemblies in App
"docker" start 
"docker start" requires at least 1 argument.
See 'docker start --help'.

Usage:  docker start [OPTIONS] CONTAINER [CONTAINER...]

Start one or more stopped containers
*** Container Started: 
##[error]Cannot bind argument to parameter 'ContainerID' because it is an empty string.
Async Command Start: Add Build Tag
Build '1286' has following tags now: mcr.microsoft.com/businesscentral/sandbox-latest-ltsc2019
Async Command End: Add Build Tag
Finishing: ALOpsDockerStart

```

**Screenshots**
![image](https://user-images.githubusercontent.com/104525381/169665763-07c2083e-055f-4540-9fcb-0a15bcd08092.png)

**Comment by waldo1001** [comment]
Clearly, your agent isn't working well.

Here's a guide that might be able to help you: https://www.waldo.be/2020/07/13/installing-a-devops-agent-with-docker-with-the-most-chance-of-success/

Can you try to go through that and report back?

**Comment by olusola-adio-sweaty** [comment]
The server is all setup according to your guide. Here is what I got back


sql_database                                                         
sql_database_user                                                    
sql_database_user_password                                           
sql_backup_file                                                      
encryption_key                                                       
taskscheduler               Keep                                     




*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** To acquire a license, please visit: https://www.alops.be/getlicense
*** For pricing options, please visit : https://www.alops.be/pricing
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Trial Key  : f7d732f3-3a2d-44f4-b8ce-75140ef1a697
  * Licensed To: ALOps Trial [28/31] days remaining. Trial ends: Monday, 20 June 2022

Add tag 'ltsc2019' to image for OS Match
*** Pull Docker Image: mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019
Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019 not found: manifest unknown: manifest tagged by "latest-ltsc2019" is not found
*** Pull Docker Image: mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019 [OK]

*** Splitting Additional Docker Parameters
*** Additional Docker parameters:
--isolation=hyperv
*** Add docker parameter: --isolation=hyperv
"docker" create --memory 8G --env accept_eula=Y --env accept_outdated=Y --restart no --label TFSBuild=BaseALApp_1289 --isolation=hyperv mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019
Unable to find image 'mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019' locally
Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019 not found: manifest unknown: manifest tagged by "latest-ltsc2019" is not found
*** Checking for Assemblies in App
"docker" start 
"docker start" requires at least 1 argument.
See 'docker start --help'.

Usage:  docker start [OPTIONS] CONTAINER [CONTAINER...]

Start one or more stopped containers
*** Container Started: 
##[error]Cannot bind argument to parameter 'ContainerID' because it is an empty string.
Async Command Start: Add Build Tag
Build '1289' has following tags now: mcr.microsoft.com/businesscentral/sandbox-latest-ltsc2019
Async Command End: Add Build Tag
Finishing: ALOpsDockerStart

**Comment by olusola-adio-sweaty** [comment]
Here is the yaml I am working with, just in case you can pick up any blind spots

name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.0.0'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/sandbox'
- name: 'TestFilter'
  value: '51130..51139'
- name: 'bc_license'
  value: 'C:\vsts-agent-azure\license.flf'

pool:
  name: DevOpsPool

steps:
- checkout: self
  clean: true
  
- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true
    memory_gb: '8'
    docker_parameters: '--isolation=hyperv'

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc_license)
    
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsAppTest@1
  inputs:
    usedocker: true
    import_action: "Skip"
    testfilter: $(TestFilter)
    show_available_tests: true
  continueOnError: true    

- task: PublishTestResults@2
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()

**Comment by waldo1001** [comment]
Where did you get this yaml from?   It seems to be an old way of doing things: using images from Microsoft.
Microsoft doesn't provide images anymore, but artifacts to create images yourself - so the yaml should look a tad different.

You can find loads of examples here: https://github.com/HodorNV/ALOps/tree/master/Examples

This could be a pipeline dat runs tests as well:
````yaml
name: $(Build.BuildId)

variables:
- name: 'AppVersion'
  value: '1.0.0.0'
- name: 'dockerimage'
  value: 'mcr.microsoft.com/businesscentral/sandbox'
- name: 'TestFilter'
  value: '51130..51139'
- name: 'bc_license'
  value: 'C:\vsts-agent-azure\license.flf'

pool:
  name: DevOpsPool

steps:
- checkout: self
  clean: true
  
- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: Sandbox

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc_license)
    
 #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Install AL TestTool' # install necessary dependent apps for testability
  inputs:
    usedocker: true
    installaltesttool: true
    skip_verification: true
    install_al_app_names: |
     Tests-TestLibraries
     System Application Test
     System Application Test Library
     Any
     Library Assert
     Test Runner
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject: 'app/app.json'                           # The App
    failed_on_warnings: true
    app_file_suffix: '_APP'                                 # A trick to uniquely identify the APP (from the TEST-app)

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension: Test-App'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject: 'test/app.json'                           # The Test-App
    failed_on_warnings: true    
    app_file_suffix: '_TEST'                                 # A trick to uniquely identify the Test-App (from the App)

- task: ALOpsAppPublish@1
  displayName: 'ALOPS - Publish Extension'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true   

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsAppTest@1
  displayName: 'ALOPS - Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    testpage: '130455'
    testsuite: 'DEFAULT'
    failed_test_action: 'Ignore'
  continueOnError: true   

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

**Comment by olusola-adio-sweaty** [comment]
Thanks for the link to the most recent templates. It's gone a lot further than it did before.
![image](https://user-images.githubusercontent.com/104525381/169797338-eead9601-e1d3-4314-8afa-4648cd3f6ae2.png)

**I am on the free trial. Please how do I create a license file?**

The logs are below:

Description  : Import Business Central license (.flf)
Version      : 1.449.3019
Author       : Hodor
Help         : Import Business Central license (.flf).
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                           value
----                                           -----
usedocker                                       True
fixed_tag                                           
nav_serverinstance                             BC140
license_path        F:\Build\_work\2\s\$(bc.license)
remove_license_file                             True
print_license_info                             False
license_scope                                Default




*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** To acquire a license, please visit: https://www.alops.be/getlicense
*** For pricing options, please visit : https://www.alops.be/pricing
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Trial Key  : f7d732f3-3a2d-44f4-b8ce-75140ef1a697
  * Licensed To: ALOps Trial [28/31] days remaining. Trial ends: Monday, 20 June 2022

*** Importing required PS-Functions
*** Connect Docker Session
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
***  License file not found on DockerHost
*** Import license in docker container.
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [BC].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\200\service]
*** Selected module: [C:\program files\microsoft dynamics nav\200\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\200\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics nav\200\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\200\service\Microsoft.Dynamics.Nav.Management.dll]
##[error]Cannot find drive. A drive with the name 'F' does not exist.
Finishing: ALOPS - License Import

**Comment by waldo1001** [comment]
Well - those are variables.

Can I please refer you to some introduction videos?
https://www.youtube.com/channel/UC8Vpdew5Ca86gGQmiq4Lvrg

If there are any more questions after watching these videos, please feel free to continue this thread.. .

**Comment by olusola-adio-sweaty** [comment]
Thanks a lot for your help. I have set up the license location on a storage account and put the location in the variable group. It downloads the file ok. I just want to confirm that the content of the file is the license-id displayed in the previous error messages. I put that license id in the file that was downloaded. Is that the right thing as your video didnt discuss the content of the file for trial users? Thanks a lot for your help.

![image](https://user-images.githubusercontent.com/104525381/169812345-cb300712-af17-43a7-8f98-0893568d95dd.png)

**Comment by olusola-adio-sweaty** [comment]
I am ok with this now. I have been able to run all the steps through. Thanks for your help.

![image](https://user-images.githubusercontent.com/104525381/169901137-d6d97842-730a-4e8b-bc03-2065527e9daf.png)

**Comment by waldo1001** [comment]
Just FYI - for that pipeline (where you are actually only compiling the extension), you can een go much simpler, and use CompilerV2.  Here are examples: https://github.com/HodorNV/ALOps/tree/master/Examples/Compiler%20V2

There, you don't need Docker (just make sure to have .Net Framework 4.8 installed).

A pipeline in that case looks something like this:

```yaml
name: $(Build.BuildId)

pool: HOD-DOCKER

trigger: none

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'Sandbox'
    appversiontemplate: '1.0.*.0'
```
