### ISSUE TITLE
Failing compile on warnings with failed_on_warnings: false   

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#525]
It looks like something changed, one of our build pipelines is failing on warnings while failed_on_warnings parameter is false. 2 weeks ago it did run fine. Any idea?

![image](https://user-images.githubusercontent.com/25202313/172857323-9614cab8-6f46-4ac6-8ba7-49bab08bd68b.png)

Full yml:

```yaml
trigger: none
name: $(Build.BuildId)

variables:
- group: 'Secrets'

pool: BHNL Business Central Pool

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image'
  inputs:
    artifacttype: OnPrem
    artifactversion: 19.0

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container'
  inputs:
    docker_parameters: |
      --volume "C:\CustomSQLbak:C:/temp"
      --volume "C:\Licenses:C:/licenses"
      --env licensefile=C:\licenses\19.flf
    sql_backup_file: 'c:\temp\W119_CU00.bak'

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.0.*'
    failed_on_warnings: false   
    targetproject: './app.json'

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```
