### ISSUE TITLE
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (401) Unauthorized."

### ISSUE THREAD

**Issue by peterz84** [HodorNV/ALOps#535]
I have a new issue with a pipeline in the CompileExtension step:

```
Invoke-RestMethod -Method Get -Uri https://74ae3b818a5f:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=18.0.0.0&tenant=default
##[error]Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (401) Unauthorized."

```
My Yaml:

```
trigger: none
name: $(Build.BuildId)

variables:
- group: 'Secrets'

pool: BHNL Business Central Pool

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image'
  inputs:
    artifacttype: OnPrem
    artifactversion: 19.0

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container'
  inputs:
    docker_parameters: |
      --volume "C:\CustomSQLbak:C:/temp"
      --volume "C:\Licenses:C:/licenses"
      --env licensefile=C:\licenses\19.flf
    sql_backup_file: 'c:\temp\Customer (W119_CU00).bak'

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.0.*'
    failed_on_warnings: false   
    targetproject: './app.json'

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true 

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

When I keep the docker container and get the log from it I have some warnings (clues?):

```
TimeGenerated : 06/20/2022 14:14:56
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: Security
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 74e6a211-f48f-498c-b5d0-92f22f65210a
ServerActivityId: 6687b1f2-04e8-4f74-9cd3-936ad220a2b2
EventTime: 06/20/2022 12:14:56
Message A security token was received that is associated with an unknown or disabled user account in Azure Active Directory.
ProcessId: 6132
Tag: 00009QY
ThreadId: 44
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 06/20/2022 14:14:56
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Information
Message : 
Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
Web service call failed Basic authentication. User does not have access.

TimeGenerated : 06/20/2022 14:14:56
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: Security
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 03330942-6d33-46bc-89c9-196383ebee88
EventTime: 06/20/2022 12:14:56
Message No user authentication object was created from authorization value.
ProcessId: 6132
Tag: 00001KM
ThreadId: 44
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 06/20/2022 14:14:57
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Error
Message : 
Server instance: BC
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 03330942-6d33-46bc-89c9-196383ebee88
EventTime: 06/20/2022 12:14:57
Message Failed request -- Method:GET; Url:https://74ae3b818a5f:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=18.0.0.0&tenant=default; StatusCode:Unauthorized; ReasonPhrase:Unauthorized; Token:
ProcessId: 6132
Tag: 00000LY
ThreadId: 44
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 06/20/2022 14:14:57
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Error
Message : 
Server instance: BC
Category: Development
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 03330942-6d33-46bc-89c9-196383ebee88
EventTime: 06/20/2022 12:14:57
Message Failed request -- Method:GET; Url:https://74ae3b818a5f:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=18.0.0.0&tenant=default; StatusCode:Unauthorized; ReasonPhrase:Unauthorized; Token:
ProcessId: 6132
Tag: 00006NR
ThreadId: 44
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 06/20/2022 14:15:52
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: a9953faa-2616-4a8f-85c8-e584319a67ef
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 03330942-6d33-46bc-89c9-196383ebee88
EventTime: 06/20/2022 12:15:52
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 828 ms
  Threshold: 750 ms
  Message: Long running SQL statement
  Task ID: 6
  Connection ID: 4
  SQL server session ID: 59
  Client Type: 
  Database Server Name: LOCALHOST\SQLEXPRESS
  Database Name: mydatabase
  Current Company Name: 
  Statement: BeginTransaction IsolationLevel=65536
  
ProcessId: 6132
Tag: 000007L
ThreadId: 73
CounterInformation: 
CustomParameters: }
GatewayCorrelationId: 

TimeGenerated : 06/20/2022 14:15:58
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 3ab1a6d0-6c1e-4bc9-a60d-d7449e2409ae
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 03330942-6d33-46bc-89c9-196383ebee88
EventTime: 06/20/2022 12:15:58
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 822 ms
  Threshold: 750 ms
  Message: Long running SQL statement
  Task ID: 9
  Connection ID: 1
  SQL server session ID: 53
  Client Type: 
  Database Server Name: LOCALHOST\SQLEXPRESS
  Database Name: mydatabase
  Current Company Name: 
  Statement: Commit
  
ProcessId: 6132
Tag: 000007S
ThreadId: 38
CounterInformation: 
CustomParameters: }
GatewayCorrelationId: 

```

This Yaml has been working for quite some time. Any idea what's wrong?
