### ISSUE TITLE
Issue with ALOps App Cleaner

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#55]
Hey Guys, 
We found another issue. This time with _ALOps App Cleaner_

I get the following error:
**Cannot bind argument to parameter 'Serverinstance' because it is an empty string.**

My task look like this:

```
- task: ALOpsAppClean@1
  displayName: 'ALOps App Cleaner'
  inputs:
    usedocker: true
    fixed_tag: test_tag
    sync_mode: Clean
```

I tried to add **nav_serverinstance** parameter to the task (it does not make sense, since I am using docker), but it did not help. I still receive the same error

```
- task: ALOpsAppClean@1
  displayName: 'ALOps App Cleaner'
  inputs:
    nav_serverinstance: NAV
    usedocker: true
    fixed_tag: test_tag
    sync_mode: Clean
```

Full log here:
```
Starting: ALOps App Cleaner

==============================================================================

Task         : ALOps App Cleaner

Description  : Cleans NAV Apps

Version      : 1.426.933

Author       : Hodor

Help         : Remove all extensions from Business Central service tier.

==============================================================================

*** Validate configuration

*** Importing required PS-Functions

*** Connect Docker Session

*** Initiate Docker Session

*** Setup Docker Session

##[error]Cannot bind argument to parameter 'Serverinstance' because it is an empty string.

Finishing: ALOps App Cleaner
```
