### ISSUE TITLE
ALOpsExtension API: Error when deploying app with same version

### ISSUE THREAD

**Issue by PeterConijn** [HodorNV/ALOps#564]
**Describe the bug**
When deploying an app with the same version as the one in the database, the deployment runs into an error rather than skipping the deployment and moving on to the next app.

We are using an OnPrem installation of BC19.0

**the used yaml**
We used a classic release pipeline, but this is the yml code:

```yaml
variables:

  ServiceUsername: 'depw1'

  ServicePassword: '<<@Dys3l-c0m-W1>>'



steps:

- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1

  displayName: 'ALOps Extension API'

  inputs:

    interaction: batch

    api_endpoint: 'http://dyslsrvvm0001:7848/Deployment-W1/api'

    authentication: usernamepassword

    username: '$(ServiceUsername)'

    password: '$(ServicePassword)'


```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
App publish failed. Check the 'Extension Deployment Status' page in the Business Central client.
App publish failed, aborting batch
```
The output in the BC extension detail is as follows:
```
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: An app with package ID '[package id]' is already published for tenant 'default'
```

**Expected behavior**
I would expect that the publication of the app with the same version is skipped and that the release pipeline moves on to the next app.

**Additional context**
BC19.0 W1 OnPrem

We are not 100% sure that this is a problem in ALOps, DevOps, or BC. Has anyone else encountered the same issue?
