### ISSUE TITLE
Question: How to use ALOps External Deployer with PTE when running Multi-Tenant On Premises

### ISSUE THREAD

**Issue by petertijsma** [HodorNV/ALOps#580]
I cannot find out how to use the External Deployer weh nusing Multi-Tenant On Premises.

Setting the Tenant doesn't work (also the Tooltip says it's only for Saas), but there is no other place to setup which tenant to deploy to.

**Yaml:**
```
steps:
- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1
  displayName: 'ENL Batch Publish PrintVis Apps'
  inputs:
    interaction: batch
    api_endpoint: 'https://og-xxxxxxx.xx.xxxxxxxx.nl:31003/CLIENT-MT/api'
    authentication: basic
    username: '$(og.serviceaccount)'
    password: '$(og.serviceaccountpassword)'
    bccompany: 'L01 xxxxx xxxxx'
    artifact_path: '$(System.ArtifactsDirectory)\_Third Party Apps\Apps\OGDT Core Dependencies\NovaVision'
    checksecondsdelay: 10
    maxtries: 10
  continueOnError: true
  condition: succeededOrFailed()
```

**Error in DevOps:**

![image](https://user-images.githubusercontent.com/86952584/197136341-2d6b9964-2b8e-4f24-830c-d084af8273e2.png)

Adding:

`azure_tenant_id: ENL`

Does not make any difference. Gives the same error

However, when I run the Get manually with `?tenant=ENL` added, It does give me the requested result:

![image](https://user-images.githubusercontent.com/86952584/197136983-42537f6e-1db1-42ed-abf5-184358da8077.png)

Thanks in advance

**Comment by waldo1001** [comment]
Do you want to push your PTE globally, or in one single Tenant?

We are working hard on the ALops.ExternalDeployer - we'll see if we can add the multitenant supportability.

For now: did you look into working with the alternative name?  Than you might be able to do it already... 🤔 (just a hunge)

**Comment by petertijsma** [comment]
Currently, we want to deploy Per Tenant (in order to phase the deployments per company), but of course a setting to choose Global or Tenant scope would be better :-)

**Comment by waldo1001** [comment]
Well - we'll check what we can do - we're a bit dependent on the automation-api as well ..

**Comment by petertijsma** [comment]
Coming back on this one again...

I've tried publishing through using the alternative name, but still without luck.
Can't wrap my head around it :-(

Info in the Status Page:
![image](https://user-images.githubusercontent.com/86952584/203548968-ff666d3c-fe4e-453b-94fd-fd31d3aa3879.png)

Although the Get companies works fine:
![image](https://user-images.githubusercontent.com/86952584/203549729-671f932b-9a98-4c1a-b651-7d1b1daee4f9.png)


Pulishing Yaml:

```
steps:
- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1
  displayName: 'ENL Batch Publish OGDT Core'
  inputs:
    interaction: batch
    api_endpoint: 'https://etiketnl.dfbxbcxvbcxvb.nl:20043/ODATA-PRD/api'
    authentication: basic
    username: '$(og.serviceaccount)'
    password: '$(og.serviceaccountpassword)'
    bccompany: 'L01 Etiket Nederland'
    artifact_path: '$(System.ArtifactsDirectory)\_OGDT Core'
    checksecondsdelay: 20
    maxtries: 10
  continueOnError: true
  condition: succeededOrFailed()
```

Publishing part:
![image](https://user-images.githubusercontent.com/86952584/203549286-e25de2c8-2cf2-4af2-89a1-941a64f00e6e.png)

Non-informative Errors in Event Viewer:
![image](https://user-images.githubusercontent.com/86952584/203549550-2ec998d5-eb3e-45a5-94bf-b63408473551.png)

![image](https://user-images.githubusercontent.com/86952584/203549574-a7f87290-8e24-448d-b0ab-89f7a8274b7f.png)


Tenant config:
![image](https://user-images.githubusercontent.com/86952584/203549615-0aa10d7a-c38e-4dd9-b893-ead18a2d97e6.png)



Maybe this helps...
