### ISSUE TITLE
ALOps Extension API: Cant find artifact filter

### ISSUE THREAD

**Issue by NAVFreak** [HodorNV/ALOps#582]
**Describe the bug**
I have done a release pipeline with ALOps Extension API but the problem is that it tries to deploy all my apps from pipeline, even my testapps which isn't ok.
When I read the manual it says there exist artifact filter:
```
        - task: ALOpsExtensionAPI@1
        displayName: 'ALOps Extension API'
      inputs:
        usedocker: False                      # Run task in Docker container. $(usedocker)
        fixed_tag:                            # Allows recycling of docker containers. $(fixed_tag)
        ...
        artifact_path: $(System.ArtifactsDirectory)# Path for App Artifact. $(artifact_path)
        **artifact_filter: *.app                # Filter used for locating App file relative to $(path_to_publish). $(artifact_filter)**
        
```
But I can't find/see the artifact filter in the GUI (taskversion 1.*):
![image](https://user-images.githubusercontent.com/34970096/199593675-1563c0c4-ff4e-452f-aab5-4770d8da8cf0.png)

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
steps:
- task: Hodor.hodor-alops.ALOpsExtensionAPI.ALOpsExtensionAPI@1
  displayName: 'ALOps Extension API'
  inputs:
    interaction: batch
    api_endpoint: 'https://api-XXXXX.com:7048/BC200/api'
    authentication: XXXX
    azure_tenant_id: default
    username: XXX
    password: 'XXX

```
**Expected behavior**
Be able to specify artifact filter in the configuraton of the release pipeline
