### ISSUE TITLE
ALOpsAppSign error

### ISSUE THREAD

**Issue by ghost** [HodorNV/ALOps#605]
**Describe the bug**
Since today we receive the following error in our build pipeline

`##[error]Signature status: UnknownError. ASN1 bad tag value met.
*** Transfer App Artifact from Docker container.
##[error]Cannot perform operation because the session Availability is set to None.
`

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsAppSign@1
  inputs:
    usedocker: true
    pfx_path: '$(PFXPath)'
    pfx_password: '$(PFXPass)'
```

**Expected behavior**
To have the app successfully signed

**Additional context**
The build pipeline worked as expected yesterday, without changing anything, today it doesn't work anymore.
When signing the same app with the same certificate trough bccontainerhelper, it works

**Comment by lassej5** [comment]
We have the same issue with code signing

**Comment by kasperdj** [comment]
We have same issue - all pipelines are failing

**Comment by CarloAxians** [comment]
We have the same problem.
This happened before, see ticket #479

**Comment by fvet** [comment]
We have the same issue with code signing

**Comment by MortenRa** [comment]
Just for info, we do not experience any problems with signing, so this seems to related when using docker

 ```
task: ALOpsAppSign@1
    displayName: 'ALOps App Sign'
    env:
      pfx_password: $(CodeSignPfxPassword)
    inputs:
      pfx_path: $(CodeSignPfxFile)
      timestamp_uri: $(TimeStampUri) #'http://timestamp.comodoca.com/authenticode' 
      usedocker: false
```
