### ISSUE TITLE
Error: A supported MIME type could not be found

### ISSUE THREAD

**Issue by cah42** [HodorNV/ALOps#615]
I am using the  ALOpsExtensionAPI@1 task in an Azure DevOps ci/cd pipeline. The deploy fails with the error:

```
*** Get Extension status
Invoke-RestMethod -Method Get -Uri 'https://api.businesscentral.dynamics.com/v2.0/xxxxx-xxxxx-xxxxxxx-xxxxxx/sandboxX/api/microsoft/automation/v1.0/companies(xxxxx-xxxxx-xxxxxxx-xxxxxx)/extensions'
Invoke-RestMethod -Method Patch -Uri 'https://api.businesscentral.dynamics.com/v2.0/xxxxx-xxxxx-xxxxxxx-xxxxxx/sandboxX/api/microsoft/automation/v1.0/companies(xxxxx-xxxxx-xxxxxxx-xxxxxx)/extensionUpload(0)/content'
##[error]{
  "error": {
    "code": "Unknown",
    "message": "A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaType, Microsoft.OData.ODataMediaTyp...' matches the content type 'application/octet-stream'."
  }
}
```

The failing build step:
```
- job: DeployTo
  dependsOn: 
  - GetParameters
  - DownloadArtifact
  strategy:
    maxParallel: 3
    matrix: $[ dependencies.GetParameters.outputs['Parameters.destinations'] ]  
  variables:
    destinations: $[ dependencies.GetParameters.outputs['Parameters.destinations'] ]  
  steps:
    - checkout: none
    - download: current
    - task: ALOpsExtensionAPI@1
      inputs:
        interaction: 'publish'
        api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(TenantId)/$(BCEnvironment)/api'
        dev_schemeupdatemode: 'synchronize'
        apiversion: 'v1.0'
        authentication: 'oauth'
        azure_tenant_id: '$(TenantId)'
        azure_app_client_id: '$(ClientId)'
        azure_app_client_secret: '$(Secret)'
        artifact_path: '$(Pipeline.Workspace)'
        artifact_filter: '*.app'
```

Pipeline powershell version: 
5.1.20348.1366

ALOps version:
![image](https://user-images.githubusercontent.com/96060864/225235177-b938b7f4-feb8-47b4-b741-7440084c1e64.png)

BC version:
![image](https://user-images.githubusercontent.com/96060864/225236974-3a30fa0b-a685-4945-a58c-69d3e4da9b5c.png)

Is it an error in my end? Do you need more information?
