### ISSUE TITLE
The name "Get-AlopsWarmUpEnabled" was not recognized as the name of a cmdlet, function, script file or executable. Check the spelling of the name, or if the path is correct (if included), and repeat the process.

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#618]
**Describe the bug**
Suddenly we get the error message

> The name "Get-AlopsWarmUpEnabled" was not recognized as the name of a cmdlet, function, script file or executable. Check the spelling of the name, or if the path is correct (if included), and repeat the process.

**the used yaml**
```yaml
- task: ALOpsAppCompiler@2
  displayName: 'ALOps App Compiler'
  inputs:
    artifactversion: '$(ArtifactVersion)'
    artifacttype: 'Sandbox'
    artifactcountry: 'de'
    alsourcepath: '$(System.DefaultWorkingDirectory)/MainApp'
    appversiontemplate: '$(AppVersion)'
    alcodeanalyzer: 'AppSourceCop,CodeCop,PerTenantExtensionCop,UICop'

```

**the output**
```
##[section]Starting: ALOps App Compiler
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extension(s) for Business Central
Version      : 2.0.3527
Author       : Hodor
Help         : Compile Business Central extension(s) from AL code.
==============================================================================
******************************************************************************
*** ALOps v2 - Preview                                                     ***
******************************************************************************
*** Importing required ALOps-Functions
*** Importing required Task-Functions

##[error]Die Benennung "Get-AlopsWarmUpEnabled" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
##[section]Finishing: ALOps App Compiler
```
