### ISSUE TITLE
The path cannot be processed because it resolved to more than one file; only one file at a time can be processed.

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#62]
Hey Guys, 
I am playing release pipelines for importing objects from my universal artifact storage. I made the following task to import the fob files from my artifact storage. 

Strangely it gives me the following error and i cannot understand why. I clearly specify the fullpath. If i navigate to that folder, i can see my file there ("C:\agent\_work\r1\a\_oma\objects.fob") 

Any ideas? Can I switch on debugging somehow to get more insight?

`"The path cannot be processed because it resolved to more than one file; only one file at a time can be processed."
`

```
- task: Hodor.hodor-alops.alopsfobimport.ALOpsFobImport@1

  displayName: 'ALOps Import FOB'

  inputs:

    nav_serverinstance: mvxtesting

    filePath: '$(System.DefaultWorkingDirectory)/_oma/objects.fob'

    import_action: Overwrite

    generate_symbol_reference: true
```

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

We made a hotfix for the Multiple ServiceTier installations, which should address this issue.
Hotfix is included in release v1.428.1187.

Kind regards,

**Comment by gintuoklis** [comment]
Hey @AdminHodor , 
I'm still exeperiencing the same issue with object import:

```
Starting: ALOps Import FOB
==============================================================================
Task         : ALOps Import FOB
Description  : ALOps Import FOB
Version      : 1.428.1187
Author       : Hodor
Help         : Import objects from .FOB file.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Setup database connection
##[error]The path cannot be processed because it resolved to more than one file; only one file at a time can be processed.
Finishing: ALOps Import FOB
```

```
- task: Hodor.hodor-alops.alopsfobimport.ALOpsFobImport@1
  displayName: 'ALOps Import FOB'
  inputs:
    nav_serverinstance: ${{ parameters.instanceName }}
    filePath: '$(Pipeline.Workspace)\Release\**\Release_CI_*.fob'
    import_action: Overwrite
    synchronize_schema_changes: no
```

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

We hotfixed this one a minute ago, please check release v1.428.1191.

Kind regards

**Comment by gintuoklis** [comment]
I got this one now:

```
Starting: ALOps Import FOB
==============================================================================
Task         : ALOps Import FOB
Description  : ALOps Import FOB
Version      : 1.428.1191
Author       : Hodor
Help         : Import objects from .FOB file.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Setup database connection
##[error]The term 'Import-ALOpsNavManagementDlls' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Finishing: ALOps Import FOB
```

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

We hotfixed this one a minute ago, please check release v1.428.1193.
Fingers crossed

Kind regards

**Comment by gintuoklis** [comment]
moving my comment to the right issue:)

it discovers navservicetier assemblies correctly, but not finsql.exe. It takes executable from older version **100**. 
Strangest thing that it keeps importing the fob, even with older finsql.exe version. At least it did not crash yet, should take about 15minutes to know the result. It's big fob file i have there.

```
Starting: ALOps Import FOB
==============================================================================
Task         : ALOps Import FOB
Description  : ALOps Import FOB
Version      : 1.428.1193
Author       : Hodor
Help         : Import objects from .FOB file.
==============================================================================
*** Validate configuration
*** Importing required PS-Functions
*** Setup database connection
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [buildTest].
*** Loadin assemblies from: [C:\program files\microsoft dynamics nav\nav140.39277\nav140.39277]
*** Using Windows-Authentication for Database
*** Setup FinSql link
*** Searching for Client-FinSql in Registry
*** Client-FinSql from registry could not be located: [C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\finsql.exe]
*** Searching for Service-FinSql in Registry
*** Service-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\Service]
*** Searching for RoleTailoredClient-FinSql in FileSystem
*** Found FinSql path: [C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe]
C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe
*** FOB File filter: C:\agent\_work\1\Release\**\Release_CI_*.fob
*** Import Action: Overwrite
*** Start processing FOB: [Release_CI_38917.fob]
*** Import NAV/BC Management DLL's
*** Loading assemblies for ServiceTier [buildTest].
*** Loadin assemblies from: [C:\program files\microsoft dynamics nav\nav140.39277\nav140.39277]
*** Import FOB: [Release_CI_38917.fob] in [buildTest]
  * DatabaseServer   : mvx-sql
  * Database Instance: 
  * Database Name    : buildTest
  * Management Port  : 7045
*** Running command: & "C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\finsql.exe" --% Command=ImportObjects,ImportAction=Overwrite,SynchronizeSchemaChanges=no,File="C:\agent\_work\1\Release\mv_Release_CI_38917_master\Release_CI_38917.fob",LogFile="C:\Users\BUILDA~1\AppData\Local\Temp\NavIde\dcfd9c22-7464-453a-bd03-f055fae3883b\Release_CI_38917.log",ServerName="mvx-sql",generatesymbolreference=1,ServerName="mvx-sql",Database="buildTest",NavServerName="localhost",NavServerInstance="buildTest",NavServerManagementport=7045 | Out-Null
```

in my own scripts, i used to take finsql from the navservicefolder.

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

Resolving of the FinSql client depends on registry settings, where only 1 client can be active. These are the challanges of multi-version installations. For the Service it is solvable, for the FinSql.exe not so much.

I could however add an extra parameter to the step, which would allow you to manually override the FinSql.exe path instead of using the resolver. Although it would require manual configuration, it would allow you total flexibility in multi-version scenario's.  

Could this work for you ? Ifso, should be an easy fix, since the override function is already available and only needs to be mapped to the Task.

Kind regards,

**Comment by gintuoklis** [comment]
It would work for me. I already have script to find the right finsql.

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

Could you enlighten me on how you can resolve the correct finsql.exe without it beeing installed?
I'll get back to you asap when the override parameter is available.

Kind regards,

**Comment by gintuoklis** [comment]
this is how i do in my scripts:

```
$NAVServerExecutable = Get-WmiObject win32_service | ?{$_.Name -like "*`$$instanceName"} | select @{Name="Path"; Expression={$_.PathName.split('"')[1]}}
$NAVServerFolder = Split-Path $NAVServerExecutable.Path

$versionNeeded = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($NAVServerExecutable.Path).FileVersion
$finsqlPath = ls -Path "C:\Program Files (x86)\Microsoft Dynamics*" finsql.exe -Recurse | % versioninfo | Where-Object {$_.ProductVersion -eq $versionNeeded} | Select -ExpandProperty FileName
$finsqlfodler = (get-item $finsqlPath).Directory.FullName
```
I presume finsql.exe is installed on "C:\Program Files (x86)\Microsoft Dynamics...."
that could be a flaw, but i take that risk

**Comment by AdminHodor** [comment]
Dear @gintuoklis ,

We just pushed hotfix v1.428.1196, which has the override parameters for the FinSql Path. 
We provided 2 ways to override the path, one Global via environment variables, a second on the tasks themselves.

Via Variables you have a global override, which will be picked up by every Tasks that uses FinSql.
```
variables:
  - name: Alops_OverrideFinSqlPath
    value: 'C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\finsql.exe'
```

If you want to override on Task level, you can use the new parameter [override_finsql_path]
```
- task: ALOpsFobImport@1
  displayName: 'ALOps Import FOB'
  inputs:
    nav_serverinstance: BC140
    filePath: '.fob/*.fob'
    import_action: 'Overwrite'
    synchronize_schema_changes: 'Yes'
    generate_symbol_reference: false
    override_finsql_path: 'C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\finsql.exe'
```

Please let us know if this validates your pipeline.

Kind regards,
