### ISSUE TITLE
BC14 Container stuck in endless error loop

### ISSUE THREAD

**Issue by PatrickSchiefer** [HodorNV/ALOps#633]
When I start a BC14 container using a database backup, I get an error in an endless loop (see output)

**the used yaml**
```yaml
- task: ALOpsDockerStart@1
  displayName:             'ALOps ${{ parameters.displayName }}'
  inputs:
    container_restart:     'always'
    accept_image_outdated: true
    docker_pull:           $(job.Docker.Pull)
    enable_symbol_loading: ${{ parameters.EnableSymbolLoading }}
    enable_api_services:   true
    memory_gb:             $(job.Docker.MemoryGB)
    docker_parameters:    '$(job.Docker.Parameters)'
    multitenant:           $(job.Docker.Multitenant)
```

**the output**
```Text
Setting up folders took 1 seconds
The account already exists.

More help is available by typing NET HELPMSG 2224.

System error 1378 has occurred.

The specified account name is already a member of the group.

WSManFault
    Message
        ProviderFault
            WSManFault
                Message = The WS-Management service cannot perform the configuration operation. A listener with Address=* and Transport=HTTPS configuration already exists. You have to delete the existing listener first in order to be able to create it with the same Address and Transport values. 

Error number:  -2144108493 0x80338033
The WS-Management service cannot create the resource because it already exists. 
Auth
    Basic = true
    Kerberos = true
    Negotiate = true
    Certificate = false
    CredSSP = false
    CbtHardeningLevel = Relaxed
```
