### ISSUE TITLE
ATTENTION - [warning] No tests where executed - [error] Running Tests failed

### ISSUE THREAD

**Issue by waldo1001** [HodorNV/ALOps#656]
**Attention**

You might run into these errors in the `ALOpsAppTest` step:

```
##[warning]No tests where executed.
##[error]*** Running Tests failed.
```
This is by design:
your tests are failing because you are running the test-step but are not running any tests: the system expects (at least one) test(s), but there are none.

Intention:
You need to make sure to run tests, if no tests are run, you want to know!

Solution:
- you can disable the step (you don't want to run tests anyway)
- you can add a dummy test
- make running tests conditional.  example:
```yaml
- task: ALOpsAppTest@1
      condition: and(succeeded(), eq(variables['skip_test_suite'], false))
      inputs:
        ...
```
