### ISSUE TITLE
Running tests onPrem ignores nav_serverinstance setting?

### ISSUE THREAD

**Issue by dvanes67** [HodorNV/ALOps#662]
**Describe the bug**
I'm trying to get some tests running on an onPrem instance and get an error: 'Service Tier [BC] not found.'

**the used yaml**

```yaml
- task: ALOpsAppPublish@1
  inputs:
    nav_serverinstance: 'Dev_DvE'                                   <---- This one works
    batch_publish_folder: '$(System.ArtifactsDirectory)'

- task: ALOpsAppTest@1
  displayName: 'Run OVO SystemHelper Tests'
  inputs:
    nav_serverinstance: 'Dev_DvE'                                    <------ This one doesn't
    companyname: 'xxxxxxxx'
    bc_username: '$(BC_Test_User)'
    bc_password: '$(BC_Test_User_Password)'    
    bc_webclient_url: 'https://xxxxxxxxxx/Dev_DvE'
    testfilter: '11054288'    
    testpage: '130455'
  continueOnError: true

```

**the output**

```
strictappnames                                                                                                    False
nav_serverinstance                                                                                              Dev_DvE
artifact_path                                                                                                          
nav_artifact_app_filter                                                                                           *.app
skip_verification                                                                                                  True
forceinstall                                                                                                      False
forcesync                                                                                                         False
publish_scope                                                                                                    Global
tenant                                                                                                          default
batch_publish_folder                                                                      C:\agent_general01\_work\13\a
publisherazureactivedirectorytenantid                                                                                  
blocksymbolsonly                                                                                                  False




*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** To acquire a license, please visit: https://www.alops.be/getlicense
*** For pricing options, please visit : https://www.alops.be/pricing
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Trial Key  : 0a6cacc8-426f-48f8-9a4f-616d1d5a6da5
  * Licensed To: ALOps Trial [9/31] days remaining. Trial ends: Friday, 08 September 2023

*** Importing required PS-Functions
*** Start Batch App-Publish.
*** Import NAV/BC Management DLL's [False]
*** Loading assemblies for ServiceTier [Dev_DvE].
*** Loading assemblies from: [C:\program files\microsoft dynamics 365 business central\210\service]
*** Selected module: [C:\program files\microsoft dynamics 365 business central\210\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics 365 business central\210\service\Microsoft.Dynamics.Nav.Management.dll]
*** Selected module: [C:\program files\microsoft dynamics 365 business central\210\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics 365 business central\210\service\Microsoft.Dynamics.Nav.Apps
```
This is the output from Publish, It uses the correct ServiceTier
```

testfilter                                                11054288
disabledtests                                                     
show_available_tests                                          True
import_testtoolkit                                            True
import_action                                            Overwrite
testpage                                                    130455
testsuite                                                  DEFAULT
extensionid                                                       
installaltesttool                                            False
failed_test_action                                         Warning
override_finsql_path                                              
resultfilename                                     TestResults.xml
testrunnercodeunitid                                              




*** No ALOps License found. Set License with the [alops-licenseid] or [alops_licenseid] variables.
*** To acquire a license, please visit: https://www.alops.be/getlicense
*** For pricing options, please visit : https://www.alops.be/pricing
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Trial Key  : 0a6cacc8-426f-48f8-9a4f-616d1d5a6da5
  * Licensed To: ALOps Trial [9/31] days remaining. Trial ends: Friday, 08 September 2023

*** Importing required PS-Functions
*** Working folder: C:\agent_general01\_work\13\s
***
*** Selected module: [C:\agent_general01\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.458.4899\ps_modules\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
*** Loading module: [C:\agent_general01\_work\_tasks\ALOpsAppTest_05bf385f-26f1-474d-a993-49930a16de43\1.458.4899\ps_modules\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
*** Test Context Url: https://xxxxxxxx/Dev_DvEcs?tenant=default&company=xxxxxxxx
*** Install Test-Tool extension for creating Test-Suites
*** Import NAV/BC Management DLL's [False]
*** Loading assemblies for ServiceTier [BC].
##[error]ServiceTier [BC] not found.
Finishing: Run OVO SystemHelper Tests

```
Here it is looking for ServiceTier [BC]

**Expected behavior**
I expect it to look for the ServiceTier I specified (as nav_serverinstance)

**Screenshots**

**Additional context**
We are still in trial, but I have already created a task to get a license
