### ISSUE TITLE
##[error]Progress check failed multiple times. Aborting check sequence

### ISSUE THREAD

**Issue by lorenzfleerackers** [HodorNV/ALOps#668]
**Describe the bug**

When the release pipeline is executed for an on-premises environment, the extension installation process succeeds. However, when the agent attempts to retrieve the status from the uploaded extension, it encounters a failure.

After some time, the pipeline itself also transitions into an error state. As a result, although the application is successfully installed, the release pipeline ends up in an error condition.

The output has been included in the attached file.

Kind regards
Lorenz 
[output.txt](https://github.com/HodorNV/ALOps/files/12649332/output.txt)

**Comment by waldo1001** [comment]
![image](https://github.com/HodorNV/ALOps/assets/12088142/4f09e7ce-82c3-4306-b9b3-d30f6cfdbb71)
Did you check the "extension deployment status" page? (page 2508)?

**Comment by waldo1001** [comment]
@lorenzfleerackers ?

Do know there are parameters to change the behavior of this a bit:
```yaml
        showdeploymentstatus: True            # Show Extension Deployment Status. $(showdeploymentstatus)
        checksecondsdelay: 30                 # Seconds of delay betweel deployment status checks. $(checksecondsdelay)
        maxtries: 20                          # Max tries for status check. $(maxtries)
```

https://docs.alops.be/ALOpsSteps/Buildstepsv1/#alops_extension_api
