### ISSUE TITLE
ALOpsLicenseImport fails if agent is located on disk other than C:

### ISSUE THREAD

**Issue by JeppeBylov** [HodorNV/ALOps#69]
Hi there,

I'm in the middle of testing ALOps in a simulated client environment. My contacts in the azure business has configured some VM's with different capabilities for me, so we can scope servers for this.
In doing that i've been asked to install the DevOps agent on a secondary disk so it's split from the OS disk.
In this setup the ALOpsLicenseImport task fails, when the path is set to "F:\agent\license.flf". I know it should be set up with a link to Azure Storage, but that's for another time..

Error message: "##[error]Cannot find drive. A drive with the name 'F' does not exist."

Temporary solution:
If i remove the devops agent and re-configure it on C:\agent\ and then change the drive letter in the license file path from F to C, everything succeeds.

```
name: $(Build.BuildId)
pool: CustomerPremSSD

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: 'F:\Agent\BC15_200218.flf'
    print_license_info: true

- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: true    

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
```
```
