### ISSUE TITLE
ALOpsAppRuntimePackage - Change Artifact Name to include the BC Version

### ISSUE THREAD

**Issue by pri-kise** [HodorNV/ALOps#697]
**Is your feature request related to a problem? Please describe.**
Is there any way to include the used BC Version in the name of the created

**Describe the solution you'd like**
Get an app name with runtime information:
`publisher_appname_appversion_runtime_bcversion.app`

**Additional context**
We use the following template to create RunTime app files and we would like to add the RunTime Version to our app name

```
parameters:
  artifacttype: 'OnPrem'
  artifactcountry: 'de'
  artifactversion: '21.0'
  alcodeanalyzer: 'AppSourceCop,CodeCop,PerTenantExtensionCop,UICop'
  appversiontemplate: ''
  codeSigningPasscode: ''

stages:
  - stage: CreateRuntimeAppFiles
    displayName: 'Create Runtime App'
    dependsOn: [] # Run indepedently
    jobs:
      - job: 'CreateRuntimeApp'
        displayName: 'Job to create Runtime App'
        workspace:
          clean: all # What to clean up before the job runs - outputs | resources | all
        steps:
          - task: ALOpsDockerCreate@1
            displayName: 'Create Docker Container'
            inputs:
              artifactversion: '${{parameters.artifactversion}}'
              artifacttype: '${{parameters.artifacttype}}'
              artifactcountry: '${{parameters.artifactcountry}}'

          - task: ALOpsDockerStart@1
            displayName: 'Start Docker Container'
            inputs:
              memory_gb: '8'

          - task: ALOpsDockerWait@1
            displayName: 'Wait for Docker Container'
            inputs:
              search_string: 'Ready for connections!'

          - template: DownloadDependencies.yml # Template reference

          - task: ALOpsAppPublish@1
            displayName: 'Publish Dependencies'
            inputs:
              usedocker: true
              nav_artifact_app_filter: '*.app'
              batch_publish_folder: '$(System.ArtifactsDirectory)'

          - task: ALOpsAppCompiler@1
            displayName: 'App Compiler'
            inputs:
              usedocker: true
              targetproject: 'MainApp/app.json'
              al_analyzer: '${{parameters.alcodeanalyzer}}'
              nav_app_version: '${{parameters.appversiontemplate}}'
              publish_artifact: false
              app_file_suffix: '_BC${{parameters.artifactversion}}'

          - task: ALOpsAppPublish@1
            displayName: 'App Publish'
            inputs:
              usedocker: true
              nav_artifact_app_filter: '*.app'

          - task: ALOpsAppSign@1
            displayName: 'App Sign'
            inputs:
              usedocker: true
              artifact_path: '$(ALOPS_COMPILE_ARTIFACT)'
              pfx_path: '\\files\DevOps\Common\CodeSigning\CodeSigning.pfx'
              pfx_password: '${{parameters.codeSigningPasscode}}'
              timestamp_uri: 'http://timestamp.digicert.com/'
              publish_artifact: false

          - task: ALOpsAppRuntimePackage@1
            displayName: 'Create Runtime Package' 
            inputs:
              usedocker: true
              targetproject: 'MainApp/app.json'
              publish_artifact: true         

          - task: ALOpsDockerRemove@1
            displayName: 'Remove Docker Container'
            condition: always()
```

I first created the following issue #694,but I think the Task `ALOpsAppRuntimePackage` is the correct one.
