### ISSUE TITLE
PublishSaasExtension fails - Bad request

### ISSUE THREAD

**Issue by JeppeBylov** [HodorNV/ALOps#70]
I'm getting the following error, when trying to use PublishSaasExtension:
![image](https://user-images.githubusercontent.com/968411/73019955-ec27d680-3e24-11ea-9b1e-585501419e13.png)

I couldn't find any specific guide to creation of these application registrations, but took some inspiration from D.Katsons blogpost here: [https://community.dynamics.com/nav/b/katsonsnavblog/posts/business-central-aad-authentication-api]

So the configured application registration looks like this:

![image](https://user-images.githubusercontent.com/968411/73020131-47f25f80-3e25-11ea-8d45-642750edb812.png)

![image](https://user-images.githubusercontent.com/968411/73020193-69ebe200-3e25-11ea-895e-d543f1562c78.png)

![image](https://user-images.githubusercontent.com/968411/73020211-76703a80-3e25-11ea-9b67-4c956ea783c3.png)

Pipelines looks like this:

```
name: $(Build.BuildId)
pool: CustomerPremSSD

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerStart@1
  inputs:
    docker_image: 'mcr.microsoft.com/businesscentral/sandbox'
    docker_pull: true

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    usedocker: true
    license_path: 'C:\agent\BC15_200218.flf'

- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: true    

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsSaaSGetExtensions@1
  displayName: 'ALOps SaaS Get Extensions Sandbox'
  enabled: false
  inputs:
    azure_tenant_id: $(azure_tenant_id)
    azure_app_client_id: $(azure_client_id)
    azure_app_client_secret: $(azure_client_secret)
    bc_impersonate_user: $(bc_user)
    bc_impersonate_password: $(bc_password)
    bc_environment: $(bc_environment)

- task: ALOpsSaaSPublishExtension@1
  displayName: 'ALOps SaaS Publish Extension'
  inputs:
    azure_tenant_id: $(azure_tenant_id)
    azure_app_client_id: $(azure_client_id)
    azure_app_client_secret: $(azure_client_secret)
    bc_impersonate_user: $(bc_user)
    bc_impersonate_password: $(bc_password)
    bc_environment: $(bc_environment)
    app_artifact_filter: '*.app'
 
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()

```
And variables like this:
![image](https://user-images.githubusercontent.com/968411/73020273-97389000-3e25-11ea-918e-42bd92d69e1c.png)
