### ISSUE TITLE
ALOps Docker Create - The system cannot find the path specified. (0x3)

### ISSUE THREAD

**Issue by joelsigurd** [HodorNV/ALOps#705]
**Describe the bug**
ALOps Docker Create fails with the following error:
re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the path specified. (0x3)

**the used yaml** 
```
  - task: ALOpsDockerCreate@1
    displayName: 'Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
    inputs:
      artifactversion: '$(artifactversion)'
      artifacttype: OnPrem
      artifactcountry: 'DK'
      memory: '16G'
```

**Screenshots**
![image](https://github.com/HodorNV/ALOps/assets/25962318/1a6f470d-7160-4b47-9c84-3af24e8afeef)
