### ISSUE TITLE
Version template [yyyyWW] evaluates as *.*.20241.* and not as expected *.*.202401.*.

### ISSUE THREAD

**Issue by ninjaniels** [HodorNV/ALOps#710]
**Describe the bug**
We use the template ?.?.[yyyyWW].* when assigning version number on our apps, as describes in the [ALOps documentation](https://docs.alops.be/ALOpsSteps/Buildstepsv1/#parameters). This is giving us a problem because we get a single digit week number 1 instead of expected 01. The version number on our new builds *.*.20241.* are evaluated as lower than last year's *.*.202352.*.
Is it possible to always get double digits week numbers when using the template [yyyyWW]?

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
#Your build pipeline references an undefined variable named ‘bc_version’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

steps:

- task: Hodor.hodor-alops.alopsdeploytask.ALOpsAppCompiler@2
  displayName: 'Compile $(APP_NAME)'
  inputs:
    artifactversion: 23
    artifactcountry: w1
    alsourcepath: app/app.json
    appversiontemplate: '$(bc_version).[yyyyww].*'
    appfilenametemplate: '%APP_NAME%_%APP_VERSION%_APP.app'
    resourceexposurepolicy_allowdebugging: Enable
    resourceexposurepolicy_allowdownloadingsource: Disable
    resourceexposurepolicy_includesourceinsymbolfile: Enable
    preprocessorsymbols: 'CLEAN17,CLEAN18,CLEAN19,CLEAN20,CLEAN21,CLEAN22,CLEAN23'
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:

[OutputLog.txt](https://github.com/HodorNV/ALOps/files/13813126/OutputLog.txt)

**Expected behavior**
We were hoping that the version number would be evaluated as *.*.202401.* and not *.*.20241.*.

**Screenshots**
App upgrades fails because the version number is evaluated as lower than previous *.*.202352.*.

![image](https://github.com/HodorNV/ALOps/assets/44019151/5e9ed110-204f-452b-8597-93613cda4b6e)

Thanks, and happy new year :)
