### ISSUE TITLE
Download-File.ps1 Error in pipelines

### ISSUE THREAD

**Issue by panas78** [HodorNV/ALOps#721]
**Describe the bug**
We are getting the following error
##[error]The term 'C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.5\Common\Download-File.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**the used yaml**
```yaml
name: $(Build.BuildId)
trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: templates
    type: git
    name: Pipeline-Templates
variables:
- group: Secrets
- group: VersionGlobal
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: DiastasysPool
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      inputs:
        repository: self
        clean: true
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      inputs:
        repository: git://Navins/SCRIPTS
    - task: DownloadPipelineArtifact@2
      displayName: "Download previous version"
      continueOnError: true
      inputs:
        buildType: "specific"
        project: "$(System.TeamProjectId)"
        definition: "$(System.DefinitionId)"
        buildVersionToDownload: "latestFromBranch"
        branchName: "refs/heads/main"
        allowPartiallySucceededBuilds: true
        itemPattern: "**/*.app"
        targetPath: '$(Build.Repository.Name)\.alpackages\Prev'
    - task: PowerShell@2
      displayName: "Check previous artifact"
      inputs:
        targetType: inline
        script: |
          $Folder = '$(Build.Repository.Name)\.alpackages\Prev\Dynamics 365'
          "Check if [$Folder] exists"
          if (Test-Path -Path $Folder) {
            echo "##vso[task.setvariable variable=prevartifactexists]true"
            "Found Prev. Artifact"
          } else {
            echo "##vso[task.setvariable variable=prevartifactexists]false"
            "Prev. Artifact not exists"
          }
    - task: CopyFiles@2
      displayName: "Copy AppSourceCop rules"
      inputs:
        SourceFolder: '$(Build.Repository.LocalPath)\SCRIPTS'
        Contents: "appsource.default.ruleset.json"
        TargetFolder: '$(Build.Repository.Name)\.codeAnalysis'
        OverWrite: true
        ignoreMakeDirErrors: true
    - task: DeleteFiles@1
      displayName: "Delete AppSourceCop.json"
      condition: eq(variables.prevartifactexists, 'false')
      inputs:
        SourceFolder: $(Build.Repository.Name)
        Contents: "AppSourceCop.json"
    - task: DownloadPipelineArtifact@2
      displayName: Download Base
      inputs:
        buildType: "specific"
        project: "$(System.TeamProjectId)"
        definition: $(definitionidbase20)
        buildVersionToDownload: "latestFromBranch"
        branchName: "refs/heads/main"
        allowPartiallySucceededBuilds: true
        itemPattern: "**/*.app"
        targetPath: $(Build.Repository.Name)\.alpackages\Base
    - task: DownloadPipelineArtifact@2
      displayName: Download Navins
      inputs:
        buildType: "specific"
        project: "$(System.TeamProjectId)"
        definition: $(definitionidnavins20)
        buildVersionToDownload: "latestFromBranch"
        branchName: "refs/heads/main"
        allowPartiallySucceededBuilds: true
        itemPattern: "**/*.app"
        targetPath: $(Build.Repository.Name)\.alpackages\Navins
    - task: ALOpsAppCompiler@2
      displayName: "ALOPS - Compile Extension: App"
      inputs:
        artifactversion: $(artifactversion20)
        artifactcountry: "W1"
        appversiontemplate: "?.?.?.?"
        updatebuildnumber: false
        appfilenametemplate: "%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%.app"
        alcodeanalyzer: "AppSourceCop"
        failonwarnings: True

```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
your output log
```

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can easily paste them in here.

**Additional context**
