### ISSUE TITLE
[FEATURE REQUEST] Automatic determine running TestSuite

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#725]
We've invested using templates in our Azure DevOps pipelines, which has proven to be very useful for maintaining our CI/CD and Current, Next Minor en Next Major pipelines cross all of our Projects.

When the [[warning]No tests where executed](https://github.com/HodorNV/ALOps/issues/656) was introduced this resolved an issue where some of our Projects where misconfigured and we discovered the test weren't executed 😳

It also brought a new challenge; Some small PTE's don't have any tests, where the pipelines now where also failing and we were blocked. So we added a small "Dummy" test for the time being. We've discussed internally for an setting in the pipeline library van ADO, but this is prone to errors and with multiple repo's within a Project, this wasn't feasible.

Now, a year further, we have fully embraced dependencies and now, more then ever, we easily create small PTE's. These could be a bridge apps between different Apps which sometimes don't require a Test Suite. Or exposing (readonly) API's for external applications like for example Power BI.

We do run Current, Next Minor en Next Major pipelines for these Apps to continue to validate of there a compile warnings and/or error. We use the ALOpsAppCompiler@2 for this. Then we also created an container, deploying the App, Test-App, run the TestSuite for our 1 Dummy Test that always will return succes 🙈 With the increasing amount of Projects and Apps, this has created an significant amount of wasted resources on the ADO agents.

So we now automatic determine if we need to run the TestTool with the 'SetIsExecuteTestsVariable' PowerShell task and this is working great for us. In our CI/CD step we always spin up a container to test Upgrade code and also for creating the OpenAPI documentation, but for the Current, Next Minor en Next Major we can now completely skip the Docker step, which is a huge improvement on resources on the ADO agents.

I've created an simplified yaml example here below, to share and maybe we can include this in de documentation as examples to share? The example shows to skip an complete stage or a specific step.

The PowerShell here isn't foolproof, but works for us. An improvement would be to parses the .AL the files like the compiler and have a more robust way of determine of there are procedures with a [Test] decorator. Now I've only doing this text based, which isn't 100% foolproof.

Are there possibilities from ALOps to support this idea? It would be great to have a way to determine of we need to run the Test Suite. Ideally in a early stage, so we can chose to exclude the need to create and start a Docker container.

```yaml
stages:
  - stage: BuildStage
    displayName: 'Build'
    jobs:
      - job: BuildJob
        displayName: 'Build'
        pool: '${{ parameters.build_pool }}'
        workspace:
          clean: all
        steps:
        - task: PowerShell@2
          name: SetIsExecuteTestsVariable
          displayName: 'Check presence of test methodes'
          env:
            BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)
            TEST_APP_FOLDER: $(Test.App.Folder)
          inputs:
            targetType: 'inline'
            script: |
              $files = Get-ChildItem -Path (Join-Path $env:BUILD_SOURCESDIRECTORY $env:TEST_APP_FOLDER) -Recurse -Filter *.al | Select-String "Subtype = Test;" -List | Select Path
              $tests = $files | Get-Content | Select-String "    \[Test\]" | Measure-Object
              Write-Host "Found $($tests.Count) test procedure(s) in $(($files | Measure-Object).Count) codeunit(s)."
              if ($tests.Count -ne 0){
                  Write-Host "##[command]IsExecuteTests:True"
                  Write-Host "##vso[task.setvariable variable=IsExecuteTests;isOutput=true]True"
              } else {
                  Write-Host "##[command]IsExecuteTests:False"
                  Write-Host "##vso[task.setvariable variable=IsExecuteTests;isOutput=true]False"
              }

        - task: ALOpsAppCompiler@2
        inputs:
          artifacttype: 'Sandbox'
          appversiontemplate: 'A.A.*.0'

  - stage: TestStage
    displayName: 'Test'
    dependsOn: BuildStage
    condition: and(succeeded(), eq(dependencies.BuildStage.outputs['BuildJob.SetIsExecuteTestsVariable.IsExecuteTests'], True))     # Skip this stage if there a no tests to be execute
    jobs:
      - job: TestJob
        displayName: 'Test'
        pool: '${{ parameters.build_pool }}'
        variables:
          IsExecuteTests: $[ stageDependencies.BuildStage.BuildJob.outputs['SetIsExecuteTestsVariable.IsExecuteTests'] ]
        workspace:
          clean: all
        steps:
        - task: ALOpsDockerCreate@1
          displayName: 'ALOPS - Create Docker Image'
          inputs:
            artifacttype: Sandbox

        - task: ALOpsDockerStart@1
          displayName: 'ALOPS - Start Docker Container'
          inputs:
            enable_api_services: true

        - task: ALOpsDockerWait@1
          displayName: 'ALOPS - Wait for Docker Container to start'
          inputs:
            search_string: 'Ready for connections!'

        - task: ALOpsAppPublish@1
          displayName: 'ALOPS - Install AL TestTool'
          condition: eq(variables['IsExecuteTests'], True)    # Skip this task if there a no tests to be execute
          inputs:
            usedocker: true
            installaltesttool: true
            skip_verification: true
            install_al_app_names: |
              Tests-TestLibraries
              System Application Test
              System Application Test Library
              Any
              Library Assert
              Test Runner
              Permissions Mock
              Library Variable Storage

        - task: ALOpsAppCompiler@1
          displayName: 'ALOPS - Compile Extension: App'
          inputs:
            usedocker: true
            nav_app_version: '1.0.[yyyyWW].*'
            targetproject: 'app/app.json'
            failed_on_warnings: true
            app_file_suffix: '_APP'

        - task: ALOpsAppPublish@1
          displayName: 'ALOPS - Publish Extension'
          inputs:
            usedocker: true
            nav_artifact_app_filter: '*.app'
            skip_verification: true

        - task: ALOpsAppCompiler@1
          displayName: 'ALOPS - Compile Extension: Test-App'
          condition: eq(variables['IsExecuteTests'], True)    # Skip this task if there a no tests to be execute
          inputs:
            usedocker: true
            nav_app_version: '1.0.[yyyyWW].*'
            targetproject: 'test/app.json'
            failed_on_warnings: true    
            app_file_suffix: '_TEST'

        - task: ALOpsAppPublish@1
          displayName: 'ALOPS - Publish Extension'
          condition: eq(variables['IsExecuteTests'], True)    # Skip this task if there a no tests to be execute
          inputs:
            usedocker: true
            nav_artifact_app_filter: '*.app'
            skip_verification: true

        - task: ALOpsAppTest@1
          displayName: 'ALOPS - Run TestSuite'
          condition: eq(variables['IsExecuteTests'], True)    # Skip this task if there a no tests to be execute
          inputs:
            usedocker: true
            import_action: "Skip"
            import_testtoolkit: false
            testpage: '130455'
            testsuite: 'DEFAULT'
            failed_test_action: 'Ignore'
          continueOnError: true   

        - task: PublishTestResults@2
          displayName: 'Publish Test Results **/TestResults.xml'
          condition: eq(variables['IsExecuteTests'], True)    # Skip this task if there a no tests to be execute
          inputs:
            testResultsFormat: XUnit
            testResultsFiles: '**/TestResults.xml'
            testRunTitle: 'BC Test Results: $(Build.BuildId)'

        - task: ALOpsOpenAPI@1
          inputs:
            usedocker: true
            api_endpoint: "https://$(ALOPS_DOCKER_HOSTNAME):7048/bc/api"
            authentication: "basic"
            username: "$(ALOPS_DOCKER_ADMINUSER)"
            password: "$(ALOPS_DOCKER_ADMINPASSWORD)"
            export_yaml: true
            discover: true
            publish_artifacts: true
            api_exclude_routes: |
              beta
              v1.0
              v2.0

        - task: ALOpsDockerRemove@1
          displayName: 'ALOPS - Remove Docker Container'
          enabled: true
          condition: always()
```

**Comment by waldo1001** [comment]
Quite tricky.  

There are many ways to run suites, including an installed app from another repo.
What you are doing here, is analyze your own code - but 
- what if I want to run suites from another app?
- What naming convention?
- What if the test-app is another repo

Also,
our previous change (fail if no tests) will be undone this way, wouldn't it?

**Comment by Arthurvdv** [comment]
I'm aware the current approach isn't feasible for everybody and maybe there's a better approach to this?

The fact is we have multiple projects in Azure DevOps and multiple repositories per project. There's a mix in repos that have tests and don't have any tests. Some repos start as a small PTE without tests and tests are later added as the PTE evaluates and grows.

The most simple approach would be a pipeline parameter for each repo, but I believe that's prone to error where this setting could be easily misconfigured and/or forgot to turn on when the first tests are added to the repo. The code review should catch this, but to be honest, when the [[warning]No tests where executed](https://github.com/HodorNV/ALOps/issues/656) was introduced, we've noticed we had multiple repos without a Install codeunit for the tests, so all that time the tests weren't executed at all 😳
Our template was static and would always execute the ALOpsAppTest@1 step, where for the repos without a test we've added a small dummy test to to circumcise the error for repos without any tests.

So I would like to have te possibility to decided in the pipeline itself if the ALOpsAppTest@1 should be executed or not. 

A generic approach could be to have an a ALOps step the returns statistics of the extension. I believe you have a possibility to [Source Code Analysis](https://www.waldo.be/2017/03/02/microsoft-dynamics-nav-source-code-analysis-linecount/), where it would be helpful as a first step if this could return the amount of tests in an extension.
 
**The "Rolls Royce of cars"**
Okay, this is the "Rolls Royce of cars" I'm going to describe here, but if we want to take this to the next level; Can ALOps create a just-in-time Test Install codeunit ?

Our template for a new App has this static codeunit in the Test-App defined. 

```AL
codeunit 80000 "TST Test Install"
{
    Subtype = Install;

    trigger OnInstallAppPerCompany()
    begin
        SetupTestSuite();
    end;

    local procedure SetupTestSuite()
    var
        ALTestSuite: Record "AL Test Suite";
        TestSuiteMgt: Codeunit "Test Suite Mgt.";
        SuiteName: Code[10];
    begin
        SuiteName := 'DEFAULT';

        if ALTestSuite.Get(SuiteName) then
            ALTestSuite.Delete(true);

        TestSuiteMgt.CreateTestSuite(SuiteName);
        ALTestSuite.Get(SuiteName);

        TestSuiteMgt.SelectTestMethodsByRange(ALTestSuite, '80000..89999');
    end;
}
```

If we could property parse the .AL files, then we could
* Determine if there are any codeunits with the property `Subtype = Test;` set
* Populate the range of object ID's that should be installed (SelectTestMethodsByRange)

```yaml
- task: ALOpsCreateInstallCodeunit@1
      displayName: 'ALOps Create Install Codeunit'
      inputs:
        alsourcepath: $(Build.SourcesDirectory)
        object_number: "80000" # Leave empty to automatic assign the next available id from the app.json configuration
        object_name: "Test Install"
        file_name: "TestInstall.Codeunit.al" # Leave empty to automatic generate based on the object_name
        test_suite_name: "DEFAULT" # Leave empty to automatic assign the 'DEFAULT' value
```

If there's none codeunits with the property `Subtype = Test;` then the setup shouldn't create the file. Based on this I could append by own logic on executing a Test Stage (or ALOpsAppTest@1 step).
