### ISSUE TITLE
Error Download-VSIXStep on ALOpsAppCompiler

### ISSUE THREAD

**Issue by JOUAIRY** [HodorNV/ALOps#738]
**Describe the bug**
Error Download-VSIXStep on ALOpsAppCompiler

`*** Importing required PS-Functions
*** VSIX found on disk [C:\AgentBC\ALLanguage.vsix]
*** Setting up AL Compiler [3.0.193882]
##[error]Le terme « Download-VSIXStep » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Async Command Start: Add Build Tag
Build '1803' has following tags now: AL.Compiler.3.0.193882
Async Command End: Add Build Tag
Finishing: Compile Current App W5
`

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
#Définit la liste des branches sur lesquels le pipeline va s'effectuer
trigger:
  branches:
    include:
    - develop

steps:
- checkout: self
  clean: true

- task: ALOpsInfo@1

#Permet de compiler l'application avec en prenant en compte le CodeAnalyser
- task: ALOpsAppCompiler@1
  displayName : 'Compile Current App W5'
  inputs:
    nav_computername: 'localhost'
    nav_serverinstance: '$(BCDEV)'
    nav_tenant: 'default'
    nav_ports_dev: 7049
    al_compiler_version: '3.0.193882'
    nav_app_version: '1.0.[yyyyWW].*'
    targetproject : './app.json'
    vsix_download_path : 'C:\AgentBC\*.vsix'
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
![2024-03-18_18h45_13](https://github.com/HodorNV/ALOps/assets/153751596/fea0eb25-63e2-4837-9476-31baa8f4bcc3)


nav_computername                                                     localhost
nav_serverinstance                                             DynamicsNAV_DEV
nav_tenant                                                             default
nav_ports_dev                                                             7049
bc_username                                                                   
bc_password                                                                   
al_compiler_version                                                 3.0.193882
ruleset                                                                       
suppresswarnings                                                          KEEP
al_analyzer                                                                   
ignorepragmas                                                                 
nav_app_version                                                 1.0.[yyyyWW].*
vsix_download_path                                  C:\AgentBC\ALLanguage.vsix
use_ssl                                                                  False
download_test_symbols                                                    False
usecompression                                                            True
publish_artifact                                                          True
publishxlif                                                              False
failed_on_warnings                                                       False
failonany                                                                False
app_file_suffix                                                               
updatebuildnumber                                                         True
setup_working_folder                                                     False
showmycode                                                                Keep
resourceexposurepolicy_allowdebugging                                     Keep
resourceexposurepolicy_allowdownloadingsource                             Keep
resourceexposurepolicy_includesourceinsymbolfile                          Keep
internalsvisibleto                                                        Keep
preprocessorsymbols                                                           
applicationinsightskey                                                        
printappmanifest                                                          True
output_alc_logs                                                           True
additionalprobingpaths                                                        
enable_external_rulesets                                                 False
allowed_publisher_names                                                       
allowed_publisher_names_separator                                            ,



*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: Groupe ***** Services (RepositoryPer5 License)

*** Importing required PS-Functions
*** VSIX found on disk [C:\AgentBC\ALLanguage.vsix]
*** Setting up AL Compiler [3.0.193882]
##[error]Le terme « Download-VSIXStep » n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Async Command Start: Add Build Tag
Build '1803' has following tags now: AL.Compiler.3.0.193882
Async Command End: Add Build Tag
Finishing: Compile Current App W5

```

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem.  You can easily paste them in here.

**Additional context**
Programme work 3 years and I have this problème this week. Any Update ?
