### ISSUE TITLE
ALOpsAppValidation@1: Could not load file or assembly 'System.Runtime'

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#739]
**Describe the bug**
We're encountering on issue on `Run-AlValidation` in our Azure DevOps pipelines with an error:
`ERROR Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

I think it could be possible a BcContainerHelper issue, but just to be sure I've started with creating an issue here.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsAppValidation@1
  displayName: "App Validation"
  condition: succeeded()
  inputs:
    affixes: "VOS,BSF,VRA"
    artifact_path: $(System.ArtifactsDirectory)
    installapps_path: $(System.DefaultWorkingDirectory)\.apps
    previousapps_path: $(System.DefaultWorkingDirectory)\.previous
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
[log.txt](https://github.com/HodorNV/ALOps/files/14649692/log.txt)
