### ISSUE TITLE
ALOps App Test Dialog Errors for NextMinor/NextMajor: You must choose a company before you can access the "Global Application User Settings" table.

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#742]
**Describe the bug**
When testing against BC NextMinor or BC NextMajor with `ALOpsAppTest` you get an dialog error message: 

> You must choose a company before you can access the "Global Application User Settings" table.

**the used yaml**
# NextMinor.yml
```yaml
name: $(Build.BuildId)

variables:
  - group: 'ALOps Settings'

pool:
  name: BusinessCentralBuildAgents

trigger:
  - main

schedules:
  - cron: '0 12 * * 0'
    displayName: Weekly Next Minor Build on Sunday 12h (UTC)
    branches:
      include:
        - main
    always: true

stages:
  - template: templates/CompileAndTest.yml
    parameters:
      appversiontemplate: '?.?.*.0'
      alcodeanalyzer: 'AppSourceCop,CodeCop,PerTenantExtensionCop,UICop'
      selectVersions: ['NextMinor']
      countries: ['de']
      alsourcepath: '$(System.DefaultWorkingDirectory)/MainApp'
```
# templates/CompileAndTest.yml
```yaml
parameters:
  selectVersions: ['Current']
  artifacttype: 'Sandbox'
  countries: ['de']
  alcodeanalyzer: 'AppSourceCop,CodeCop,PerTenantExtensionCop,UICop'
  alsourcepath: ''
  appversiontemplate: ''

stages:
  - ${{each country in parameters.countries}}:
      - ${{each selectVersion in parameters.selectVersions}}:
          - stage: 'buildAndTest${{country}}${{selectVersion}}'
            displayName: 'Build Version ${{selectVersion}} for ${{country}}'
            pool:
              name: BusinessCentralBuildAgents
            jobs:
              - job: 'build${{country}}${{selectVersion}}'
                displayName: 'Job - Validate  ${{country}} ${{selectVersion}}'
                workspace:
                  clean: all # What to clean up before the job runs - outputs | resources | all
                steps:
                  - task: ALOpsDockerCreate@1
                    displayName: 'Create Docker Container'
                    inputs:
                      artifactcountry: '${{country}}'
                      versionselect: '${{selectVersion}}'
                      artifacttype: '${{parameters.artifacttype}}'
                      appversiontemplate: '${{parameters.appversiontemplate}}'
                      alsourcepath: '${{parameters.alsourcepath}}'
                      licensefile: '\\files\DevOps\Common\bc.bclicense'
                      accept_insider_eula: true

                  - task: ALOpsDockerStart@1
                    displayName: 'Start Docker Container'
                    inputs:
                      memory_gb: '8'

                  - task: ALOpsDockerWait@1
                    displayName: 'Wait for Docker Container'
                    inputs:
                      search_string: 'Ready for connections!'

                  - template: DownloadDependencies.yml # Template reference

                  - task: ALOpsAppPublish@1
                    displayName: 'Publish Dependencies'
                    inputs:
                      usedocker: true
                      nav_artifact_app_filter: '*.app'
                      batch_publish_folder: '$(System.ArtifactsDirectory)'

                  - task: ALOpsAppCompiler@1
                    displayName: 'App Compiler'
                    inputs:
                      usedocker: true
                      targetproject: 'MainApp/app.json'
                      al_analyzer: '${{parameters.alcodeanalyzer}}'
                      nav_app_version: '${{parameters.appversiontemplate}}'
                      publish_artifact: false

                  - task: ALOpsAppPublish@1
                    displayName: 'App Publish'
                    inputs:
                      usedocker: true
                      nav_artifact_app_filter: '*.app'

                  # TestApp
                  - task: ALOpsAppPublish@1
                    displayName: 'Install AL TestTool'
                    inputs:
                      usedocker: true
                      installaltesttool: true
                      install_al_app_names: |
                        System Application Test Library  
                        Library Variable Storage  
                        Permissions Mock  
                        Library Assert  
                        Any  
                        Test Runner  
                        Tests-TestLibraries
                      strictappnames: true

                  - task: ALOpsAppCompiler@1
                    displayName: 'Compile Test-App'
                    inputs:
                      usedocker: true
                      targetproject: 'TestApp/app.json'
                      nav_app_version: '${{parameters.appversiontemplate}}'
                      publish_artifact: false

                  - task: ALOpsAppPublish@1
                    displayName: 'Publish Test-App'
                    inputs:
                      usedocker: true
                      nav_artifact_app_filter: '*.app'

                  - task: ALOpsAppTest@1
                    displayName: 'Run TestSuite'
                    inputs:
                      usedocker: true
                      import_testtoolkit: false
                      testpage: '130455'
                      failed_test_action: Error
                    continueOnError: false

                  - task: PublishTestResults@2
                    displayName: 'Publish Test Results'
                    inputs:
                      testResultsFormat: 'XUnit'
                      testResultsFiles: '**/TestResults.xml'
                      testRunTitle: 'BC Test Results: $(Build.BuildId)'

                  - task: ALOpsDockerRemove@1
                    displayName: 'Remove Docker Container'
                    condition: always()
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
##[section]Starting: Run TestSuite
==============================================================================
Task         : ALOps App Test
Description  : Run AL-TestSuite for Business Central
Version      : 1.463.5245
Author       : Hodor
Help         : Run Business Central Test-Suite and collect results.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                           value
----                           -----
usedocker                       True
fixed_tag                           
nav_serverinstance                  
tenant                       default
companyname                         
profile                             
bc_username                         
bc_password                         
bc_authentication    NavUserPassword
bc_webclient_url                    
testfilter                          
disabledtests                       
show_available_tests            True
import_testtoolkit             False
import_action              Overwrite
testpage                      130455
testsuite                    DEFAULT
extensionid                         
installaltesttool              False
failed_test_action             Error
override_finsql_path                
resultfilename       TestResults.xml
testrunnercodeunitid                



True
*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
*** Working folder: C:\agent\_work\1492\s
***
*** Prepare Docker Session
*** Connect Docker Session
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Copy Modules to Docker
*** Setup Docker Session
*** Checking for container-specific Test Assemblies
*** Using container-specific Test Assemblies
*** Import Modules in Docker Session
*** Import UI Client [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
*** Selected module: [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
*** Loading module: [C:\Run\DevOps\BCAppTest\bin\Microsoft.Dynamics.Framework.UI.Client.dll]
*** Import NewtonSoft JSON [C:\Program Files\Microsoft Dynamics NAV\240\Service\Management\Newtonsoft.Json.dll]
*** Import Modules in Docker Session: class_ClientContext
*** Test Context Url: https://4005c86d0b37/BC/cs?tenant=default
*** Setup BC Credentials in Docker
*** Resolve Docker Credentials
*** Set TCP Keep-Alive
*** Start TestSuite
*** Running TestSuite with authentication [NavUserPassword] with User [admin]
*** Run warm-up with page [130455]
*** Warm-up Client Context
ERROR DIALOG: You must choose a company before you can access the "Global Application User Settings" table.
*** Create Client Context
*** Get Available Tests for suite [DEFAULT] with page [130455]
Show dialog 00000000-0000-0000-0800-0000836bd2d2
Title: Dialog Error
ERROR DIALOG: You must choose a company before you can access the "Global Application User Settings" table.
##[error]Run-Test-Exception: Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder  and retry. You might also have URL or Company name wrong.
*** Get XUnit Test file from [] to [C:\agent\_work\1492\s\]
##[error]Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
##[section]Finishing: Run TestSuite
```
