### ISSUE TITLE
Increased duration of ALOpsAppPublish@1

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#758]
**Describe the bug**
In our pipelines we have a step to install the Test-Libraries in the container, before running the Test Suite with ALOpsAppTest@1.

We're experiencing a increased duration from 30 seconds to 4 minuten. Probably due to the changes with the release of v24.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
steps:
  - task: ALOpsAppPublish@1
    displayName: "Install AL TestTool"
    inputs:
      usedocker: true
      installaltesttool: true
      skip_verification: true
      install_al_app_names: |
        Tests-TestLibraries
        System Application Test
        System Application Test Library
```

**the output**
[before.txt](https://github.com/HodorNV/ALOps/files/15141058/before.txt)
[after.txt](https://github.com/HodorNV/ALOps/files/15141059/after.txt)

**Screenshots**
![before](https://github.com/HodorNV/ALOps/assets/44637996/6620644a-883d-45b1-8dff-d3dfa866a35e)
![after](https://github.com/HodorNV/ALOps/assets/44637996/1985fdf9-47a2-46bf-aebc-63b23fdf1feb)

**Comment by Arthurvdv** [comment]
I've come to the realization that this step has become unnecessary, which then kinda resolves my issue.

Creating the docker images had a wrong parameter;

```yaml
- task: ALOpsDockerCreate@1
  inputs:
    artifacttype: Sandbox
    artifactcountry: BE
    versionselect: Daily
    accept_insider_eula: true
    includetesttoolkit: true
    includetestframeworkonly: true
```

Changed the `includetestframeworkonly` to `includetestlibrariesonly`, and removed the step ALOpsAppPublish@1 step.

**Comment by waldo1001** [comment]
Yeah, we noticed it was slower since v24.
Thanks for the suggestion!

**Comment by joandrsn** [comment]
We also have a large pipeline which uses the `ALOpsAppPublish`-step. The step is much slower on BC24 than on BC23.

We also see an increase in compilation time using the following step:
```yaml
    - task: ALOpsAppCompiler@2
      displayName: "ALOps - Fast Compiler apps"
      condition: succeeded()
      inputs:
        artifactversion: $(Version)
        artifactcountry: $(Localization)
        artifacttype: $(EnvironmentType)
        versionselect: $(ArtifactVersion)
        appversiontemplate: $(CompilerArgumentForVersionNo)
        preprocessorsymbols: $(preprocessorSymbols)
        appfilenametemplate: "EVSBA__%APP_NAME%_%APP_VERSION%_APP.app"
        alsourcepath: "$(System.DefaultWorkingDirectory)/Apps"
        publishartifact: ne(variables['SBA_CreateXliff'], '1')    # If we create xliff, then those will be published
        failonwarnings: $(FailAppOnWarnings)
        accept_insider_eula: True
```
We are talking increase of 2m30s on average for 14 apps. We also compile tests like this, which have increased by 3m52s on average.

When we have 2x fast compile + 3x publish steps in the same pipeline, we have an increase in pipeline runtime of 18 minutes from BC23 to BC24 with the exact same YAML.

Maybe it is having something to do with the new Cmdlets? On Viva Engage, there is thread going on these new Cmdlets being slower: https://www.yammer.com/dynamicsnavdev/#/threads/show?threadId=2746068688338944
