### ISSUE TITLE
ALOpsAppLicenseCheck: Could not load file or assembly 'DocumentFormat.OpenXml.Framework, Version=3.0.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'.

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#797]
**Describe the bug**
We have been encountering the following error message with ALOpsAppLicenseCheck:
```
Could not load file or assembly 'DocumentFormat.OpenXml.Framework, Version=3.0.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'.
```

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
parameters:
  artifact_exclude: ''
  artifact_include: ''
  exclude_codeunits: false
  exclude_pages: false
  exclude_queries: false
  exclude_ranges: ''
  exclude_reports: false
  exclude_tables: false
  exclude_xmlports: false
  licensefile: ''
  warning_only: false

steps:
  - task: ALOpsAppLicenseCheck@1
    displayName: 'App License Check'
    condition: and(succeeded(), ne('${{parameters.licensefile}}', ''))
    inputs:
      licensefile: '${{parameters.licensefile}}'
      artifact_filter: '*.app'
      artifact_include: '${{parameters.artifact_include}}'
      artifact_exclude: '${{parameters.artifact_exclude}}'
      exclude_ranges: '${{parameters.exclude_ranges}}'
      exclude_tables: '${{parameters.exclude_tables}}'
      exclude_codeunits: '${{parameters.exclude_codeunits}}'
      exclude_pages: '${{parameters.exclude_pages}}'
      exclude_reports: '${{parameters.exclude_reports}}'
      exclude_xmlports: '${{parameters.exclude_xmlports}}'
      exclude_queries: '${{parameters.exclude_queries}}'
      warning_only: ${{parameters.warning_only}}
      pwsh: true
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
##[section]Starting: App License Check
==============================================================================
Task         : ALOps App License Check
Description  : Check App files agains a license
Version      : 1.466.6292
Author       : Hodor
Help         : Check App files agains a license.
==============================================================================
*** Using Powershell 7
*** Validate configuration
*** Task Inputs:

[32;1mname              [0m[32;1m                     value[0m
[32;1m----              [0m [32;1m                    -----[0m
usedocker                              False
fixed_tag                                   
licensefile        CustomerLicence.bclicense
artifact_path          C:\agent\_work\6733\a
artifact_filter                        *.app
artifact_include                 prisma*.app
artifact_exclude                            
exclude_ranges                              
expiry_text                                 
expiry_dateformat                           
expiry_dayswarning                          
exclude_tables                         False
exclude_codeunits                      False
exclude_pages                          False
exclude_reports                        False
exclude_xmlports                       False
exclude_queries                        False
warning_only                           False
pwsh                                    True


True
*** For documentation, please visit   : https://www.alops.be/documentation

*** Imported required PS-Functions
*** Parse Task Parameters
*** Load Management DLL's
*** Import NAV/BC Management DLL's [True]
*** ServiceTier not specified, loading default assemblies.
*** Default Assemblies not found. Load via BC-Artifacts
*** Install/Update BCContainerHelper [https://github.com/microsoft/navcontainerhelper]
*** Check BcContainerHelper
*** Load BcContainerHelper
BcContainerHelper version 6.0.22
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 7.4.5

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.0.22                BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder,…



*** New Cache Item
##[command]"Get-BCArtifactUrl" 
Name                           Value
----                           -----
country                        W1
type                           Sandbox
select                         Weekly

 -country: W1 -type: Sandbox -select: Weekly
Downloading artifact /sandbox/25.0.23364.24925/w1
Downloading C:\Users\script-service\AppData\Local\Temp\fd79a57b-1231-4913-9842-88e41888224b.zip
Unpacking artifact to tmp folder using 7zip
Downloading platform artifact /sandbox/25.0.23364.24925/platform
Downloading C:\Users\script-service\AppData\Local\Temp\e1f18e1b-106c-44a9-8a76-10be2c14ab9a.zip
Unpacking artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
*** Platform: C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform
*** Localisation: C:\bcartifacts.cache\sandbox\25.0.23364.24925\w1
*** BC Management DLL: C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Module [Microsoft.Dynamics.Nav.Ncl.dll] not available
*** BC Types DLL: C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Types.dll
*** Selected module: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Types.dll]
*** Loading module: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Types.dll]
*** BC Management DLL: C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Load module [Microsoft.Dynamics.Nav.Apps.Management]
*** BC App Management DLL: not available
*** Load CodeAnalysis from [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management]
*** Loading assemblies from: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management]
*** Loading: [C:\bcartifacts.cache\sandbox\25.0.23364.24925\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.CodeAnalysis.dll]
##[error]Could not load file or assembly 'DocumentFormat.OpenXml.Framework, Version=3.0.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'. Das System kann die angegebene Datei nicht finden.
*** PWSH Run Completed: 1
##[section]Finishing: App License Check
```
