### ISSUE TITLE
Question about Test Suites

### ISSUE THREAD

**Issue by Drad88** [HodorNV/ALOps#80]
Hi Guys,

I've got an ALOpsAppTest task in my pipeline, but my test method does not seem to be running and no test results are being found in my publishing task.

```
- task: ALOpsAppTest@1
  displayName: 'ALOps Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    show_available_tests: true
    testpage: '130455'
    testsuite: 'DEFAULT'
    failed_test_action: 'Ignore'
  continueOnError: true   

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'
```

I've got a Test codeunit with a single Test method. I've also got an Install and an Upgrade codeunit to add my test method to the DEFAULT test suite.

```
codeunit 50102 "Test Install"
{
    Subtype = Install;

    trigger OnInstallAppPerCompany()
    begin
        SetupTestSuite();
    end;

    procedure SetupTestSuite()
    var
        ALTestSuite: Record "AL Test Suite";
        TestSuiteMgt: Codeunit "Test Suite Mgt.";
        SuiteName: Code[10];
        Me: ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(Me);
        SuiteName := 'DEFAULT';

        if ALTestSuite.Get(SuiteName) then
            ALTestSuite.Delete(true);

        TestSuiteMgt.CreateTestSuite(SuiteName);
        TestSuiteMgt.SelectTestMethodsByExtension(ALTestSuite, me.id());
    end;
}
```

What am I missing here?

Thanks,
Darren.
