### ISSUE TITLE
updateruntime error

### ISSUE THREAD

**Issue by panas78** [HodorNV/ALOps#805]
When trying to use updateruntime in ALOps App Compiler we get the following error :

##[error]Unable to find type [Microsoft.Dynamics.Nav.CodeAnalysis.RuntimeVersion].

yaml is the following
```
parameters:
  - name: artifactversion
    type: string
  - name: versiontemplate
    type: string
    default: "?.?.?.?"
  - name: failonwarnings
    type: boolean
    default: false
  - name: preprocessorsymbols
    type: string
    default: ""
  - name: updateruntime
    type: string
    default: ""

steps:
  - task: ALOpsAppCompiler@2
    displayName: "ALOPS - Compile Extension: App"
    inputs:
      artifactversion: "${{parameters.artifactversion}}"
      artifactcountry: "W1"
      appversiontemplate: "${{parameters.versiontemplate}}"
      updatebuildnumber: false
      appfilenametemplate: "%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%.app"
      alcodeanalyzer: "AppSourceCop"
      failonwarnings: "${{parameters.failonwarnings}}"
      preprocessorsymbols: "${{parameters.preprocessorsymbols}}"
      updateruntime: "${{parameters.updateruntime}}"``
```

i tried using "14.0" or "Highest" but the same error occurs
