### ISSUE TITLE
Ability to turn off telemetry on container

### ISSUE THREAD

**Issue by joandrsn** [HodorNV/ALOps#818]
**Is your feature request related to a problem? Please describe.**
Currently when running tests in a container, telemetry is emitted from the container. It would be nice to be able to disable the telemetry sent.

**Describe the solution you'd like**
A way to disable telemetry on the servicetier running in the container. The would preferably be on the `ALOpsDockerCreate`-step 

**Describe alternatives you've considered**
Doing it myself, but it would be easier if the setting was present in ALOps

**Additional context**
According to the documentation from Microsoft, this can be done on the service tier:
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/disable-limit-telemetry-events

**Comment by waldo1001** [comment]
As we talked about - you can apply this in a dockerexec after the docker wait.

```yaml
    - task: ALOpsDockerExec@1
      displayName: 'ALOps - No Telemetry'
      inputs:
        inline_script: Set-NAVServerConfiguration -ServerInstance BC -KeyName TraceLevel -KeyValue Off -ApplyTo All
```
