### ISSUE TITLE
Error when compiling: Use dotnet System.IO.Compression instead of Expand-Archive

### ISSUE THREAD

**Issue by epernst** [HodorNV/ALOps#819]
When compiling using ALOps App Compiler (Version: 2.0.6362)

Downloading artifact /onprem/24.7.25890.0/w1
Downloading C:\Users\AzDevOps\AppData\Local\Temp\592b374c-e208-49f8-b030-7ff77f55c151.zip
Unpacking artifact to tmp folder using Expand-Archive
*** Use dotnet System.IO.Compression instead of Expand-Archive
Could not rename 'c:\bcartifacts.cache\onprem\24.7.25890.0\fjtgazgz.mxq' retrying in 5 seconds.

Expected behavior:
I expected it to compile as it did fine with version 24.6.

**Comment by waldo1001** [comment]
Tested with:

```yaml
- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'OnPrem'
    artifactversion: 24
    artifactcountry: w1
    appversiontemplate: 'A.A.*.0'
    alcodeanalyzer: CodeCop, PerTenantExtensionCop
    ignorepragmas: 'AA0215,AA0137'
    track_source_build_metadata: true
    accept_insider_eula: true

```
Works like a charm.

Try to remove the BCCH artifact cache either yourself, or:
```yaml
- task: ALOpsAgentMaintenance@1
  inputs:
    removebcartifacts: true
```
