### ISSUE TITLE
ALOpsExtensionAPI does not publish a *.app, even though it finds the file

### ISSUE THREAD

**Issue by ibudasov** [HodorNV/ALOps#820]
**Describe the bug**
Hallo Waldo,

I am trying to use `ALOpsExtensionAPI` with `interaction: publish` according to [the example](https://github.com/HodorNV/ALOps/blob/master/Examples/26_PublishSaaS%20-%20S2S%20-%20AppClientSecret.yml) but getting an error that the file is not found 

This cannot be true, because I see in the logs that the file _is_ found. 

In some of the previous steps I have compiled my extension with `ALOpsAppCompiler` -- it worked perfectly.

**the used yaml**

This is the step which fails for me

```yaml
              - task: ALOpsExtensionAPI@1  # Publishes 1 app (the first one in your filter)
                displayName: 'ALOps Extension API - Publish - AutomationAPI - Service2Service Authentication'
                inputs:
                  interaction: publish
                  api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/NL_Dev/api'
                  authentication: oauth
                  azure_tenant_id: '$(azure_tenant_id)'
                  azure_app_client_id: '$(azure_client_id)'
                  azure_app_client_secret: '$(azure_client_secret)'
                  artifact_path: '$(System.ArtifactsDirectory)\*.app'
                  showdeploymentstatus: false
```

**the output**

These are the logs produced for this step:

```
-select: Weekly -type: Sandbox -country: W1
*** Platform: C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform
*** Localisation: C:\bcartifacts.cache\sandbox\25.1.25873.27757\w1
*** BC Management DLL: C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** BC Management DLL: C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\bcartifacts.cache\sandbox\25.1.25873.27757\platform\ServiceTier\program files\Microsoft Dynamics NAV\250\Service\Management\Microsoft.Dynamics.Nav.Management.dll]
*** Load module [Microsoft.Dynamics.Nav.Apps.Management]
*** BC App Management DLL: not available
*** Publish Extension
  * Artifact Path  : C:\agent\_work\1\a\*.app
  * Artifact Filter: *.app
*** Resolved App File: [C:\agent\_work\1\a\********_sandbox_25.1_fr.app].
*** Resolved App Path: [C:\agent\_work\1\a\********__sandbox_25.1_fr.app]
*** Upload extension [C:\agent\_work\1\a\********__sandbox_25.1_fr.app]
*** Get App Info
##[error]The system cannot find the file specified
Finishing: ALOps Extension API - Publish - AutomationAPI - Service2Service Authentication

```

**Expected behavior**

I would expect my file published as smoothly as compiled.

**Screenshots**

N/A

**Additional context**

N/A
