### ISSUE TITLE
Creation of Runtime Package fails on NAV 2018

### ISSUE THREAD

**Issue by bboiteauPerso** [HodorNV/ALOps#824]
**Describe the bug**
We are able to create runtime Packages on BC artifacts, the same pipeline fails when trying to create the package agains NAV2018

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
name: $(Build.BuildId)

trigger:
  branches:
    include:
      - NAV2018-transherbe

variables:
- group: 'bcpipelines'  # link to a variable group that has secret variables, like URL to license file.

pool: BCBuild

steps:
- checkout: self
  clean: true 

- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifactversion: '11.0.24742.0'
    artifactcountry: 'na'
    alternativeartifacturl: 'https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/11.0.24742.0/na'

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsLicenseImport@1
  displayName: 'ALOPS - License Import'
  inputs:
    usedocker: true
    license_path: '$(nav.2018.licence)' 

- task: ALOpsAppCompiler@1
  displayName: 'ALOPS - Compile Extension'
  inputs:
    usedocker: true
    targetproject: 'apps/ERA EFT Basic/app.json'
    nav_app_version: '1.0.[yyyyWW].*'
    failed_on_warnings: true
    app_file_suffix: '_APP'

- task: ALOpsAppPublish@1
  displayName: 'Publish AL-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsAppRuntimePackage@1
  inputs:
    usedocker: true
    targetproject: 'apps/ERA EFT Basic/app.json'  # point to the folder in your repo that you want to compile in this step
    appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_runtime.app'
    
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'ALOPS - Remove Docker Container'
  enabled: true
  condition: always()
```

**the output**
```
Starting: ALOpsAppRuntimePackage
==============================================================================
Task         : ALOps App Runtime Package
Description  : Create Runtime Package from AL Extension
Version      : 1.467.6362
Author       : Hodor
Help         : Get a NAV App runtime package for onprem deployment.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                                               value
----                                                               -----
usedocker                                                           True
fixed_tag                                                               
nav_serverinstance                                                 BC140
nav_tenant                                                       default
targetproject           C:\_agents\_work\3\s\apps\ERA EFT Basic\app.json
appfilenametemplate %APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_runtime.app
showmycode                                                         False
publish_artifact                                                    True



False
*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
 - Use Docker         = True
*** Importing required PS-Functions
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Container Session Powershell Version


Name  : PSVersion
Value : 5.1.20348.2849

Name  : PSEdition
Value : Desktop

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.20348.2849

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1

*** Import NAV/BC Management DLL's [False]
*** Loading assemblies for ServiceTier [NAV].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\110\service]
*** BC Management DLL: C:\program files\microsoft dynamics nav\110\service\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\program files\microsoft dynamics nav\110\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\110\service\Microsoft.Dynamics.Nav.Management.dll]
*** BC App Management DLL: C:\program files\microsoft dynamics nav\110\service\Microsoft.Dynamics.Nav.Apps.Management.dll
*** Selected module: [C:\program files\microsoft dynamics nav\110\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\110\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Setup VSIX for ALTOOL
*** ALTool Path: Not available
*** Using AL Compiler  located [C:\Run\Microsoft.al\al-\extension\bin\alc.exe]
***
*** Target Project: \apps\ERA EFT Basic\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Multiple projects found:
   - C:\Run\DevOps\apps\ERA EFT Basic
   - C:\Run\DevOps\test
*** Retrieving App-Info [\apps\ERA EFT Basic\app.json]
*** Loading Json Object: [c:\Run\DevOps\apps\ERA EFT Basic\app.json]
  * App.ID          = 5d17aa9c-1610-49cd-8777-2199be6f496d
  * App.Name        = ERA EFT Basic
  * App.Publisher   = Groupe ERA
*** Retrieving Published App Info [\apps\ERA EFT Basic\app.json] from [NAV]
  * App.Version     = 1.0.202502.8233
***
*** Exporting App [ERA EFT Basic] as RuntimePackage [c:\Run\DevOps\Groupe ERA_ERA EFT Basic_1.0.202502.8233_runtime.app]
##[error]Parameter set cannot be resolved using the specified named parameters.
```

**Expected behavior**
We should be able to create a runtime version using NAV2018

**Screenshots**
attached is the _diag log file
[Worker_20250110-131552-utc.log](https://github.com/user-attachments/files/18380251/Worker_20250110-131552-utc.log)

**Additional context**
