### ISSUE TITLE
What does  publishartifact: True do?

### ISSUE THREAD

**Issue by JulianTillmann** [HodorNV/ALOps#829]
What does the ALOpsAppCompiler@2 parameter " publishartifact: True" do? 

The documentation says "# Publish generated App Artifact to DevOps. $(publishartifact) $(publishartifact)" but I don't understand what that would mean, what's "DevOps" in this context? It does not seem to mean the Azure Dev Ops Artifacts Feed, but I cannot find any other documentation.

**Comment by Arthurvdv** [comment]
It will publish the artifact inside the run of pipeline itself after a successful compile.

![Image](https://github.com/user-attachments/assets/d412db33-2439-4531-ab0b-52ae65b68504)

![Image](https://github.com/user-attachments/assets/3c749ddd-44d1-4db6-8076-c3ea7e476ccf)

In this way you can share the artifact between stages, like the Build, Test and Publish in the example below.

For publishing the app as a NuGet package to the Azure DevOps feed, we're utilizing the [BCCH](https://github.com/microsoft/navcontainerhelper) for this.

A simplified representation of how we have implemented this in our pipelines:

```yaml
- stage: PublishStage
  displayName: 'Publish'
  dependsOn: TestStage
  jobs:
    - job: PublishDevOpsArtifactFeedJob
      displayName: 'DevOps Artifacts Feed'
      pool:
        vmImage: 'ubuntu-latest'
      workspace:
        clean: all
      steps:
        - checkout: none

        - task: DownloadPipelineArtifact@2
          displayName: "Get Current Pipeline Artifact"
          inputs:
            buildType: "current"
            artifactName: "Dynamics 365"
            itemPattern: "**/**/*.app"
            targetPath: "$(Build.BinariesDirectory)"

        - task: PowerShell@2
          displayName: "Generate NuGet Package and publish to Feed"
          env:
            BUILD_BINARIESDIRECTORY: $(Build.BinariesDirectory)
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
            ORGANISATIONNAME: "MyAzureDevOpsOrganizationName"
            PACKAGEFEEDNAME: "MyAzureDevOpsArtifactsFeedname"
          inputs:
            targetType: "inline"
            script: |
              Install-Module -Name BcContainerHelper -Force -Scope CurrentUser -AllowClobber

              $appFile = Get-ChildItem -Path $env:BUILD_BINARIESDIRECTORY -Depth 0 -Filter *.app | Select-Object -First 1
              $package = New-BcNuGetPackage -appfile $appFile.FullName

              $nuGetServerUrl = "https://$env:ORGANISATIONNAME.pkgs.visualstudio.com/_packaging/$env:PACKAGEFEEDNAME/nuget/v3/index.json"
              $nuGetToken = $env:SYSTEM_ACCESSTOKEN
              $package = New-BcNuGetPackage -appfile $appFile.FullName
              Push-BcNuGetPackage -nuGetServerUrl $nuGetServerUrl -nuGetToken $nuGetToken -bcNuGetPackage $package
```
