### ISSUE TITLE
How to Add Supplemental content in Appsource Release

### ISSUE THREAD

**Issue by abzmdc** [HodorNV/ALOps#830]
We want to Upload Supplemental Content (Test App) to App source
We are currently using ALOps to send automate release to AppSource through the **ALOps AppSource** task. Our release process is automated—whenever new artifacts are produced in the main branch, it triggers the release pipeline, where we sign the apps and then those app files are release to Partner Center.

For our initial release, we manually uploaded the Test App, but we would now like to automate this process as well. We have the Test App in artifacts working directory. Could you please confirm if it is possible to automate the Test App release through ALOps? If so, we would appreciate any guidance on the necessary steps. 

Looking forward to your response.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
steps:
- task: Hodor.hodor-alops.ALOpsAppSource.ALOpsAppSource@1
  displayName: 'Publish to AppSource'
  inputs:
    azure_tenant_id: '$(azure_tenant_id)'
    azure_app_client_id: '$(partner_id)'
    azure_app_client_secret: '$(partner_secret)'
    pwsh: true

```
