### ISSUE TITLE
Cannot bind argument to parameter 'InputObject' because it is null.

### ISSUE THREAD

**Issue by Arthurvdv** [HodorNV/ALOps#832]
**Describe the bug**
All of our pipelines fail on the build step currently. I believe one of the resourceexposurepolicy parameters is causing this error.

**the used yaml**
```yaml
parameters:
  artifactversion: ""
  artifacttype: "Sandbox"
  artifactcountry: "W1"
  versionselect: "Daily"
  acceptinsidereula: false
  alternativevsixurl: ""
  ruleset: ""
  suppresswarnings: "None"
  ignorepragmas: "LC0013"
  appversiontemplate: "A.A.*.0"
  updatebuildnumber: false
  alcodeanalyzer: ""
  allowedpublishernames: "VanRoey"
  resourceexposurepolicy_allowdebugging: "Enable"
  resourceexposurepolicy_allowdownloadingsource: "Disable"
  resourceexposurepolicy_includesourceinsymbolfile: "Disable"
  internalsvisibleto: "Keep"
  showmycode: "false"
  applicationinsightskey: ""
  failonwarnings: true
  publishartifact: true
  sign_app: false
  pfx_path: ""
  pfx_password: ""
  prerelease: false

steps:
  - task: ALOpsAppCompiler@2
    displayName: "Compile Extension"
    condition: succeeded()
    inputs:
      alternativeartifacturl: "$(BCARTIFACTURL_PROXY)"
      alternativevsixurl: "${{ parameters.alternativevsixurl }}"
      alsourcepath: '$(System.DefaultWorkingDirectory)\App'
      ruleset: "${{ parameters.ruleset }}"
      suppresswarnings: "${{ parameters.suppresswarnings }}"
      appversiontemplate: "${{ parameters.appversiontemplate }}"
      updatebuildnumber: "${{ parameters.updatebuildnumber }}"
      allowed_publisher_names: "${{ parameters.allowedpublishernames }}"
      alcodeanalyzer: ${{ parameters.alcodeanalyzer }}
      enable_external_rulesets: true
      showmycode: "${{ parameters.showmycode }}"
      resourceexposurepolicy_allowdebugging: "${{ parameters.resourceexposurepolicy_allowdebugging }}"
      resourceexposurepolicy_allowdownloadingsource: "${{ parameters.resourceexposurepolicy_allowdownloadingsource }}"
      resourceexposurepolicy_includesourceinsymbolfile: "${{ parameters.resourceexposurepolicy_includesourceinsymbolfile }}"
      internalsvisibleto: "${{ parameters.internalsvisibleto }}"
      applicationinsightskey: "${{ parameters.applicationinsightskey }}"
      failonwarnings: ${{ parameters.failonwarnings }}
      publishartifact: ${{ parameters.publishartifact }}
```

**the output**
```
##[section]Starting: Compile Extension
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extension(s) for Business Central
Version      : 2.0.6460
Author       : Hodor
Help         : Compile Business Central extension(s) from AL code.
==============================================================================
******************************************************************************
*** ALOps v2 - Preview                                                     ***
******************************************************************************
*** Importing required ALOps-Functions
*** Task Inputs:

name                                             value                                                                 
----                                             -----                                                                 
artifactversion                                                                                                        
artifacttype                                     OnPrem                                                                
artifactcountry                                                                                                        
versionselect                                    Latest                                                                
updateruntime                                                                                                          
alternativeartifacturl                           https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.3.2...
alternativevsixurl                               Latest                                                                
alsourcepath                                     C:\vsts-agent-alops-warp10\_work\6613\s\App                           
ruleset                                          https://<redacted>.blob.core.windows.net/rulesets/cicd.pte.ruleset...
suppresswarnings                                 None                                                                  
appversiontemplate                               A.A.*.0                                                               
updatebuildnumber                                False                                                                 
appfilenametemplate                              %APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_%BC_TYPE%_%BC_VERSION%_%BC...
alcodeanalyzer                                   CodeCop,UICop,PerTenantExtensionCop,BusinessCentral.LinterCop.dll     
ignorepragmas                                                                                                          
enable_external_rulesets                         True                                                                  
showmycode                                       false                                                                 
resourceexposurepolicy_allowdebugging            Enable                                                                
resourceexposurepolicy_allowdownloadingsource    Disable                                                               
resourceexposurepolicy_includesourceinsymbolfile Disable                                                               
internalsvisibleto                               Keep                                                                  
preprocessorsymbols                                                                                                    
applicationinsightskey                                                                                                 
alcachepath                                      C:\vsts-agent-alops-warp10\_work\6613\s                               
publishartifact                                  True                                                                  
publishxlif                                      False                                                                 
failonwarnings                                   True                                                                  
failonany                                        False                                                                 
storageaccount                                                                                                         
sastoken                                                                                                               
printappmanifest                                 True                                                                  
outputalclogs                                    True                                                                  
additionalprobingpaths                                                                                                 
allowed_publisher_names                          VanRoey                                                               
allowed_publisher_names_separator                ,                                                                     
accept_insider_eula                              False                                                                 
track_source_build_metadata                      True                                                                  



True
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: Van Roey (Collection License)

*** Importing required Task-Functions

*** Artifact Type   : [OnPrem]
*** Artifact Version: []
*** Artifact Country: []
*** AL Source Path  : [C:\vsts-agent-alops-warp10\_work\6613\s\App]
*** AL Cache Path   : [C:\vsts-agent-alops-warp10\_work\6613\s]


*** Fetching LATEST VSIX from Marketplace
*** Fetching Alternative VSIX: [https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/14.2.1249978/1733905314434/Microsoft.VisualStudio.Services.VSIXPackage]

*** Downloading Extension from...[https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/14.2.1249978/1733905314434/Microsoft.VisualStudio.Services.VSIXPackage]
##[command]Invoke-RestMethod -Method Get -Uri "https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/14.2.1249978/1733905314434/Microsoft.VisualStudio.Services.VSIXPackage" -OutFile "C:\vsts-agent-alops-warp10\_work\_temp\VSIX\custom.vsix"
*** Download complete
*** VSIX Downloaded to [C:\vsts-agent-alops-warp10\_work\_temp\VSIX\custom.vsix]
*** Prepare Extension for Unpack
*** Unpacking Extension to folder...
*** VSIX Available: [C:\vsts-agent-alops-warp10\_work\_temp\VSIX\custom]
*** Default Working Folder: C:\vsts-agent-alops-warp10\_work\6613\s
*** Artifact Folder       : C:\vsts-agent-alops-warp10\_work\6613\a
*** Agent Tool Folder     : C:\vsts-agent-alops-warp10\_work\_tool
*** Agent Temp Folder     : C:\vsts-agent-alops-warp10\_work\_temp

*** Resolving Path: [C:\vsts-agent-alops-warp10\_work\6613\s\App]
*** AL Source Folder      : C:\vsts-agent-alops-warp10\_work\6613\s\App
*** Resolving Path: [C:\vsts-agent-alops-warp10\_work\6613\s]
*** AL Cache Folder       : C:\vsts-agent-alops-warp10\_work\6613\s

*** Check BcContainerHelper
*** Load BcContainerHelper
BcContainerHelper version 6.0.33
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.17763.3770

*** Use BC-Artifact-Url from Cache: [https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.3.28755.30014/be]
*** Platform: c:\bcartifacts.cache\sandbox\25.3.28755.30014\platform
*** Localisation: c:\bcartifacts.cache\sandbox\25.3.28755.30014\be
*** Alternative VSIX: [C:\vsts-agent-alops-warp10\_work\_temp\VSIX\custom]
*** ALC Path: C:\vsts-agent-alops-warp10\_work\_temp\VSIX\custom\extension\bin\win32\alc.exe
*** ALTool Path: C:\vsts-agent-alops-warp10\_work\_temp\VSIX\custom\extension\bin\win32\altool.exe
*** Get [*.app] and [app.json] files recursive from [C:\vsts-agent-alops-warp10\_work\6613\s\App]
*** Found [1] file.
*** Using ALTool
*** Extract App detail from [C:\vsts-agent-alops-warp10\_work\6613\s\App\app.json]
*** Starting Batch compile of Apps:
  * C:\vsts-agent-alops-warp10\_work\6613\s\App
*** Start Compiling: [C:\vsts-agent-alops-warp10\_work\6613\s\App]
*** Get App Information [C:\vsts-agent-alops-warp10\_work\6613\s\App]
*** Loading Json Object: [C:\vsts-agent-alops-warp10\_work\6613\s\App\app.json]
  * Id         : 8d05cf7e-dbaf-4498-9f05-28bfc82d55da
  * Publisher  : VanRoey
  * Name       : <redacted>
  * Description: 
  * Version    : 1.0.0.0
*** Check for Allowed Publishers: VanRoey
*** Check Runtime: [13.0]
*** Runtime: 13
*** Overrule 'ResourceExposurePolicy.allowDebugging': ENABLE
*** Add 'resourceExposurePolicy.allowDebugging' in App Manifest
##[error]Cannot bind argument to parameter 'InputObject' because it is null.
##[section]Finishing: Compile Extension
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/b10d9220-98d2-465d-b812-9a86b29bed80)

**Additional context**
In the app.json the following resourceExposurePolicy is set
```json
  "resourceExposurePolicy": {
    "allowDebugging": true,
    "allowDownloadingSource": true,
    "includeSourceInSymbolFile": true
  },
```
