### ISSUE TITLE
Build pipelines failing on system test library installation

### ISSUE THREAD

**Issue by PeterConijn** [HodorNV/ALOps#844]
**Describe the bug**
All pipelines failing on system test library installation as of today (Monday 31-3-2025)

2025-03-31T08:04:27.4944970Z ERROR DIALOG: Cannot build the page 130455.
2025-03-31T08:04:27.4945129Z 
2025-03-31T08:04:27.4945375Z       The metadata object Page 130455 was not found.
2025-03-31T08:04:27.4945756Z       The application might be incompatible with the current compiler. Please unpublish the application that contains the application object Page 130455 and republish it. 
2025-03-31T08:04:27.4946012Z       Or, run a technical upgrade of the application database with the 'Force' flag set.
2025-03-31T08:04:27.4946180Z    

Is this an issue in the Microsoft's weekly build or does this lie elsewhere? Is anyone else having these issues as of today?

**the used yaml**
```yaml
name: $(Build.BuildId)
trigger:
  branches:
    include:
    - Dummy
variables:
- group: 'PipelineVariables'
resources:
  repositories:
  - repository: BuildTemplates
    name: ELC25/Templates
    type: Git
    ref: main

stages:
- stage: __default
  jobs:
  - job: 'Build'
    pool:
      name: DyselBC_A2
    displayName: 'Create Build'
    timeoutInMinutes: 120
    steps:
    - task: PowerShell@2
      displayName: "Remove all .app files from $(Agent.BuildDirectory) and sub folders"
      inputs:
        targetType: 'inline'
        script: Get-ChildItem -Path "$(Agent.BuildDirectory)" -Filter "*.app" -Recurse | Remove-Item -Force:$true -Confirm:$false -ErrorAction SilentlyContinue
        errorActionPreference: 'continue'
    - task: ALOpsDockerCreate@1
      displayName: 'ALOPS - Create Docker Image'
      inputs:
        artifactversion: ''
        artifacttype: Sandbox
        artifactcountry: W1
        versionselect: weekly
        memory: 8G
        accept_insider_eula: true
    - task: ALOpsDockerStart@1
      displayName: 'ALOPS - Start Docker Container'
    - task: ALOpsDockerWait@1
      displayName: 'ALOPS - Wait for Docker Container to start'
      inputs:
        search_string: 'Ready for connections!'
    - task: ALOpsLicenseImport@1
      displayName: 'ALOPS - Dev License Import'
      inputs:
        usedocker: true
        license_path: $(BCDevLicense)
    - task: ALOpsAppPublish@1
      displayName: 'ALOPS - Install AL TestTool'
      condition: True
      inputs:
        pwsh: true
        usedocker: true
        installaltesttool: true
        skip_verification: true
        install_al_app_names: |-
          Tests-TestLibraries
          System Application Test
          System Application Test Library
          Any
          Library Assert
          Test Runner
          Business Foundation Test Libraries
          Permissions Mock
          Library Variable Storage
    - task: DownloadPipelineArtifact@2
      displayName: Download Artifact - Dysel System App
      inputs:
        buildType: 'specific'
        project: [Redacted]
        definition: 13
        buildVersionToDownload: 'latest'
        itemPattern: '**/*_APP.app'
        targetPath: '$(Pipeline.Workspace)'
    - task: DownloadPipelineArtifact@2
      displayName: Download Artifact - Dysel System Test
      inputs:
        buildType: 'specific'
        project: [Redacted]
        definition: 13
        buildVersionToDownload: 'latest'
        itemPattern: '**/*_TEST.app'
        targetPath: '$(Pipeline.Workspace)'
    - task: DownloadPipelineArtifact@2
      displayName: Download Artifact - Dysel W1
      inputs:
        buildType: 'specific'
        project: [Redacted]
        definition: 10
        buildVersionToDownload: 'latest'
        itemPattern: '**/*_APP.app'
        targetPath: '$(Pipeline.Workspace)'
    - task: DownloadPipelineArtifact@2
      displayName: Download Artifact - Dysel W1 Test
      inputs:
        buildType: 'specific'
        project: [Redacted]
        definition: 10
        buildVersionToDownload: 'latest'
        itemPattern: '**/*_TEST.app'
        targetPath: '$(Pipeline.Workspace)'
    - task: ALOpsAppPublish@1
      displayName: 'Publish: Dysel Apps'
      inputs:
        usedocker: true
        installpublishedapps: true
        batch_publish_folder: '$(Pipeline.Workspace)'
        nav_artifact_app_filter: '*.app'
        skip_verification: true
        pwsh: false
      continueOnError: true
    - task: ALOpsAppCompiler@1
      displayName: 'ALOPS - Compile:  App'
      inputs:
        usedocker: true
        nav_app_version: 25.5.202504.*
        targetproject: App/app.json
        ruleset: [Redacted]
        al_analyzer: ''
        internalsvisibleto: Keep
        failed_on_warnings: false
        preprocessorsymbols: ''
        app_file_suffix: '_APP'
        pwsh: false
    - task: ALOpsAppPublish@1
      displayName: 'ALOPS - Publish:  App'
      inputs:
        usedocker: true
        nav_artifact_app_filter: '*_APP.app'
        skip_verification: true
        pwsh: false
    - task: ALOpsAppCompiler@1
      displayName: 'ALOPS - Compile:  Test-App'
      condition: true
      inputs:
        usedocker: true
        targetproject: Test/app.json
        nav_app_version: 25.5.202504.*
        ruleset: [Redacted]
        preprocessorsymbols: ''
        failed_on_warnings: false
        app_file_suffix: '_TEST'
        pwsh: false
    - task: ALOpsAppPublish@1
      displayName: 'ALOPS - Publish:  Test App'
      condition: true
      inputs:
        usedocker: true
        nav_artifact_app_filter: '*_TEST.app'
        skip_verification: true
        pwsh: false
    - task: ALOpsAppTest@1
      displayName: 'ALOPS - Run TestSuite'
      condition: True
      inputs:
        usedocker: true
        import_action: "Skip"
        import_testtoolkit: false
        testpage: '130455'
        testsuite: GDB
        failed_test_action: 'Error'
        show_available_tests: false
        allow_zero_tests: true
        disabledtests: ''
        pwsh: false
      continueOnError: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Test Artifacts: TestResults.xml'
      condition: True
      inputs:
        targetPath: '$(Agent.BuildDirectory)/TestResults'
        artifact: 'TestResults'
        publishLocation: 'pipeline'
        pwsh: false
    - task: ALOpsDockerRemove@1
      displayName: 'ALOPS - Remove Docker Container'
      enabled: true
      condition: always()
      inputs:
        createsqlbackup: 'disabled'
  - job: 'Merge'
    pool:
      name: DyselBC_A2
    dependsOn:
    - 'Build'
    displayName: 'Merge to Accept'
    condition: succeeded()
    steps:
    - task: CreatePullRequest@1
      continueOnError: true
      inputs:
        repoType: 'Azure DevOps'
        repositorySelector: 'currentBuild'
        sourceBranch: '$(Build.SourceBranch)'
        targetBranch: 'Accept'
        title: 'Merge Development into [BRANCH_NAME]'
        description: 'Merge development changes into Accept branch'
        linkWorkItems: false
        autoComplete: true
        commitMessage: 'Automatic merge DEV -> ACC'


```

**the output**
Attached output as file. Relevant bit below.
```
*** Get App Info: C:\Applications\System Application\Test\Microsoft_System Application Test Library.app
*** Get App Tenant Info
WARNING: Caution: Your program license expires in 14 days.
*** Publish App: [Microsoft / System Application Test Library]
WARNING: Caution: Your program license expires in 14 days.
##[error]AL-TestTool installation failed: Publish-NAVApp: 
Line |
  15 |      $output = Publish-NAVApp @cmdletArgs;
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | An unexpected error occurred after a database command was cancelled.

*** AL-TestTool installation finished.
```

[Build Log.txt](https://github.com/user-attachments/files/19532399/Build.Log.txt)

**Expected behavior**
I would expect the libraries to install as usual.

**Screenshots**
N/A

**Additional context**
This started happening today, which might indicate an issue with the MS builds, but investigation learned that publishing other apps results in the same issue, so I am not certain.

EDIT:
 - Fixed copying of incorrect error snippet.
 - Added findings with regard to publishing in general
