### ISSUE TITLE
Question - Test Fails to Execute

### ISSUE THREAD

**Issue by dsaveyn** [HodorNV/ALOps#849]
Hi,

We are running tests using ALOps. 

When we run the tests locally on a Docker everything works fine, however via ALOps the pipeline hangs:

 
2025-04-23T07:46:58.7766145Z *** Get Available Tests for suite [DEFAULT] with page [130455]
2025-04-23T07:46:59.1208330Z Show form 0001fd97-0000-0001-0c00-0000836bd2d2
2025-04-23T07:46:59.2147190Z Title: Command Line Test Tool Command Line Test Tool
2025-04-23T07:46:59.3223176Z *** Set [CurrentSuiteName] => [DEFAULT]
2025-04-23T07:47:00.3427052Z Show dialog 00000000-0000-0000-0400-0000836bd2d2
2025-04-23T07:47:00.3633851Z Title: Dialog Confirm
2025-04-23T07:47:00.3733662Z DIALOG: Dialog Confirm - close Dialog

When I compare it to a test the runs succesfully, I notice the following difference:

![Image](https://github.com/user-attachments/assets/058931f8-d8e4-4145-a243-67dd53ebec61)

I'm not sure where the Dialog Confirm originates from. In other tests (which execute correctly) this does not appear and as far as I can see there's no single confirm in the code. Any ideas? Did I forget to set a parameter somewhere?

**Comment by dsaveyn** [comment]
Here's the log file:

[tasklog_67.log](https://github.com/user-attachments/files/19864739/tasklog_67.log)

**Comment by waldo1001** [comment]
Can you include the yaml you're using?
Is the yaml different from successful and unsuccessful?
Did you try to run the tests with powershell when you concluded "tests locally on a Docker everything works fine"
Can you try to use page 130455 to load the tests?
Did you by any chance extend anything on the test toolkit?
What BC version?

**Comment by dsaveyn** [comment]
This is the yaml:

```
steps:
- task: Hodor.hodor-alops.alopsapptest.ALOpsAppTest@1
  displayName: 'Run Testsuite Dynavision Advanced Sync-Test'
  inputs:
    usedocker: true
    import_testtoolkit: false
    testpage: 130455
    extensionid: '24a518f9-b859-4c37-bbca-11808d766cd1'

```

The yaml appears to be identical (except the extension id) to a test that runs succesfully:

```
steps:
- task: Hodor.hodor-alops.alopsapptest.ALOpsAppTest@1
  displayName: 'Run Testsuite Dynavision Planning and Dispatch-Test'
  inputs:
    usedocker: true
    import_testtoolkit: false
    testpage: 130455
    extensionid: 'ca885e7a-87f8-4ad9-8fb7-b68a972591c6'

```

I ran the tests locally via the AL Test Tool as well as via Powershell:

```

PS C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64> Run-TestsInBcContainer -containerName bcdev -credential admin -extensionId 24a518f9-b859-4c37-bbca-11808d766cd1 -testPage 130455
Using Container
WARNING: TaskScheduler is running in the container, this can lead to test failures. Specify -EnableTaskScheduler:$false to disable Task Scheduler.
Connecting to http://localhost:80/BC/cs?tenant=default
Setting test codeunit range ''
  Codeunit 80950 ESCY OData Filter Tests Success (0.656 seconds)
```

We did not extend anything to the test toolkit.

The docker container we are using is a BC26 container:

```
2025-04-23T09:27:38.8260107Z *** Artifact Url: [https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/26.0.30643.33309/be]
2025-04-23T09:27:38.8267640Z *** Build new Image based on [https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/26.0.30643.33309/be]
2025-04-23T09:27:38.8314736Z *** Artifact Type   : [sandbox]
2025-04-23T09:27:38.8322052Z *** Artifact Version: [26.0.30643.33309]
2025-04-23T09:27:38.8328950Z *** Artifact Country: [be]
2025-04-23T09:27:38.8610088Z *** OS: [2019]
2025-04-23T09:27:39.3231469Z *** OS version: [ltsc2019]
```
