### ISSUE TITLE
ALOps Problem with expired license in BAK file

### ISSUE THREAD

**Issue by SimonOfHH** [HodorNV/ALOps#85]
I created a pretty simple Build-pipeline, using the template provided [here](https://dev.azure.com/HodorNV/ALOps%20Templates/_git/Base%20AL%20App?path=%2Fazure-pipelines.yml&version=GBmaster). I only added the parameters "accept_image_outdated" (because it's for an older version) and "sql_backup_file"
```
- task: ALOpsDockerStart@1
  displayName: 'ALOps Docker Start'
  inputs:
    docker_image: $(dockerimage)
    docker_pull: true
    accept_image_outdated: true
    sql_backup_file: "https://<uri-to-bak-file>"
```

I have an old build-pipeline where this BAK worked fine, but the old pipeline uses the previous scripts from Freddy where the license is set in "Create build container" before finishing.
In ALOpsDockerWait my pipeline failed because the container says:
> Your program license has expired.

So I now recreated the BAK with an updated license and it works just fine. But it would be great, if there is an option to already set the license before the "ALOpsDockerWait"/during "ALOpsDockerStart" to avoid this.

*Edit* Maybe I should add that I use the ALOpsLicenseImport-step as well. So I provide a valid license to the pipeline, but the "ALOpsDockerWait"-step already quits with the error
```
  - task: ALOpsLicenseImport@1
    displayName: 'ALOps License Import'
    inputs:
      usedocker: true
      license_path: $(bc_license)
```
