### ISSUE TITLE
Performance of ALOpsAppPublish, batch publishing is slow

### ISSUE THREAD

**Issue by joandrsn** [HodorNV/ALOps#852]
**Describe the bug**
It takes around 13-14 minutes to publish our 39 apps to the container.

**Expected behavior**
The process to take around 4-5 minutes as doing it manually takes.

Would it be possible to optimize the step to make it faster?
Normally I only make changes to 1-2 apps, but I still have to publish all 39 apps to my container (To run tests). The whole pipeline takes 28 minutes to complete.
A saving of 8-10 minutes is a lot in my context.

For context, my script is simply (`$appstopublish` is already sorted):
```powershell
foreach($filepath in $appstopublish) {
  $appinfo = Get-NAVAppinfo -Path $filepath
  $appid = $appinfo.AppId.Value
  Publish-NAVApp -ServerInstance "BC" -Path $filepath
  Sync-NAVApp -ServerInstance "BC" -AppId $appid
  Install-NAVApp -ServerInstance "BC" -Appid $appid -Version $appinfo.Version
}
```

**the used yaml**
```yaml
- task: AlOpsAppPublish@1
  displayName: Publish Apps
  inputs:
    usedocker: true
    pwsh: true
    batch_publish_folder: $(bc_appfolder)\artifacts
```

**the output**
[publish_step.log](https://github.com/user-attachments/files/20037384/publish_step.log)
