### ISSUE TITLE
Artifact URL could not be retrieved

### ISSUE THREAD

**Issue by Friesens-JeffreyR** [HodorNV/ALOps#853]
**Describe the bug**
ALOps build fails with error
```
"Get-BCArtifactUrl" 
Name                           Value                                                                                   
----                           -----                                                                                   
select                         Latest                                                                                  
type                           Sandbox                                                                                 
country                        ca                                                                                      



Error querying artifacts. Error message was The remote server returned an error: (404) Not Found.

Repeating download attempt ( 2  of  10 )...

##[error]Artifact Url could not be retrieved.

```

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
name: $(Build.BuildId)

variables:
- group: 'Business Central'

pool:
  name: OnPremise

steps:
- checkout: self
  clean: true 

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'Sandbox'
    artifactcountry: 'ca'
    appversiontemplate: '[yyyy].[MM].[dd].*'
    appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%_%BC_VERSION%.app'
    alcodeanalyzer: 'UICop, CodeCop, PerTenantExtensionCop'
    failonwarnings: false
    
- task: ALOpsAgentMaintenance@1
  inputs:
    removeoldtasks: true
    removebcartifacts: true
    daysunused: '3'
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```

*** Artifact Type   : [Sandbox]
*** Artifact Version: []
*** Artifact Country: [ca]
*** AL Source Path  : [E:\Agents\OnPremiseAgent1\_work\631\s]
*** AL Cache Path   : [E:\Agents\OnPremiseAgent1\_work\631\s]


*** Default Working Folder: E:\Agents\OnPremiseAgent1\_work\631\s
*** Artifact Folder       : E:\Agents\OnPremiseAgent1\_work\631\a
*** Agent Tool Folder     : E:\Agents\OnPremiseAgent1\_work\_tool
*** Agent Temp Folder     : E:\Agents\OnPremiseAgent1\_work\_temp

*** Resolving Path: [E:\Agents\OnPremiseAgent1\_work\631\s]
*** AL Source Folder      : E:\Agents\OnPremiseAgent1\_work\631\s
*** Resolving Path: [E:\Agents\OnPremiseAgent1\_work\631\s]
*** AL Cache Folder       : E:\Agents\OnPremiseAgent1\_work\631\s

*** Check BcContainerHelper
*** Load BcContainerHelper
BcContainerHelper version 6.0.19
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.17763.7131


"Get-BCArtifactUrl" 
Name                           Value                                                                                   
----                           -----                                                                                   
select                         Latest                                                                                  
type                           Sandbox                                                                                 
country                        ca                                                                                      



Error querying artifacts. Error message was The remote server returned an error: (404) Not Found.

Repeating download attempt ( 2  of  10 )...

##[error]Artifact Url could not be retrieved.
Finishing: ALOpsAppCompiler

```

**Expected behavior**
Build should succeed and produce an app package

**Screenshots**
None

**Additional context**
A build of the identical source code worked on Wednesday, but started to fail on Friday
