### ISSUE TITLE
Batch Generate Runtime Apps

### ISSUE THREAD

**Issue by MattTraxinger** [HodorNV/ALOps#860]
Is there a way to generate runtime apps for all of the apps in the project, as opposed to one by one? I'm looking for something similar to signing.
```
- task: ALOpsAppSign@1
      displayName: 'ALOps App Sign'
      inputs:
        batchsigncompiledapps: true

- task: ALOpsAppRuntimePackage@1
      displayName: 'ALOps App Runtime Package'
      inputs:
        batchgeneratepackages: true # <-- Want this
```

I can see that it has the proper context in the pipeline output:
```
*** Check for app.json files: c:\Run\DevOps\
*** Multiple projects found:
   - C:\Run\DevOps\app\App1
   - C:\Run\DevOps\app\App2
   - C:\Run\DevOps\test\TestApp1
```

Or even a way to pass a dynamic path, or list of apps if I had to, would be sufficient. In the case above, I don't want to hardcode multiple tasks into the YAML.
