### ISSUE TITLE
ALOpsAppSource - Separate Stage issue

### ISSUE THREAD

**Issue by JeremyVyska** [HodorNV/ALOps#861]
**Describe the bug**
I'm creating heavily templated stages for a project.   I'm creating a new Stage template that is just the deployment job to AppSource.  Previous stages compiled, tested, then signed the app.

When I use the ALOpsAppSource task, I'm downloading the signed app artifact from a build pipeline.  This release pipeline is an entirely separate pipeline run.   ALOpsAppSource doesn't seem to find the app file.

Either I need a parameter that I can specify the app file to upload or I need to know what pipeline variables I need to set for ALOpsAppSource to know which app to use.

**the used yaml**
```yaml
parameters:
  tenantId: ''
  clientId: ''
  clientSecret: ''
  sourcePipelineId: ''

steps:
- task: DownloadPipelineArtifact@2
  displayName: "Download Signed App"
  inputs:
    buildType: "specific"
    project: "$(System.TeamProject)"
    definition: "${{ parameters.sourcePipelineId }}"
    buildVersionToDownload: "latest"
    pipelineId: "${{ parameters.sourcePipelineId }}"
    artifactName: "Dynamics 365"
    itemPattern: "**/**/*.app"
    targetPath: "$(Build.BinariesDirectory)"

- task: Hodor.hodor-alops.ALOpsAppSource.ALOpsAppSource@1
  displayName: 'Push to AppSource'
  inputs:
    azure_tenant_id: '${{ parameters.tenantId }}'
    azure_app_client_id: '${{ parameters.clientId }}'
    azure_app_client_secret: '${{ parameters.clientSecret }}'
    pwsh: true
```

This template is used in a Release Pipeline that triggers off of a Build pipeline.  The ALOps compile & signing is happening in the Build pipeline separately.

**the output**
Not including the whole log on this step, but it does reach AppSource fine, it's just that the "Discover available .app files" step doesn't work.  This may be as simple as "what folder should I download to?"
```
**** Filter list for Dynamics365 Business Central Apps
*** Business Central Offerings found: 12
[...]
*** Discover available .app files
*** App Manifests [0]:

*** Unique App Manifests in latest version [0]:
```

**Expected behavior**
I would have expected the downloaded .app file in the build artifacts folder to have been discovered.
