### ISSUE TITLE
How to set the supresswarnings parameter in CompileStep v2

### ISSUE THREAD

**Issue by RonKoppelaar** [HodorNV/ALOps#865]
**Describe the bug**
When trying to set the supresswarnings the pipelineline fails

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
- task: ALOpsAppCompiler@2
    displayName: 'ALOps - Compile Extension: All'
    inputs:
      artifactversion: '26.2.34746.34995'
      artifacttype: 'Sandbox'
      artifactcountry: 'nl'
      appversiontemplate: 26.2510.*.0
      alsourcepath: ./ERP AL/extensions/EmpireSystemApplication
      alcachepath: $(AlFolder)
      additionalprobingpaths: $(AddinsFolder)
      printappmanifest: true
      failOnWarnings: false
      suppresswarnings: AL0432,AL0433
```

**the output**
```
Updated field in the app.,json:
    "suppressWarnings":  "AL0432,AL0433",

*** Set Pipeline variable $(ALOPS_COMPILE_ARTIFACT) = 'C:\agent1\_work\32\a\Zig_Empire System Application_26.2510.223972.0_sandbox_26.2_nl.app'
*** Set Pipeline variable $(ALOPS_COMPILE_ARTIFACT_ARRAY) = 'C:\agent1\_work\32\a\Zig_Empire System Application_26.2510.223972.0_sandbox_26.2_nl.app'
*** AL Compiler raw logs: Start
Microsoft (R) AL Compiler version 15.0.23.34357
Copyright (C) Microsoft Corporation. All rights reserved
C:\agent1\_work\32\s\ERP AL\extensions\EmpireSystemApplication\app.json(59,5): error AL1044: The value for the manifest property 'suppressWarnings' is not valid. Expected type: array.


```

**Expected behavior**
How to set this field in YML. I tried multiple solutions but it keeps failing
