### ISSUE TITLE
ALOpsAppCompiler@2 Exception calling "GetResult" with "0" argument(s)  500

### ISSUE THREAD

**Issue by sarathTegra** [HodorNV/ALOps#866]
**Describe the bug**
Every other build using the ALOpsAppCompiler@2 is throwing an Error in the GetArtifactURL step:

> Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 500 (Internal Server Error).

**the used yaml**
```yaml
name: Build $(Rev:r)

pool: Default

steps:
  - task: ALOpsAppCompiler@2
    inputs:
      artifactversion: "22.4.59114.59535"
      artifactcountry: "is"
      versionselect: Closest
      alsourcepath: "$(System.DefaultWorkingDirectory)"
      appversiontemplate: "22.4.[yyyyMMdd].*"
      appfilenametemplate: "%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%.app"
      alcodeanalyzer: "CodeCop,UICop"
      alcachepath: "$(System.DefaultWorkingDirectory)"
      preprocessorsymbols: "NONE"
      publishxlif: true
      failonany: true
      failonwarnings: true

```

**the output**
```
Starting: ALOpsAppCompiler
==============================================================================
Task         : ALOps App Compiler
Description  : Compile AL Extension(s) for Business Central
Version      : 2.0.6601
Author       : Hodor
Help         : Compile Business Central extension(s) from AL code.
==============================================================================
printappmanifest                                 True                                        
outputalclogs                                    True                                        
additionalprobingpaths                                                                       
allowed_publisher_names                                                                      
allowed_publisher_names_separator                ,                                           
accept_insider_eula                              False                                       
track_source_build_metadata                      True                                        
pwsh                                             False                                       


True
*** For documentation, please visit   : https://www.alops.be/documentation

*** ALOps License:
  * Licensed To: ********** (Collection License)

*** Importing required Task-Functions

*** Artifact Type   : [OnPrem]
*** Artifact Version: [22.4.59114.59535]
*** Artifact Country: [is]
*** AL Source Path  : [C:\agent\_work\8\s]
*** AL Cache Path   : [C:\agent\_work\8\s]


*** Default Working Folder: C:\agent\_work\8\s
*** Artifact Folder       : C:\agent\_work\8\a
*** Agent Tool Folder     : C:\agent\_work\_tool
*** Agent Temp Folder     : C:\agent\_work\_temp

*** Resolving Path: [C:\agent\_work\8\s]
*** AL Source Folder      : C:\agent\_work\8\s
*** Resolving Path: [C:\agent\_work\8\s]
*** AL Cache Folder       : C:\agent\_work\8\s


*** Check BcContainerHelper
*** Load BcContainerHelper
BcContainerHelper version 6.1.4
WinRM service is not running, will not try to use WinRM sessions
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.26100.4202
nt authority\network service does NOT have modify permissions to C:\WINDOWS\System32\drivers\etc\hosts
You need to run as administrator or you can run Check-BcContainerHelperPermissions -Fix to fix permissions
nt authority\network service does NOT have permissions to run docker commands
You need to run as administrator or you can run Check-BcContainerHelperPermissions -Fix to fix permissions


"Get-BCArtifactUrl" 
Name                           Value                                                                                   
----                           -----                                                                                   
select                         Closest                                                                                 
version                        22.4.59114.59535                                                                        
type                           OnPrem                                                                                  
country                        is                                                                                      



Downloading Platform index to C:\agent\_work\_temp\bcContainerHelper.platform.json
Downloading is index to C:\agent\_work\_temp\bcContainerHelper.is.json
Error downloading..., retrying in 4 seconds...
Error downloading..., retrying in 8 seconds...
Error downloading..., retrying in 16 seconds...
Error downloading..., retrying in 32 seconds...
BcContainerHelper\Get-BCArtifactUrl Telemetry Correlation Id: 5b4ab090-0a27-4ef6-859b-4eecf70bddc0
##[error]Exception calling "GetResult" with "0" argument(s): "Response status code does not indicate success: 500 (Internal Server Error)."
Response status code does not indicate success: 500 (Internal Server Error).
Finishing: ALOpsAppCompiler

```
