### ISSUE TITLE
BC14 Docker: [ODBC Driver Manager] Data source name not found and no default driver specified

### ISSUE THREAD

**Issue by DanielGoehler** [HodorNV/ALOps#867]
**Describe the bug**
When creating a Docker container for BC14.17 and importing the FOB file, we encounter the following error from the ODBC Driver Manager:  **"Data source name not found and no default driver specified."**  
The last time this worked for us was on 2025-04-02.

It seems that the issue is caused by the missing SQL Server Native Client (`sqlncli64.msi`). This component is no longer included in the docker itself.

Is there an easy way to install the required SQL Server Native Client (`sqlncli64.msi`) in this scenario? The file can be found on older BC 14 CU DVDs under `Prerequisite Components\Microsoft SQL Server`. If so, could you please provide guidance or suggest an alternative solution?

I've encountered the same issue before, particularly with newer BC14 CU DVDs where the SQL Server Native Client is missing, and the development environment cannot connect to SQL Server as a result.

**the used yaml**
please provide the yaml that you used.  It helps you put the yaml like this: 
```yaml
              - task: ALOpsFobImport@1
                displayName: 'Import PRI TestToolkit'
                inputs:
                  usedocker: true
                  filePath: 'PRITestToolkit.fob'
                  import_action: 'Overwrite'
```

**the output**
Also the complete output is necessary for us to see what is going on.  Also use backtics:
```
##[section]Starting: Import PRI TestToolkit
==============================================================================
Task         : ALOps Import FOB
Description  : Import objects from .FOB file
Version      : 1.470.6601
Author       : Hodor
Help         : Import objects from .FOB file.
==============================================================================
*** Validate configuration
*** Task Inputs:

name                                                                    value
----                                                                    -----
usedocker                                                                True
fixed_tag                                                                    
nav_serverinstance                                                      BC140
filePath                             C:\agent\_work\1177\s\PRITestToolkit.fob
import_action                                                       Overwrite
synchronize_schema_changes                                                Yes
generate_symbol_reference                                               False
force_full_generate_symbol_reference                                    False
override_finsql_path                                                         



True
*** For documentation, please visit   : https://www.alops.be/documentation

*** Importing required PS-Functions
*** Connect Docker Session
*** Initiate Docker Session
*** Set Docker Container ErrorActionPreference = Stop
*** Container Session Powershell Version


Name  : PSVersion
Value : 5.1.17763.7434

Name  : PSEdition
Value : Desktop

Name  : PSCompatibleVersions
Value : {1.0, 2.0, 3.0, 4.0...}

Name  : BuildVersion
Value : 10.0.17763.7434

Name  : CLRVersion
Value : 4.0.30319.42000

Name  : WSManStackVersion
Value : 3.0

Name  : PSRemotingProtocolVersion
Value : 2.3

Name  : SerializationVersion
Value : 1.1.0.1




*** Setup Docker Session
*** Setup database connection
*** Import NAV/BC Management DLL's [False]
*** Loading assemblies for ServiceTier [NAV].
*** Loading assemblies from: [C:\program files\microsoft dynamics nav\140\service]
*** BC Management DLL: C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Management.dll]
*** BC App Management DLL: C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll
*** Selected module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Loading module: [C:\program files\microsoft dynamics nav\140\service\Microsoft.Dynamics.Nav.Apps.Management.dll]
*** Setup VSIX for ALTOOL
*** ALTool Path: Not available
*** Using AL Compiler  located [C:\Run\Microsoft.al\al-\extension\bin\alc.exe]
***
*** Using Windows-Authentication for Database
*** Setup FinSql link
*** Searching for Client-FinSql in Registry
*** Client-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\RoleTailored Client]
*** Searching for Service-FinSql in Registry
*** Service-FinSql not found in registry: [HKLM:\SOFTWARE\Wow6432Node\Microsoft\Microsoft Dynamics*\*\Service]
*** Searching for RoleTailoredClient-FinSql in FileSystem
*** Found FinSql path: [C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe]
C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe
*** FOB File filter: C:\agent\_work\1177\s\PRITestToolkit.fob
*** Import Action: Overwrite
*** Start processing FOB: [PRITestToolkit.fob]
*** Transfer FOB to session: [PRITestToolkit.fob]
*** Import FOB: [PRITestToolkit.fob] in [NAV]
  * DatabaseServer   : localhost\SQLEXPRESS
  * Database Instance: SQLEXPRESS
  * Database Name    : CRONUS
  * Management Port  : 7045
*** Running command: & "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe" --% Command=ImportObjects,ImportAction=Overwrite,SynchronizeSchemaChanges=Yes,File="C:\Run\PRITestToolkit.fob",LogFile="C:\Users\ContainerAdministrator\AppData\Local\Temp\NavIde\15cf6671-3999-4909-8ee3-b43f7c1110b5\PRITestToolkit.log",ServerName="localhost\SQLEXPRESS",generatesymbolreference=0,ServerName="localhost\SQLEXPRESS",Database="CRONUS",NavServerName="localhost",NavServerInstance="NAV",NavServerManagementport=7045 | Out-Null
2025-06-27T08:45:40.2454486Z ##[error]: [22922069] The following ODBC error occurred:
Error: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified
tate ID: IM002 -- File: C:\Run\PRITestToolkit.fob

2025-06-27T08:45:40.3390381Z ##[section]Finishing: Import PRI TestToolkit
```

**Comment by DanielGoehler** [comment]
Quick update from my side: I tried installing the missing components, but unfortunately, that didn’t resolve the issue. I’m not sure if the installation failed, if a restart is necessary, or if this step even solves the problem.

 ```yml
          - task: ALOpsDockerExec@1
                displayName: 'Install missing SQL Server Native Client'
                inputs:
                  inline_script: 'Start-Process msiexec.exe -ArgumentList ''/i "$(Build.SourcesDirectory)\.azuredevops\install\sqlncli.msi" /qn /norestart'' -Wait'
              - task: ALOpsDockerExec@1
                displayName: 'Install missing SQL Server Native Client'
                inputs:
                  inline_script: 'Start-Process msiexec.exe -ArgumentList ''/i "$(Build.SourcesDirectory)\.azuredevops\install\sqlncli64.msi" /qn /norestart'' -Wait'
```

**Comment by DanielGoehler** [comment]
Using the Generic Image (`use_generic_image`), as recommended in https://github.com/microsoft/navcontainerhelper/issues/3968, provides an temporary solution to this problem.

**Example configuration:**
```yml
- task: ALOpsDockerCreate@1
  displayName: 'Create Docker Container'
  inputs:
    artifactversion: '14.17'
    artifacttype: 'onprem'
    artifactcountry: 'de'
    use_generic_image: 'mcr.microsoft.com/businesscentral:10.0.17763.7314' # Windows Server 2019
```
