### ISSUE TITLE
ALOps SaaS Publish Extension doesnt support MFA

### ISSUE THREAD

**Issue by jordan992** [HodorNV/ALOps#92]
If I enable Multi factor authentication on the office account I cannot use this task. 

Is it possible to modify the authentication with business central and use the Web Service Access Key instead of the username and password?

**Comment by waldo1001** [comment]
Hi @jordan992 ,
this is by design, I'm afraid.  There is nothing (yet) we can do about that as long as MIcrosoft doesn't allow it.

Are you a delegated admin to the environment?

**Comment by AdminHodor** [comment]
Dear @jordan992 ,

>>Is it possible to modify the authentication with business central and use the Web Service Access Key instead of the username and password?
First tests seem positive for this, we will look into including other authentication options for this step.

Kind regards

**Comment by AdminHodor** [comment]
Dear @jordan992 ,

We did manage to get Username/Password working for the SaaS deploy, which will be release in one of the upcoming updates.
On the downside, we got news that the entire Username/Password flow for BC-SaaS will be deprecated.

Kind regards,

**Comment by AdminHodor** [comment]
Dear @jordan992 ,

Fix for this is in version v1.429, which we just released. Please note we replaced both the ALOpsSaaS tasks with one new task:  ALOpsExtensionAPI. Setup is similar and allows for all types of authentication. For SaaS you can use the BC-Username and a WebserviceAccessKey instead of OAuth.

Get Extensions:
```yaml
- task: ALOpsExtensionAPI@1
  displayName: 'Get Extensions - Azure Basic WebserviceAccessKey'
  inputs:
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api'
    authentication: basic
    azure_tenant_id: '$(azure_tenant_id)'
    username: '$(bc_ws_user)'
    password: '$(bc_ws_pass)'
```

Publish Extension:
```yaml
- task: ALOpsExtensionAPI@1
  displayName: 'Publish Extensions - Azure Basic WebserviceAccessKey'
  inputs:
    interaction: publish
    api_endpoint: 'https://api.businesscentral.dynamics.com/v2.0/$(azure_tenant_id)/Sandbox/api'
    authentication: basic
    azure_tenant_id: '$(azure_tenant_id)'
    username: '$(bc_user)'
    password: '$(bc_password)'
    artifact_filter: '*.app'
```

Could you please validate the solution?

Kind regards,
