### ISSUE TITLE
Build fails on compilation step (BC 16.0)

### ISSUE THREAD

**Issue by ernestasjuska** [HodorNV/ALOps#96]
Hello,

We are converting our extensions to BC 16.0 (next major Business Central version) and get the following error in task `ALOpsAppCompiler@1`:
![bc160error](https://user-images.githubusercontent.com/53167314/76082902-08d33480-5fb5-11ea-9a3e-69068dff45ec.PNG)
```
##[error]Cannot find path 'c:\Run\DevOps\Default publisher_hello-alops-2020_1.0.0.0.app' because it does not exist.
```

I used "AL: Go!" app template.

Next minor version (15.2, docker image bcinsider.azurecr.io/bcsandbox:lt) and lower versions work fine.

Thanks.

Pipeline log: 
[pipelines-log.txt](https://github.com/HodorNV/ALOps/files/4298322/pipelines-log.txt)

Pipeline file:
[azure-pipelines.yml.txt](https://github.com/HodorNV/ALOps/files/4298263/azure-pipelines.yml.txt)

**Comment by waldo1001** [comment]
Hi, 
I can't seem to repro this scenario.  Can you share that app (the code)?
In the meantime, can you try with hyper-v isolation?  Just to rule that out?  I know that alc.exe behaves weird in some cases on february-update for windows server .. .
Thanks!

**Comment by waldo1001** [comment]
I tested it here:
https://dev.azure.com/msdyn365bc/WaldoDevOpsDemos/_git/WaldoApp-Base?path=%2F.devops%2FBuildNext.yml

can you try do add the path to the app.json?  Like:
```yaml
- task: ALOpsAppCompiler@1
  displayName: 'Compile Extension'
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: true
    targetproject: app.json
```

**Comment by dNsl9r** [comment]
Hi @waldo1001 ,
for me the CI process also fails with BC16.
ALC exits with: `*** AL Compiler Exit Code: -1073741502`

When I try to start the docker container with "--isolation hyperv" I get the error, that the feature is not installed on the machine. I'm not allowed to add the feature on the server..

**Comment by ChristianMuetzePrintVis** [comment]
Hi @waldo1001,

same here. We try to implement it, but we ran into the same issue.

``` Pascal
*** Starting AL Compiler...
*** App.Name         = PV
*** App.Publisher    = PV
*** App.Compiler Path= C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe
*** Checking for Assemblies in App
*** Assemblies in App found. Adding Probing Path.
*** Add Windows Assembly Path [C:\Windows\assembly]
& C:\Run\Microsoft.al\al-ALLanguage\extension\bin\alc.exe /packagecachepath:"c:\Run\DevOps\PackageCache" /project:"c:\Run\DevOps\PVApp" /out:"c:\Run\DevOps\PV_PV_16.1.202013.1327_PVALAPP.app" /fullpaths /ruleset:"c:\Run\DevOps\PVApp\Rules\CodeCop.ruleset.json" /assemblyprobingpaths:c:\Run\DevOps\,C:\Windows\assembly
*** AL Compiler Exit Code: -1073741502
*** AL Compiler raw logs: Start

*** AL Compiler raw logs: End
*** Start processing compile results.
*** Compile OK.
*** Start processing compile results done.
*** Transfer App Artifact from Docker container.
##[error]Cannot find path 'c:\Run\DevOps\PV_PV_16.1.202013.1327_PVALAPP.app' because it does not exist.
Async Command Start: Add Build Tag
```

I used this image:

``` YAML
- task: ALOpsDockerStart@1
  inputs:
    fixed_tag: '$(docker_container_name)'
    docker_image: 'bcinsider.azurecr.io/bcsandbox-master:w1'
    dockerauthentication: 'UsernamePassword'
    docker_username: '$(docker_username)'
    docker_password: '$(docker_password)'
```

// Christian
