### ISSUE TITLE
Issue with ALOpsLicenseImport step

### ISSUE THREAD

**Issue by gintuoklis** [HodorNV/ALOps#97]
Hey Guys,
We are testing ALOpsLicenseImport task, and ran into the issue. 
Here's simple task that does license import. 

```
steps:
- task: Hodor.hodor-alops.alopslicenseimport.ALOpsLicenseImport@1
  displayName: 'ALOps License Import'
  inputs:
    nav_serverinstance: MV8BAT
    license_path: '$(System.DefaultWorkingDirectory)/_license_very_special_customer-bv/*.flf'
    remove_license_file: false
    print_license_info: true

```

It strangely shows the contents of the license correctly but import fails due to the error:

`"##[error]Cannot bind parameter 'LicenseFile' to the target. Exception setting "LicenseFile": "Illegal characters in path.""`

I i harcode license name, it goes through. 

![image](https://user-images.githubusercontent.com/16342128/76225031-3968d780-621c-11ea-8e61-17c4c1bed6cb.png)
