### ISSUE TITLE
Error when checking out multiple repos

### ISSUE THREAD

**Issue by Darren-OO** [HodorNV/ALOps#99]
Hi Guys,

I get this error in the compile step when I check out multiple repositories:

```
*** Docker Working Folder: c:\Run\DevOps\
*** Copy from [C:\DevOps\BCBuildAgent\_work\2\s] to [c:\Run\DevOps\]
*** Source File setup completed
*** Target Project: \app\app.json
*** Check for app.json files: c:\Run\DevOps\
*** Multiple projects found:
   - C:\Run\DevOps\MyRepository\app
   - C:\Run\DevOps\MyRepository\test
*** Retrieving App-Info [\app\app.json]
*** Loading Json Object: [c:\Run\DevOps\app\app.json]
  * App.ID          = 
  * App.Name        = 
  * App.Publisher   = 
  * App.Version     = 
  * App.Platform    = 
  * App.Application = 
***
*** Match: yyyyWW
##[warning]Get-NAVInfoStep: Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format."
***
##[error]Application manifest [c:\Run\DevOps\app\app.json] not found.
```

I assume this is because compile step is pointing to app/app.json, which exists when there's only one repo, but doesn't exist when multiple repos are downloaded - ie it's now MyRepository/app/app.json

Is there any way around this? I'm trying to template as much as possible, so it would be good if there was a variable that pointed to `C:\Run\DevOps\app\app.json` when it was the only repo, and `C:\Run\DevOps\MyRepository\app\app.json` when there were multiple repositories downloaded.

Should I just avoid using multiple repositories?

Thanks,
Darren.

**Comment by waldo1001** [comment]
Looks there is something wrong in the yml icm with your repo.  Can you send me the repo root structure and the compile step in yaml?  In fact, sharing the complete yaml might help as well .. .

I never build a pipeline including multiple repos, so at this point, that isn't included in our tests.. .  But that doesn't mean we can't do anything about it.

did you try to change the setting to "MyRepository/app/app.json"?

**Comment by Darren-OO** [comment]
Hi Waldo,

I have 3 repos of interest.

MyRepository - the source that I want to build
Tools - repo to store YAML templates
Dependency - repo containing an ISV app file which is a common dependency for several of our extensions

MyRepository structure is:
- root
  - app
    - app.json
    - azure-pipelines.yml
    - al.files.al
  - test
    - app.json
    - al.files.al

I also have 2 YAML files which I think are relevant

azure-pipelines.yml@MyRepository

```
name: $(Build.BuildId)

variables:
  #Can be changed
  BCVersion: 15

pool: 
  name: local

resources:
  repositories:
  - repository: Tools
    type: git
    name: Tools 
  - repository: Dependency
    type: git
    name: Dependency
    ref: test

steps:
- checkout: self
  clean: true 
- checkout: Dependency
  clean: true

#### Set up Container
- template: build/SetupContainer.yml@Tools

#### DO NOT MODIFY ABOVE THIS LINE

#### Add dependencies here
- task: ALOpsAppPublish@1
  displayName: 'Publish Dependency'
  enabled: true
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app' 
    batch_publish_folder: 'C:\Run\DevOps\Dependency\'
    skip_verification: true

#### DO NOT MODIFY BELOW THIS LINE

#### Run Tests
- template: build/CompileAndTest.yml@Tools

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
```

CompileAndTest.yml@Tools

```
steps:

- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: '?.?.[yyyyWW].*'
    targetproject: 'app/app.json'                           # The App
    failed_on_warnings: true    
    publish_artifact: true
    app_file_suffix: _APP

- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish Extension: App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true   

- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: Test-App'
  inputs:
    usedocker: true
    nav_app_version: '?.?.[yyyyWW].*'
    targetproject: 'test/app.json'                     # The Test-App
    failed_on_warnings: true    
    publish_artifact: true
    app_file_suffix: _TEST

- task: ALOpsAppPublish@1
  displayName: 'ALOps Publish Extension: Test-App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true   

- task: ALOpsAppTest@1
  displayName: 'ALOps Run TestSuite'
  inputs:
    usedocker: true
    import_action: "Skip"
    import_testtoolkit: false
    show_available_tests: true
    testpage: '130455'
    testsuite: 'DEFAULT'
    failed_test_action: 'Ignore'
  continueOnError: true   

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TestResults.xml'
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'
```

If I change the compile step to MyRepostory/app/app.json then it will work, however I am trying to keep the compile step in a separate YAML file which is shared between many extensions.

I think that the core of the issue has to do with how Microsoft have implemented multi repo checkout.

When checking out only one repo, the files in the agent are:
_work\1\s\app\app.json

When checking out more than one repo, the files in the agent are:
_work\1\s\MyRepository\app\app.json

Is it possible for the compile step to try to prepend the repository name to the targetproject input behind the scenes if the targetproject doesn't exist?

For example, if I have `targetproject: 'app/app.json'` and it doesn't find anything at `C:\Run\DevOps\app\app.json` can it fall back to `C:\Run\DevOps\MyRepository\app\app.json`?

Thanks for taking the time to read through all this - hope it makes sense.

**Comment by waldo1001** [comment]
Why don't you use parameters in the templates?  this way you could feed it from where it's used?

**Comment by Darren-OO** [comment]
Thanks for the suggestion, that works well for me.

Updates for others with the same problem:

CompileAndTest.yml@Tools
```
parameters:
- name: multirepo
  type: boolean
  default: false
```

```
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: App'
  inputs:
    usedocker: true
    nav_app_version: '?.?.[yyyyWW].*'
    ${{ if eq(parameters.multirepo,false) }}:
      targetproject: 'app/app.json'
    ${{ if eq(parameters.multirepo,true) }}:
      targetproject: '$(Build.Repository.Name)/app/app.json'                           # The App
    failed_on_warnings: true    
    publish_artifact: true
    app_file_suffix: _APP
```

```
- task: ALOpsAppCompiler@1
  displayName: 'ALOps Compile Extension: Test-App'
  inputs:
    usedocker: true
    nav_app_version: '?.?.[yyyyWW].*'
    ${{ if eq(parameters.multirepo,false) }}:
      targetproject: 'test/app/json'
    ${{ if eq(parameters.multirepo,true) }}:
      targetproject: '$(Build.Repository.Name)/test/app.json'                     # The Test-App
    failed_on_warnings: true    
    publish_artifact: true
    app_file_suffix: _TEST
```

azure-pipelines.yml@MyRepository
```
- template: CompileAndTest.yml@Tools
  parameters:
    multirepo: 'true'
```
